### ISSUE TITLE
[react-native] Allow setting codeBundleId from native

### ISSUE THREAD

**Issue by danilobuerger** [bugsnag/bugsnag-js#1000]
Before upgrading from `bugsnag-react-native` to `@bugsnag/react-native` it was possible to set the `codeBundleId` from native like so:
```
BugsnagConfiguration *config = [BugsnagConfiguration new];
config.codeBundleId = @"foo";
[BugsnagReactNative startWithConfiguration:config];
```
Now `codeBundleId` has disappear from the public interface and seems to only be intended to be set from js. However, internally its still available as 
```
[Bugsnag updateCodeBundleId:@"foo"];
```
Could this be made public or integrated into `BugsnagConfiguration`?

**Comment by phillipsam** [comment]
Hi @danilobuerger - generally we believe the point of the codeBundleId is to uniquely identify a new JS bundle that is loaded.

Can you tell us more about your use case here and why you would want to set this in native?

**Comment by danilobuerger** [comment]
@phillipsam I investigated and turns out we don't need to do it anymore. Setting it in js is fine. Sorry for the noise.
