### ISSUE TITLE
[react-native] Missing typescript types in npm package

### ISSUE THREAD

**Issue by danilobuerger** [bugsnag/bugsnag-js#1001]
https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/package.json#L5 lists the types as being at:
```
"types": "types/bugsnag.d.ts"
```
However, the npm package does not include that file:
https://unpkg.com/browse/@bugsnag/react-native@7.3.1/
<img width="956" alt="Screenshot 2020-08-17 at 12 50 34" src="https://user-images.githubusercontent.com/996231/90388553-44a41700-e088-11ea-9976-0e99498776ea.png">

**Comment by johnkiely1** [comment]
hi @danilobuerger 
Thanks for reporting this. We are creating a fix for this asap. We will update you as soon as it is ready.

**Comment by steve-nester-uk** [comment]
Fixed in [v7.3.2](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.2)
