### ISSUE TITLE
[react-native][android] Installation help: Package com.bugsnag.android does not exist 

### ISSUE THREAD

**Issue by katye333** [bugsnag/bugsnag-js#1005]
Hi All,

I am attempting to add @bugsnag/react-native to my react native project but while adding the imports to the MainApplication.java file, I keep encountering errors that the com.bugsnag.android package does not exist. I have checked the instructions given and went through each file on the example project to no avail. 

Does anyone know what I am doing wrong? 

Bugsnag version: 7.3.2
React Native version: 0.61.4
Gradle version: 6.1.1

**Comment by bengourley** [comment]
Did you add this to your gradle file?

`apply from: "../../node_modules/@bugsnag/react-native/bugsnag-react-native.gradle"`

https://docs.bugsnag.com/platforms/react-native/react-native/#android

**Comment by katye333** [comment]
@bengourley Yes

**Comment by steve-nester-uk** [comment]
@katye333 would you be able to email a reproduction case through to support@bugsnag.com and we'll take a closer look.

**Comment by steve-nester-uk** [comment]
Closing for now as we have not been able to reproduce, please let us know if you're able to reproduce and we can reopen.

**Comment by rajprakash00** [comment]
I'm facing same error too(even after trying the steps mentioned above),also i tried to link manually but it didn't work :(
@katye333  did you solve it?

**Comment by calz10** [comment]
hi @rajprakash00 , just asking if you did managed to build this? got the same error

**Comment by jpmc3630** [comment]
I was getting

```
/MainApplication.java:3: error: package com.bugsnag.android does not exist
import com.bugsnag.android.Bugsnag;
                          ^
MainApplication.java:88: error: cannot find symbol
    Bugsnag.start(this);
    ^
  symbol:   variable Bugsnag
  location: class MainApplication
2 errors

FAILURE: Build failed with an exception.
```

Running:
`react-native link @bugsnag/react-native`
Solved it, I'm not sure why it didn't add this as part of the install. I think it has to do with my project being an older React Native project (<0.60) that has been migrated up to 0.60)

The command added these lines:

adds to app/build.gradle: 
`implementation project(':@bugsnag_react-native')`

adds to settings.gradle:
```
include ':@bugsnag_react-native'
project(':@bugsnag_react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@bugsnag/react-native/android')
```
