### ISSUE TITLE
Bugsnag reporting unreproducible errors only in Windows Chrome.

### ISSUE THREAD

**Issue by hasan-wajahat** [bugsnag/bugsnag-js#1013]
### Describe the bug
Ever since in our project we upgraded our babel so that we only transpile stuff that should be transpiled, bugsnag has been reporting non-stop errors like: `SyntaxError: Unexpected token 'const'` or `SyntaxError: Use of reserved word 'class'`. Interestingly enough all of these errors only show for chrome windows.
But I can not reproduce a single one of these errors in any Windows Chrome I use and the app is working just as expected. Our users are using Chrome 79 and higher so both `const` and `class` is available to them. 

### Steps to reproduce
Not sure how this can be reproduced for other people, I assume this can't be reproduced in a normal setting otherwise this bug would have been addressed. But may be test by targeting Chrome: 79 or higher in babel and then test in windows chrome.

### Environment
* Bugsnag version: 7.1
* Browser version (e.g. chrome, safari): Only Chrome
* Device (e.g. iphonex): Only for windows

<details><summary>Error messages:</summary>

```
Error SyntaxError: Unexpected token 'const' 
```
</details>

**Comment by phillipsam** [comment]
Hi @hasan-wajahat - What do you mean when you say you upgraded your babel? Which version did you upgrade to?

These are not errors that we have seen in the past. Would you be able to write into support@bugsnag.com with a full code example which reproduces the issue?

**Comment by hasan-wajahat** [comment]
@phillipsam I had: 
babel-preset-env: "^1.7.0" 
which I upgraded to:
@babel/core: "^7.11.1",
@babel/preset-env: "^7.11.0",

I actually have contacted support but they were unable to help me. That's why I opened the issue for the community.

**Comment by steve-nester-uk** [comment]
@hasan-wajahat we have not been able to reproduce this issue, if you can send a repro case as mentioned above, we'll be happy to reopen and investigate further.
