### ISSUE TITLE
[react-native][js] unhandled rejections

### ISSUE THREAD

**Issue by radko93** [bugsnag/bugsnag-js#1029]
### Describe the bug
I upgraded to the new React Native SDK and now I'm getting unhandled rejections in my bugsnag Inbox. The problem is that it's hard to tell what's going on as in the "Promise Rejection Tracking" tab there's only `non-error parameter
false`. I'm uploading source maps but maybe there's something wrong with that?

### Environment
* Bugsnag version: @bugsnag/react-native 7.3.3
* Device (e.g. iphonex): Android release build, Hermes enabled.

<details><summary>Error messages:</summary>

```
node_modules/promise/setimmediate/rejection-tracking.js:71
promise rejection tracking received a non-error. See "promise rejection tracking" tab for more detail.
```
</details>

**Comment by steve-nester-uk** [comment]
@radko93 as far as I can tell this is not an issue with the notifier so I'm going to close this issue from here.  However, please send an email to support@bugsnag.com and we'll be very happy to assist with the issue.
