### ISSUE TITLE
A missing source map banner remains visible if stacktrace contains "Global Code"

### ISSUE THREAD

**Issue by ubmit** [bugsnag/bugsnag-js#1039]
### Description

The stack trace seems fine, but I got this warning: 

`Source mapping failed: A source map could not be applied`

Is something really not working as expected?

![image](https://user-images.githubusercontent.com/8797405/89309821-d2850880-d66b-11ea-83d9-f9272ec1b03d.png)

### Issue

Source mapping failed: A source map could not be applied

### Environment

Library versions:

```shell
react-native-with-moxy@0.0.0 /Users/guilherme/workspace/moxy/react-native-with-moxy
├── bugsnag-react-native@2.23.10 
└── react-native@0.61.5 
```

- cocoapods version (if any) (`pod --version`):
- iOS/Android version(s): Android 10
- simulator/emulator or physical device?: simulator
- debug mode or production?: production

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class? No

**Comment by johnkiely1** [comment]
This has been transferred to the bugsnag-js repo as the Bugsnag react native library is now part of this repository (as of v7.3).
