### ISSUE TITLE
[v7][Android] Native library could not be linked, couldn't find DSO to load: libreactnativejni.so 

### ISSUE THREAD

**Issue by cristianoccazinsp** [bugsnag/bugsnag-js#1040]
### Description

Recent migration to v7 is now causing a bunch of new linking crashes that did not happen before.

### Issue

Android app startup crashes / warnings due to linking errors.

![image](https://user-images.githubusercontent.com/48869228/91988319-84643300-ed05-11ea-8bb3-501f1027c35f.png)

Note: I'm not using Hermes.

Note2: After reviewing the affected "users", it seems like each single user got all 3 errors, from the warnings to the unhandled one, meaning they were not able to start the app at all.

### Environment

Library versions:

```shell
"@bugsnag/react-native": "7.3.3"
"react-native": "0.62.2"
```

- iOS/Android version(s): 5.1, 5.1.1, 6.0.1
- simulator/emulator or physical device?: Physical Device
- debug mode or production?: Production

- [X] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [X] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

I have also read the linked docs, but it really seems like a bad alternative (yet another dependency for something that used to work?). If anything, and if this is common, it should at least be done automatically by the library as its own dependency.

It is also very strange that when releasing the build, there was 1 less ABI in the build results (reported as a warning on the google console, `armeabi`, although `armeabi-v7a` is included).

**Comment by johnkiely1** [comment]
This has been transferred to the bugsnag-js repo as the Bugsnag react native library is now part of this repository (as of v7.3).

**Comment by xander-jones** [comment]
The Bugsnag library doesn't make any calls to load the Hermes SO, so it's unlikely to be related to this upgrade. Did you upgrade any other packages at the same time as Bugsnag, that might enable Hermes? To my knowledge, Hermes is disabled by default even in the latest RN versions.

We don’t think it's an issue with the notifier. `libhermes.so` showing as missing indicates that it either hasn’t been bundled into the APK, or that perhaps the APK is being installed on the wrong architecture. Most often this happens when users download an APK from 3rd party source. 

> handled errors were reported for the exact same device at the same time

This seems reasonable since the SO's are going to be loaded on initialization. `AnrLinkError`/`NdkLinkError` only occur when linking the Bugsnag SO library fails. `UnsatisfiedLinkError` will occur when a SO file matching the device’s architecture is not loaded successfully.

**Comment by cristianoccazinsp** [comment]
After some testing, looks like there was an import to a Hermes class somewhere in the native code, even if hermes was not being used.  This may not be the cause of the crashes since the app would still work everywhere else, but we will see in the following weeks if this seemingly naive import was the culprit.

**Comment by mattdyoung** [comment]
Thanks for the update @cristianoccazinsp 

Closing for now as it sounds like it's not an issue with Bugsnag but do let us know if you see any evidence to the contrary.

**Comment by cristianoccazinsp** [comment]
Strange, I have updated the other project that was using bugsnag, and the Hermes crash is still happening, even if it is now not being referenced / imported from anywhere.  Thoughts on where it could be getting required?

Here's a fresh stack trace again:

```
java.lang.UnsatisfiedLinkError couldn't find DSO to load: libhermes.so 
    SoLoader.java:789 com.facebook.soloader.SoLoader.doLoadLibraryBySoName
    SoLoader.java:639 com.facebook.soloader.SoLoader.loadLibraryBySoName
    SoLoader.java:577 com.facebook.soloader.SoLoader.loadLibrary
    SoLoader.java:525 com.facebook.soloader.SoLoader.loadLibrary
    HermesExecutor.java:20 com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>
    HermesExecutorFactory.java:29 com.facebook.hermes.reactexecutor.HermesExecutorFactory.create
    ReactInstanceManager.java:997 com.facebook.react.ReactInstanceManager$5.run
    Thread.java:761 java.lang.Thread.run
```

**Comment by mattdyoung** [comment]
We actually ran into the same issue ourselves in testing on Friday. It appears to be a bug in React Native that a few people have encountered:
https://stackoverflow.com/questions/57036317/react-native-java-lang-unsatisfiedlinkerror-couldnt-find-dso-to-load-libherm

There are some ideas on that stackoverflow thread. In our case the issue went away after running `./gradlew clean` and then re-installing the app.

**Comment by cristianoccazinsp** [comment]
Interesting, but I'm not using hermes anywhere, nor requiring it.

Any chance the dependency `@bugsnag/plugin-react-native-hermes` that I'm seeing in package-lock.json is causing issues? Maybe the plugin is doing an import somewhere?

**Comment by xander-jones** [comment]
With the exception of our test framework, there are no references to Hermes that would suggest Bugsnag is going to import this library.

The StackOverflow thread above suggests that people are seeing this issue even without enabling Hermes.

**Comment by cristianoccazinsp** [comment]
@mattdyoung I have just upgraded from 7.5.3 to 7.5.5 and I'm now getting `AnrLinkError: Native library could not be linked. Bugsnag will not report ANRs. See https://docs.bugsnag.com/platforms/android/anr-link-errors` every single time I launch the app installed from an APK file.  Note that this never happened in any of my test devices, and after the upgrade, it is happening every single time the app is started.  I will be re-trying with a clean build folder just in case, but what changed?

**Comment by cristianoccazinsp** [comment]
Interestingly, after a clean build the warning has gone away again. I wonder if building for local dev and then release causes some kind of conflict.

**Comment by xander-jones** [comment]
@cristianoccazinsp; to confirm, are you cleaning between every build in dev & release in order to resolve this? Or has one clean since upgrading to v7.5.5 fixed this issue for you? I can't say I've seen this behaviour before, thanks for reporting this back to us though.

**Comment by fabriziobertoglio1987** [comment]
https://github.com/bugsnag/bugsnag-android/issues/899 https://github.com/bugsnag/bugsnag-android/issues/863
