### ISSUE TITLE
Update @bugsnag/plugin-vue docs for Vue.js 3

### ISSUE THREAD

**Issue by livthomas** [bugsnag/bugsnag-js#1054]
### Describe the bug
Vue.js 3 was released a few days ago and I'm trying to integrate Bugsnag into an application based on it. However, I'm not sure how to plug in `BugsnagPluginVue`. The documentation says that you can initialize the plugin this way:

```typescript
Bugsnag.getPlugin('vue').installVueErrorHandler(Vue);
```

However, Vue.js 3 no longer uses `Vue` constructor to initialize the application. Instead, it uses `createApp` function. There's also no contructor being exported from `vue` module.

So my question is: What is the right way to initialize `BugsnagPluginVue` in Vue.js 3 application? And can you update the documentation?

### Steps to reproduce
1. Create a new application using Vue.js 3
2. Try to integrate Bugsnag with `BugsnagPluginVue`
3. See there's no `Vue` constructor anymore

### Environment
* Bugsnag version: 7.3.5
* Browser framework version (if any):
    * Vue: 3.0.0

**Comment by mattdyoung** [comment]
Hi @livthomas 

We need to make some changes to the Bugsnag plugin to accommodate the breaking changes in Vue 3:
https://v3.vuejs.org/guide/migration/global-api.html#global-api

We'll be releasing a new version of bugsnag-js which supports Vue 3 soon as well as updating the installation docs.

**Comment by livthomas** [comment]
@mattdyoung I can see that a few minor versions of `bugsnag-js` have been released since I reported this issue. But nothing related to Vue.js has been changed. There are only React Native updates. When can we except a new version of `bugsnag-js` which supports Vue.js 3?

**Comment by gerardnll** [comment]
Any update on this? Thanks

**Comment by mattdyoung** [comment]
This is very much on our radar and we're looking to address Vue 3 support in the near future. We'll need to consider how we maintain backwards compatibility with Vue 2 when we make the changes.

We have a number of competing priorities right now so it's likely to be a few weeks before this work gets underway.

**Comment by morr** [comment]
@mattdyoung please upgrade to vue3. We have paid account in Bugsnag and are going to upgrade our app to vue3, but bugsnag dependency is blocking upgrade.

**Comment by mattdyoung** [comment]
Hi @morr 
We've now started work on Vue 3 compatibility. It's a non-trivial change as we still need to maintain compatibility with Vue 2 as well.

We'll be sure to provide an update here once the implementation is finished and released.

**Comment by fabien7337** [comment]
+1 So there is no way to have Bugsnap with Vue 3?

**Comment by xander-jones** [comment]
The `bugsnag-js` library now supports Vue 3 as of https://github.com/bugsnag/bugsnag-js/releases/tag/v7.7.0. 

Check out the docs here: https://docs.bugsnag.com/platforms/javascript/vue/

**Comment by fabien7337** [comment]
Awesome!!! Thank you for your work. Congrats the team :)
