### ISSUE TITLE
Errors with Selenium Webdriver

### ISSUE THREAD

**Issue by mattimatti** [bugsnag/bugsnag-js#106]
Hello, 
FYI, i'm having issues with bugsnag and selenium WebDriver.
Webdriver cannot find elements.

@see https://github.com/cobrateam/splinter/issues/376

**Comment by ConradIrwin** [comment]
Hey @mattimatti, it looks like the conclusion on that bug report is that it's a selenium problem?

Happy to look into it if there's a reproducible problem caused by Bugsnag.

**Comment by jamiekyle-eb** [comment]
This error seems to have come back in `6.3.2`:

```
WebDriverException: Message: Permission denied to access property "handleEvent"
```

`handleEvent` was re-introduced by https://github.com/bugsnag/bugsnag-js/commit/f954d63e2d7ccd93fb1158be01ba9dd3c54eec00 cc @bengourley

**Comment by mattdyoung** [comment]
It looks like we previously worked around this issue in Bugsnag by wrapping `handleEvent` access in a try-catch.

We'll look at applying something similar against the new usage.

**Comment by abigail-bugsnag** [comment]
@jamiekyle-eb This has now been released in the latest version of bugsnag-js: https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.0
