### ISSUE TITLE
Doesn't work on firefox

### ISSUE THREAD

**Issue by edi9999** [bugsnag/bugsnag-js#109]
seems that I get Busgnag undefined with the latest version of firefox (37.0.2)

**Comment by ConradIrwin** [comment]
Hi @edi9999, Are you using AdBlock?

**Comment by edi9999** [comment]
Yes, does it have an impact ?

**Comment by ConradIrwin** [comment]
@edi9999, Unfortunately Bugsnag is on the list of sites to block, see #96 for more details.

You can fix this by hosting bugsnag-2.js on your own server under a different name, or by disabling AdBlock.

Please let me know how you get on,

Conrad
