### ISSUE TITLE
CodePush integration technically not possible with react-native package

### ISSUE THREAD

**Issue by spacesuitdiver** [bugsnag/bugsnag-js#1105]
### Describe the bug
The following block of code makes it impossible to update the JS layer appVersion which is required once the jsbundle is updated via CodePush. For us we need to stick to the standard js layer and native layer integrations separately as a workaround. It's probably worth considering removing this limitation but I need more investigation as to what the react-native package for this actually provides. Any input regarding why this limitation exists would be helpful.

https://github.com/bugsnag/bugsnag-js/blob/ad7ada1f726c65062f3599c00395721a1234eb22/packages/react-native/src/config.js#L102-L105

**Comment by johnkiely1** [comment]
Hi @spacesuitdiver.

Could you explain how you are versioning your releases in a bit more detail? 

The reason I ask is you can set the [codeBundleId](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#codebundleid) via the JS layer. The intention of this is that you update the codeBundleId when performing a codepush release and that's what's then used to uniquely identify that codepush release e.g. to apply the correct source maps.

**Comment by spacesuitdiver** [comment]
@johnkiely1 perfect timing, I was starting migrating back to the old react-native-bugsnag :D

You are right, I completely missed that as coming from legacy react-native I was able to just supply another appVersion. Let me give that a go.

**Comment by spacesuitdiver** [comment]
Seems like exactly what I need sorry for noise.
