### ISSUE TITLE
Unexpected end of input (from within bugsnag.js)

### ISSUE THREAD

**Issue by JacobMarshallPP** [bugsnag/bugsnag-js#111]
I'm scratching my head for this one. I can't seem to track the cause of this error.

![screen shot 2015-06-14 at 10 23 58 am](https://cloud.githubusercontent.com/assets/10407590/8146244/971031c0-1281-11e5-8bf1-3e9813969c07.png)

This user was using Chrome 28.0.1500 on Windows 7.

Any help is appreciated :smiley:

**Comment by eanakashima** [comment]
I did some investigating here, but I can't find a way to reproduce this with the v2 notifier. I wonder if this was someone console-hacking and editing the script in some way. I'm going to mark this as closed for now, but please comment if you can reproduce or see another example.

**Comment by jacobmarshall** [comment]
Cheers @eanakashima, yeah I don't think we've seen it since to be honest. If it was a major issue, I'm sure we would have seen it crop up again since 😛
