### ISSUE TITLE
Bugsnag.maxDepth (=[RECURSIVE])

### ISSUE THREAD

**Issue by Yappli** [bugsnag/bugsnag-js#113]
Hi,

I'd like to be able to set a variable ```maxDepth``` in the config.

I'am talking about this pice of code :
```javascript
if (depth >= 5) {
    return encodeURIComponent(prefix) + "=[RECURSIVE]";
}
```

Now we have the value ```5``` hardcoded. It's a little be short for me. I'd like 7.

Can we imagine use the syntax below ?

```javascript
Bugsnag.maxDepth = 7;
```

If yes, I can make the change and pull request.

**Comment by jessicard** [comment]
@Yappli Ah, that makes sense, and the syntax seems reasonable, probably something that would go into the config. It should default to 5 if not set, however. Thanks for bringing this up - I'd like to see a PR if you have time!

**Comment by Yappli** [comment]
OK, I plan to do a PR. Probably on august.

Thanks

**Comment by jacobmarshall** [comment]
@Yappli I actually have already made a PR for you #114.

**Comment by Yappli** [comment]
Wonderful. Thanks @jacobmarshall

**Comment by thomaslangston-mongodb** [comment]
This maxDepth config option isn't defined in https://docs.bugsnag.com/platforms/javascript/configuration-options/. Has it been removed?

**Comment by bengourley** [comment]
It is removed. The logic that determines the max depth is now encapsulated in this module: https://github.com/bugsnag/safe-json-stringify

**Comment by thomaslangston-mongodb** [comment]
Thanks!
