### ISSUE TITLE
[react-native][iOS] Whole App is re-rendered when Style Inspector is opened or closed.

### ISSUE THREAD

**Issue by alimek** [bugsnag/bugsnag-js#1142]
### Describe the bug

I found that I am not able to inspect my styles in ReactNative project, because of bugsnag.
Every time when I am opening Style Inspector my whole app gets re-render and I am losing my screen stack.

### Environment
* Bugsnag version: "@bugsnag/react-native": "^7.5.2",
* Browser framework version (if any):
    * ReactNative: 0.63.3
* Device (e.g. iphonex): iPhone Simulator

### Example code snippet 

```
Bugsnag.start({
    codeBundleId: packageJson.version,
    plugins: [new BugsnagPluginReactNavigation()],
});

const App = () => {
 console.log('Render');

 return (
    <DefaultProvider>
      <AppContainer />
    </DefaultProvider>
 );
};
```

When I comment `Bugsnag.start()` i can inspect all my styles on all screens normally and i have just one `Render` log, otherwise when Opening and Closing Inspector, I have them 3 times -> 1st - Start App, 2nd - Open Inspector, 3rd - Close inspector.

I havent checked how its working on Android at the moment.
</details>

**Comment by mattdyoung** [comment]
Hi @alimek 

I've tried adding `console.log('Render');` in our [example app](https://github.com/bugsnag/bugsnag-js/tree/next/examples/reactnative/rn063example), and like you can see `Render` being logged when I open or close the inspector.

But I also see exactly the same behavior when I remove the call to `Bugsnag.start`. And in both cases the style inspector works correctly.

Is this definitely related to Bugsnag? Can you share any more details or how to reproduce and what the impact is?

**Comment by alimek** [comment]
Thanks @mattdyoung for reply.

I tried to find if something else may affect this, but coulnt find anything and i finished that i am not calling any bugsnag function when doing development using `if (!__DEV__)` statement - its only executed in release bundle, which fixed problem for me.

What is different as I remember, console.log with Render was not called twice after removing calling `.start()`.

I will try to reproduce this on fresh repo and will come back with update. Hopefully over the weekend or next week.

**Comment by xander-jones** [comment]
Hi @alimek, did you have any joy in reproducing this issue?

**Comment by xander-jones** [comment]
Closing this out as the issue as it's gone stale, but please do add further if this is found to be reproducible and we'll reopen the issue.
