### ISSUE TITLE
Bugsnag  pollutes window when being included via commonjs/webpack/browserify

### ISSUE THREAD

**Issue by nelix** [bugsnag/bugsnag-js#115]
```
import Bugsnag from 'bugsnag-js';
console.log(window.Bugsnag, ':(');
```

I'm working on some third party js, and if possible I'd rather not touch the window object at all, tried to use webpack to provide another window object, but it broke lots of things :p

**Comment by jessicard** [comment]
Hey @nelix! Bugsnag actually has a [noConflict function](https://bugsnag.com/docs/notifiers/js#noconflict-support) for removing itself from the window object and restoring the previous binding. The object returned from noConflict() is the full Bugsnag object so can be used in the same way:

```js
var myBugsnag = Bugsnag.noConflict();
// window.Bugsnag is now bound to what it was before the bugsnag script was loaded.
myBugsnag.apiKey = "my-special-api-key";
try {
  // highly volatile code
} catch (e) {
  myBugsnag.notifyException(e, "OhNoes");
}
```

**Comment by nelix** [comment]
Yeah, I know. But it leaves an empty object on window.Bugsnag. It would be nice if it did not touch window at all

**Comment by jacobmarshall** [comment]
If it is a strict requirement, you could of course modify the source yourself. I know it's not ideal, but if you want what you're asking for, it's likely to be the best solution.

**Comment by eanakashima** [comment]
@nelix thanks for the report. We'll get @jacobmarshall's fix out in the next release.
