### ISSUE TITLE
Error while launching the app although I have started the Bugsnag in appDelegate.m

### ISSUE THREAD

**Issue by radhakrishnant2s** [bugsnag/bugsnag-js#1170]
<img width="464" alt="Screenshot 2020-12-03 at 5 16 54 PM" src="https://user-images.githubusercontent.com/30921040/101014287-a632b780-358b-11eb-9fb0-6d9b25f91ddd.png">

I am invoking the Bugsnag in Js file like below:

setTimeout(()=> {
    Bugsnag.start();
}, 1000);

This is done because the app never launches when timeout is not provided

**Comment by mattdyoung** [comment]
Hi @radhakrishnant2s 

Have you followed the full instructions here:
https://docs.bugsnag.com/platforms/react-native/react-native/
including the iOS configuration:
https://docs.bugsnag.com/platforms/react-native/react-native/#ios

If you're still having issues can you write in to support@bugsnag.com and share the full details of what changes you've made to configure Bugsnag in your app?

**Comment by radhakrishnant2s** [comment]
Yes. I followed all the instructions. I was able to set up it in a separate project which I created but not in my project where I want to integrate.

**Comment by mattdyoung** [comment]
Closing as we haven't had a response and would require further information to investigate.
