### ISSUE TITLE
Bugsnag.noConflict() did not work corectly

### ISSUE THREAD

**Issue by qoomon** [bugsnag/bugsnag-js#118]
Hi there, i have a very strange problem with Bugsnag.noConflict() even so i do so i still get error notifications from the host site

**Comment by jacobmarshall** [comment]
`Bugsnag.noConflict()` only removes the `Bugsnag` object from the `window`, it does not stop Bugsnag from doing it's thing. I'm not sure I understand the issue, care to attach a stacktrace, code snippet or screenshot?

**Comment by qoomon** [comment]
Sorry i forgot t to say that i've set autoNotify to false
 var BugsnagNoConflict = Bugsnag.noConflict();
            BugsnagNoConflict.apiKey = "Key_Key_Key";
            BugsnagNoConflict.appVersion = "1.0.1";
            BugsnagNoConflict.releaseStage = "Production";
            BugsnagNoConflict.autoNotify = false;

but i still get notification from other scripts
