### ISSUE TITLE
plugin-koa: body not showing up in request tab

### ISSUE THREAD

**Issue by frankyjuang** [bugsnag/bugsnag-js#1183]
Same as https://github.com/bugsnag/bugsnag-js/issues/620 but for plugin-koa

Looks like what was fixed in https://github.com/bugsnag/bugsnag-js/pull/872 still exists in plugin-koa

https://github.com/bugsnag/bugsnag-js/blob/55443da3eeed541adb585cc33d78e738e3d8aef9/packages/plugin-koa/src/koa.js#L24-L28

**Comment by johnkiely1** [comment]
Hi @frankyjuang,

Thanks for reporting this, and creating the linked PR. We will look into reviewing this when we can.

**Comment by xander-jones** [comment]
Hi @frankyjuang, this has been fixed in https://github.com/bugsnag/bugsnag-js/releases/tag/v7.9.0
