### ISSUE TITLE
Notifying Technique Not Allowed in Chrome Apps

### ISSUE THREAD

**Issue by jprokop-va** [bugsnag/bugsnag-js#119]
Hello,

I am trying to use Bugsnag for monitoring of a chrome app,  but the notifying technique of using an Image object does not work in chrome apps because chrome apps restrict Image src to the app's resources (https://developer.chrome.com/apps/contentSecurityPolicy#what).
```
Refused to load the image 'https://notify.bugsnag.com/js?... because it violates
the following Content Security Policy directive: 
"img-src 'self' blob: filesystem: data: chrome-extension-resource:".
```
Bugsnag also seems to ignore the bugs from chrome apps for the same reason it ignores chrome extension bugs as in issue #94, but the same workaround applies.

Would Bugsnag consider accommodating this use case? I am currently working around this by modifying the library to report using the `fetch` api when a `useFetch` setting is true.

**Comment by eanakashima** [comment]
@jprokop-va thanks for opening this. #124 should handle this case for now, although I like the idea of supporting the Fetch API (and maybe even Beacon) in the future. :sparkles:
