### ISSUE TITLE
beforeSend does not exist on Config type

### ISSUE THREAD

**Issue by isaachinman** [bugsnag/bugsnag-js#1193]
### Describe the bug

The `beforeSend` function does not exist on the `Config` type. Specifically, I want to pass `beforeSend` into `Bugsnag.start`.

**Comment by mattdyoung** [comment]
Hi @isaachinman 

Which version of bugsnag-js are you using? The `beforeSend` callback was renamed `onError` in [v7.0.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.0.0). This can be passed into `Bugsnag.start` as shown here:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#onerror

Please see the upgrade guide for information on the other changes in v7.0.0:
[UPGRADING.md#6x-to-7x](https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md#6x-to-7x)

**Comment by isaachinman** [comment]
Hey @mattdyoung, we are indeed on `@bugsnag/js v7.5.3`

I was following [these docs](https://help.fullstory.com/hc/en-us/articles/360020827233-Bugsnag) to link FullStory. My implementation looked as such:

```
beforeSend: (report) => {
  if (window?.FS?.getCurrentSessionURL) {
    report.updateMetaData('fullstory', {
      urlAtTime: window.FS.getCurrentSessionURL(true),
    })
  }
},
```

Do you have a link to updated docs on how to achieve this?

**Comment by mattdyoung** [comment]
Aha - I see!

Those Fullstory docs aren't owned by Bugsnag and are out of date. They only provide instructions for v3 and v4 of bugsnag-js.

For the latest v7 the equivalent syntax would be:
```
Bugsnag.start({
  apiKey: 'YOUR_API_KEY',
  onError: function (event) {
    // Make sure FullStory object exists.
    if (window.FS && window.FS.getCurrentSessionURL) {
      event.addMetadata('fullstory', {
        urlAtTime: window.FS.getCurrentSessionURL(true)
      })
    }
  }
})
```

**Comment by isaachinman** [comment]
Great, thanks for that. I suggest you contact Fullstory and have them
update their docs.

**Comment by djwhatley-fs** [comment]
Hey, Daniel from FS here. We're in the process now of getting this updated, and we have an update coming to our integration soon to formally support v7. Thanks for the code snippet @mattdyoung! I was literally like 5 minutes away from putting that together for our support team when this came through my inbox. Impeccable timing!
