### ISSUE TITLE
@bugsnag/plugin-react@7.5.3" has unmet peer dependency "@bugsnag/core@^7.0.0

### ISSUE THREAD

**Issue by greggb** [bugsnag/bugsnag-js#1206]
### Describe the bug
When installing Bugsnag with the React plugin following the install instructions a peerDependency warning is show during `yarn install`. 

While it *is* listed as a peerDependency in [`package.json`](https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-react/package.json) the @bugsnag/core package actually says that it's not likely something a user would want to install and the instruction in the React plugin README do not mention it.

Seems like an incorrect PeerDependency, or READMEs need to be updated?

### Steps to reproduce
1. Go to https://github.com/bugsnag/bugsnag-js/tree/next/packages/plugin-react#installation
2. Add bugsnag to project with `yarn add @bugsnag/js @bugsnag/plugin-react` per install instructions
3. PeerDep warning will display `warning " > @bugsnag/plugin-react@7.5.3" has unmet peer dependency "@bugsnag/core@^7.0.0".`

### Environment
* Bugsnag version: 7.5.3
* Browser framework version (if any):
    * React: 16.13.1

**Comment by yousif-bugsnag** [comment]
Hi @greggb,

Thanks for the report. We're aware of this and think that the best route forward is to mark the peer dependency as optional for yarn. We don't have a firm timeframe for when this will be scheduled yet, but it's on our backlog.

**Comment by greggb** [comment]
Thanks for the update Yousif

**Comment by johnkiely1** [comment]
Hi @himynameisdave, this is still on our backlog, and we do plan on working on it soon. I don't have an exact timeframe to give you but we will post here with updates.

**Comment by luke-belton** [comment]
We've just released [`v7.16.5`](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.16.5) of `bugsnag-js` which [marks `@bugsnag/core` as an optional peer dependency](https://github.com/bugsnag/bugsnag-js/pull/1735/files)  to avoid the warnings described above 🎉
