### ISSUE TITLE
The cloudfront version should support vary accept encoding

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-js#121]
https://gtmetrix.com/specify-a-vary-accept-encoding-header.html

**Comment by mtchavez** [comment]
Doesn't look like this is supported by S3 origin behind CloudFront, [see support thread][1] and [the docs][2]. We would have to host non-compressed versions of the assets in S3 or use a custom-origin, one which allows this header, to serve from CloudFront.

[1]: https://forums.aws.amazon.com/thread.jspa?threadID=48276
[2]: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorS3Origin.html

**Comment by eanakashima** [comment]
For now, to support clients with no gzip, we could recommend self-hosting the script and/or bundling it in with your other JS files. @snmaynard does that seem like an OK workaround? Or do you think it makes sense to also push a version to s3 with compression off?

**Comment by snmaynard** [comment]
We can support this with https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/ @gkze might be able to help

**Comment by gkze** [comment]
Happy to help out! What do we need @snmaynard, a CloudFront-fronted S3 bucket with the final artifact in there?

**Comment by bengourley** [comment]
Hey @gkze, did this ever get set up?

**Comment by donaldboulton** [comment]
The above link, [https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/] (https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/) helps set up Cloud Front but the Accept encoding heder must be set up on you site or CMS as stated in Serving Compressed Files [http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html),
which cannot be done on a shared server situation without full control of IIS or Apache.
Is there a work around for shared servers?

**Comment by bengourley** [comment]
Hi @donaldboulton is there a particular problem that you're having? If you're having trouble serving Bugsnag from your own server, feel free to open up a different issue to see if we can help, as that would be unrelated to this ticket. This conversation/issue relates to the CDN version we distribute, so as a consumer of bugsnag-js in this way you don't need to do any server configuration. Thanks!

**Comment by bengourley** [comment]
This is fixed:

```
Development/bugsnag-js - [master] » curl -I https://d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.min.js
HTTP/1.1 200 OK
Content-Type: application/javascript; charset=UTF-8
Content-Length: 31712
Connection: keep-alive
Date: Mon, 04 Dec 2017 18:34:31 GMT
Last-Modified: Mon, 04 Dec 2017 18:02:27 GMT
ETag: "18778d32bec5b77581465168cd7a2074"
Cache-Control: public, max-age=315360000
Accept-Ranges: bytes
Server: AmazonS3
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 838e90f138fb32ccb28a128273765f44.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 6vld51j7n0kPdOn-lZ3-MV9DbbAHslGhFihpEhrvKZ0PJfMiQE7KPw==
```
