### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-js#122]
It would be a great feature if you could deliver typescript definitions for the JS bindings.

https://github.com/borisyankov/DefinitelyTyped

**Comment by rolandoldengarm** [comment]
+1

**Comment by jacobmarshall** [comment]
Looks like it's being worked on atm by @kattrali in the [`kattrali/typescript-defs`](https://github.com/bugsnag/bugsnag-js/tree/kattrali/typescript-defs) branch :+1:

**Comment by snmaynard** [comment]
Nothing gets past you @jacobmarshall :D

**Comment by jacobmarshall** [comment]
:eyes:

**Comment by jacobmarshall** [comment]
Thanks @kattrali, this is awesome :+1:
