### ISSUE TITLE
Support different notify (request) handlers (for CSP, Chrome extensions, etc)

### ISSUE THREAD

**Issue by jacobmarshall** [bugsnag/bugsnag-js#123]
The idea allows the developer to specify how they want their error events sent to Bugsnag. This way, projects with tight CSP restrictions (ie. Chrome extensions) can utilise Bugsnag by opting into XHR instead of temporary `Image` objects.

There would be two built in handlers, `image` and `xhr` (defaulting to `image`) - and they would be specified as strings with either `data-notifyhandler="xhr"` or `Bugsnag.notifyHandler = "xhr"`. Optionally the user could specify a `Function` which allows them to do whatever the please with the payload - this has another little benefit as we could remove the `testRequest` code.

```js
Bugsnag.notifyHandler = 'xhr';
```

```js
/**
 * @param {String} url A fully constructed URL to the /js endpoint (with params)
 * @param {String} endpoint The configured endpoint
 * @param {Object} payload The error payload
 */
Bugsnag.notifyHandler = function fetchNotifyHandler(url, endpoint, payload) {
    // An example of using the Fetch API to send the error
    window.fetch(url);
};
```

One thing to note - right now the https://notify.bugsnag.com/js endpoint does not include a `Access-Control-Allow-Origin` header - which causes browsers to scream, yet the actual request works perfectly. Bugsnag gets notified of the event, and as far as I can tell, the whole process works as usual.

I'm making this issue before I submit the PR, just to get some feedback - what do you think?

cc @ConradIrwin @jprokop-va @KaoruDev @thomchop @H2go #119 #94

**Comment by KaoruDev** [comment]
i don't know the lib well enough but if you're telling me that this will work in chrome extensiosn so long as I configure `notifyHandler` to use `'xhr'` then I :heart: it thx!

**Comment by jprokop-va** [comment]
That looks like a nice and tidy solution -- I'm curious what the use case would be for the custom function, though.

**Comment by tnokovski** [comment]
I had to fix this for a chrome app, so I decided to share the solution with a Pull Request.

**Comment by jacobmarshall** [comment]
Awesome. Sorry, I've been pretty busy, haven't had a chance to think about my PR, so thank you for submitting yours.

The other part that doesn't seem to be required (but would be good to have) is the `Access-Control-Allow-Origin` header set - just to prevent the console spam.

Firstly @ConradIrwin and @snmaynard, is this functionality something you intend to support (PR and headers)?

**Comment by tnokovski** [comment]
The console spam can be prevented with providing the URL in the "permissions" array in manifest.json in the Chrome app: `{ "permissions": [ "https://notify.bugsnag.com/*" ] }` or if you already use `"<all_urls>"` there it will just work without the `Access-Control-Allow-Origin` set server side. So the header is not really required to stop the console spam since this can be configured on client side.

**Comment by jacobmarshall** [comment]
That's great @tnokovski - I was not aware of that. I wonder if it is still worth noting, in case people (for whatever reason) want to opt-in to xhr (and aren't using the library within a Chrome extension). Edge case I know, however it *may* be a requirement for people with strict CSP policies to meet.

**Comment by eanakashima** [comment]
Thanks for opening this, @jacobmarshall, and thanks @tnokovski for #124. I've deployed a change to the `notify.bugsnag.com/js` endpoint to set `Access-Control-Allow-Origin: *`, so with that and #124 I think we are good to call this fixed.

**Comment by jacobmarshall** [comment]
Cheers @eanakashima :smiley: - much appreciated!
