### ISSUE TITLE
iOS archiving fail with version 7.5.6 (duplicate symbols)

### ISSUE THREAD

**Issue by asaf-demetria** [bugsnag/bugsnag-js#1239]
### Describe the bug
Archiving an iOS (react-native) app with Xcode 12.3 results in a failure, due to duplicate symbols for architecture arm64.

### Steps to reproduce
1. Create a new RN app with native platform `iOS`.
2. Add Bugsnag as a depndency => `"@bugsnag/react-native": "7.5.6"`
3. Archive on Xcode 12.3 (didn't try on earlier versions of Xcode)

==> Archive fails (same reproduction with 7.5.5 works).

### Environment
* Bugsnag version: 7.5.6
* Device: iOS

### Example Repo

- [x] Create a minimal repository that can reproduce the issue
- [x] Link to it here: https://github.com/asaf-demetria/bugsnag-error-report

### Error Message
```
❌  duplicate symbol '_bsg_mach_headers_image_at_base_of_image_index' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_image_at_address' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_register_for_changes' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_get_images' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_first_cmd_after_header' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_populate_info' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_initialize' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_remove_image' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_add_image' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  duplicate symbol '_bsg_mach_headers_image_named' in
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbeff8aafe81fd298218c6466b22939ecceb.o
> BSG_KSMachHeaders-7f14412fb1c74761627544d2af69fbefe877cd236e32a08d7d810cb7f317bad4.o
❌  ld: 10 duplicate symbols for architecture arm64
```

**Comment by mattdyoung** [comment]
Hi @asaf-demetria 

I've tried cloning your [example project](https://github.com/asaf-demetria/bugsnag-error-report) but if I run `npm install` and `pod install` on that and then Archive in Xcode, I'm instead seeing an issue with React/RCTBridgeDelegate.h file not found in the AppDelgate.h. I think there's something not quite right in the React Native build system on that project.

I've tried creating a completely clean React Native project on those versions:
- `npx react-native init MyProject --version 0.63.4`
- `cd MyProject && npm install --save @bugsnag/react-native@7.5.6`
- `cd ios && pod install`
- Configure Bugsnag for iOS as described [here](https://docs.bugsnag.com/platforms/react-native/react-native/#basic-configuration)
- Open in Xcode 12.3 and Archive

For me that works without issue. Is there anything different about the way you're creating your React Native project?

**Comment by asaf-demetria** [comment]
Hi @mattdyoung,

Thanks for getting back to me so quickly. I just want to say that this issue is not a blocker for us, as we were able to archive and send a version to AppStore using version 7.5.5.

Regarding your comments:
> I think there's something not quite right in the React Native build system on that project.

Can you try again but first deleting the `Podfile.lock` file? It was committed by mistake. To be sure you don't have any cached content due to this file, I would clean `Pods` cache completely, using the following command (from your RN project root):

`cd ios && rm -rf "${HOME}/Library/Caches/CocoaPods" && rm -rf Pods && rm Podfile.lock && pod update`

> Is there anything different about the way you're creating your React Native project?

I did the same, except from the `init` command. This is what I run:

`npx react-native init BugsnagErrorReport --template react-native-template-typescript`

Also, maybe it's worth mentioning, that this issue happened to me both on my local machine and during my CI/CD process, using [Bitrise cloud](https://www.bitrise.io/).

**Comment by yousif-bugsnag** [comment]
Hi @asaf-demetria,

I've tried reproducing using your example project by first deleting the `Podfile.lock` and clearing the `Pods` cache as suggested but am running into the same build issue regarding the `React/RCTBridgeDelegate.h` file.

I've also tried recreating using a clean react native project but this time using the typescript template you mentioned, and was able to archive without any issue:

- `npx react-native init MyProject --version 0.63.4 --template react-native-template-typescript`
- `cd MyProject && npm install --save @bugsnag/react-native@7.5.6`
- `cd ios && pod install`
- Configure Bugsnag for iOS as described here
- Open in Xcode 12.3 and Archive

Can you think of any other differences in your environment that may explain this?

**Comment by asaf-demetria** [comment]
Unfortunately, I don't have any other idea of why there are such differences. I'll try to release another version of my app with `7.5.6` and will let you guys know. 

Anyway, seems like I'm the only one suffering from this issue, so I suggest you close it and I'll re-open it if I'll have some news about it.

**Comment by yousif-bugsnag** [comment]
Thanks @asaf-demetria. I will close this out for now, let us know if you find any more info and we can re-open.
