### ISSUE TITLE
Bugsnag latest versions broke Fullstory compatibility to record Fetch requests

### ISSUE THREAD

**Issue by laukstein** [bugsnag/bugsnag-js#1257]
Bugsnag is the official Fullstory integration published in https://help.fullstory.com/hc/en-us/articles/360020827233-Bugsnag

I reported the issue details to Fullstory for investigation and here is the conclusions:
After December 6th 2020 Fullstory is no longer able to record Fetch requests when using Bugsnag https://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js (without Bugsnag all works fine). Can reproduce it when used both Bugsnag + Fullstory and **after fetch request success the page is automatically refreshed**. Fullstory uses navigator.sendBeacon() to report recent data of page unload, maybe Bugsnag broke sendBeacon and not Fetch.

As we can see here both, Bugsnag and Fullstory, are overriding native Fetch API

Bugsnag network-breadcrumbs.js 
![image](https://user-images.githubusercontent.com/183966/105413003-272e3700-5c3e-11eb-8237-53d13cf79534.png)
![image](https://user-images.githubusercontent.com/183966/105413088-475df600-5c3e-11eb-9e94-765a10b6666d.png)

Fullstory
![image](https://user-images.githubusercontent.com/183966/105413036-3319f900-5c3e-11eb-8f30-d0e9270a9c63.png)

Maybe the best would be if Bugsnag directly together with Fullstory would investigate and solve this issue.

BTW why Bugsnag needs to overriding Fetch API, and can I prevent Bugsnag doing it?

**Comment by mattdyoung** [comment]
Hi @laukstein 

Bugsnag is overriding the fetch API to capture breadcrumbs on error reports for network requests leading up to the error.

You can disable network request breadcrumbs via the `enabledBreadcrumbTypes` config option:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#enabledbreadcrumbtypes

By default all breadcrumb types are enabled:
```
Bugsnag.start({ 
  enabledBreadcrumbTypes: ['error', 'log', , 'navigation', 'request', 'user']
})
```

You can disable the network request breadcrumbs like this:
```
Bugsnag.start({ 
  enabledBreadcrumbTypes: ['error', 'log', , 'navigation', 'user']
})
```

Can you confirm if that configuration change resolves the issue?

**Comment by laukstein** [comment]
Just experienced this error (likely related to this) 
![grabilla em2908](https://user-images.githubusercontent.com/183966/108025192-ba387200-702e-11eb-8313-548af0f36d61.png)

I added now to my configuration `enabledBreadcrumbTypes: ["error", "log"]` , will see if it makes change. Anyway this is a bug and conflict with Fullstory fetch.

**Comment by yousif-bugsnag** [comment]
Hey @laukstein - as discussed in the support ticket you raised, `Failed to fetch` is a genuine failure from `fetch()`, but because we are monkey-patching the `fetch()` method it appears as though it's originating from our code.

Has disabling network request breadcrumbs resolved the original issue for you?

**Comment by laukstein** [comment]
Since I disabled the network request breadcrumbs I have no longer experiencing this issue. Anyway this doesn't make Fullstory + Bugsnag integration stabile.

**Comment by yousif-bugsnag** [comment]
Hi @laukstein,

I haven't been able to reproduce this. I integrated Fullstory with the [Bugsnag CDN example app](https://github.com/bugsnag/bugsnag-js/tree/next/examples/js/browser-cdn) and a successful fetch request did not trigger a page reload, even with network request breadcrumbs enabled.

Are you able to provide a simple reproduction case that demonstrates the issue you're seeing?

**Comment by laukstein** [comment]
Here is my Bugsnag setup. As you can see I use also Fullstory.

    Bugsnag.start({
        apiKey: "...",
        autoTrackSessions: false,
        collectUserIp: false,
        onError: function (event) {
            if (event && window.FS && typeof FS.getCurrentSessionURL === "function") {
                var urlAtTime = FS.getCurrentSessionURL(true);

                if (urlAtTime) {
                    event.addMetadata("fullstory", {
                        urlAtTime: urlAtTime
                    });
                }
            }
        }
    });

**Comment by yousif-bugsnag** [comment]
Hi @laukstein, I'm afraid I'm still not able to reproduce this with that configuration. If you are able to provide a full reproduction case that demonstrates the issue we'd be happy to investigate further.
