### ISSUE TITLE
Skip environments

### ISSUE THREAD

**Issue by simkessy** [bugsnag/bugsnag-js#1258]
How do i skip tracking errors in Development?

**Comment by xander-jones** [comment]
Hey @simkessy, the option you're looking for is [enabledReleaseStages](https://docs.bugsnag.com/platforms/javascript/configuration-options/#enabledreleasestages). In conjunction with setting your `releaseStage`, you can now skip tracking errors in development environment.

If you have any further questions, drop us a message at support@bugsnag.com
