### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by chriskjaer** [bugsnag/bugsnag-js#126]
Is there any plan on releasing the latest code to npm?

I see the following additions since the last release:
- Feature: maxDepth - commit da20a486eb5b6976ce27f6792a87b6ec543f8334
- Bugfix: fix null exception - commit 4e93acfd378e391ae2be23252894d0c2c37ca051

**Comment by jacobmarshall** [comment]
:+1:

**Comment by kattrali** [comment]
Yep, planning on releasing master later today, should be regularly on Tuesdays from then on.

**Comment by jacobmarshall** [comment]
Ooh thanks @kattrali, good to know.

**Comment by kattrali** [comment]
Closing for PR #127.
