### ISSUE TITLE
releaseStage not change [react-native]

### ISSUE THREAD

**Issue by idanlevi1** [bugsnag/bugsnag-js#1263]
I try to configure the Bugsnag with different releaseStage for each environment and it's don't change (always report with develipment)

`Bugsnag.start({ releaseStage: 'staging' })`

![image](https://user-images.githubusercontent.com/21155847/105691828-642c4f00-5f06-11eb-9adb-aca994578c7e.png)

same in Android and Ios

> @bugsnag/react-native 7.6.0v
> react-native 61.5v

**Comment by xander-jones** [comment]
Hey @idanlevi1, in `@bugsnag/react-native`, it'll use the native configuration always. This is the design intent, to ensure that the configuration is set as early as possible so native errors get caught with the correct configuration including `releaseStage`. Please do let us know if this behaviour is different from that which I've described here.

It is possible to set these values at build time, as discussed in the reply here: https://github.com/bugsnag/bugsnag-js/issues/1264#issuecomment-767191963
