### ISSUE TITLE
How to define apiKey in real time? [react-native]

### ISSUE THREAD

**Issue by idanlevi1** [bugsnag/bugsnag-js#1264]
I work with react-native, and i want to allow the `apiKey` to be dynamic (by env file)
in the last package of Bugsnag for react native it was easy, but now in the new package (@bugsnag/react-native) we need to put the `apiKey` in operation system of android and ios

i want to do it like this way:
`Bugsnag.start({ apiKey: Config.BUGSNAG_API_KEY })`

how i can do it? this code not working...

*same in Android and Ios

> @bugsnag/react-native 7.6.0v
> react-native 61.5v

**Comment by xander-jones** [comment]
Hey @idanlevi1, believe we spoke via email too, but just to reiterate here for future travellers. Setting these values in the JS layer is no longer a supported method for a React Native application. Our recommendation in terms of best practice is to set both the `releaseStage` and the `apiKey` in the `AndroidManifest.xml` and `Info.plist`, which our SDK will automatically read when you call `Bugsnag.start()`.

This ensures 100% that for all types of errors and crashes whether in Javascript or native Android / iOS code, the correct configuration is used. If you wanted to set these values at build time, this is possible for both Android and iOS builds:

#### For `Info.plist`

Using a build phase script in your Xcode build, use a tool like `PlistBuddy` (run `$ /usr/libexec/PlistBuddy -h` for help) to modify the `Info.plist` values as you need.

#### For `AndroidManifest.xml` 

Using a manifest placeholder in your `AndroidManifest.xml`

```xml
<meta-data android:name="com.bugsnag.android.RELEASE_STAGE"
    android:value="${placeholderReleaseStage}"/>
```

and then assigning a value to that placeholder using in your `build.gradle`

```gradle
android {
    defaultConfig {
        manifestPlaceholders = [placeholderReleaseStage:"production"]
    }
}
```

which could scrape this data from wherever your data is stored.
