### ISSUE TITLE
Bugsnag CLI Issue

### ISSUE THREAD

**Issue by kp47** [bugsnag/bugsnag-js#1275]
### Describe the bug
I was trying to integrate bugsnag in my app and in the documentation it says cli is best way to setup things. However I didn't understand what values to insert for the questions and hence I ended up doing manual integration.

The issue is now I want to make android build but it keeps on giving me the following error:
> A problem was found with the configuration of task ':app:uploadBugsnagReleaseSourceMaps' (type 'BugsnagUploadJsSourceMapTaskGradle53Plus').
> File '.../node_modules/@bugsnag/source-maps/bin/cli' specified for property 'bugsnagSourceMaps' does not exist.

Please guide me to resolve this issue.

**Comment by mattdyoung** [comment]
Hi @kp47 

I think the issue may be that you haven't installed `@bugsnag/source-maps`.

We've just realised that our documentation for manual setup didn't make it clear that was required.

You can install as shown here:
https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#installation

We're also updating our documentation to make this clear.

Can you confirm whether installing the package resolves your issue?

**Comment by mattdyoung** [comment]
Closing for now, but if the above advice doesn't resolve the issue please provide further details and we'll take a look.
