### ISSUE TITLE
Publish as ES Modules

### ISSUE THREAD

**Issue by hansottowirtz** [bugsnag/bugsnag-js#1276]
I noticed that all packages are only published as CommonJS, not as ES Modules. Is it possible to also publish ES Modules so bundlers can take advantage of tree shaking? This would require adding a `"module"` field to all `package.json`, and probably splitting `dist` into `dist/cjs` and `dist/esm`.

I noticed this because Angular outputs this warning, which is harmless and can be disabled but might still confuse some users:
```
Warning: <project>/src/app/app.module.ts depends on '@bugsnag/js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

I can make a PR if needed.

**Comment by mattdyoung** [comment]
Hi @hansottowirtz 

Thanks for your thoughts. This is something we've considered in the past and which is discussed in detail on this issue:
https://github.com/bugsnag/bugsnag-js/issues/463#issuecomment-454693484

Essentially though, nothing is included in the bundle which isn't used so there is no benefit to tree shaking as nothing would be removed.

We therefore have no plans to move to using ES modules.

**Comment by aseem2625** [comment]
We are using serverless deno functions via supabase. And since bugsnag doesn't have esm, we cannot use it :|

**Comment by aseem2625** [comment]
@mattdyoung 
We are using serverless deno functions via supabase. And since bugsnag doesn't have esm, we cannot use it :|

**Comment by micahjon** [comment]
@mattdyoung , just wanted to second @aseem2625 's comment. I'm also using Supabase's Edge Functions, which use Deno's runtime. Having trouble getting Bugsnag to work in that enivironment. Any help would be appreciated!

FWIW, Deno also powers Netlify's Edge Functions, not just Supabase.
https://deno.com/deploy

**Comment by mclack** [comment]
Hi @micahjon 

We currently have an item on our backlog to publish the JavaScript notifier as an ES Module, and we also have a separate item to look into support for Deno.

I have relayed this information and made our Product Team aware of this thread for consideration. I unfortunately can't give any ETA as to when this may be looked into, but we will make sure to post any relevant updates on this thread.

**Comment by maysam** [comment]
Hi @aseem2625 @micahjon what did you end up using instead?

**Comment by micahjon** [comment]
> Hi @aseem2625 @micahjon what did you end up using instead?

I ended up just switching to Sentry.

**Comment by Gipetto** [comment]
Any progress on this? I'm pretty close to switching to Sentry to get this functionality.
Thanks!

**Comment by clr182** [comment]
Hi @Gipetto 

Unfortunately I do not have an update on this as of right now. Once we have more information to share we will be sure to update this thread
