### ISSUE TITLE
Using `@bugsnag/react-native` in monorepo

### ISSUE THREAD

**Issue by maxkomarychev** [bugsnag/bugsnag-js#1277]
This is not so much of a feature request but more to consult with maintainers how to fix a problem I faced trying to use it in monorepo environment. I don't mind opening PR (as long as we reach a conclusion soon and I'm still in the loop :) )

### Description

I am working on react-native app located inside learna managed monorepo. When I tried to upgrade to version 7 or bugsnag-js I started seeing lots of errors like https://github.com/bugsnag/bugsnag-js/issues/1255 :

```
   > Could not find com.bugsnag:bugsnag-android:5.5.1-react-native.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/bugsnag/bugsnag-android/5.5.1-react-native/bugsnag-android-5.5.1-react-native.pom
       - https://dl.google.com/dl/android/maven2/com/bugsnag/bugsnag-android/5.5.1-react-native/bugsnag-android-5.5.1-react-native.jar
       - https://maven.google.com/com/bugsnag/bugsnag-android/5.5.1-react-native/bugsnag-android-5.5.1-react-native.pom
       - https://maven.google.com/com/bugsnag/bugsnag-android/5.5.1-react-native/bugsnag-android-5.5.1-react-native.jar
       - .....
```

eventually after reading these lines https://github.com/bugsnag/bugsnag-js/blob/8e142100e20880500c1d374871b6b7871aec1db6/packages/react-native/android/build.gradle#L51-L67 I figured a plugin makes certain assumptions about paths in a project which were not true in case of a package under `packages/....` in a typical lerna monorepo.

I managed to fix these errors by adding 

```
    dependencies {
        maven {
            url "$rootDir/../../../node_modules/@bugsnag/react-native/android"
        }
    }
```

to my  `packages/app/android/build.gradle`

**Describe the solution you'd like**

I would like this project to be easier to use in monorepo environment.

**Describe alternatives you've considered**

I consider 2 options which are good enough for me:

1.  https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/android/build.gradle could be smarter about layout of directories (which I understand would be an assumption on it's own)
2. or simply add few lines into readme explaining how to fix these errors

**Additional context**

thanks

**Comment by xander-jones** [comment]
Hey @maxkomarychev, you're right, `@bugsnag/react-native` is designed to be used in a non-monorepo environment using the standard React Native environment.

It's something that we already have one our map to implement. We're open to PRs, however I can't guarantee a timeframe as there's a number of competing priorities. Since you have a functioning workaround for this at the moment, you can leave with us to look into.

**Comment by xander-jones** [comment]
As of https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v5.7.4 you can now specify where your `node_modules` directory is using the `nodeModulesDir` Gradle configuration option which will allow you to use `@bugsnag/react-native` in a monorepo.

Update your Bugsnag Android Gradle Plugin dependency to `v5.7.4`. Then, in your app's `build.gradle` file, add to your `bugsnag` config:
```gradle
bugsnag {
	// relative to the project directory
    nodeModulesDir = project.layout.projectDirectory.dir("../../../node_modules/").asFile
	// or using an absolute path
	nodeModulesDir = new File("/custom-path/node_modules")
	// ...
}
```
https://docs.bugsnag.com/build-integrations/gradle/#custom-node_modules-directory

**Comment by maxkomarychev** [comment]
@xander-jones thanks! I'll give it a shot.

**Comment by MohammadAzimi** [comment]
Hey @xander-jones 
Thanks for your responses
Where should I add this line of code?
```groovy
bugsnag {
	// relative to the project directory
    nodeModulesDir = project.layout.projectDirectory.dir("../../../node_modules/").asFile
	// or using an absolute path
	nodeModulesDir = new File("/custom-path/node_modules")
	// ...
}
```

**Comment by johnkiely1** [comment]
Hey @MohammadAzimi, 

This should be placed in your <project_dir>/<module_name>/build.gradle file. 

General information on how to install the plugin here:
https://docs.bugsnag.com/build-integrations/gradle/#installation

Additional configuration options: 
https://docs.bugsnag.com/build-integrations/gradle/#additional-configuration

**Comment by MohammadAzimi** [comment]
@johnkiely1 Thank you for your response
I know the file: **android/app/build.gradle** (please correct me if I'm doing it wrong) but where? under the android block? like this
```groovy
android {
      defaultConfig {
          applicationId "com.project"
          minSdkVersion rootProject.ext.minSdkVersion
          targetSdkVersion rootProject.ext.targetSdkVersion
          // ...
      }
      bugsnag {
	//bugsnag configs
	nodeModulesDir = new File("/custom-path/node_modules")
	// ...
      }
      splits {
      //...
      }
}
```
if yes when I add even and empty bugsnag block I get this error

A problem occurred evaluating project ':app'.
> Could not find method bugsnag() for arguments [build_5ogx1rilzl2l5f31funi4hhyr$_run_closure1$_closure7@959c06f] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

if I add it outside of android block I get the error below

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method bugsnag() for arguments [build_5ogx1rilzl2l5f31funi4hhyr$_run_closure3@2399b618] on project ':app' of type org.gradle.api.Project.

**Comment by johnkiely1** [comment]
Hi @MohammadAzimi, 

The `bugsnag { }` configuration should be in its own section outside of the `android` block. 

With regards the error you see if you do that,  have you added the line

`apply plugin: "com.bugsnag.android.gradle"` 

after

`apply from: "../../../node_modules/react-native/react.gradle"` within that file?
 
https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/#android

**Comment by MohammadAzimi** [comment]
Thanks @johnkiely1 
```groovy
apply plugin: "com.bugsnag.android.gradle"

after

apply from: "../../../node_modules/react-native/react.gradle"
```

It was my mistake
