### ISSUE TITLE
IE 10/11/Edge reports of NotFoundError

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-js#128]
We have had some reports of NotFoundError from IE10/11/Edge coming from the notifyException function. It could be coming from the findScript stuff potentially. Reported by a customer in [helpscout](https://secure.helpscout.net/conversation/159360373/10202)

**Comment by jacobmarshall** [comment]
I can't access the link cited. Do you have any more information about this report? We support IE10, IE11 and Edge - so it would be good to know whether we are effected.

I'd be happy to investigate this - but it would be nice to know some more info first, if any :+1:

**Comment by snmaynard** [comment]
Unfortunately thats pretty much all the info we have, the stacktrace just comes from notifyException and the error message is NotFoundError. The customer has minification enabled, with no sourcemaps so knowing the exact column is tricky too (im not sure that ie even tells us the column from memory)

**Comment by jacobmarshall** [comment]
Sweet thanks @snmaynard, I'll see what I can do.

Quick additional question, if you can: is the error replicable/reoccurring?

**Comment by snmaynard** [comment]
Its happening multiple times, but I dont know if it happens every time, all I have at the moment is the stacktrace and browser to go on really. I wonder whether the script tag is not retrievable for some reason - but its not really a great explanation. The error is only happening on these browsers.

**Comment by jacobmarshall** [comment]
Ok cool, thanks @snmaynard - I appreciate it.

**Comment by JacobMarshallPP** [comment]
Just as an update - I've been keeping my eye out for this issue, however in all this time I haven't once experienced/heard of it happen on any of our dev's local test environments or during any browser testing (in IE10-11, or Edge).

**Comment by eanakashima** [comment]
Thanks for keeping an eye out, Jacob. The instances of `NotFoundError` I've seen on our own projects have come from failed calls to DOM operations like `appendChild` and `removeChild`, which we don't do much of in bugsnag-js right now. I wonder if this is a false alarm from a wonky stacktrace, or maybe from code we don't have in the library anymore. Let's call this closed for now, and we can re-open if we hear more reports.
