### ISSUE TITLE
Callbacks of the event listeners getting duplicated by bugsnag library

### ISSUE THREAD

**Issue by Esteban26** [bugsnag/bugsnag-js#1287]
Hi we're facing some issues with bugsnag

Open this [URL](https://montedesign.com/products/modern-nursery-glider)

The website has been created with Shopify and according with the Shopify's feedback your **bugsnag.js** library is loaded on any page that renders a video.

When the page is loaded on a iPad with iOS 13 and Safari 13, try rotate the furniture by dragging horizontally the glider chair, the first time it rotates properly. 

Then change the features using the configuration panel of the right section  and try to rotate the furniture again, here is the error, sometimes it opens the zoom unexpectedly, even if you try to rotate it keeps opening the zoom and it is not the expected behavior.

(If you were not able to reproduce the issue please refresh the page and try again)

As a background, we listen for the touch events to detect if the user taps the screen to rotate the viewer or if the user double taps the screen to enter the zoom mode.

To achieve that, we create two event listeners for the **cylindo-viewer-container** element; one of them checks if the user rotates the viewer and the other one keeps listening if the user double taps the screen to open the zoom module. In the right panel of the below screenshot as you can see both functions "c" and "l" are set properly when a user enters the website the first time.

![unnamed-17](https://user-images.githubusercontent.com/1881501/107434038-c9c83000-6aef-11eb-8ba5-73f77749f94a.png)

Then, when features are changed, the library bugsnag.js changes our core and creates some wrapper functions that override our internal functions and it causes the error because one of our functions is duplicated. 

The duplicated function is the one that we use to open the zoom module when the user double taps the screen. Since both resultant functions are triggered when the user touches the screen once, our core understands that as a double tap and opens the zoom module. Please see the below screenshot, it shows the duplicated functions in the right panel and the function "c" has dissapeared.

![unnamed-18](https://user-images.githubusercontent.com/1881501/107434128-f11efd00-6aef-11eb-9d5a-02788ff9a122.png)

As you can see the functions were created within the file inline-script-content.js that file belongs to the bugsnag library and in that file there is the logic that is affecting the viewer. Actually I think you may already aware about the issue because you've have some comments saying that the resultant function mustn't be anonymous due to a bug in the stack generation logic and you pointed the code to an issue report.

![unnamed-19](https://user-images.githubusercontent.com/1881501/107434652-a5208800-6af0-11eb-8c2e-fafdfd022f9b.png)

So currently, the bugsnag library is hijacking the callbacks of the event listeners and for some reason is duplicating some of them, any idea why this is happening?

* Bugsnag version: It seems to be version 6
* Browser version: iOS 13, Safari 13:
* Device: iPad

**Comment by Esteban26** [comment]
Hi bugsnag team, any update on this ^ ?

**Comment by Esteban26** [comment]
Hi bugsnag team, do you have any updates on this issue?

**Comment by yousif-bugsnag** [comment]
Hi @Esteban26, we've been looking into this but haven't been able to reproduce the issue you're seeing. 

I did notice that the DOM structure for that page has changed slightly since you raised the issue - have you been able to get to the bottom of the problem?

For some additional context, the Bugsnag code you're referring to wraps every builtin place you can provide a callback so that we can trace it back in case an inline script caused it. The code comments here are referring to an issue where that particular function was being named incorrectly when generating a backtrace.

**Comment by mattdyoung** [comment]
@Esteban26 can you confirm if you're still seeing the issue and if so share a reliable way to reproduce?

**Comment by Esteban26** [comment]
Hi Matt, sorry for the late reply, I'll try to reproduce it by early next week and if I'm able I'll share with you some videos of the current behavior.

**Comment by mattdyoung** [comment]
@Esteban26 - were you able to reproduce? If so please share the full details and we can re-open this issue.
