### ISSUE TITLE
Bugsnag client cannot be created within a worker context

### ISSUE THREAD

**Issue by birtles** [bugsnag/bugsnag-js#1299]
This is related to #172 but more fundamental.

### Describe the bug
Despite the fact that [the docs suggest](https://docs.bugsnag.com/platforms/javascript/configuration-options/#apptype) that Bugsnag can be started in a Web worker context, attempting to call `Bugsnag.start` in a worker context produces a number of errors due to attempted references to things like `window` and `document` etc.

### Steps to reproduce
1. In a worker, attempt to call `Bugsnag.start`.

### Environment
* Bugsnag version: 7.7.0
* Browser framework version (if any): n/a
* Server framework version (if any): n/a
* Browser version (e.g. chrome, safari): Firefox, Safari
* Device (e.g. iphonex): Windows 10

<details><summary>Error messages:</summary>

```
 ReferenceError: window is not defined db-worker.07fc2ef68538318f7afb.js line 18 > eval:2233:5
    _$device_40 bugsnag.js:2233
    createClient bugsnag.js:3406
    start bugsnag.js:3428
    initializeBugsnag bugsnag.ts:12
    <匿名> worker.ts:3
    ts db-worker.07fc2ef68538318f7afb.js:93
    __webpack_require__ db-worker.07fc2ef68538318f7afb.js:237
    <匿名> db-worker.07fc2ef68538318f7afb.js:289
    <匿名> db-worker.07fc2ef68538318f7afb.js:291
```
</details>

Digging into the code, the error appears to arise from this line in `plugin-browser-device`:

https://github.com/bugsnag/bugsnag-js/blob/f72041588895a88bb21770838744234d4be3c1a2/packages/plugin-browser-device/device.js#L30

But if you fix that, you'll only move on to the next error.

I tried to work around this by defining a global `window` object, and `document` and all the various sub-properties that were queried (`window.location.host`, `document.documentElement.clientWidth`, `window.XMLHttpRequest` etc.) but it turned into a big game of whack-a-mole so I gave up.

For what it's worth, it looks like Rollbar had the same issue but fixed it a couple of years ago: https://github.com/rollbar/rollbar.js/pull/703

**Comment by xander-jones** [comment]
👋. hey @birtles, `bugsnag-js` doesn't currently support web workers in a Browser environment. Whilst the library can be used in Node.js worker threads, it won't work in Browser environments at the moment.

It's something on our map, that's tracked through the original FR #172, so I'm closing this one out in favour of that original ticket. Whilst it has gone stale, this will bubble it back up and we'll raise it with our product team for re-review.

From our side, we'll make sure the docs are cleared up for absolute clarity here as I agree it's misleading.

**Comment by birtles** [comment]
Thanks for following up on this. I really hope the product team picks this up.
