### ISSUE TITLE
High-resolution event timestamp breaks eventToMetaData

### ISSUE THREAD

**Issue by majido** [bugsnag/bugsnag-js#130]
[Chrome](https://www.chromestatus.com/features/5523910145605632) is switching the Event.timeStamp from [DOMTimeStamp][timestamp-mdn] to a [DOMHighResTimeStamp][highres-timestamp-mdn] in 49th release ([Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1026804) is going to make the switch in near future too). After this change the value is no longer comparable to ```Date.now()``` in chrome which is likely to impact your [```eventToMetaData```](https://github.com/bugsnag/bugsnag-js/blob/master/src/bugsnag.js#L515) function logic for calculating ```millisecondsAgo```.

Note that the current logic is actually broken in Firefox, as it does not use an epoch timeStmap for  most input events.

I am the developer who is making the change in Chrome, and I came across your library as I was doing bulk static analysis. This [blog post](https://developers.google.com/web/updates/2016/01/high-res-timestamps?hl=en) has additional details about the change but I am happy to answer any questions you have as well.

[timestamp-mdn]: https://developer.mozilla.org/en-US/docs/Web/API/DOMTimeStamp
[highres-timestamp-mdn]: https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp

**Comment by ConradIrwin** [comment]
@majido just want to thank you for making that change! progress++

Fixing the library should be relatively easy, if it's close to `new Date().getTime()` we can use it as a TimeStamp, if not, it's a DOMHighResTimeStamp https://github.com/RByers/rbyers.github.io/blob/master/scroll-latency.js#L23-L26. That also explains why this feature didn't work reliable on Firefox :)

**Comment by majido** [comment]
Thanks! It is definitely a step in the right direction. :)

@rbyers approach works fine as long as you know that the event in question occurred fairly recently.
The approach I have been using is to take a Date.now() timestamp at page load time and treat any value larger than that as DOMTimeStamp with unix epoch timestamp. You can take a look at how that approach can work here: https://github.com/majido/high-resolution-timestamp-polyfill/blob/master/translate-timeStamp.js

That logic also handles the Firefox case too. It is fairly new code and has not been extensively tested. So feel free to send pull request if you noticed something.
