### ISSUE TITLE
Expect building IOS release without upload source map.

### ISSUE THREAD

**Issue by panda6412** [bugsnag/bugsnag-js#1305]
### Describe the bug
First, thanks for Bugsnag team providing all cool thing. I have been using bugsnag with react-native, and I note that if I wanna see unminify stack traces and get human-readable method names, files, and line numbers. I could follow [Showing full stacktraces](https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#manual-setup) step by step, I follow the step and finish the settings, and work well.

However,  I want to build production mode on device or simulator (IOS/Android)
## Android
I could using below command build android release.
> npx react-native run-android --variant=release

And It will show below warning message, that's make sense, because I only wanna build production without upload source map.
```
Bugsnag: JS sourcemaps and JVM/NDK mapping files are not uploaded when using the react-native 
CLI (e.g. react-native run-android --variant=release). 
You should generate a release APK using ./gradlew assembleRelease or ./gradlew bundleRelease instead. 
See the React Native docs for further info: https://reactnative.dev/docs/signed-apk-android#generating-the-release-apk
```
## IOS
I could using below command build ios release.
> react-native run-ios --configuration Release

However, after I execute above command, it won't ignore upload source map instead. If there has already existed same version source map, it will also cause error by 409 error.

###  Expected result
- Build production mode on IOS(device/simulator) without upload source map just like android do.

### Environment
* Bugsnag version: 7.7.0
* Browser framework version (if any):
    * React: 16.13.1
    * React Native: 0.63.4
    * @bugsnag/source-maps: 1.0.1
* Device (e.g. iphonex): iPhone 11

**Comment by xander-jones** [comment]
👋. hey @panda6412, a simple fix for this is to update your `@bugsnag/source-maps` dependency to `^2.0.0`: https://github.com/bugsnag/bugsnag-source-maps/releases/tag/v2.0.0

You are seeing the `409` error because a source map already exists for the configuration on your Bugsnag project, and so the map is rejected. With v2.0.0 of the source map CLI tool, we default to overwrite any source maps so this issue will not be present anymore. 😄

**Comment by xander-jones** [comment]
Closing this out as it's been a couple of weeks. Please let us know if you're still experiencing any issues after the recommendation above.
