### ISSUE TITLE
[React Native] "Bugsnag.notify" doesn't work with Android JS

### ISSUE THREAD

**Issue by jiggag** [bugsnag/bugsnag-js#1313]
### Describe the bug
An error occurred when using "Bugsnag.notify" in "Android JS".
The error was resolved in ["bugsnag-android v5.6.2"](https://github.com/bugsnag/bugsnag-android/pull/977).
But in "@bugsnag/react-native" I still get the error.

### Steps to reproduce
1. Use Bugsnag.notify()
2. See error log

### Environment
- Android
- react-native: 0.63.3
- @bugsnag/react-native: 7.8.0
- @bugsnag/react-native/android/build.gradle
	- com.bugsnag:bugsnag-android:5.6.2-react-native
	- com.bugsnag:bugsnag-plugin-react-native:5.6.2-react-native

<details><summary>Error messages:</summary>

```
Failed to call dispatch on bugsnag-plugin-react-native, continuing
java.lang.NoSuchMethodError: No direct method <init>(Ljava/util/List;Lcom/bugsnag/android/Logger;)V in class Lcom/bugsnag/android/Stacktrace; or its super classes (declaration of 'com.bugsnag.android.Stacktrace' ...)
		at com.bugsnag.android.ErrorDeserializer.deserialize(ErrorDeserializer.java:30)
		at com.bugsnag.android.EventDeserializer.deserialize(EventDeserializer.kt:49)
		at com.bugsnag.android.BugsnagReactNativePlugin.dispatch(BugsnagReactNativePlugin.kt:140)
		at com.bugsnag.android.BugsnagReactNative.dispatch(BugsnagReactNative.kt:167)
		...
```
</details>

**Comment by johnkiely1** [comment]
Hi @jiggag, 

The fix whereby the logger references were removed you are referencing was actually introduced in v5.7.0 not v5.6.2 of the Android notifier. Currently the v7.8.0 React Native notifier uses v5.6.2 of the Android notifier under the hood.

We suspect your setup may be attempting to pull in the v5.7.0 version of the Android Notifier incorrectly and hence causing this problem. 

Would you mind sharing your `build.gradle` configuration for us to check that?

Feel free to sent that via support@bugsnag.com if you don't want to share that here.
Thanks.

**Comment by jiggag** [comment]
Thank you for your answer. @johnkiely1

I used `com.bugsnag:bugsnag-android-gradle-plugin:5.+` by referring to the document.
https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/#android

Currently I am using the modified version of `@bugsnag/react-native/android/build.gradle`.
```
com.bugsnag:bugsnag-android:5.6.2-react-native -> 5.7.0
com.bugsnag:bugsnag-plugin-react-native:5.6.2-react-native -> 5.7.0
```

If the version of `build.gradle` is `v5.6.+`, no error occurs.
Then should I enable `v7.8.0 React Native notifier` and `com.bugsnag:bugsnag-android-gradle-plugin:5.6.+`?

**Comment by johnkiely1** [comment]
@jiggag 

Would you be able to show us your complete `build.gradle` file where you are setting the Bugsnag related dependencies?

The `bugsnag-android-gradle-plugin` package is completely separate to the `bugsnag-android` package which the React Native notifier depends on. Are you modifying the `bugsnag-android `package dependency somewhere? Perhaps you have something in place that is setting both the `bugsnag-android-gradle-plugin` and `bugsnag-android` packages to be the same version?

**Comment by jiggag** [comment]
Sent to "support@bugsnag.com". @johnkiely1

Thanks.

**Comment by mattdyoung** [comment]
We've now released @bugsnag/react-native [https://github.com/bugsnag/bugsnag-js/releases/tag/v7.8.2](v7.8.2) which includes bugsnag-android v5.7.1.

We wouldn't recommend changing the underlying bugsnag-android dependency when using @bugsnag/react-native as we only test the version combinations we officially release in the bugsnag-js repository so there could be unexpected behaviour.

If you use the latest @bugsnag/react-native as is without overriding the bugsnag-android dependency you'll avoid this issue.
