### ISSUE TITLE
Not Getting screen name with Navigation Library react-navigation

### ISSUE THREAD

**Issue by dasDeepankar** [bugsnag/bugsnag-js#1346]
### Describe the bug
I am using Navigation libraries for getting screen name , But not getting screen name in error log. not sure what i'm doing wrong. 

### Steps to reproduce
1 . lunch the app .
2 open the screen with react-navigation.

### Environment
*  "@bugsnag/react-native": "^7.9.1",
* "@bugsnag/plugin-react-navigation": "^7.9.0",

* Device ( iphone 11 , google pixel):

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```   import Bugsnag from '@bugsnag/react-native'
import BugsnagPluginReactNavigation from '@bugsnag/plugin-react-navigation'
import { NavigationContainer } from '@react-navigation/native'

Bugsnag.start({
  plugins: [new BugsnagPluginReactNavigation()]
})

const { createNavigationContainer } = Bugsnag.getPlugin('reactNavigation')

// The returned BugsnagNavigationContainer has exactly the same usage
// except now it tracks route information to send with your error reports
const BugsnagNavigationContainer = createNavigationContainer(NavigationContainer)

class Routers extends Component {
    constructor(props) {
        super(props);
    }
            render() {
             return (
                <BugsnagNavigationContainer>
                  { /* your navigator and screens here */ }
                </BugsnagNavigationContainer>
              )
 
          }
    }


<!-- Error messages, if any -->
<details><summary>Error messages:</summary>

```

```
</details>

**Comment by johnkiely1** [comment]
Hi @dasDeepankar, 

When you say error log, do you mean the Bugsnag dashboard event information? Or breadcrumbs messages? or something else? Where are you expecting to see this information?

Could you share your full Bugsnag configuration along with showing what is contained within the `BugsnagNavigationContainer`. Along with how you are triggering an error. 
 
Could you write in to support@bugsnag.com with some links to the errors you see in your Bugsnag dashboard which you expect to have the screen information?

Thanks

**Comment by johnkiely1** [comment]
Closing this as we have not had any response. Please let us know if this is still a problem and we can reopen.
