### ISSUE TITLE
Error: No Bugsnag API Key set

### ISSUE THREAD

**Issue by yuriedmundo** [bugsnag/bugsnag-js#1349]
**AndroidManifest.xml**
`<meta-data
             android:name="com.bugsnag.android.API_KEY"
             android:value="<<MYCODE>>" />`

Version **"@bugsnag/react-native": "^7.6.1",**

**Problem in Android!!!**

![image](https://user-images.githubusercontent.com/5764593/113077756-1fdc5a00-91a8-11eb-8536-6c351293aa36.png)

**Comment by yuriedmundo** [comment]
@mattdyoung in MyApplication.java i call, but when i run android yarn it crash the app

`@Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    Bugsnag.start(this);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }`

**Comment by mattdyoung** [comment]
I'm unable to reproduce this issue on a new project using @bugsnag/react-native v7.6.1:
```
$ npx react-native init MyProject
$ cd MyProject
$ npx @bugsnag/react-native-cli init
$ yarn android
```

Is the API key definitely specified correctly in the correct section of your `android/app/src/main/AndroidManifest.xml`?
https://docs.bugsnag.com/platforms/android/#basic-configuration

If so are you able to cut this down to a minimal reproduction example so we can investigate further? Feel free to email this to support@bugsnag.com if you'd rather not share on the public github issue.

**Comment by yuriedmundo** [comment]
Yes, it is configured correctly. In my version, production in stores is working, but when I send it to run it shows the error.

My file: 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="br.com.inku.inkyou"
  xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@drawable/icon"
      android:roundIcon="@drawable/icon"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data android:name="com.bugsnag.android.API_KEY"
             android:value="77da530935e738e0e5a63cd4194ac1c4"/>
      <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notification" />

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@android:color/white"
            tools:replace="android:resource" />
    </application>

</manifest>

**Comment by yuriedmundo** [comment]
I use codepush, does it have to do with the problem?

**Comment by yousif-bugsnag** [comment]
Hi @yuriedmundo, Codepush is supported and shouldn't have an effect on this.

Your `AnroidManifest.xml` config looks correct too - would you be able to provide us with a simple reproduction case so we can investigate further?

**Comment by xander-jones** [comment]
Closing this issue out as it's gone stale, but please let us know if this issue is persisting.

**Comment by romreed** [comment]
still get issue

**Comment by yousif-bugsnag** [comment]
Hi @romreed, do you have the following dependency in your `app/build.gradle` file?

`implementation "com.bugsnag:bugsnag-android:5.+"`

If so, please can you remove that line and see if that resolves the issue?

**Comment by romreed** [comment]
@yousif-bugsnag i just add firebase notification service and all work. thank you

**Comment by Babazon** [comment]
> Hi @romreed, do you have the following dependency in your `app/build.gradle` file?
> 
> `implementation "com.bugsnag:bugsnag-android:5.+"`
> 
> If so, please can you remove that line and see if that resolves the issue?

It worked for us @yousif-bugsnag 
Thank you.
I don't know why it happened, we have not changed anything in the project that would cause this since our last release couple weeks ago.
