### ISSUE TITLE
Google Play Rejection: Policy Violations

### ISSUE THREAD

**Issue by curiousdustin** [bugsnag/bugsnag-js#1352]
### Describe the bug
One of our apps was rejected by Google Play with the following message:

> We have detected that your app includes non-certified ad SDKs and/or SDKs that are not approved for use in child-directed services. Any SDKs used in the app must be appropriate for use in child-directed services. Additionally, apps that solely target children must not contain any SDKs that are not approved for use in child-directed services, including ads SDKs. Apps in the Designed for Families program must only use ad SDKs that have certified their compliance with the [Families Ads Program](https://support.google.com/googleplay/android-developer/answer/9283445).

> We have detected the use of **Bugsnag** (App Bundle:642, Internal Testing Track), which is not allowed in apps that are in the Families program. An ad SDK is not allowed if it has not self-certified its compliance with Play’s Families Ads Program (certified ad SDKs), or it is non-COPPA compliant per its own public documentation. Please note, the status of SDKs often changes and it is your responsibility to review documentation of all SDKs used in your app to ensure compliance with Families policies.

### Steps to reproduce
1. Upload to Google Play. 
2. Wait forever and a day.
3. Get rejected.
4. Contact Google Play Support.
5. Wait forever and 2 days.
6. Receive email claiming Bugsnag is an ad SDK.

### Environment
* Bugsnag version: 
```
"@bugsnag/js": "^7.9.0",
"@bugsnag/react-native": "^7.9.1", 
```

### How to continue using Bugsnag

Is anything being done to get Bugsnag SDK on this [Families Ads Program](https://support.google.com/googleplay/android-developer/answer/9283445) approved list?

Is there a setting or alternative version of the SDK that we can use that will not get flagged for this violation?

**Comment by johnkiely1** [comment]
We would recommend that you appeal this decision with Google. As you're aware, Bugsnag is not an Ad SDK. Its sole purpose is to report data on application errors and crashes to app developers. It does not serve ads under any circumstances, nor does it expose any data to any other party besides the app developer.

We are investigating alternatives but for now appealing with Google is the best way to influence this.

**Comment by mattdyoung** [comment]
@curiousdustin 
We have now discussed this with Google Play who have agreed to allow use of the Bugsnag SDK for apps in their Families program. We'd recommend publishing a new version of your app including Bugsnag and please do let us know if you encounter any further issues.

**Comment by mattdyoung** [comment]
Closing this issue, but please do let us know if you encounter further issues with publishing new versions for approval.

**Comment by curiousdustin** [comment]
I can confirm that after a period of wasting time trying to get any useful info at all out of Google Play support black hole, I submitted another build with no significant changes, still including Bugsnag. This build was approved with no further action. As you say, one day they just changed their mind.
