### ISSUE TITLE
TypeError: _useTransactions__WEBPACK_IMPORTED_MODULE_3___default(...) is not a function

### ISSUE THREAD

**Issue by stupendousaj99** [bugsnag/bugsnag-js#1354]
### Environment
* Bugsnag version:
* Browser framework version (if any):
    * Vue:
    * React:
    * Angular:
* Server framework version (if any):
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex):

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by yousif-bugsnag** [comment]
Hi @stupendousaj99,

can you fill in the issue template above with some more details about the issue you're seeing?

**Comment by johnkiely1** [comment]
Closing this as we have not had a response and don't have enough details to investigate. We are happy to reopen if you can provide more information.
