### ISSUE TITLE
Release 2.5.0

### ISSUE THREAD

**Issue by dtaniwaki** [bugsnag/bugsnag-js#136]
It seems v2.5.0 npm package has not been released while the tag and commit exists in this repository.

<img width="1199" alt="npm" src="https://cloud.githubusercontent.com/assets/1162120/13382229/4d562d54-de24-11e5-8678-12b9f0b7b19e.png">

**Comment by kattrali** [comment]
Oh weird, thanks for the report, @dtaniwaki. Fixed.
