### ISSUE TITLE
Request tab not showing

### ISSUE THREAD

**Issue by kakashihuli** [bugsnag/bugsnag-js#1380]
The request tab is not showing, do I need to do any configuration to show the request tab?

![image](https://user-images.githubusercontent.com/45687248/116654992-da849580-a9bc-11eb-97db-c5795cdf5da1.png)

### Environment
* Bugsnag version: 7.3.3
* Server framework version (if any):
    * Express: 4.17.1

**Comment by mattdyoung** [comment]
Hi @kakashihuli 

No, you shouldn't need to do any configuration although the request tab would only appear if an error is captured while processing a request.

If this looks like it's not working it would be useful if you could write in to support@bugsnag.com with details of how you've configured Bugsnag, how the error is being triggered in code and a link to the Bugsnag error in your dashboard.
