### ISSUE TITLE
Link broken on FireFox 45.0.2

### ISSUE THREAD

**Issue by ramaboo** [bugsnag/bugsnag-js#142]
![screen shot 2016-04-26 at 3 06 24 pm](https://cloud.githubusercontent.com/assets/84117/14835787/90adb51c-0bc0-11e6-9166-432dc18794b3.png)

Strange error i get on FireFox but not on Chrome. URL is identical though on Firefox it redirects to the same URL with a / at the end. Hope it's just a temporary thing.

**Comment by jacobmarshall** [comment]
Hey @ramaboo, I can't seem to replicate this issue myself.

Are you perhaps on a VPN/proxy, of sorts, which could be performing the redirect?

![screen shot 2016-04-27 at 10 09 25 am](https://cloud.githubusercontent.com/assets/4710291/14835839/2bd4700e-0c60-11e6-8d14-570aa3160945.png)

**Comment by jacobmarshall** [comment]
All I can think is if at some point (for whatever reason) there was a permanent redirect from `https://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js` to `https://d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js/`, your browser cache is probably holding onto it for a while. Maybe try clearing the cache and trying again?

**Comment by ramaboo** [comment]
Yep it's working now again.. very strange. Maybe just a hickup somewhere.
