### ISSUE TITLE
Feature Request: Async Support

### ISSUE THREAD

**Issue by parisholley** [bugsnag/bugsnag-js#145]
Currently, this is the only thing preventing me from moving from rollbar. I believe their library will queue up onerror's locally until the script loads then fire off the backlog. I'd prefer to not have the script blocking page load.

**Comment by kattrali** [comment]
Thank you for the report, @parisholley. [Rollbar setup instructions](https://rollbar.com/docs/notifier/rollbar.js/#quick-start) require pasting the contents of the script (4.5KB) into the `<head>` of your page, which blocks until it loads. [The contents of the Bugsnag library](https://github.com/bugsnag/bugsnag-js#how-to-install) is about 6.5KB and blocks in the same way to maximize the number of errors caught. This behavior is unlikely to change in the near future, but we could potentially look into loading parts of the library asynchronously in an upcoming release.

**Comment by parisholley** [comment]
@kattrali I'm not talking about the code required to embed on the page. Their code specifically, sets up a "proxy" on the page prior to loading their JS asynchronously, which will capture all errors and then fire them off once rollbar has instantiated. Right from their documentation:

"By default, the snippet loads the full Rollbar source asynchronously. You can disable this which will cause the browser to download and evaluate the full rollbar source before evaluating the rest of the page."

Bugsnag is not blocking in the same way as it requires a HTTP request before it can start capturing errors, Rollbar will queue errors before it has loaded.

**Comment by kattrali** [comment]
I apologize for the misunderstanding - I was suggesting that you could embed the script source with a small change in page weight. As long as the `data-apikey` attribute is still set on the script element, it should work as expected.

**Comment by parisholley** [comment]
@kattrali ah, good to know. you should document that :)
