### ISSUE TITLE
plugin-react-navigation causing app to hang at startup/splash

### ISSUE THREAD

**Issue by jehartzog** [bugsnag/bugsnag-js#1457]
### Describe the bug
Our dev team suddenly simultaneously all hit a splash screen freeze on our iOS simulators. This occurred around 11:05AM MT on 7/1/21.

There are only a small number of components between our `NavigationContainer` getting mounted and hiding our splash screen, and the `@bugsnag/plugin-react-navigation` was one of these. Quick troubleshooting confirmed removing `@bugsnag/plugin-react-navigation` cleared the issue.

The way this occurred at the same time on two different dev machines (in different locations) makes me suspect that somehow a hiccup on bugsnag API can somehow prevent our app from getting it through the splash screen.

We've had a small number of reports in the prod of splash screen freezes we haven't yet been able to isolate, so we were keen to squash any possible cause of this.

For now we have removed `@bugsnag/plugin-react-navigation` and are manually breadcrumbing `navigation` events again.

### Environment
- @bugsnag/react-native: 7.9.5
- @bugsnag/plugin-react-navigation: 7.9.2
- react-native: 0.64.1
- @react-navigation/native: 6.0.0-next.8

iOS iPhone 12 simulator, OS 14.5

### Implementation details

The only thing I'm aware of our app does slightly differently than the docs is that we use dependency injection rather than module singletons, which requires slightly different plugin initialization.

```tsx
  const [BugsnagNavigationContainer, setBugsnagNavigationContainer] = React.useState<
    typeof NavigationContainer | undefined
  >(undefined);

  const {errorService, config} = useDependencies().services;
  const {getReactNavigationPlugin} = errorService;

  React.useEffect(() => {
    const {createNavigationContainer} = getReactNavigationPlugin(); // This returns Bugsnag.getPlugin('react').createErrorBoundary(React);
    setBugsnagNavigationContainer(createNavigationContainer(NavigationContainer));
  }, []);

  if (!BugsnagNavigationContainer) return null;

  return (
    <BugsnagNavigationContainer>
...


```

Other than that, we followed the doc examples closely for implementation. It's been working fine overall, except for the non-reproducible failures we happen to finally notice just now.

**Comment by yousif-bugsnag** [comment]
Hi @jehartzog,

> `const {createNavigationContainer} = getReactNavigationPlugin(); // This returns Bugsnag.getPlugin('react').createErrorBoundary(React);`

Did you actually mean `Bugsnag.getPlugin('reactNavigation')` here? Would you be able to share exactly how you're initialising Bugsnag (and the navigation plugin) in your app?

> Quick troubleshooting confirmed removing @bugsnag/plugin-react-navigation cleared the issue.

Is this something you're able to reproduce in development? If so are you able to provide a reproduction case that demonstrates the issue?

**Comment by jehartzog** [comment]
@yousif-bugsnag Thank you for such a quick response!

As I mentioned, we used dependency injection so the way we actually initialize is properly a little different from the standard module singleton.

I've removed some dev logging stuff to keep the examples shorter
`ErrorService.ts`
```ts
export class ErrorService {
  #config: ConfigService;
  #client: Client;

  constructor(config: ConfigService) {
    this.#config = config;

    this.#client = Bugsnag.start({
      codeBundleId: this.#config.CODE_BUNDLE_ID,
      plugins: [new BugsnagPluginReactNavigation()],
    });
  }

  setUser = (user: User): void => {
    this.#client.setUser((user.id || '').toString(), user.email!, user.firstName!);
  };

  leaveBreadcrumb = (msg: string, metadata?: Record<string, any>, type?: BreadcrumbType) => {
    // https://docs.bugsnag.com/platforms/javascript/configuration-options/#onbreadcrumb
    this.#client.leaveBreadcrumb(msg, metadata, type);
  };

  // https://docs.bugsnag.com/platforms/react-native/react-native/#capturing-react-render-errors
  getErrorBoundary = () => Bugsnag.getPlugin('react').createErrorBoundary(React);

  // https://docs.bugsnag.com/platforms/react-native/react-native/navigation-libraries/#react-navigation
  getReactNavigationPlugin = (): any => Bugsnag.getPlugin('reactNavigation');
}
```

Inside our `app.tsx`
```tsx
  React.useEffect(() => {
    const createEnv = async () => {
      const env = await createEnvironment();
      setDependencies(env);
    };

    createEnv();
  }, []);

  if (!dependencies) return null;

  return (
    <WholeAppTree...>
  );
```

our `createEnvironment()` looks like...
```ts
  constructor() {
    const {version, codeBundleId} = pckg;
    const config = new ConfigService(version, codeBundleId);
    const errorService = new ErrorService(config);
    // ...do the rest
```

We then wrap with the `BugsnagNavigationContainer` per the code in the original post.

---

On the subject of reproduction, we definitely saw this in development. In fact, two devs independently saw it happen at the exact same time, which led us to guess this was somehow dependent on responses the lib could be receiving from the API. When we experienced this, we could not use our app for about a 10 minute period, during that time we were both completely locked out. During that time span, we happened to isolate and bypass the issue by removing the `BugsnagNavigationContainer`.

When we later tried to reproduce the issue, the `BugsnagNavigationContainer` worked normally with no negative issues, like it had through the almost all the previous dev and QA testing we were doing.

**Comment by johnkiely1** [comment]
@jehartzog 

It's interesting that you have seen this behaviour, it's not something we are currently aware of. However it sounds like it is now working as expected and without a reliable reproduction case it's going to be exceptionally difficult for us to investigate further. I will close this for the moment but happy to reopen if you do see this again and find a way of reproducing.
