### ISSUE TITLE
plugin-inline-script-content/inline-script-content - SecurityError - The operation is insecure.

### ISSUE THREAD

**Issue by loren138** [bugsnag/bugsnag-js#1470]
### Describe the bug

`plugin-inline-script-content/inline-script-content.js:146:26` is logging security errors into bugsnag.

### Steps to reproduce

I'm not sure how to reproduce, but I'm getting unhandled bugsnag errors from this plugin.  I'm guessing it's because it's trying to adjust JS from another domain (in this case Google Tag Manager).

### Environment
* Bugsnag version: 7.10.5 (7.10.0 for plugin-react)
* Browser framework version (if any): React 17.0.2
* Server framework version (if any): None
* Browser version (e.g. chrome, safari): Mobile Safari
* Device (e.g. iphonex): 14.0.0, 14.0.1, 14.0.3, 14.1.0, 14.1.1

### Example Repo 

<img width="1466" alt="Screen Shot 2021-07-13 at 3 30 19 PM" src="https://user-images.githubusercontent.com/1224505/125513801-47a8a887-7b12-4500-8d4c-c7bb2ac2bfdc.png">

<details><summary>Error messages:</summary>

```
SecurityError The operation is insecure. 
    https://my-website/page:1:48 global code
    [native code] insertBefore
    https://www.googletagmanager.com/gtm.js:6516:426 
    https://www.googletagmanager.com/gtm.js:6518:160 c
    https://www.googletagmanager.com/gtm.js:6221:500 Te
    https://www.googletagmanager.com/gtm.js:6314:280 e
    https://www.googletagmanager.com/gtm.js:6178:131 
    https://www.googletagmanager.com/gtm.js:6315:359 
    https://www.googletagmanager.com/gtm.js:6315:98 
    https://www.googletagmanager.com/gtm.js:6315:830 hn
    https://www.googletagmanager.com/gtm.js:6319:45 pn
    https://www.googletagmanager.com/gtm.js:6397:238 Xt
    https://www.googletagmanager.com/gtm.js:6400:395 Zt
    https://www.googletagmanager.com/gtm.js:6403:92 
    https://www.googletagmanager.com/gtm.js:6402:221 
    ../../plugin-inline-script-content/inline-script-content.js:146:26 
```
</details>

**Comment by johnkiely1** [comment]
Hi @loren138, 

Would you be able to contact support@bugsnag.com and include a link to this error as you see it in your Bugsnag dashboard. Thanks

**Comment by loren138** [comment]
@johnkiely1 I've sent it, but I haven't seen an auto-reply from support so I'm not sure if it went through properly.

**Comment by johnkiely1** [comment]
Hi @loren138 ,

Yep got it thanks, let me take a look and we can continue the conversation on the support ticket.

**Comment by luke-belton** [comment]
Hi @loren138 I'm going to close this issue now as we've been dealing with this via the support ticket.

For future travellers - it looks like the errors that were seen `Security Error: The operation is insecure`​, were genuine errors related to blocking cookies. The reason Bugsnag appears in the stacktrace for these errors is because the inline script plugin works by monkey-patching global functions such as `addEventListener`​ so that we can track inline scripts.
