### ISSUE TITLE
Typescript definitions for notifyException are wrong

### ISSUE THREAD

**Issue by trashhalo** [bugsnag/bugsnag-js#148]
`notifyException(exception: Error, name?: string, metaData?: any, severity?: string): void;`
***
does not account for the valid method call of
`Bugsnag.notifyException(e, { foo: 5 })`

I suggest you define an additional method definition that omits name.

**Comment by kattrali** [comment]
Thank you for the report, @trashhalo. This issue will be addressed in #175.
