### ISSUE TITLE
Expo SDK 42 support

### ISSUE THREAD

**Issue by LinusU** [bugsnag/bugsnag-js#1483]
### Describe the bug

`@bugsnag/expo` depends on `expo-constants@9.3.5` and `expo-file-system@9.3.0`, but SDK 42 ships with `expo-constants@11.0.1` and `expo-file-system@11.1.3`.

### Steps to reproduce
1. Create new expo project `expo init`
2. Install bugsnag `npm add @bugsnag/expo`
3. Build your project with EAS `eas build --platform android`

> [...]
> Make sure following dependencies of your project are resolving to one specific version:
>  expo-constants, expo-file-system
> [stderr] FAILURE: Build failed with an exception.
> [stderr] * Where:
> [stderr] Script '/build/workingdir/build/node_modules/@unimodules/core/unimodules-core.gradle' line: 15
> [stderr] * What went wrong:
> [stderr] A problem occurred evaluating project ':expo-device'.
> [stderr] > Project with path ':unimodules-permissions-interface' could not be found in project ':expo-device'.
> [...]

### Environment

* Bugsnag version: `7.10.5`

### Example code snippet 

```
# The error occurs at build time so no code necessary, see "Steps to reproduce"
```

**Comment by LinusU** [comment]
The specific error I get seems to be from expo-device, where this module also depends on an old version. These are the version ranges that should be used with SDK 42:

Package | Range
----- | -----
`expo-constants` | `~11.0.1`
`expo-device` | `~3.3.0`
`expo-file-system` | `~11.1.3`

**Comment by johnkiely1** [comment]
Hi @LinusU, 

Would you be able to retry this but build using `expo build:android`. I've tried reproducing using your steps and I've used `expo build:android`. It works fine for me without any dependency conflicts. I'd be interested to know if this is something specific to [eas build](https://docs.expo.io/build/introduction/).

**Comment by LinusU** [comment]
@johnkiely1 hmm, this is probably due to EAS Build. `expo build:android` uses the builtin packages no matter what, and the changes are probably small enough that it happens to work with e.g. the expo-constants@9.3.5 javascript code even though the native part is expo-constants@11.0.1.

(even so, I would still recommend updating the dependencies since users ends up with duplicated installations of the modules otherwise...)

I managed to work around this by adding `expo-constants`, `expo-device`, and `expo-file-system` to my dependencies, and then edited the package-lock file manually to point the old versions to the new one. In fact, I actually think that just adding the three dependencies to my dependencies would have worked, since I _think_ that the problem was the old expo-device package (which no other part of my code depended on, so the new version wasn't installed) that caused the problem (since it tried using the permissions unimodule which is no more). Indeed, this can be seen from the warning I posted; it said that it had multiple copies of `expo-constants` and `expo-file-system`, and that it would use the latest version.

Switching back to the older build system is not an option for us though, so I would like to get this working on EAS Build. Do you want me to open a new issue specific to EAS Build?

**Comment by LinusU** [comment]
@johnkiely1 would you accept a PR to bump `expo-constants`, `expo-device`, and `expo-file-system`?

**Comment by LinusU** [comment]
@johnkiely1 I've submitted a PR here: #1488 

Would love to get this published asap so that we can ship the next version of our app 🙌

**Comment by brentvatne** [comment]
i think it would be better for these to be optional dependencies. something like this:

![Screen Shot 2021-07-29 at 9 52 19 PM](https://user-images.githubusercontent.com/90494/127602199-9fb2bf0a-82ac-44e7-86d2-e593acfa8923.png)

it is also possible using try/catch around `require` to then only use these modules if they exist, eg:

```js
// Device.js
let Device;
try {
  Device = require('expo-device');
} catch {
  // no device available
  console.warn('If it is very important, possibly warn?');
}

export function getBrand() {
  return Device ? Device.brand : 'unknown';
}

// etc..
```

elsewhere:

```
import * as Device from './Device';

Device.getBrand();
```

full source: https://github.com/brentvatne/optionalexample

this way bugsnag-js doesn't need to be tied to a specific SDK version and update every SDK release.

**Comment by yousif-bugsnag** [comment]
Hi @LinusU, we already have a task scheduled to look at this in our next sprint, and will let you know as soon as this becomes available.

**Comment by LinusU** [comment]
@yousif-bugsnag did you read the reply from Brent (who is on the Expo team)? I think that approach seems better. As it is now we have to pin your dependency and update it in lockstep with our Expo SDK.

I'll be switching over to Sentry for now since their Expo integration seems much more polished, it would be great if you could make your process as smooth as theirs 👍 

-----

> (note: this currently uses peerDependencies, which i think is not ideal because this can be problematic with npm 7. best to just leave them out of package.json imo)

What specifically is the problem with `peerDependencies` on npm 7? I thought that the only change is that they are installed automatically if the root package don't already have them, which should work great in this case as the end user doesn't have to run `expo install expo-application expo-...` then?

**Comment by brentvatne** [comment]
@LinusU - they do install automatically, but then you end up with the same problem as if they were dependencies - you have to keep the versions up to date with whatever version is depended on for a particular expo sdk

**Comment by LinusU** [comment]
> you have to keep the versions up to date with whatever version is depended on for a particular expo sdk

Wouldn't the best way be if the peer dependencies includes all of the major versions that it works with. Because if it is just up to the user to install the appropriate packages than a breaking change/major release in e.g. `expo-device` could silently break something deep down in Sentry/Bugsnag?

Something like this 👇 to support both SDK 41 and SDK 42

```
"peerDependencies": {
  "expo-device": "~3.2.0 || ~3.3.0"
}
```

**Comment by brentvatne** [comment]
that's not a bad idea, but i think it still is vulnerable to the same problem. if you are using sdk 41 and don't have expo-device installed, then i suspect what npm 7 would do is install the latest version that matches `"~3.2.0 || ~3.3.0"` - in which case you'd have an incompatible version

**Comment by LinusU** [comment]
Hmmm, yeah. It's a bit tricky 🤔

One approach could be that `expo` would check the actually installed version of every package and see if it satisfies the ranges given in https://github.com/expo/expo/blob/master/packages/expo/bundledNativeModules.json

If it doesn't, it could give warning, or even refuse to build the project.

That would also solve the initial problem that I was having in this issue. That I had multiple versions of e.g. `expo-device` installed in my dependency tree. Since the check could look at the entire deep tree of dependencies.

I feel that doing an `import` of a package not declared in your dependencies (peer or not) can easily lead to problems. It basically takes away the dependency handling from npm and places all the burden on the end user instead.

While it's easy to just run an extra `expo add` line when you add the package. It's very hard to not accidentally remove the package a few months later when you remove that single part of you app that was using e.g. `expo-device`...

-----

(also: I wonder what would happen if Sentry had a peer dependency on `"~3.2.0 || ~3.3.0"` and the Expo SDK 41 package had an optional peer dependency on `"~3.2.0"`. Would npm 7 then install the `~3.2.0` version? 🤔)

**Comment by yousif-bugsnag** [comment]
Thanks @brentvatne and @LinusU. 

Apologies for the delayed response. We think that removing our explicit dependencies and requiring users install them manually would be the best approach, but this would mean users apps would break until they installed the required packages and so would require a major version bump.

It looks like we can use #1488 as a starting point so I’ve reopened that PR.

**Comment by LinusU** [comment]
> We think that removing our explicit dependencies and requiring users install them manually would be the best approach

Did you read my comments about this approach:

> I feel that doing an `import` of a package not declared in your dependencies (peer or not) can easily lead to problems. It basically takes away the dependency handling from npm and places all the burden on the end user instead.
> 
> While it's easy to just run an extra `expo add` line when you add the package. It's very hard to not accidentally remove the package a few months later when you remove that single part of you app that was using e.g. `expo-device`...

Right now I think that peer dependencies is the best approach, but I would love to discuss this more! Especially in a broader context, since this is something that very many libraries for Expo runs into...

**Comment by brentvatne** [comment]
@LinusU - i started a discussion topic here where i attempted to summarize the issue https://github.com/expo/expo/discussions/13963

**Comment by xander-jones** [comment]
👋. For future travellers: Expo 42 support was added to `@bugsnag/expo` in https://github.com/bugsnag/bugsnag-js/releases/tag/v7.12.0, with thanks to @LinusU  for the PR 🙏
