### ISSUE TITLE
Adblock error not being ignored?

### ISSUE THREAD

**Issue by arjun810** [bugsnag/bugsnag-js#150]
We're getting a ton of notifications for what appears to be a bug in adblock.

We see a script tab with content like this:
	
```js
(function()
{
  var style = document.getElementById("xxxxxxx") ||
              document.documentElement.shadowRoot.getElementById("xxxxxxx");
  style.removeAttribute("id");
  Object.defineProperty(style, "disabled", {value: false, enumerable: true});
  Object.defineProperty(style.sheet, "disabled", {value: false, enumerable: true});
  var deleteRule = CSSStyleSheet.prototype.deleteRule;
  CSSStyleSheet.prototype.deleteRule = function(index)
  {
    if (this != style.sheet)
      deleteRule.call(this, index);
  }
  var removeRule = CSSStyleSheet.prototype.removeRule;
  CSSStyleSheet.prototype.removeRule = function(index)
  {
    if (this != style.sheet)
      removeRule.call(this, index);
  }
})();
```

Others report something similar here:
http://stackoverflow.com/questions/38143879/cannot-read-property-removeattribute-of-null-cant-find-source-of-it

**Comment by jacobmarshall** [comment]
Are you receiving errors from this script ending up on your Bugsnag dashboard? If so: I can't immediately think of a solution to this, if Adblock is pushing their own inline script tag into a webpage. This would cause all stacktrace frames to end up looking like they originated from the webpage itself, and not the extension's origin.

**Comment by eanakashima** [comment]
@jacobmarshall has it right — the `script` tab shows the contents of scripts that are in the current document, and, unfortunately, if adblock (or another extension) is pushing a script tag into the page, there's no way for us to detect after the fact that it came from adblock. 

Using [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) headers with `unsafe-inline` disabled is probably the best way to mitigate this kind of thing, but I know for many sites, adding CSP can be a massive undertaking. The most practical thing may just be to mark errors like this as "Ignored" in the Bugsnag dashboard, if they appear to have this code in the stacktrace.

**Comment by jacobmarshall** [comment]
I've been thinking about this, and the only possible thing I can think of is - depending on how AdBlock is adding that script tag into the page, if they were using `document.createElement('script')`, I wonder whether it would be possible to "enhance" `document.createElement` and figure out where it's being called from (by stacktrace)? I don't know if it's really worth doing, but if we really wanted to capture it, I reckon this would be *our only hope*.

![dumb movie reference](http://45.media.tumblr.com/tumblr_lkot6w6QHJ1qcrzkko1_500.gif)

**Comment by five23** [comment]
Or that error reporting services like Bugsnag and TrackJS get put on blocklists by zealots. :facepalm:
