### ISSUE TITLE
does Bugsnag have apm functionality?

### ISSUE THREAD

**Issue by btmiller13** [bugsnag/bugsnag-js#1502]
### Description

was wondering if Bugsnag has full apm functionality like new relic or is it just bugReporting for express?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mattdyoung** [comment]
Hi @btmiller13 

Bugsnag is designed as a tool to provide error reporting and application stability monitoring. We don't support APM functionality. There is some useful context on the differences between APM and application stability in this article:
https://devops.com/apm-and-application-stability-where-two-monitoring-roads-merge-and-diverge/

If you have any more specific questions feel free to email us at support@bugsnag.com. Thanks!
