### ISSUE TITLE
Hermes now supported on iOS CodePush

### ISSUE THREAD

**Issue by henrymoulton** [bugsnag/bugsnag-js#1503]
### Describe the bug

Docs need to be updated:
https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#codepush-and-hermes

CodePush has been updated to support Hermes on iOS:
https://github.com/microsoft/appcenter-cli/releases/tag/v2.10.0

**Comment by henrymoulton** [comment]
Thanks, I'm actually experiencing a crash recently when loading a new CodePush so perhaps this isn't actually working properly.

Thanks to Bugsnag for providing :)

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/30093692/128905638-c45735b5-1d36-499b-a310-4309eab72f93.png">

**Comment by henrymoulton** [comment]
Thanks, I'm actually experiencing a crash recently when loading a new CodePush so perhaps this isn't actually working properly.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/30093692/128906187-4c925966-09f4-4e23-acd5-dabf45866d10.png">


Thanks to Bugsnag for providing :)

**Comment by henrymoulton** [comment]
Have written up a crash report here: https://github.com/microsoft/react-native-code-push/issues/2124

Weird one!

**Comment by xander-jones** [comment]
Hey @henrymoulton & future travellers: We've tested this through with `appcenter-cli` v2.10.0 on iOS and Android; the source maps appear to now be generating all as expected for both platforms when Hermes is enabled, the [docs](https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#codepush) have been updated accordingly. Thanks for raising this with us!
