### ISSUE TITLE
[react-native-cli] Fails to install packages: spawn yarn ENOENT

### ISSUE THREAD

**Issue by srmagura** [bugsnag/bugsnag-js#1511]
### Describe the bug
When `@bugsnag/react-native-cli init` tries to install a package with yarn, it fails with `spawn yarn ENOENT`.

FYI, I am using Yarn Berry (aka v2) with the node-modules linker. I do have Yarn v1 installed globally.

### Steps to reproduce
1. `npx react-native init BugsnagRepro --skip-install`
2. `yarn set version berry`
3. Edit `.yarnrc.yml` to add `nodeLinker: node-modules`.
4. Run `yarn` to install packages.
5. Run `yarn dlx @bugsnag/react-native-cli init`, or equivalently, `npx @bugsnag/react-native-cli init`.

Output:
```
PS> yarn dlx @bugsnag/react-native-cli init
i Detecting repo state                                                                                        09:19:04

 WARN  This command may make modifications to your project. Afterwards you can                                09:19:04
review the diff and commit them to your project.

√ Do you want to continue anyway? ... yes
√ Are you using Bugsnag on-premise? ... no
i Adding @bugsnag/react-native dependency                                                                     09:19:11
√ If you want the latest version of @bugsnag/react-native hit enter, otherwise type the version you want ... latest

 ERROR  spawn yarn ENOENT                                                                                     09:19:14

  at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
  at onErrorNT (internal/child_process.js:467:16)
  at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Environment
* Bugsnag version: 7.10.5
* Browser framework version (if any): React Native 0.64.2
* Server framework version (if any): N/A
* Browser version (e.g. chrome, safari): N/A
* Device (e.g. iphonex): N/A
* OS: Windows 10

### Example Repo

https://github.com/srmagura/BugsnagRepro, master branch

**Comment by yousif-bugsnag** [comment]
Hi @srmagura, thanks for reporting this. I've been able to reproduce the issue just using npm. We'll look into this as soon as priorities allow.

**Comment by xander-jones** [comment]
Hey @srmagura, I'm afraid the `@bugsnag/react-native-cli` toolchain currently only supports macOS & Linux platforms, and as such won't play nicely with Node.js on Windows.

However, this is not to say that you can't manually implement `@bugsnag/react-native` using the instructions as documented here: https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/.
