### ISSUE TITLE
[react-native] Automatic sourcemap upload as part of Gradle release build fails on Windows

### ISSUE THREAD

**Issue by srmagura** [bugsnag/bugsnag-js#1512]
### Describe the bug
After setting up automatic sourcemap upload with Gradle, `./gradlew bundleRelease` fails with the error 
```
java.io.IOException: Cannot run program "C:\Projects\CareServices\BugsnagRepro\node_modules\@bugsnag\source-maps\bin\cli": CreateProcess error=193, %1 is not a valid Win32 application
```

### Steps to reproduce
1. `npx react-native init BugsnagRepro --skip-install`
2. `yarn set version berry`
3. Edit `.yarnrc.yml` to add `nodeLinker: node-modules`.
4. Run `yarn` to install packages.
5. Follow the [Bugsnag manual setup guide](https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/) for React Native on Android. At this point, `./gradlew bundleRelease` will succeed.
6. `yarn dlx @bugsnag/react-native-cli automate-symbolication`
```
PS> yarn dlx @bugsnag/react-native-cli automate-symbolication
i Detecting repo state                                                                                        09:41:16

 WARN  This command may make modifications to your project. Afterwards you can                                09:41:16
review the diff and commit them to your project.

√ Do you want to continue anyway? ... yes
√ Are you using Bugsnag on-premise? ... no
√ Do you want to automatically upload JavaScript source maps as part of the Xcode build? ... yes
i Modifying the Xcode project                                                                                 09:41:27
i Ensuring React Native build phase outputs source maps                                                       09:41:27
i Adding build phase to upload source maps to Bugsnag                                                         09:41:27
√ Written changes to Xcode project                                                                            09:41:27
√ To configure your project to upload dSYMs, follow the iOS symbolication guide:

    https://docs.bugsnag.com/platforms/ios/symbolication-guide/

  This will enable you to see full native stacktraces. It can't be done automatically.

 ... Hit enter to continue …
√ Do you want to automatically upload JavaScript source maps as part of the Gradle build? ... yes
» Enabling Bugsnag Android Gradle plugin React Native mappings                                                09:41:33
√ React Native mappings enabled in android/app/build.gradle                                                   09:41:33
i Adding @bugsnag/source-maps dependency                                                                      09:41:33
√ If you want the latest version of @bugsnag/source-maps hit enter, otherwise type the version you want ... latest

 ERROR  spawn yarn ENOENT                                                                                     09:41:37

  at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
  at onErrorNT (internal/child_process.js:467:16)
  at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
(See issue #1511 for the "spawn yarn ENOENT" problem.)

7. Since adding `@bugsnag/source-maps` failed, install it manually with `yarn add --dev @bugsnag/source-maps`.
8. Run `./gradlew bundleRelease` again. Error occurs (see full Gradle output below).

### Environment
* Bugsnag version: `"@bugsnag/react-native": "^7.11.0"`
* Browser framework version (if any): `"react-native": "0.64.2"`
* Server framework version (if any): N/A
* Browser version (e.g. chrome, safari): N/A
* Device (e.g. iphonex): N/A
* OS: Windows 10

### Example Repo

https://github.com/srmagura/BugsnagRepro, `no-source-maps` branch: Gradle release build will succeed.
https://github.com/srmagura/BugsnagRepro, `source-maps` branch: Gradle release build will fail with the following output:

<details><summary>Error messages:</summary>

```
PS> .\gradlew bundleRelease

> Task :app:bugsnagReleaseReleaseTask
Bugsnag: Uploading to Releases API

> Task :app:uploadBugsnagReleaseSourceMaps FAILED
Bugsnag: uploading react native sourcemap: [C:\Projects\CareServices\BugsnagRepro\node_modules\@bugsnag\source-maps\bin\cli, upload-react-native, --api-key, ***REDACTED***, --app-version, 1.0, --app-version-code, 1, --platform, android, --source-map, C:\Projects\CareServices\BugsnagRepro\android\app\build\generated\sourcemaps\react\release\index.android.bundle.map, --bundle, C:\Projects\CareServices\BugsnagRepro\android\app\build\generated\assets\react\release\index.android.bundle, --project-root, C:\Projects\CareServices\BugsnagRepro]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:uploadBugsnagReleaseSourceMaps'.
> java.io.IOException: Cannot run program "C:\Projects\CareServices\BugsnagRepro\node_modules\@bugsnag\source-maps\bin\cli": CreateProcess error=193, %1 is not a valid Win32 application

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
59 actionable tasks: 12 executed, 47 up-to-date
```
</details>

The contents of `@bugsnag/source-maps/bin/cli` are:
```
#!/usr/bin/env node

require('../dist/bin/cli.js').default(process.argv)
```
**Looks like the first line needs to be tweaked to work on Windows!**

**Comment by yousif-bugsnag** [comment]
Hi @srmagura, thanks for the report. We'll look into this along with #1511 as soon as priorities allow.

**Comment by xander-jones** [comment]
Hi @srmagura, as per https://github.com/bugsnag/bugsnag-js/issues/1511#issuecomment-904118746; the `@bugsnag/source-maps` CLI tool only support macOS & Linux which is why Windows will throw an error that the binary `node_modules\@bugsnag\source-maps\bin\cli` is not executable.

Therefore, in order to upload source maps from a Windows machine, you will need to invoke `curl` (or `Invoke-WebRequest` if `curl` is not available for any reason) directly from PowerShell. You can find details on how to interact with the React Native source map upload API here: https://docs.bugsnag.com/api/rn-source-map-upload/. Or alternatively, you can interact with the `@bugsnag/source-maps` JavaScript API: https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#usage.

To stop Bugsnag from trying to upload source maps through Gradle, you can remove the `uploadReactNativeMappings` option from you `app/build.gradle`.
