### ISSUE TITLE
Trouble with Chrome extension source maps

### ISSUE THREAD

**Issue by flushentitypacket** [bugsnag/bugsnag-js#152]
I'm using Bugsnag in a Chrome extension and am having trouble getting source maps working. I have tried both inline source maps and uploading source maps separately, and neither seem to work.

I'm using webpack with babel transpiler. Source maps generated via the devTools directive in the webpack config.

SS of current result on bugsnag webUI:
<img width="1081" alt="screen shot 2016-07-12 at 2 51 24 pm" src="https://cloud.githubusercontent.com/assets/1355249/16805980/a48edfd6-48e0-11e6-8b58-1e79bb93bbcb.png">

I'm wondering if it has to do with [this fix for allowing chrome extension backtraces](https://github.com/bugsnag/bugsnag-js#browser-extensions). Perhaps the source maps do not match up with the doctored stacktraces on the Bugsnag side?

To test that theory, I tried uploading source maps via [this doc](http://docs.bugsnag.com/api/js-source-map-upload/). The extension source code is not hosted publicly, so I passed in the URL as it would appear to the browser `chrome-extension://theidgoeshere/path/to/source`. In case it had to do with the stacktrace doctoring, I also tried `chrome-extension://theidgoeshere/path/to/source`.

Forgive me, I do not really understand the dirty details of source maps nor the particulars of how Bugsnag uses and displays them. Definitely in the dark here!

**Comment by samrispaud** [comment]
@flushentitypacket I'm having a similar issue with webpack and babel transpiler. In my webpack config I have config.devtool = '#cheap-module-eval-source-map' which I don't believe is compatible with Bugsnag. What config are you using? Have you tried '#eval-source-map' or '#source-map' as it seems like these may be compatible?

**Comment by flushentitypacket** [comment]
@samrispaud I tried 'source-map' and 'inline-source-map', and wasn't able to get either to work (as far as I could tell, at least). I've shelved this, so I haven't done anything with it since I created this issue, though.

**Comment by eanakashima** [comment]
@flushentitypacket two questions that could help us debug further:

- If you run your sourcemaps through a validator, do you get any warnings or errors?
- Did you see any change when you tried uploading your source maps?

We've had a few intermittent issues with our backend source map processing recently, so it's possible that you happened to run into one of those when you first tried this out.

The chrome extension hack would change column numbers, so it might interfere with accurate sourcemapping, but you'd likely see mapped stacktraces that were off by a few characters or lines rather than seeing mapping that is missing entirely. I believe you could replace `chrome-extension` with `chrome_extension` instead to keep the column numbers from changing.

**Comment by flushentitypacket** [comment]
@eanakashima Great idea on the column numbers. I'm off the particular project now, but I'll look back on it as soon as I can and let you know. Thanks!

**Comment by flushentitypacket** [comment]
@eanakashima I went ahead and created a dummy repo just to test the simplest-case source maps. See here: https://github.com/flushentitypacket/bugsnag-test

This is what I received in the UI:
http://share.wi.st/3a3C3X2r2E0l

I must be doing something wrong (the alternative being that source maps are totally broken). Any ideas?

**Comment by jacobmarshall** [comment]
> This is what I received in the UI:
> http://share.wi.st/3a3C3X2r2E0l

I think this is expected if Bugsnag can't download your sourcemap, have you tried this repo running on a website publically available from the web?

**Comment by flushentitypacket** [comment]
@jacobmarshall Is bugsnag unable to read inline source maps? That's what I'm using right now.

**Comment by jacobmarshall** [comment]
> @jacobmarshall Is bugsnag unable to read inline source maps? That's what I'm using right now.

I'm almost certain it isn't able to. The bugsnag-js notifier sends as little data over the web, so it doesn't end up sending 2MB of sourcemap every time there's an error. The Bugsnag server reads where the sourcemap file is, and attempts to download it (from their end).

**Comment by flushentitypacket** [comment]
That makes a lot of sense. That's probably the source of my woes!

**Comment by jacobmarshall** [comment]
> That makes a lot of sense. That's probably the source of my woes!

I'm thinking it probably is indeed.

You will need to make sure that your bundle has the sourcemap url set to a publically accessible web server (cloudfront/s3 for example). Because extensions are local addresses, not externally accessible.

**Comment by flushentitypacket** [comment]
I'm a bit confused as to why it needs to be hosted on the web. Looking at [these docs](https://docs.bugsnag.com/api/js-source-map-upload/), why isn't it sufficient to upload the compiled file and source map without specifying `minifiedUrl`? Seems extraneous when `minifiedFile` is provided.

**Comment by flushentitypacket** [comment]
Also, thank you for being so helpful and responsive! @jacobmarshall :)

**Comment by jacobmarshall** [comment]
> Also, thank you for being so helpful and responsive! @jacobmarshall :)

No problem.

> I'm a bit confused as to why it needs to be hosted on the web. Looking at these docs, why isn't it sufficient to upload the compiled file and source map without specifying minifiedUrl? Seems extraneous when minifiedFile is provided.

I could be wrong here, because I've never used that feature of Bugsnag, but I'm pretty sure the `minifiedUrl`is required because it's needed to relate the source with the map file. You could have multiple sourcemaps for a single project, Bugsnag needs to know which one is which.

It looks like there could be a webpack plugin coming, which will help out with this process (see https://twitter.com/TheLarkInn/status/788534472085872640).

**Comment by eanakashima** [comment]
@jacobmarshall thanks for jumping in here. Looking through our code, I can verify that `minifiedUrl` is currently a required param like it suggests in the [docs](https://docs.bugsnag.com/api/js-source-map-upload/), without it, we won't process your source maps correctly.

I'll forward your issue along with to the team that works on source map processing to see if there's a way to work around that requirement — I could see how providing a minified url seems a bit strange for the chrome extension case.

**Comment by flushentitypacket** [comment]
@eanakashima Hey, still having trouble with this. I tried hosting the source and source maps on S3 to make it fall more in line with Bugsnag requirements, but it seems like something still isn't quite working , and I'm not sure whether it's because I'm doing something wrong or the Chrome Extension use case simply isn't supported.

Here's the curl I used to upload:

```
curl https://upload.bugsnag.com/ \
   -F apiKey=iputmyapikeyhere \
   -F appVersion=0.5.1.2 \
   -F minifiedUrl=https://s3.amazonaws.com/wistia-chrome-extension/0.5.1.2/popup.js \
   -F sourceMap=@dist/popup.js.map \
   -F minifiedFile=@dist/popup.js \
   -F overwrite=true
```

Is it possible to open a line to the source maps engineers so we can work together to get to the bottom of this?

Thanks for all your help so far!

**Comment by eanakashima** [comment]
@flushentitypacket would you mind pinging this in to our support so we can get the right folks to take a look at it? You can email support@bugsnag.com or click the chat bubble in the lower right hand corner of the Bugsnag dashboard.

**Comment by flushentitypacket** [comment]
Done

**Comment by flushentitypacket** [comment]
Okay, thanks to a suggestion from support, I was able to get 1 reported error working with source maps (I'm assuming the rest will work, haha)!

The issue was that I was misinterpreting `minifiedUrl`. That url should point to what the Bugsnag client reports to the servers on notify. In other words, it should be the same url as what shows up in your Bugsnag dashboard. Or in even more other words, it should be the same url as what shows up in your stacktraces.

This is especially confusing in chrome-extension land, since [the reported stacktrace needs to be modified to get through a Bugsnag filter](https://github.com/bugsnag/bugsnag-js/issues/94#issuecomment-66153172).

In any case, this is the CURL that did the job for me:

```
curl https://upload.bugsnag.com/ \
   -F apiKey=apikeygoeshere \
   -F appVersion=versiongoeshere \
   -F minifiedUrl=chromeextension://chromeextensionid/yourfile.js \
   -F sourceMap=@path/to/yourfile.js.map \
   -F minifiedFile=@path/to/yourfile.js \
   -F overwrite=true
```

Hope this clarifies things for anyone else having this issue.
