### ISSUE TITLE
Remove userId setting in v3

### ISSUE THREAD

**Issue by jacobmarshall** [bugsnag/bugsnag-js#153]
Seeing as #149 was just merged into `master` and it increments the notifier version to 3.0.0-rc.1, I just thought it was worth mentioning that the `userId` setting was deprecated and due to be removed in v3.

See https://github.com/bugsnag/bugsnag-js/blob/master/src/bugsnag.js#L771

**Comment by kattrali** [comment]
Hey @jacobmarshall, nice catch! I guess that’s why we do RCs :)
