### ISSUE TITLE
autoNotify not working?

### ISSUE THREAD

**Issue by donbonifacio** [bugsnag/bugsnag-js#154]
Hello,

We have a project with bugsnag registered on the HTML file:

```html
 <script src="//d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js"
              data-apikey="..."
               data-autonotify="true"></script>
```

On the source code, if we use `Bugsnag.notify`, the error is registered on bugsnag. However, if we have some uncaught exception (for exemple running `null.something()`), nothing is registered.

I already tried to set `autoNotify` everywhere, and the truth is that `onerror` seems to be ok:

```
$ window.onerror
(c,d,e,g,h){var i=l("autoNotify",!0),j={};!g&&a.event&&(g=a.event.errorCharacter),f(j),v=null,i&&!z&&n({name:h&&h.name||"window.onerror",message:c,file:d,lineNumber:e,columnNumber:g,stacktrac…
```

How can we troubleshoot this?

Thanks.

**Comment by jacobmarshall** [comment]
Could you provide the example code which is not working? In something line [JS Bin](https://jsbin.com/).

**Comment by donbonifacio** [comment]
Hey @jacobmarshall 

A very simple test case there works... as expected. :) 

We use webpack and can't make this work on the big app. How can we torubleshoot this?

**Comment by wordofchristian** [comment]
Where you running the test error code from the browser console? `null.something()` if run from the console would not get caught. However,`window.addEventListener('click', function() { throw new Error("asdfasdf") })`, then clicking somewhere, should get caught. 
I could take a look if the page live somewhere? If not, here's what I would recommend to debug it:

1.  Switch to the non-minified version of the script (change //d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.min.js to //d2wy8f7a9ursnm.cloudfront.net/bugsnag-2.js)
2. Open up the sources tab of the browser console and add a breakpoint to line 600 of the bugsnag-2.js script. 
![](https://www.dropbox.com/s/usl2oa7l4nwtwp6/Screenshot%202016-07-25%2010.00.49.png?dl=1)
3. Trigger an exception and it should hit your breakpoint, you can then step through the code and see why it might not be sending. Be sure to also step into the `sendToBugsnag` function (line 379). There is some conditional logic in there as well about when to notify or not.


Additional FYI: the `autoNotify` setting is defaulted to true, so you shouldn't need to set it.

Good luck.

**Comment by donbonifacio** [comment]
Thanks @wordofchristian 

It bails here:

```javascript
if (payload.lineNumber === 0 && (/Script error\.?/).test(payload.message)) {
  return log("Ignoring cross-domain script error. See https://bugsnag.com/docs/notifiers/js/cors");
}
```

But this is not a CORS issue right? This was generated just by:

```javascript
componentDidUpdate() {
   null.something();
   ...
}
```

You have a staging version of the app here: http://clanhr-repack-frontend.herokuapp.com/

**Comment by wordofchristian** [comment]
That's weird. Those conditions normally indicate a CORS problem.
see: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#Notes
and: http://stackoverflow.com/a/7778424/80559

But you don't seem to be loading the bundle.js file cross domain.
How can I reproduce this error on the page? Which component has this error throwing function?

**Comment by donbonifacio** [comment]
Hey @wordofchristian 

I reproduced this going to:
http://clanhr-repack-frontend.herokuapp.com/

On Chrome, then opened up console and typed:

```javascript
setTimeout(function() {null.hello()}, 1000);
```

Result:

<img width="636" alt="screen shot 2016-07-27 at 09 40 06" src="https://cloud.githubusercontent.com/assets/483669/17169184/30df52d8-53de-11e6-916b-3b9745455a60.png">

**Comment by wordofchristian** [comment]
I think I've found the cause. Your source code is all generated using `eval`. You probably have the `devtool` option set to `eval` in your webpack config. This is causing the error message obfuscation  and the line number weirdness. We'll probably adjust our script to catch these cases but I recommend that you change your `devtool` setting it to `source-map` or `inline-source-map` for the production environment. Otherwise everything that shows up in the bugsnag dashboard will just say `Script error`

**Comment by donbonifacio** [comment]
Thanks @wordofchristian for the help. :)

**Comment by jayseeg** [comment]
@wordofchristian—I'm hitting this same issue without devtool set to eval. Interestingly, we are logging errors to bugsnag in most cases. However, for a small set of errors, I'm able to step into the `payload.lineNumber === 0 && (/Script error\.?/).test(payload.message)` predicate which returns true. The payload does indeed have 0 as the line number.

payload (both references in the stacktrace point pack to bugsnag code rather than the origin of the error):
```
{
  "notifierVersion": "2.4.9",
  "apiKey": [deleted],
  "projectRoot": [deleted],
  "context": [deleted],
  "metaData": {},
  "releaseStage": "qa",
  "url": [deleted],
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36",
  "language": "en-US",
  "severity": "error",
  "name": "window.onerror",
  "message": "Script error.",
  "stacktrace": "<generated>\nError\n    at y ([deleted]/application-3d5e7acc2e3e9a50d8a0018acdb9e43b.js:10780:25960)\n    at [deleted]/application-3d5e7acc2e3e9a50d8a0018acdb9e43b.js:10780:28062",
  "file": "",
  "lineNumber": 0,
  "payloadVersion": "2"
}
```

console output:
```
[Bugsnag] Ignoring cross-domain script error. See https://bugsnag.com/docs/notifiers/js/cors
Uncaught TypeError: Cannot read property 'subscriptions' of undefined
```

Please let me know if I'm missing something here, or if there is anything else I can do?

**Comment by eanakashima** [comment]
@jayseeg If it's only for some errors, some possibilities: 
- A particular codepath that happens to use `eval`, maybe in a framework, library, or plugin
- A cross-origin script error from a script that is missing [CORS headers](https://docs.bugsnag.com/platforms/browsers/cors/) or the `crossorigin` attribute.

**Comment by jayseeg** [comment]
Hmm, neither fit in this case,... the error isn't throwing from any frameworks, libraries, or plugins cross-origin or otherwise.
