### ISSUE TITLE
React Native Android: Missing Bug

### ISSUE THREAD

**Issue by nsh96hp** [bugsnag/bugsnag-js#1543]
### Describe the bug
Although the error content is the same, most bugs are not sent to Bugsnag
![image](https://user-images.githubusercontent.com/34828185/137848905-c4061635-d44f-4ec5-8fae-f808976e4db7.png)
I tested with the above error but sometimes it gets reported to Bugsnag
All error tests are detected at Bugsnag.start ({onError}) but most are not reported

### Steps to reproduce
1. Running function error 
2. See an error  on the Bugsnag dashboard
3. Error not reported

### Environment
* Bugsnag version:  ^7.13.2
* React Native version: ^0.64.2 
* Device : Samsung Galaxy S20 5G(SC-51A)
* ReleaseStages: production, dev (I checked on both)

### Bugsnag Setting
index.js file.
![image](https://user-images.githubusercontent.com/34828185/137849861-7b24b8a2-e276-4659-8589-03e13685ed56.png)

![image](https://user-images.githubusercontent.com/34828185/137849949-4e37aca2-fe8a-4817-837d-1607aa9957b4.png)

### Note
- With iOS absolutely no problem.
- If using Bugsnag.notify() also no problem, but I want to use at Bugsnag.start({onError})

Did I set something wrong? If yes, I hope you can help me.
Thank you very much!

**Comment by johnkiely1** [comment]
Hi @nsh96hp, 

Im closing this as we have not heard back from you in quite a while. It's difficult for us to investigate further without more information. Happy to reopen if you can provide us with this or an example project the reproduces the behaviour you are seeing.
