### ISSUE TITLE
How to skip caught error in error boundary

### ISSUE THREAD

**Issue by alimertcakar** [bugsnag/bugsnag-js#1553]
```
<ErrorBoundary FallbackComponent={ErrorPage}>
</>
```

```
// inside error page

<Text>Error occured.</<Text>
<Text>Error reported to development team.</<Text>
<button>Ok, skip.</button>

//? How to skip?
```

ErrorBoundary itself does not return props.children to FallbackComponent. It should.

**Comment by johnkiely1** [comment]
Hi @alimertcakar,

You should be able to call [`clearError`](https://docs.bugsnag.com/platforms/javascript/react/#customizing-the-error-boundary) to reset the error boundary, which will re-render the children. You would need to pass [this as a property](https://github.com/bugsnag/bugsnag-js/blob/5ee330e41ac101f770d50a9910ad28323fac89ad/packages/plugin-react/src/index.js#L85) to the fallback component. This should avoid you needing to create your own custom error boundary.

**Comment by alimertcakar** [comment]
> Hi @alimertcakar,
> 
> You should be able to call [`clearError`](https://docs.bugsnag.com/platforms/javascript/react/#customizing-the-error-boundary) to reset the error boundary, which will re-render the children. You would need to pass [this as a property](https://github.com/bugsnag/bugsnag-js/blob/5ee330e41ac101f770d50a9910ad28323fac89ad/packages/plugin-react/src/index.js#L85) to the fallback component. This should avoid you needing to create your own custom error boundary.

Children immediately throws again, now what?

**Comment by johnkiely1** [comment]
I imagine this would be because of whatever caused the render error in the first place.

I think you would need to fix/avoid whatever caused that error and then call `clearError` to reset the error boundary. 
Alternatively you may need to consider redirecting to another page if they original page has errors such that it cannot be reloaded.

**Comment by alimertcakar** [comment]
Thanks for the answer, it isn't optimal for errors on the homepage. It's rare, but its breaks the app completely.
You may take this as a feature suggestion.

**Comment by jakecronin** [comment]
Hey Bugsnag team, please just provide a full example of the ErrorBoundary component :)

**Comment by johnkiely1** [comment]
Hi @alimertcakar, 

Thanks for the suggestion. I don't think this is something we would look to create a bespoke solution for.  I think, as you mentioned yourself, this type of the error would be rare and sounds like it would be significant enough that it possibly should break the app if it is not possible it handle it.
