### ISSUE TITLE
Console log breadcrumb changes line number of log messages

### ISSUE THREAD

**Issue by wordofchristian** [bugsnag/bugsnag-js#156]
Because of we are overriding console.log to capture breadcrumbs, those messages when printed to the console get attributed to [our script](https://github.com/bugsnag/bugsnag-js/blob/f5dfe8f6b2bc508a39da1c28584e133ebc08d395/src/bugsnag.js#L481) rather than the original source.

![](https://www.dropbox.com/s/rer76ol6zud4g69/Screenshot%202016-07-26%2015.38.00.png?dl=1)

It would be nice to find a way to avoid this.

**Comment by wordofchristian** [comment]
Did a lot of searching on this problem. There are [several ways](http://stackoverflow.com/questions/13815640/a-proper-wrapper-for-console-log-with-correct-line-number) to duplicate the original console.log function without altering the line number, but I haven't yet found an approach that let's you perform some logic before calling the original. 

Some browsers have a feature called [blackboxing](https://developer.chrome.com/devtools/docs/blackboxing) which will allow people to ignore the bugsnag.js library in stacktraces, but this is less than ideal as it requires extra setup.

**Comment by ptrwtts** [comment]
I need this functionality to debug an app. My standard method of logging to the console is useless without line numbers. Is there any way to disable this, at least during development, without completely turning off bugsnag?

**Comment by wordofchristian** [comment]
@ptrwtts 

Yes, you can disable any of the automatic breadcrumbs https://docs.bugsnag.com/platforms/browsers/configuration-options/#autobreadcrumbs

in code:
```javascript
Bugsnag.autoBreadcrumbsConsole = false;
```

as script tag attribute
```
<script src="//d2wy8f7a9ursnm.cloudfront.net/bugsnag-3.min.js"
        data-apikey="YOUR-API-KEY-HERE"
        data-autobreadcrumbsconsole="false"></script>
```

We're actually considering disabling the console breadcrumbs in development by default.

**Comment by ekeric13** [comment]
For bugsnag via npm version 3.3.2 I was running into some issues.

For some reason `Bugsnag. autoBreadcrumbsConsole = false` was not working.

But `Bugsang. disableAutoBreadcrumbsConsole()` worked.

Looks like there was some changes to v4 so probably not relevant to people using that version.

**Comment by DmitryGonchar** [comment]
Nope, same in v4

**Comment by PhilibertDugas** [comment]
👋 I've added the `Bugsnag.disableAutoBreadcrumbsConsole()` in my source code, yet it seems like the console is highjacked, is there a way to keep the original console?

![image](https://user-images.githubusercontent.com/5460957/36615871-c91c6fc6-18af-11e8-9ba3-93c714a0d118.png)

In this case, bugsnag is inside a 3rd party lib that I control where it's initialized with `Bugsnag.noConflict();`

https://docs.bugsnag.com/platforms/browsers/v3/faq/#how-do-i-use-bugsnag-in-third-party-embedded-javascript
