### ISSUE TITLE
How to catch console.error?

### ISSUE THREAD

**Issue by duveborg** [bugsnag/bugsnag-js#1565]
Hi! Im using a 3rd party lib that throws errors with console.error. This seems to not get picked up by bugsnag. Is there a way to configure this?

**Comment by mattdyoung** [comment]
Bugsnag does intercept and store the output from `console.error`, but this doesn't automatically trigger an error notification in its own right. The console output gets stored as breadcrumbs, so if an [unhandled error](https://docs.bugsnag.com/platforms/javascript/#reporting-unhandled-errors) or notification of a [handled error](https://docs.bugsnag.com/platforms/javascript/#reporting-handled-errors) happens shortly afterwards you'll see the console output in the bugsnag dashboard under the breadcrumbs tab associated with that error.

See the documentation for some more info on which breadcrumbs we automatically capture:
https://docs.bugsnag.com/platforms/javascript/#automatically-captured-breadcrumbs

You may be able to detect when the 3rd party lib calls `console.error` by hooking into the `onBreadcrumb` callback which would get called when Bugsnag leaves the console breadcrumb:
https://docs.bugsnag.com/platforms/javascript/customizing-breadcrumbs/#discarding-and-amending-breadcrumbs

But to notify a console error to Bugsnag as an error report you'd need to explicitly call `Bugsnag.notify`:
https://docs.bugsnag.com/platforms/javascript/reporting-handled-errors/

**Comment by duveborg** [comment]
thanks! ⭐
