### ISSUE TITLE
Expo source map upload timing out

### ISSUE THREAD

**Issue by dubchoi** [bugsnag/bugsnag-js#1573]
### Describe the bug
The post publish hook of @bugsnag/expo consistently times out on request. This used to work on the same project, so not sure what's happening.

### Steps to reproduce
1. expo publish
2. See error

### Environment
* @bugsnag/expo version: 7.13.3

```
ℹ Uploading source maps to Bugsnag                                                                          12:18:29
ℹ Preparing upload of React Native source map (release / android)                                           12:18:29
....
› Initiating upload to "https://upload.bugsnag.com/react-native-source-map"                                 12:18:29

 ERROR  The request timed out.                                                                              12:23:34

 Connection timed out

  at ClientRequest.<anonymous> (node_modules/@bugsnag/source-maps/src/Request.ts:223:17)
  at Object.onceWrapper (events.js:519:28)
  at ClientRequest.emit (events.js:400:28)
  at TLSSocket.emitRequestTimeout (_http_client.js:790:9)
  at Object.onceWrapper (events.js:519:28)
  at TLSSocket.emit (events.js:412:35)
  at TLSSocket.Socket._onTimeout (net.js:484:8)
  at listOnTimeout (internal/timers.js:557:17)
  at processTimers (internal/timers.js:500:7)

NetworkError: Connection timed out
    at ClientRequest.<anonymous> (/Users/dubchoi/code/jomo/allo-client/node_modules/@bugsnag/source-maps/src/Request.ts:223:17)
    at Object.onceWrapper (events.js:519:28)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.Socket._onTimeout (net.js:484:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  isRetryable: true,
  code: 2,
  cause: null,
  responseText: null
}
```

**Comment by luke-belton** [comment]
Hi @dubchoi - I've not been able to reproduce this using `v7.13.3`.

What version of `@bugsnag/source-maps` do you have installed? We recently updated `bugsnag-source-maps` ([`v2.3.0`](https://github.com/bugsnag/bugsnag-source-maps/releases/tag/v2.3.0)) to increase the the default HTTP request timeout to 10 minutes (from 5 minutes). Looking at your logs the timeout occurs after ~5 minutes so I suspect this is related. If you upgrade does this issue resolve itself `bugsnag-source-maps`?

**Comment by dubchoi** [comment]
Hi, I have @bugsnag/source-maps at 1.0.1, which is the version that the latest @bugsnag/expo depends on (maybe it should be updated). I can definitely try forcing the dependency resolution to v2.3.0, but doesn't seem like it's a timeout issue? 5 minutes is quite long already, and it happens very reliably, every single time. Is there any way I can give you more diagnostics data?

**Comment by dubchoi** [comment]
weird, that actually worked with v2.3.0. and it only took about a minute to upload, so I'm guessing there were some other changes in the version upgrade that I needed.

https://github.com/bugsnag/bugsnag-js/blob/v7.13.3/packages/expo/package.json#L48 probably should be updated to ^2.3.0...

**Comment by johnkiely1** [comment]
Hi @dubchoi, 

Thanks for the suggestion, yes we will look to update to the latest bugsnag/source-maps a soon as priorities allow. We will update here as soon as that happens.

**Comment by xander-jones** [comment]
The `@bugsnag/source-maps` version dependency has been updated in `bugsnag-js` https://github.com/bugsnag/bugsnag-js/releases/tag/v7.15.1.

**Comment by efstathiosntonas** [comment]
I'm encountering this with "@bugsnag/source-maps": "2.3.1", any idea what might be happening?

**Comment by efstathiosntonas** [comment]
hi @clr182 

the index.js.map is 46MB and the index.bundle is 29MB

**Comment by mclack** [comment]
Hi @efstathiosntonas 

Thanks for sharing that.

If you are continuing to have issues with your source map uploads, could you please open a ticket with us directly by reaching out to support@bugsnag.com and referencing your initial comment: https://github.com/bugsnag/bugsnag-js/issues/1573#issuecomment-1934659464

When you reach out, can you please answer:
- How often are you seeing the uploads failing?
- If you retry a failed upload, does it succeed?
- Are the uploads consistently timing out at 10 minutes, or are you noticing a different timeout?
- Can you share the upload command you are using to perform your uploads?
