### ISSUE TITLE
Doc about createClient?

### ISSUE THREAD

**Issue by weilinzung** [bugsnag/bugsnag-js#1578]
Any docs about the `createClient` option?

**Comment by johnkiely1** [comment]
Hi @weilinzung, could you explain a little more about what you are trying to achieve with wanting to use this?

**Comment by weilinzung** [comment]
We have a backend app that using Express and also some pubsub functions, and both of them hosted in Firebase. 

Express side is using the plugin as middleware, and pubsub functions are not under the Express, so ideally we would need to use ‘createClient’ and export it for both of them.

We want to see the instruction what/why/how about using ‘createClient’, with examples would be even better.

thanks!

**Comment by mattdyoung** [comment]
Hi @weilinzung 

There shouldn't be any need to use `createClient`. We'd recommend using `Bugsnag.start` which automatically creates a client internally and will safely ignore and carry on using the existing client if you call it twice:
https://github.com/bugsnag/bugsnag-js/blob/c013924bc17ada497b0fb7c4f026fe67c50b79c5/packages/node/src/notifier.js#L67-L74

So we'd recommend just using `Bugsnag.start` as described in our documentation:
https://docs.bugsnag.com/platforms/javascript/express/#basic-configuration

If you wanted you could have one file that calls `Bugsnag.start` and import it in both your Express and pubsub code.

Provided `Bugsnag.start` has already been called, any calls to `Bugsnag.notify` or other `Bugsnag.` methods with just use the client that's been created internally.
