### ISSUE TITLE
Bugsnag not showing errors in my dashboard

### ISSUE THREAD

**Issue by Dhaxor** [bugsnag/bugsnag-js#1594]
I have a vue 2 application and I'm using bugsnag. I've followed all the steps but bugsnag does not show any error on my dashboard. I have a created method where i call Bugsnag.notify(new Error('An Error')) but nothing displays on my dashboard

**Comment by xander-jones** [comment]
Hey @Dhaxor 👋 , please drop us a message at support@bugsnag.com with how you're configuring Bugsnag in your application and we'll be able to take a look into this.
