### ISSUE TITLE
Expo Insert API Key Into app.json instead of app.config.js

### ISSUE THREAD

**Issue by thomashzhang** [bugsnag/bugsnag-js#1605]
### Describe the bug
When running `npx bugsnag-expo-cli init` the app tries to insert the API key and postPublish steps into `app.json`, which would be correct for most apps. But some setups use `app.config.js` instead which is not easily convertable into `app.json` for the keys to be inserted.

### Steps to reproduce
1. Run `npx bugsnag-expo-cli init` without an app.json file
2. During the API insertion step, I get (which is reasonable):

```
Inserting API key into app.json

  Error: Couldn’t find app.json in "/Users/<user>/Desktop/projects/<project>". Is this the root of your Expo project?
```

It should instead look for `app.config.js` if `app.json` doesn't exist. It's very minor, but I think it would save a teeny bit of time. Thanks!

### Environment
* Bugsnag version: v7.13.2
* Browser framework version (if any):
    * Vue:
    * React: yes
    * Angular:
* Server framework version (if any): n/a
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari): n/a
* Device (e.g. iphonex): n/a

I think this is fairly straight forward. It borders between feature request and bug.

**Comment by yousif-bugsnag** [comment]
Hi @thomashzhang,

Thanks for the suggestion, but CLI tools such as `bugsnag-expo-cli` should only be modifying static config files such as `app.json`. Dynamic config files such as `app.config.js` should be manually updated by the developer: https://docs.expo.dev/workflow/configuration/#configuration-resolution-rules 

The CLI tool simply adds in the Bugsnag API key and a `postPublish` hook for uploading source maps - if you don't have an `app.json` you should follow our manual setup guide to add the same to your `app.config.js` file: https://docs.bugsnag.com/platforms/react-native/expo/manual-setup/
