### ISSUE TITLE
Building with XCode fails : main.jsbundle.map could not be found

### ISSUE THREAD

**Issue by lc3t35** [bugsnag/bugsnag-js#1607]
### Describe the bug
When build with XCode, react-native / Expo SDK43 using "@bugsnag/react-native": "^7.14.1", here is the error : 

```
/bin/sh -c /Users/laurent/Library/Developer/Xcode/DerivedData/Shares-ffxwshugamgcxphhliriheesafcu/Build/Intermediates.noindex/ArchiveIntermediates/Shares/IntermediateBuildFilesPath/Shares.build/Release-iphoneos/Shares.build/Script-F1942C4D17D945208F03C662.sh

Error: SOURCE_MAP /var/folders/mw/kg3_gh9j26n8qd_w2sxkgkhm0000gn/T//884bc07e99d40030ad4d5ab846c7f5ac-main.jsbundle.map could not be found.
Ensure the --sourcemap-output option is passed to the react-native bundle command.
Command PhaseScriptExecution failed with a nonzero exit code
```

### Steps to reproduce
1. npx @bugsnag/react-native-cli init
2. build with XCode

### Environment
* Bugsnag version: 7.14.1
* Device (e.g. iphonex): XCode

**Comment by mattdyoung** [comment]
Hi @lc3t35 

When you say "build with XCode", I assume you're talking about an Expo app that you've ejected to the bare workflow with `expo eject` in order to work with it in XCode?
https://docs.expo.dev/bare/exploring-bare-workflow/

We believe we've reproduced the issue you describe and we're just looking into how to resolve.

**Comment by mattdyoung** [comment]
Hi @lc3t35 

We've identified the issue and will be preparing a fix.

A workaround until the fix is released would be to add the following into the Xcode project's "Bundle React Native code and images" build phase (before the `react-native-xcode.sh` script is called):
```
export EXTRA_PACKAGER_ARGS="--sourcemap-output $TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"
```

**Comment by luke-belton** [comment]
Hi @lc3t35 - just to let you know that a [fix](https://github.com/bugsnag/bugsnag-js/pull/1623) for this was released in [`v7.14.2`](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.14.2) of `bugsnag-js` 🎉

**Comment by systemlevel** [comment]
> 

This does not work to fix the issue for us.

**Comment by xander-jones** [comment]
@systemlevel can you let us know some more details about the error that you're seeing, what steps you're taking in the run up to the issue, your configuration and environment?

**Comment by systemlevel** [comment]
> @systemlevel can you let us know some more details about the error that you're seeing, what steps you're taking in the run up to the issue, your configuration and environment?

Thank you, we ran through the standard installation steps in your installation guide. We are running the latest React Native 0.67.2.

The setup CLI script automatically tried to add `export EXTRA_PACKAGER_ARGS="--sourcemap-output $TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"` and I verified it was in there as well.

Android works but iOS is erroring out.

**Comment by yousif-bugsnag** [comment]
Hi @systemlevel, please can you share some more details about the exact error you're seeing, as well as some more details about your setup? 

Is your project an ejected Expo app? What versions of Expo and Xcode are you using? Can you share the contents of both your 'Bundle React Native code and images' and 'Upload source maps to Bugsnag' build phase scripts?

 If you'd prefer you can send these details to us directly at support@bugsnag.com

**Comment by luke-belton** [comment]
@systemlevel - we haven't heard anything from you on this in a little while so we're not going to progress this any further at this stage, but do let us know if you can share any additional details and we'd be happy to investigate 👍
