### ISSUE TITLE
Hard crash on launch iOS at [BugsnagBreadcrumb objectValue] (BugsnagBreadcrumb.m:105:37)

### ISSUE THREAD

**Issue by evelant** [bugsnag/bugsnag-js#1625]
### Describe the bug
My app crashes immediately after launch on iOS, presumably when the first breadcrumb is added with

```
NSInvalidArgumentException: -[__NSArrayI objectForKeyedSubscript:]: unrecognized selector sent to instance 0x283eb3900

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  CoreFoundation          -[NSObject(NSObject) doesNotRecognizeSelector:]
3  CoreFoundation          ____forwarding___
4  CoreFoundation          ___forwarding_prep_0___
5  MyApp                -[BugsnagBreadcrumb objectValue] (BugsnagBreadcrumb.m:105:37)
6  MyApp                -[BugsnagBreadcrumbs dataForBreadcrumb:] (BugsnagBreadcrumbs.m:217:21)
7  MyApp                -[BugsnagBreadcrumbs addBreadcrumbWithBlock:] (BugsnagBreadcrumbs.m:113:20)
8  MyApp                -[BugsnagClient addBreadcrumbWithBlock:] (BugsnagClient.m:861:5)
9  MyApp                -[BugsnagClient leaveBreadcrumbWithMessage:metadata:andType:] (BugsnagClient.m:594:5)
10 MyApp                +[Bugsnag leaveBreadcrumbWithMessage:metadata:andType:] (Bugsnag.m:183:9)
11 MyApp                -[BugsnagReactNative leaveBreadcrumb:] (BugsnagReactNative.m:82:9)
12 CoreFoundation          ___invoking___
13 CoreFoundation          -[NSInvocation invoke]
14 CoreFoundation          -[NSInvocation invokeWithTarget:]
15 MyApp                -[RCTModuleMethod invokeWithBridge:module:arguments:] (RCTModuleMethod.mm:584:3)
16 MyApp                facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) (RCTNativeModule.mm:183:17)
17 MyApp                facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const (RCTNativeModule.mm:104:7)
```

This may have happened after a minor version bump from bugsnag. It began when I created a new iOS build.

### Steps to reproduce
1. Launch iOS app, immediate crash
2. See crash from bugsnag in bugsnag

### Environment
* Bugsnag version: "@bugsnag/react-native": "^7.14.1",
* Browser framework version (if any):
    * Vue:
    * React:
    * Angular:
* Server framework version (if any):
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex): iPhone 13 mini iOS 15.1.1

<details><summary>Error messages:</summary>

```
see above
```
</details>

**Comment by yousif-bugsnag** [comment]
Hi @AndrewMorsillo, thanks for the report.

> My app crashes immediately after launch on iOS, presumably when the first breadcrumb is added

Are you making any calls to `Bugsnag.leaveBreadcrumb` or `console.log` prior to the app crashing? If so, can you share the kind of data are you attempting to add as breadcrumb metadata? (by default Bugsnag will automatically capture log messages as breadcrumbs)

Are these crashes being reported to Bugsnag? If so, please can you share a link to the error in your Bugsnag Dashboard so that we can take a look? You can drop a link here or write in to us at support@bugsnag.com

**Comment by xander-jones** [comment]
Closing this out as we've not heard anything further, but do let us know if you've got some more details behind the crash.
