### ISSUE TITLE
Expo SDK44 - @expo/bugsnag using expo-constants "~12.1.3" breaks build

### ISSUE THREAD

**Issue by lc3t35** [bugsnag/bugsnag-js#1629]
### Describe the bug
With @bugsnag/expo@^7.14.1 it is impossible to build the app because of incorrect expo-modules-core used by expo-constants "~12.1.3"

Please update @bugsnag/expo for SDK44 using "expo-constants": "~13.0.0", this will remove dependency on expo-modules-core@0.4.9.

### Steps to reproduce

after npx bugsnag-expo-cli init
Yarn.lock contains : 

```
"@bugsnag/expo@^7.14.1":
  version "7.14.1"
  resolved "https://registry.yarnpkg.com/@bugsnag/expo/-/expo-7.14.1.tgz#abca70a5b456ad41c6554c58d5286778d1dfa2c7"
  integrity sha512-QqrB8c6dipxfhRxoYkN7oIXsvFBuykHcErntakWpZX6FFV+bJHOAK4Ijqg3ICP1UjseBvaicFoWEzaxzJYHrKw==
  dependencies:
    "@bugsnag/core" "^7.14.0"
    "@bugsnag/delivery-expo" "^7.14.0"
    "@bugsnag/plugin-browser-session" "^7.14.0"
    "@bugsnag/plugin-console-breadcrumbs" "^7.14.0"
    "@bugsnag/plugin-expo-app" "^7.14.0"
    "@bugsnag/plugin-expo-device" "^7.14.0"
    "@bugsnag/plugin-network-breadcrumbs" "^7.14.1"
    "@bugsnag/plugin-react" "^7.14.0"
    "@bugsnag/plugin-react-native-app-state-breadcrumbs" "^7.14.0"
    "@bugsnag/plugin-react-native-connectivity-breadcrumbs" "^7.14.0"
    "@bugsnag/plugin-react-native-global-error-handler" "^7.14.0"
    "@bugsnag/plugin-react-native-orientation-breadcrumbs" "^7.14.0"
    "@bugsnag/plugin-react-native-unhandled-rejection" "^7.14.0"
    "@bugsnag/source-maps" "^1.0.1"
    bugsnag-build-reporter "^1.0.1"
    expo-constants "~12.1.3"
```

I had to remove @bugsnag/expo package from the build which is not good ;)

**Comment by lc3t35** [comment]
As a workaround, until you solve this issue, Expo's team member @tsapeta suggested adding a 'resolutions' item in package.json : 

```
"resolutions": {
  "**/expo-constants": "~13.0.0"
}
```

I didn't test this as I removed bugsnag until the issue is solved.

**Comment by xander-jones** [comment]
Hey @lc3t35, Expo SDK 44 is not yet supported. But we'll keep you posted here when support for Expo SDK 44 is added.

**Comment by kennethlynne** [comment]
Any timeline in when SDK44 will be supported?

**Comment by djskinner** [comment]
Expo SDK v44 is now supported in the latest release [v7.15.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.15.0)

**Comment by xander-jones** [comment]
Release v7.15.0 encountered an issue, and was patched in https://github.com/bugsnag/bugsnag-js/releases/tag/v7.15.1, please use this release instead 😄
