### ISSUE TITLE
React Navigation plugin: capture route params

### ISSUE THREAD

**Issue by swrobel** [bugsnag/bugsnag-js#1631]
### Description
It's nice that I can see the route names that the user is navigating to/from, but route params are important for knowing exactly what version of a screen they're on. It would be great if these were captured/displayed.

**Comment by luke-belton** [comment]
Hi @swrobel - have you considered using an [`onBreadcrumb` callback](https://docs.bugsnag.com/platforms/react-native/react-native/customizing-breadcrumbs/#discarding-and-amending-breadcrumbs) to add the route params to navigation breadcrumbs yourself?

**Comment by yousif-bugsnag** [comment]
Closing this as we haven't had a response but we're happy to revisit this if the solution above doesn't work for you.
