### ISSUE TITLE
null is not an object (evaluating 'this.bugsnagClient.Event')

### ISSUE THREAD

**Issue by c2ofh** [bugsnag/bugsnag-js#1632]
### Describe the bug
Bugsnag logs a bugnsag error

### Environment
* Bugsnag version:7.9.2
* Browser framework version (if any):
    * Angular: 10.2.5
* Browser version (e.g. chrome, safari):

![image](https://user-images.githubusercontent.com/10913793/148034974-76510c69-b8e7-4fd0-9879-25b2242a2a15.png)

### Breadcrumbs
![image](https://user-images.githubusercontent.com/10913793/148037131-0ed72a11-5985-4861-9020-dc8f7e61b9a4.png)

### Occuring error
![image](https://user-images.githubusercontent.com/10913793/148037182-45f01dd4-5bf1-4e43-abdf-7d3cfd33b1f8.png)

```
TypeError null is not an object (evaluating 'this.bugsnagClient.Event')      
  node_modules/@bugsnag/plugin-angular/__ivy_ngcc__/dist/esm2015/index.js:30:41 handleError     
  node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28109:49 next     
  node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:24923:37      
  node_modules/rxjs/_esm2015/internal/Subscriber.js:183:20 __tryOrUnsub     
  node_modules/rxjs/_esm2015/internal/Subscriber.js:122:34 next   
  node_modules/rxjs/_esm2015/internal/Subscriber.js:72:30 _next     
  node_modules/rxjs/_esm2015/internal/Subscriber.js:49:23 next  
  node_modules/rxjs/_esm2015/internal/Subject.js:39:29 next     
  node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:24913:19 emit     webpack:/node_modules/zone.js/dist/zone-evergreen.js:134:49 run     
  node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27581:17 onHandleError     
  webpack:/node_modules/zone.js/dist/zone-evergreen.js:181:55 runTask     
  webpack:/node_modules/zone.js/dist/zone-evergreen.js:487:41 invokeTask
```

### Example code snippet
**app.module.ts**
```ts
...
import { BugsnagErrorHandler } from '@bugsnag/plugin-angular';
...
export function errorHandlerFactory() {
  return new BugsnagErrorHandler();
}
...
@NgModule({
  declarations: [...],
  imports: [...]
  providers: [{provide: ErrorHandler, useFactory: errorHandlerFactory}, ...] 
```

First when the user has accepted the analytics cookies and data transfer, bugsnag will be initialized.

**app.component.ts**
```ts
bugsnagClient: any

observeBugsnagEnabled() {
  ...cookies.subscribe((cookies: CookieSetting) => {
     if (cookies.analytics) {
       this.startBugsnag();
     } else {
       this.bugsnagClient = undefined;
     }
  })
}

startBugsnag() {
  this.bugsnagClient = this.bugsnagClient || bugsnag.start({
    apiKey: environment.bugsnag_id,
    appVersion: environment.version,
    enabledBreadcrumbTypes: ['error', 'log', 'navigation', 'request', 'user'],
    autoTrackSessions: true,
    collectUserIp: false,
    generateAnonymousId: false,
    releaseStage: environment.name,
    enabledReleaseStages: ['production', 'staging']
  });
  this.setBugsnag();
}

setBugsnag() {
  if (this.bugsnagClient) {
    this.bugsnagClient.setUser(this.guest?.id || '0')
    this.bugsnagClient.addOnError(event => {
      if (event.originalError instanceof FirebaseError) {
        return false;
      }

      if (this._module?.type) {
        event.context = this._module.pretty_mode ? this._module.type + ' : ' + this._module.pretty_mode : this._module.type;
      } else {
        event.context = window.location.pathname;
      }

      event.addMetadata('user',
        {
          id: this.guest?.id || 0,
          name: this.guest?.name || '',
          locale: this.guest?.locale || ''
        }
      );

      const regex = new RegExp('zone.js|@angular|rxjs');
      event.errors[0].stacktrace.forEach(function (frame) {
        frame.inProject = !regex.test(frame.file);
      });
    });
  }
}
```

**Comment by xander-jones** [comment]
Hey @c2ofh, there seems to be a bit of left-over v6-style Bugsnag usage in your codebase perhaps, leading to the issue. I can replicate the error using Bugsnag in the way you are:

```js
export class AppComponent {
  obj = Bugsnag.start('YOUR_API_KEY');

  // this function is triggered by the 'handled' button in app.component.html
  triggerHandledError() {
    try {
      throw Error("Bad thing!");
    } catch (e) {
      this.obj.notify(e);
    }
}
```

This results in the same error you're seeing (albeit without source mapping)

![image](https://user-images.githubusercontent.com/9535852/148562311-b2240072-c187-4d74-987b-60225528daeb.png)

However, if you use Bugsnag as per the docs here: https://docs.bugsnag.com/platforms/javascript/angular/, you'll get functionality as expected:

```js
Bugsnag.start('YOUR_API_KEY');
// .. setup code removed for brevity

export class AppComponent {
  // this function is triggered by the 'handled' button in app.component.html
  triggerHandledError() {
    try {
      throw Error("Bad thing!");
    } catch (e) {
      Bugsnag.notify(e);
    }
  }
}
```

![image](https://user-images.githubusercontent.com/9535852/148563794-7efc7ae0-cc18-4831-89cd-15e5110985f7.png)

From v7, `Bugsnag` is a singleton object and should be used as such. Your `app.module.ts` configuration looks fine. However, where you're configuring Bugsnag you should be doing something as follows:

```diff
- bugsnagClient: any

observeBugsnagEnabled() {
  ...cookies.subscribe((cookies: CookieSetting) => {
     if (cookies.analytics) {
       this.startBugsnag();
-     } else {
-       this.bugsnagClient = undefined;
     }
  })
}

startBugsnag() {
-  this.bugsnagClient = this.bugsnagClient || bugsnag.start({
+  Bugsnag.start({ 
    apiKey: environment.bugsnag_id,
    appVersion: environment.version,
    enabledBreadcrumbTypes: ['error', 'log', 'navigation', 'request', 'user'],
    autoTrackSessions: true,
    collectUserIp: false,
    generateAnonymousId: false,
    releaseStage: environment.name,
    enabledReleaseStages: ['production', 'staging']
  });
  this.setBugsnag();
}

setBugsnag() {
-  if (this.bugsnagClient) {
-    this.bugsnagClient.setUser(this.guest?.id || '0')
+  Bugsnag.setUser(this.guest?.id || '0')
// etc
```

Then, from anywhere else in your app, if you need to use Bugsnag, you can just `import Bugsnag from '@bugsnag/js' and access the `Bugsnag` object to call methods.

**Comment by c2ofh** [comment]
@xander-jones I saved it in `bugsnagClient`, because I need to know if it is already initialized.  
Is there a function to check this with the Singleton `Bugsnag`?

**Comment by xander-jones** [comment]
@c2ofh, there's no public API to check if Bugsnag is instantiated, as it is designed to be launched from the beginning of your application. You could in theory check for the presence of `Bugsnag._client`, but this is a private API so I can't guarantee this won't change without warning.

Why do you need to know if Bugsnag is already initialized? Perhaps we can offer a better solution here? As you're just checking whether the call to start Bugsnag has been made, you could equally just set a global var to see whether the user has accepted your tracking, but switch to using `Bugsnag.fn()` calls.

**Comment by c2ofh** [comment]
@xander-jones yeah, good point. I made changes as you've mentioned, but the same error still occures, when an error occurs.
![image](https://user-images.githubusercontent.com/10913793/148836446-1e176a4c-c04f-41d5-8964-4f38d4ba06cf.png)

But I think if the user now changes his setting and I then set bugsnagEnabled to false, it will continue to send the session and errors.

Unfortunately this is very important, because otherwise we get problems because of the Europe Data protection under GDPR.

**app.component.ts**
```js
import Bugsnag from '@bugsnag/js'```js

bugsnagEnabled: boolean

observeBugsnagEnabled() {
  ...cookies.subscribe((cookies: CookieSetting) => {
     if (cookies.analytics) {
       this.startBugsnag();
     } else {
       this.bugsnagEnabled = false;
     }
  })
}

startBugsnag() {
  if (!this.bugsnagEnabled) {
    Bugsnag.start({
      apiKey: environment.bugsnag_id,
      appVersion: environment.version,
      enabledBreadcrumbTypes: ['error', 'log', 'navigation', 'request', 'user'],
      autoTrackSessions: true,
      collectUserIp: false,
      generateAnonymousId: false,
      releaseStage: environment.name,
      enabledReleaseStages: ['production', 'staging']
    });
    this.bugsnagEnabled = true;
    this.setBugsnag();
  }
}

setBugsnag() {
  if (this.bugsnagEnabled) {
    Bugsnag.setUser(this.guest?.id || '0')
    Bugsnag.addOnError(event => {
      if (event.originalError instanceof FirebaseError) {
        return false;
      }

      if (this._module?.type) {
        event.context = this._module.pretty_mode ? this._module.type + ' : ' + this._module.pretty_mode : this._module.type;
      } else {
        event.context = window.location.pathname;
      }

      event.addMetadata('user',
        {
          id: this.guest?.id || 0,
          name: this.guest?.name || '',
          locale: this.guest?.locale || ''
        }
      );

      const regex = new RegExp('zone.js|@angular|rxjs');
      event.errors[0].stacktrace.forEach(function (frame) {
        frame.inProject = !regex.test(frame.file);
      });
    });
  }
}
```

**Comment by xander-jones** [comment]
If the user is able to change their cookie option during runtime of the application, I would highly encourage you to make use of `onError` and `onSession` callbacks instead. Make a check at the top of each callback to see whether `cookies.analytics` allows the transmission of the event or session, and if not reject it.

* https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#discarding-events
* https://docs.bugsnag.com/platforms/javascript/capturing-sessions/#discarding-and-amending-sessions

How is the event being thrown where you're seeing that error?

**Comment by c2ofh** [comment]
@xander-jones I will take care of those callbacks. This seems really to be the right way.
I've just added in a view an output of an undeclared variable

````html
{{ notDefined }}
```

**Comment by xander-jones** [comment]
Ah, I think this might be because you're configuring the Angular plugin before instantiating Bugsnag. As `app.module.ts` bootstraps `app.component.ts`, any render errors before Bugsnag is instantiated have no sink. If you instead start Bugsnag _before_ the call to `@NgModule({...` this should resolve your issue. Now you're using callbacks to disable reporting where not wanted, you should be able to configure Bugsnag as per the installation docs.

**Comment by c2ofh** [comment]
@xander-jones 
```ts
export function errorHandlerFactory() {
  return new BugsnagErrorHandler();
}
```
is already place before `@NgModule({...`

**Comment by pavloldev6** [comment]
I have been dealing with the same issue and it's insane. I see it in an Angular application. I have setup Bugsnag as instructed in documentation by having a BugsnagErrorHandler instantiated as ErrorHandler factory and also calling Bugsnag.start in the app.component's ngOnInit(). I'm getting an unhandled error upon application start however that error is being obscured by this Bugsnag error:
_zone.js:182 Uncaught TypeError: Cannot read properties of null (reading 'Event')
    at BugsnagErrorHandler.handleError (index.js:30)
    at Object.next (core.mjs:26030)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at EventEmitter_.next (Subject.js:39)
    at EventEmitter_.emit (core.mjs:22416)
    at core.mjs:25498
    at ZoneDelegate.invoke (zone.js:372)_

What I actually see reported in the Bugsnag dashboard is the Bugsnag's error but not the actual application error.

**Comment by c2ofh** [comment]
@xander-jones 
I have cleaned out a bit.

So I start `bugsnag(self)` in the app.compents.ts.
I've added the two callbacks in.

Unfortunately the session is still sent when `enabled` is `false`. 
I also tested it with `reject()`, but even with that the session is tracked. 

**app.compents.ts**
```ts
export class AppComponent implements OnInit {
  ...

  constructor(private router: Router
              private globals: Globals,
              private location: Location,
              private api: ApiService) {
    this.bugsnag(this);
  }

  ...

  bugsnag(self) {
    Bugsnag.start({
      apiKey: environment.bugsnag_id,
      appVersion: environment.version,
      releaseStage: environment.name,
      autoTrackSessions: true,
      autoDetectErrors: true,
      collectUserIp: false,
      generateAnonymousId: false,
      enabledBreadcrumbTypes: ['error', 'log', 'navigation', 'request', 'user'],
      enabledReleaseStages: ['development', 'production', 'ickarus', 'torted'],
      onError: (_event) => {
        new Promise((resolve, reject) => {
          self.globals.bugsnagEnabled().then(enabled => {
            enabled ? resolve() : resolve(false)
          })
        })
      },
      onSession: (_session) => {
        new Promise((resolve, reject) => {
          self.globals.bugsnagEnabled().then(enabled => {
            enabled ? resolve() : resolve(false)
          })
        })
      }
    });
  }
}
```

**globals.ts**
```ts
bugsnagEnabled(): any {
  return new Promise((resolve) => {
    this.guestService.cookieSubj.pipe(filter(Boolean)).subscribe((cookies: CookieSetting) => {
      resolve(cookies.analytics)
    });
  })
}
```

**Comment by yousif-bugsnag** [comment]
Hi @c2ofh and @pavloldev6,

I've now been able to reproduce the error you're seeing - the error happens because you are calling `Bugsnag.start()` after the Angular plugin (`BugsnagErrorHandler`) has been initialised, and so when errors are caught by the `errorHandlerFactory` it does not have a reference to the Bugsnag client.

`Bugsnag.start()` should not be called from `app.component.ts` - instead it should be called as early in your app as possible, and before the Angular plugin is initialised, i.e. before the call to  `@NgModule({...`

We have an Angular example app that demonstrates how to initialise Bugsnag correctly: https://github.com/bugsnag/bugsnag-js/tree/next/examples/ts/angular

**Comment by c2ofh** [comment]
@yousif-bugsnag thank you for the information.
But at app.module I can't get the information I need in the OnError / OnSession Callback to define, if I'm allowed to send the information. This information I will get first, if the system was initialized. 

Unfortunately, there is no possibility to change the settings of `autoTrackSessions` and `autoDetectErrors` at a later time.

I started a weird experiment, which seems to work. But it's not very pretty.
I change a variable in the session object which is 0 by default. If sending is allowed, I change the value to 1
In the error event I've added a metadata value, which is normaly undefined or after I have the user information true or false 

This is a workaround that works, but I am not happy with it.

**app.module.ts**
```ts
Bugsnag.start({
  apiKey: environment.bugsnag_id,
  appVersion: environment.version,
  releaseStage: environment.name,
  autoTrackSessions: true,
  autoDetectErrors: true,
  collectUserIp: false,
  generateAnonymousId: false,
  enabledBreadcrumbTypes: ['error', 'log', 'navigation', 'request', 'user'],
  enabledReleaseStages: ['production', 'ickarus', 'torted'],
  onError: (event) => {
    return (<any>event)._metadata?.block?.show || false;
  },
  onSession: (session) => {
    return (<any>session)._handled === 1
  }
});

export function errorHandlerFactory() {
  return new BugsnagErrorHandler();
}
```

**app.component.ts**
```ts
Bugsnag.addOnError( (event) => {
  this.globals.bugsnagMeta(event)
  event.addMetadata('block', { send: this.bugsnagEnabled() && !(event.originalError instanceof FirebaseError) })
})
Bugsnag.addOnSession((session) => {
  (<any>session)._handled = this.bugsnagEnabled() ? 1 : 0
})
```

**Comment by yousif-bugsnag** [comment]
Thanks @pavloldev6, we'll look to see if we can make the docs a bit clearer on that.

@c2ofh I would not recommend altering `session._handled` in this way as this is a private property and is used for tracking the number of events that occur in a session.

Ultimately this will come down to how you handle state in your app, but you should be able to achieve what you're after without disabling `autoTrackSessions` or `autoDetectErrors`, and with a single set of `onError` and `onSession` callbacks. 

For example you could initialise Bugsnag with a user id of 0 and then later in your app when the user logs in or settings change update the user id by calling `Bugsnag.setUser()`: https://docs.bugsnag.com/platforms/javascript/angular/customizing-error-reports/#adding-user-data 

Both the event and session objects have a `getUser()` method,  so you callbacks could then simply check if the user id has been set: 

```js
Bugsnag.start({
  apiKey: environment.bugsnag_id,
  appVersion: environment.version,
  releaseStage: environment.name,
  autoTrackSessions: true,
  autoDetectErrors: true,
  collectUserIp: false,
  generateAnonymousId: false,
  enabledBreadcrumbTypes: ['error', 'log', 'navigation', 'request', 'user'],
  enabledReleaseStages: ['production', 'ickarus', 'torted'],
  user: {
    id: '0'
  },
  onError: (event) => {
    return event.getUser().id !== '0';
  },
  onSession: (session) => {
    return session.getUser().id !== '0';
  }
});

export function errorHandlerFactory() {
  return new BugsnagErrorHandler();
}
```

And later in your app:
```js
// Enable error and session reporting
 Bugsnag.setUser('non-zero-id');
```

**Comment by xander-jones** [comment]
Let us know if you have any further questions on the usage of Bugsnag at support@bugsnag.com
