### ISSUE TITLE
NextJS Bugsnag example is outdated

### ISSUE THREAD

**Issue by LucasLemanowicz** [bugsnag/bugsnag-js#1638]
The NextJS + Bugsnag integration in the docs links to an example that is built on NextJS 7 (+ React 16.5) and has not been updated in over 2 years now (https://github.com/bugsnag/bugsnag-js/tree/next/examples/js/nextjs). NextJS is currently on version 12, React is on 17.0 (with support for hooks introduced in 16.8), and a lot more developers are also now using Typescript.

Can you please update the example to properly integrate with NextJS 12 (and preferably also with Typescript)?

A non-exhaustive list of things that should be updated:

1. If I follow the setup in the example, I get `[bugsnag] Bugsnag.start() was called more than once. Ignoring.` errors in the console. In order to fix it I needed to wrap the `Bugsnag.start()` method in an `if (!(Bugsnag as any)._client) {` block. (see: https://github.com/bugsnag/bugsnag-js/issues/811#issuecomment-703853628)
2. If I follow the example, NextJS warns me of `warn  - You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.`. Probably worth adding a simple 404 page example (and even showcasing how Bugsnag can capture 404 errors)
3. The typing for the custom _error class is at best ambiguous, but quite likely wrong (what is in `ctx`? The TS definition requires the ErrorBoundary FallbackComponent to have these props: `{ error: Error, info: React.ErrorInfo, clearError: () => void }` yet the example checks for `err` - where is `err` coming from? Is it even still correct?)
4. APIs have been added since NextJS 7. Add example to show handling of api server-side errors

You are likely losing customers during the trial period, and possibly even more pre-trial period by making it hard to integrate with NextJS.

**Comment by luke-belton** [comment]
Hi @LucasLemanowicz - thanks for the details, we've noted this to take into account when we update the Next.JS example as priorities allow. I don't currently have a timeframe that I can share for this as Vercel/Next.JS aren't currently officially supported by Bugsnag.

In the meantime I'm going to close this issue out - in future this can be tracked over at #811.
