### ISSUE TITLE
Support plugin-react-navigation V6

### ISSUE THREAD

**Issue by Gregoirevda** [bugsnag/bugsnag-js#1644]
### Description
Currently @bugsnag/plugin-react-navigation has a peer dependency on @react-navigation/native V5

**Describe the solution you'd like**
Add support for @react-navigation/native V6

**Comment by johnkiely1** [comment]
Hi @Gregoirevda. 

Thanks for raising this.
We will look to update as soon as priorities allow.

**Comment by luke-belton** [comment]
Hi @Gregoirevda - we've just released a new version of `bugsnag-js` ([`v7.16.2`](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.16.2)), which allows `@react-navigation/native` `v6` as a peer dependency 🎉

**Comment by Gregoirevda** [comment]
Thank you @luke-belton working well
