### ISSUE TITLE
Vue3: Two hits to sessions.bugsnag.com on each route change

### ISSUE THREAD

**Issue by bbotto-pdga** [bugsnag/bugsnag-js#1697]
### Describe the bug
My team is in the process of upgrading from Vue 2 to Vue 3:

* in our Vue 2 app, each time a route changes we see ONE post to session.bugsnag.com;
* after upgrading to Vue 3, we see TWO posts to sessions.bugsnag.com.

### Steps to reproduce

I've attached a small zip archive with reproduction code.  Unzip it, install deps, then run the code:

```
unzip vue-bs-repro
cd vue-bs-repro
npm install
```
Update `src/main.js` with a valid API key on line 32.

Run the app:

```
npm run dev
```

Open http://localhost:3001/first-page in a browser.  Note that each time a link is clicked in the app, there are two posts to sessions.bugsnag.com.  Below is a screenshot that shows the network requests after opening the aforementioned link, then navigating one time using the link on the page:
![session-screenshot](https://user-images.githubusercontent.com/76966373/157141966-bb81b250-e732-4288-805b-73dad3ff5a86.png)

If I recreate the same code in Vue 2, I see only one hit to session.bugsnag.com on each route change.

### Environment
* Bugsnag version: 7.16.1
* Browser framework version (if any):
    * Vue: NOTE: The reproduction code is not using the `@bugsnag/plugin-vue` dependency, although it has it specified in package.json.
* Server framework version (if any):
    * None/SPA
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex):
[vue-bs-repro.zip](https://github.com/bugsnag/bugsnag-js/files/8201704/vue-bs-repro.zip)

**Comment by bbotto-pdga** [comment]
After digging in to this further, I don't think that this is a bug with Bugsnag.  Sorry for the noise.

For the record, the new Vue Router (`vue-router@4`) does a `replaceState` and a `pushState` each time the route changes.  ([See lines 283 and 292.](https://github.com/vuejs/router/blob/v4.0.13/src/history/html5.ts#L283-L292))  As documented, Bugsnag's automatic session tracking is triggered on each call, so twice per navigation.

Vue 3's router differs from Vue 2's, which just does a `pushState`.  ([See line 61.](https://github.com/vuejs/vue-router/blob/v3.5.3/src/history/html5.js#L61))

**Comment by luke-belton** [comment]
Hi @bbotto-pdga - thanks for bringing this to our attention.

Although this isn't strictly an issue with Bugsnag in the sense that `bugsnag-js` is behaving as documented whenever the URL changes via Vue router's `pushState`/`replaceState` events, we're still going to investigate this to see if there's anything we can do to improve the behaviour in this area 👍

**Comment by bbotto-pdga** [comment]
Thanks @luke-belton.  I read through #1071 prior to adding this issue and ended up going with manual session tracking.  After reading up on the subject, I think we should have been using manual session tracking all along, even in Vue 2.  For us, our Vue application is an SPA.  We now start a single session when the SPA is loaded--no new sessions on route change.
