### ISSUE TITLE
Expo[WEB] + V 7.16.2 - You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by biller-aivy** [bugsnag/bugsnag-js#1704]
We are using Expo SDK 44 and we get the error: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 

We fixed the version to 7.16.1 but the dependencies Childs are 7.16.2 than because of the ^. 

"@bugsnag/expo@7.16.1":
  version "7.16.1"
  resolved "https://registry.yarnpkg.com/@bugsnag/expo/-/expo-7.16.1.tgz#e757dc23cdce44e7627668f35e46d1cfc9e20f7f"
  integrity sha512-PPQjBy8qk9xWsmSFlQwudb46d/UqE+VRinnzMAYKUzKFWxiOjTOlXlPBBXzb52MDs8ZCa1WVnxuRaprUmuuaeA==
  dependencies:
    "@bugsnag/core" "^7.16.1"
    "@bugsnag/delivery-expo" "^7.16.1"
    "@bugsnag/plugin-browser-session" "^7.16.1"
    "@bugsnag/plugin-console-breadcrumbs" "^7.16.1"
    "@bugsnag/plugin-expo-app" "^7.16.1"
    "@bugsnag/plugin-expo-device" "^7.16.1"
    "@bugsnag/plugin-network-breadcrumbs" "^7.16.1"
    "@bugsnag/plugin-react" "^7.16.1"
    "@bugsnag/plugin-react-native-app-state-breadcrumbs" "^7.16.1"
    "@bugsnag/plugin-react-native-connectivity-breadcrumbs" "^7.16.1"
    "@bugsnag/plugin-react-native-global-error-handler" "^7.16.1"
    "@bugsnag/plugin-react-native-orientation-breadcrumbs" "^7.16.1"
    "@bugsnag/plugin-react-native-unhandled-rejection" "^7.16.1"
    "@bugsnag/source-maps" "^2.3.0"
    bugsnag-build-reporter "^1.0.1"
    expo-constants "~13.0.0"

**Comment by biller-aivy** [comment]
run expo build:web and get this error: 

```
./node_modules/@bugsnag/plugin-expo-app/app.js 32:29
Module parse failed: Unexpected token (32:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|     client.addOnSession(session => {
>       if (Constants.manifest?.revisionId) {
|         session.app.codeBundleId = Constants.manifest.revisionId
|       } else if (Constants.manifest2?.extra?.expoClient?.revisionId) {
./node_modules/@bugsnag/plugin-expo-device/device.js 34:36
Module parse failed: Unexpected token (34:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         reactNative: rnVersion,
|         expoApp: Constants.expoVersion,
>         expoSdk: Constants.manifest?.sdkVersion || Constants.manifest2?.extra?.expoClient?.sdkVersion,
|         androidApiLevel: Constants.platform.android ? String(Platform.Version) : undefined
|       },
Failed to compile.

./node_modules/@bugsnag/plugin-expo-app/app.js 32:29
Module parse failed: Unexpected token (32:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|     client.addOnSession(session => {
>       if (Constants.manifest?.revisionId) {
|         session.app.codeBundleId = Constants.manifest.revisionId
|       } else if (Constants.manifest2?.extra?.expoClient?.revisionId) {
```

**Comment by xander-jones** [comment]
Hey @biller-aivy, we don't currently support Expo (or React Native more broadly) for Web at present. We're tracking this feature request here: https://github.com/bugsnag/bugsnag-js/issues/1038, but I don't have an ETA of when this would be worked on I'm afraid. 

If you're seeing the same or similar issue when building for Android or iOS though please do let us know, and I'll re-open the issue to investigate further.

**Comment by giaset** [comment]
The version of Webpack used by Expo doesn't support optional chaining, so you need to run some of the Bugsnag modules through Babel first. Here's what worked for me:

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: [
          '@bugsnag/expo',
          '@bugsnag/plugin-expo-app',
          '@bugsnag/plugin-expo-device'
        ]
      }
    },
    argv
  );
  return config;
```
