### ISSUE TITLE
upload source maps from Expo EAS  Build

### ISSUE THREAD

**Issue by white-room** [bugsnag/bugsnag-js#1706]
### Description
@bugsnag/expo provides a `postPubllish` hook to conveniently use with `expo publish` but there's not a corresponding hook for projects built with EAS using `eas build`.

**Describe the solution you'd like**
A drop in hook like `@bugsnag/expo/hooks/post-publish.js` to upload source maps from `eas build` similar to `expo publish`.

**Describe alternatives you've considered**
Write our own hook using [@bugsnag/source-maps](https://docs.bugsnag.com/build-integrations/js/#uploading-source-maps) from [EAS Build-specific npm hooks](https://docs.expo.dev/build-reference/how-tos/#eas-build-specific-npm-hooks) such as `eas-build-pre-upload-artifacts`.

**Comment by johnkiely1** [comment]
Hi @white-room, 

At the moment we don't offer official support for `eas build`, but this is something we plan to consider in the future. Thanks for the suggestion and we will take that into consideration at the same time. As of right now we don't have definitive timeframes on this but we will update here as soon as we have any more information to share.

**Comment by slytter** [comment]
This feature is very important in order to fully support Expo, as `expo build` will be depricated January 4, 2023.

**Comment by dubchoi** [comment]
Is there a workaround here while this is being worked on?
I believe many teams are moving to EAS builds because many other dependencies have stopped updating/supporting `expo build`. If we can't find a solution, we don't see a path but to leave bugsnag entirely.

**Comment by yousif-bugsnag** [comment]
Hi @dubchoi, I'm afraid I don't have a workaround to share, however we are actively working on this at the moment. We're aiming to have a plugin for the EAS build mechanism available some time soon, and we'll be sure to update this issue when that is released.

**Comment by hardfire** [comment]
@yousif-bugsnag since this issue is real for us as well, i'd be curious if we have a timeline for the expo-plugin.

**Comment by thorbenprimke** [comment]
It's coming - https://github.com/bugsnag/bugsnag-expo/pull/42

**Comment by luke-belton** [comment]
Hi all - we've just released [`v45.1.1`](https://github.com/bugsnag/bugsnag-expo/releases/tag/v45.1.1) of `bugsnag-expo`, which updates our Expo CLI to automate the installation of the sourcemap plugin. Please check out [our docs](https://docs.bugsnag.com/platforms/react-native/expo/#showing-full-stacktraces) for more info on this!
