### ISSUE TITLE
update docs to clarify that `Bugsnag.getPlugin('react')` can return undefined

### ISSUE THREAD

**Issue by neb-b** [bugsnag/bugsnag-js#1721]
### Description
We recently had a production app crash because `Bugsnag.getPlugin('react')` began returning undefined. The error was `Can not read property 'createErrorBoundary' of undefined`

 I'm not sure of the exact reasons this happened but during the investigation I noticed the type definition for `getPlugin`
```
// add a new call signature for the getPlugin() method that types the react plugin result
declare module '@bugsnag/core' {
  interface Client {
    getPlugin(id: 'react'): BugsnagPluginReactResult | undefined
  }
}
```

**Describe the solution you'd like**
When setting up bugsnag I looked at the React integration on this page
https://docs.bugsnag.com/platforms/javascript/react/#basic-configuration

Since the official docs didn't say anything about `getPlugin` returning undefined I never thought I would need to add some additional checks to avoid a crash. It would be helpful if this page mentioned this fact, or if the example included some sort of extra check for undefined like this
```
const bugsnagReactPlugin = Bugsnag.getPlugin('react')
const BugsnagErrorBoundary = bugsnagReactPlugin?.createErrorBoundary(React) || React.Fragment
```

**Additional context**
my bugsnag initialization code is described in this comment https://github.com/bugsnag/bugsnag-js/issues/1112#issuecomment-1098298810

**Comment by luke-belton** [comment]
Hi @neb-b - thanks for raising this, I've responded to you over on #1112, but quoting my reply here too for visibility:

> Bugsnag.getPlugin('react') would only return undefined if BugsnagPluginReact is not passed into the Bugsnag.start() plugins property, or if Bugsnag.getPlugin('react') is called before Bugsnag.start().

We're going to update our docs to clarify that `Bugsnag.start` needs to be called with a valid `apiKey` prior to calling `getPlugin`.
