### ISSUE TITLE
Error when built archive 

### ISSUE THREAD

**Issue by Salmankhan033** [bugsnag/bugsnag-js#1758]
I put the same API key I was used in the free trial account now it was expired.
The app runs on the simulator but can't build an archive
see the image and help me, please!
I search out more but can't find any solution
<img width="965" alt="Screenshot 2022-06-08 at 7 36 04 PM" src="https://user-images.githubusercontent.com/58082294/172650016-6d0d8e1b-430e-4a19-b863-83ed8a16c2ad.png">

**Comment by Salmankhan033** [comment]
Use the Rocket.chat react native code the use the bugsang.
Here is the error screenshot
<img width="763" alt="Screenshot 2022-06-11 at 1 53 11 AM" src="https://user-images.githubusercontent.com/58082294/173148719-22b337f2-6f62-4a9e-89ac-afab2f5ab599.png">

**Comment by johnkiely1** [comment]
Hi @Salmankhan033, we have not heard from you on the related support ticket. It would be good if you could provide some more information on that as there are some outstanding questions. I'm going to go ahead and close this for now but happy to re-open if you can give us some more information to investigate.
