### ISSUE TITLE
@bugsnag/electron: Can't resolve fs/path/other node dependencies when bundling renderer process with webpack

### ISSUE THREAD

**Issue by donovanhiland** [bugsnag/bugsnag-js#1766]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I'm bundling javascript for the project I'm working on with webpack. When I import `@bugsnag/electron` from my renderer process webpack starts complaining about missing dependencies (node dependencies). It seems it's trying to bundle the "main.js" codepath in `src/notifier.js`.

I went through a couple different variations of a solution until I landed on this one using the browser field in the package.json. Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@bugsnag/electron/package.json b/node_modules/@bugsnag/electron/package.json
index c95596e..e1ce4e3 100644
--- a/node_modules/@bugsnag/electron/package.json
+++ b/node_modules/@bugsnag/electron/package.json
@@ -47,5 +47,8 @@
     "@bugsnag/plugin-window-onerror": "^7.17.0",
     "@bugsnag/plugin-window-unhandled-rejection": "^7.17.0"
   },
+  "browser": {
+    "./src/client/main.js": "./src/client/renderer.js"
+  },
   "gitHead": "e8ce8f9b486a8985db4c1f71a90194f383c995f6"
 }
```

This tells the bundler that when it's bunding code meant for the browser to replace imports from "./src/client/main.js" with "./src/client/renderer.js" which fixes the issue. Because both imports are the same it has the added benefit of removing some dead code in the renderer environment (when dead code removal is turned on). This doesn't apply to the code bundled for the node environment. This is the bundled output without dead code removal:

```javascript
let createClient
const isMain = typeof process !== 'undefined' && process.type === 'browser'
if (isMain) {
  createClient = __webpack_require__(/*! ./client/main */ "./release/app/node_modules/@bugsnag/electron/src/client/renderer.js")
} else {
  createClient = __webpack_require__(/*! ./client/renderer */ "./release/app/node_modules/@bugsnag/electron/src/client/renderer.js")
}
```
after compression/tree shaking:
```javascript
let createClient;
const isMain = "undefined" != typeof process && "browser" === process.type;
createClient = __webpack_require__(9630);
```

Thought it might be worth a shout out and maybe a PR, thoughts?

**Comment by johnkiely1** [comment]
Hi @donovanhiland closing this out as we haven't heard from you. In order to progress this we could do with the information asked for above. Happy to reopen as required.
