### ISSUE TITLE
@bugsnag/react-native - Support React Native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by tom-sherman** [bugsnag/bugsnag-js#1767]
### Description
Support the new architecture to unlock users of the library to use new React and React Native features

**Describe the solution you'd like**
Support new architecture

**Describe alternatives you've considered**
None

**Additional context**

https://reactnative.dev/docs/new-architecture-library-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by johnkiely1** [comment]
Hi @tom-sherman , 

Thanks for the suggestion. We have now added an investigation into this to our backlog. 
As it’s still an experimental feature, we will need to take an initial look to see what’s involved and figure out if and how we could support it. We will however post any further updates about this here.

**Comment by tom-sherman** [comment]
@johnkiely1 Thanks! I would say at this point the new architecture is no longer experimental (altho the documentation is still in flux), it's an opt in mostly because third party libraries need time to update.

Switching on the new architecture is a blocker for using React 18 features, see https://reactnative.dev/docs/next/react-18-and-react-native

**Comment by shamilovtim** [comment]
Yeah it's not experimental and won't be optional in the future @johnkiely1

**Comment by LeviWilliams** [comment]
We are looking for this support as well, would be curious on updates here.

**Comment by evelant** [comment]
@johnkiely1 Any movement on this?  The new architecture is not experimental, it is stable. Many popular community libraries are supporting the new architecture now. Libraries such as Bugsnag which use the legacy architecture are now becoming blockers.

**Comment by johnkiely1** [comment]
Hi @evelant. No updates to report I'm afraid. Other priorities have meant we haven't been able to work on this yet but this is still on the backlog.

**Comment by evelant** [comment]
@johnkiely1 Do you have an idea of when this might get implemented? We may need to find an alternative bug reporting product if this falls more into the "not planned, not any time soon" category.

**Comment by shamilovtim** [comment]
You guys are going to lose a huge market over a very trivial amount of work. If you aren't already bleeding mobile customers over this. Failure to identify this work as critical is pointing at problems in your leadership or organizational decision making. You might want to tell your decision makers about this. This is work that could be done by a contractor. I'd do it for a cost if I had any free time but alas I do not.

**Comment by luke-belton** [comment]
Hi all - just wanted to provide another update on this. We are indeed committing effort into supporting Turbo Modules and this is something we are aiming to deliver as soon as we're able. However we have discovered an issue reporting unhandled events (i.e. JS exceptions).

Our testing has shown that unhandled events are not delivered when Turbo Modules are enabled. There appears to be a difference in event handling at the time of the exception with Turbo Modules enabled and the message isn't getting sent over the bridge to our native handler. Significant efforts are being made to track down the cause of this issue, but with it only being apparent with Hermes and in production builds, it is proving a tricky issue to debug and fix.

As always we will keep this thread updated with our progress, and apologies for any inconvenience in the meantime.

**Comment by efstathiosntonas** [comment]
Hi @luke-belton is there any update on this? Thanks

**Comment by mclack** [comment]
Hi @efstathiosntonas
We are continuing to work on this and are hoping to have more updates soon.
As always, we will report any developments on this thread as we have them.

**Comment by tomlongridge** [comment]
Thanks for your patience on this – we've had some particularly tricky issues to track down in getting the library to work consistently with the new features. However, I'm pleased to say that [v7.21.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.21.0) now supports the New Architecture (in particular Turbo Modules).
