### ISSUE TITLE
@bugsnag/react-native - Fatal errors for RN 0.69.0

### ISSUE THREAD

**Issue by greenafrican** [bugsnag/bugsnag-js#1769]
### Describe the bug
The following error occurs when trying `yarn run ios` on a clean RN 0.69.0 repo with latest Bugsnag package:
```
../AppDelegate.mm:1:9: fatal error: 'Bugsnag/Bugsnag.h' file not found
#import <Bugsnag/Bugsnag.h>
```

And an error occurs trying `yarn run android`:
```
MainApplication.java:3: error: package com.bugsnag.android does not exist
import com.bugsnag.android.Bugsnag;
                          ^
.../TestRN69Bugsnag/android/app/src/main/java/com/testrn69bugsnag/MainApplication.java:56: error: cannot find symbol
    Bugsnag.start(this);
```

### Steps to reproduce
1. new RN project using `npx react-native init TestRN69Bugsnag`
2. `cd TestRN69Bugsnag`
3. `npx @bugsnag/react-native-cli init` (using all default options)
4. `yarn && cd ios && pod install && cd..`
5. `yarn start`
6. `yarn run iOS` or `yarn run android`
7. fails with error above

I have tried this on my app's project and a clean repo and both have the same error.

### Environment
* "@bugsnag/react-native": "^7.17.0"
* "@bugsnag/source-maps": "^2.3.1",
* Browser framework version (if any):
    * "react": "18.0.0"
    * "react-native": "0.69.0"
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex): iPhone 13 (iOS 15.5) simulator

**Comment by kassemitani** [comment]
I have the same issue
