### ISSUE TITLE
Lambda - For Bugsnag call at end of function not getting logged

### ISSUE THREAD

**Issue by himanshufize** [bugsnag/bugsnag-js#1771]
### Describe the bug
The bugsnag log which gets called at the end in function is not logged. For making it work I have to make it async using Promise and setTimeout for 200ms.

### Steps to reproduce
1. Create a lambda handler in local
2. Initialise bugsnag from the handler.
3. Create a function that gets called from the handler and logs to bugsnag in catch block.
4. Run handler using AWS SAM.
5. Check if log from another function in different file get logged or not.

### Environment
* Bugsnag version: 7.17.0
* Browser framework version (if any):
    * Vue:
    * React:
    * Angular:
* Server framework version (if any):
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex):

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by luke-belton** [comment]
Hi @himanshufize - thanks for updating your post above with more details. Unfortunately I've been able to reproduce the issue you described. Are you able to share a cut-down reproduction example demonstrating the issue please? Feel free to share it with support@bugsnag.com 👍
