### ISSUE TITLE
Bugsnag request failed to complete

### ISSUE THREAD

**Issue by Salmankhan033** [bugsnag/bugsnag-js#1779]
I am making a release abb build of react-native.
The first time I built the abb but now can't build it.
give this error
> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Bugsnag request failed to complete

**Comment by johnkiely1** [comment]
Hi @Salmankhan033.

Could you give me a little more detail about the steps taken prior to this error happening. 
What commands are you using to build this? 
Also if you could include more of your log from around the time of the error it would be helpful. 

Thanks

**Comment by Salmankhan033** [comment]
Thanks for the quick response, 
I fixed the issue it's from my side.
Thanks

**Comment by Salmankhan033** [comment]
when  free trial ended the it give issues
