### ISSUE TITLE
React Native 0.69 support

### ISSUE THREAD

**Issue by AmirDoreh** [bugsnag/bugsnag-js#1792]
did the RN package start to support [new version of React Native ](https://reactnative.dev/blog/2022/06/21/version-069)?

**Comment by luke-belton** [comment]
Hi @AmirDoreh - this was also discussed over on https://github.com/bugsnag/bugsnag-js/issues/1769, and support for React Native 0.69 was released in `bugsnag-js` [`v7.17.1`](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.17.1). The latest version of `bugsnag-js` is [`v7.17.3`](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.17.3) 👍
