### ISSUE TITLE
Error: "No Bugsnag API Key set"  while creating release build with proguard enabled in react native android. 

### ISSUE THREAD

**Issue by samabl88** [bugsnag/bugsnag-js#1796]
React native :
"react": "17.0.2",
"react-native": "0.67.4",
"@bugsnag/react-native": "^7.17.3"

On react native side:

import Bugsnag from '@bugsnag/react-native'
Bugsnag.start({
  apiKey: 'ec93654e567XXXXXXXXXXXXXXXXXXXX3',
})

Added log in the bugsnag library to check the error:

 if (schema.apiKey) {
      console.log("schema ---- ",schema );
      // missing api key is the only fatal error
      console.log("config ---- ",config );
      if (!config.apiKey) throw new Error(**'No Bugsnag API Key set**')
      // warn about an apikey that is not of the expected format
      if (!/^[0-9a-f]{32}$/i.test(config.apiKey)) errors.apiKey = 'should be a string of 32 hexadecimal characters'
    }

log value of schema:
{ apiKey: 
       { defaultValue: [Function: defaultValue],
         message: 'is required',
         validate: [Function] },
      appVersion: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a string',
         validate: [Function: validate] },
      appType: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a string',
         validate: [Function: validate] },
      autoDetectErrors: 
       { defaultValue: [Function: defaultValue],
         message: 'should be true|false',
         validate: [Function: validate] },
      enabledErrorTypes: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an object containing the flags { unhandledExceptions:true|false, unhandledRejections:true|false }',
         allowPartialObject: true,
         validate: [Function: validate] },
      onError: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a function or array of functions',
         validate: [Function] },
      onSession: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a function or array of functions',
         validate: [Function] },
      onBreadcrumb: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a function or array of functions',
         validate: [Function] },
      endpoints: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an object containing endpoint URLs { notify, sessions }',
         validate: [Function: validate] },
      autoTrackSessions: 
       { defaultValue: [Function: defaultValue],
         message: 'should be true|false',
         validate: [Function: validate] },
      enabledReleaseStages: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an array of strings',
         validate: [Function: validate] },
      releaseStage: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a string',
         validate: [Function: validate] },
      maxBreadcrumbs: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a number ≤100',
         validate: [Function: validate] },
      enabledBreadcrumbTypes: 
       { defaultValue: [Function: defaultValue],
         message: 'should be null or a list of available breadcrumb types (navigation,request,process,log,user,state,error,manual)',
         validate: [Function: validate] },
      context: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a string',
         validate: [Function: validate] },
      user: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an object with { id, email, name } properties',
         validate: [Function: validate] },
      metadata: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an object',
         validate: [Function: validate] },
      logger: 
       { defaultValue: [Function: defaultValue],
         message: 'should be null or an object with methods { debug, info, warn, error }',
         validate: [Function: validate] },
      redactedKeys: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an array of strings|regexes',
         validate: [Function: validate] },
      plugins: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an array of plugin objects',
         validate: [Function: validate] },
      featureFlags: 
       { defaultValue: [Function: defaultValue],
         message: 'should be an array of objects that have a "name" property',
         validate: [Function: validate] },
      codeBundleId: 
       { defaultValue: [Function: defaultValue],
         message: 'should be a string',
         validate: [Function: validate] } }
         
         
         Log value of config ---- : 
         
          { **apiKey: null,**
      appVersion: undefined,
      appType: undefined,
      autoDetectErrors: true,
      enabledErrorTypes: 
       { unhandledExceptions: true,
         unhandledRejections: true,
         anrs: true,
         ndkCrashes: true,
         ooms: true },
      onError: [],
      onSession: [],
      onBreadcrumb: [],
      endpoints: 
       { notify: 'https://notify.bugsnag.com',
         sessions: 'https://sessions.bugsnag.com' },
      autoTrackSessions: true,
      enabledReleaseStages: null,
      releaseStage: 'production',
      maxBreadcrumbs: 25,
      enabledBreadcrumbTypes: 
       [ 'navigation',
         'request',
         'process',
         'log',
         'user',
         'state',
         'error',
         'manual' ],
      context: undefined,
      user: {},
      metadata: {},
      logger: 
       { debug: [Function],
         info: [Function],
         warn: [Function],
         error: [Function] },
      redactedKeys: [ 'password' ],
      plugins: [],
      featureFlags: [],
      codeBundleId: undefined }
      
      
      We can clearly see that apiKey is null.

**Comment by yousif-bugsnag** [comment]
Hi @samabl88, when using `@bugsnag/react-native` you will need to configure the API key in `AndroidManifest.xml` (and `Info.plist` for iOS) and not in the JS layer, as described in the docs: https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/#basic-configuration

I am going to close this issue as it looks like a misconfiguration but if that is not the case please provide some more details  of your setup and we can revisit it.

**Comment by samabl88** [comment]
Hi @yousif-bugsnag 
I have used the API key in Manifest now. But still getting the same issue: 
React native :
"react": "17.0.2",
"react-native": "0.67.4",
"@bugsnag/react-native": "^7.17.3"

On react-native side:

import Bugsnag from '@bugsnag/react-native'
Bugsnag.start()


 <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:requestLegacyExternalStorage="true"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
        <meta-data android:name="com.bugsnag.android.API_KEY"
            android:value="****654e567*************c284603"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      
      
      
      Please check the above comment in the issue where I am getting:
      
       Log value of config ---- : 
     
      { **apiKey: null,**
  appVersion: undefined,
  appType: undefined,
  autoDetectErrors: true,
  enabledErrorTypes: 
  
  
  I have added these logs in bugsnag lib itself to check.
  
  Thanks

**Comment by samabl88** [comment]
The logcat trace of the same:

2022-08-02 14:55:41.358 26505-26652/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.ProjectName, PID: 26505
    com.facebook.react.common.JavascriptException: Error: No Bugsnag API Key set, stack:
    value@1407:2064
    s@1407:697
    _@1377:806
    p@1377:694
    start@1377:1767
    <unknown>@1376:130
    h@2:1585
    <unknown>@2009:142
    h@2:1585
    <unknown>@1983:160
    h@2:1585
    <unknown>@403:696
    h@2:1585
    <unknown>@6:53
    h@2:1585
    d@2:958
    global code@2099:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(SourceFile:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:27)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:226)
        at java.lang.Thread.run(Thread.java:920)
2022-08-02 14:55:41.369 1715-3192/? D/OplusAppStartupMonitor: notifyUnstableAppInfo: Bundle[{unstableTime=1659432341369, reason=crash, userId=0, safecenter=unstable, exceptionMsg=Error: No Bugsnag API Key set, stack:
    value@1407:2064
    s@1407:697
    _@1377:806
    p@1377:694
    start@1377:1767
    <unknown>@1376:130
    h@2:1585
    <unknown>@2009:142
    h@2:1585
    <unknown>@1983:160
    h@2:1585
    <unknown>@403:696
    h@2:1585
    <unknown>@6:53
    h@2:1585
    d@2:958
    global code@2099:3
    , exceptionClass=com.facebook.react.common.JavascriptException, packageName=com.Projectname, unstable_restrict_switch=true}]

**Comment by samabl88** [comment]
@yousif-bugsnag 
This error only occur when trying to create release build on Android with Proguard rules = true

**Comment by samabl88** [comment]
@yousif-bugsnag 
This issue is resolved now.

I need to comment below line from gradle.properties
android.enableR8.fullMode=true
