### ISSUE TITLE
Node.js integration crashes on Windows 7

### ISSUE THREAD

**Issue by FlyingDR** [bugsnag/bugsnag-js#1799]
Hello,

At this moment Node.js integration for Bugsnag crashes on Windows 7. The main reason is https://github.com/ericelliott/cuid/issues/263 which affects you due to [your fork](https://github.com/bugsnag/cuid) of this library, and you have one more reference to the `os.hostname()` function in your code:

https://github.com/bugsnag/bugsnag-js/blob/a129ec4cef2c48157a04513fef9bc51fe648a601/packages/node/src/config.js#L17

Since the required update is tiny and Windows 7 is still used by developers - I would want to propose adding a workaround for using a broken function in your code.

**Comment by luke-belton** [comment]
Hi @FlyingDR - thanks for raising this, we've noted this on our internal ticket tracking this issue so I'll close this issue out for now as a duplicate. We'll keep you updated over on https://github.com/bugsnag/bugsnag-js/issues/1783 👍
