### ISSUE TITLE
Bugsnag react native throws TypeError: undefined is not an object (evaluating 'navigator.userAgent.length') error

### ISSUE THREAD

**Issue by prrrthiksh** [bugsnag/bugsnag-js#1807]
### Describe the bug
Getting an error TypeError: undefined is not an object (evaluating 'navigator.userAgent.length') with the react native implementation
Please note that this happens with both manual and CLI setup
Probably similar to https://github.com/bugsnag/bugsnag-js/issues/1676

### Steps to reproduce
1. Setup bugsnag react native according to https://docs.bugsnag.com/platforms/react-native/react-native/
2. Call Bugsnag.start() in index.js
3. Run RN instance (react-native run-android/ios --variant debug) on android or iOS simulator

### Environment
"react": "17.0.2",
"react-native": "0.67.2",
"@bugsnag/react-native": "7.17.3",
"@bugsnag/source-maps": "2.3.1",
"@react-navigation/native": "6.0.11",
"@react-navigation/native-stack": "6.7.0",

#### iOS dependencies
pod **BugsnagReactNative 7.17.3**

#### Android dependencies
gradle plugin **com.bugsnag:bugsnag-android-gradle-plugin:5.+**

<details><summary>Error messages:</summary>

```
TypeError: undefined is not an object (evaluating 'navigator.userAgent.length')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

```
</details>

**Comment by Cga95** [comment]
Hi @prrrthiksh , I have responded via the support ticket you raised, but for the benefit of future users that come across this thread, we haven't been able to reproduce this issue given the above reproduction step. I will keep this thread updated if anything changes.

**Comment by johnkiely1** [comment]
Hi @prrrthiksh. Going to close this out as we haven't heard from you on the related support ticket. If you can help us with some of the outstanding questions on there we can investigate further. Thanks

**Comment by kennethlynne** [comment]
I am seeing this, too with Expo SDK 48 🤔 ..

<img width="407" alt="image" src="https://user-images.githubusercontent.com/390817/233341845-57094295-ebc9-4895-9707-91d0684f716a.png">

**Comment by prrrthiksh** [comment]
I had this issue happen to me while using `rnx-kit/metro-config`
Magically disappeared when I reverted back to the default metro config.

**Comment by HanggiAnggono** [comment]
I managed to fix the error by adding this patch on the Bugsnag client unique ID library

```patch
diff --git a/node_modules/@bugsnag/cuid/package.json b/node_modules/@bugsnag/cuid/package.json
index bc86e74..0ece09c 100644
--- a/node_modules/@bugsnag/cuid/package.json
+++ b/node_modules/@bugsnag/cuid/package.json
@@ -15,6 +15,7 @@
       "require": "./dist/index.js"
     },
     "./lib/fingerprint": {
+      "react-native": "./lib/fingerprint.react-native.mjs",
       "browser": "./lib/fingerprint.browser.mjs",
       "node": "./lib/fingerprint.mjs",
       "default": "./lib/fingerprint.react-native.mjs"
@@ -22,6 +23,7 @@
   },
   "imports": {
     "#fingerprint": {
+      "react-native": "./lib/fingerprint.react-native.mjs",
       "browser": "./lib/fingerprint.browser.mjs",
       "node": "./lib/fingerprint.mjs",
       "default": "./lib/fingerprint.react-native.mjs"

```
