### ISSUE TITLE
Doesn't play nice with node-source-map-support

### ISSUE THREAD

**Issue by dumbmatter** [bugsnag/bugsnag-js#181]
Despite what its name might suggest, I'm using [node-source-map-support](https://github.com/evanw/node-source-map-support) in a client-side JS app because otherwise [stack traces from Bluebird don't take advantage of source maps](https://github.com/petkaantonov/bluebird/issues/363).

I'm also using Bugsnag to log errors.

The problem is, when I have node-source-map-support and Bugsnag enabled at the same time, it goes quite poorly. I see errors like:

    Unhandled rejection NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://d2wy8f7a9ursnm.cloudfront.net/bugsnag-3.min.js'.
        at Error (native)
        at retrieveSourceMapURL (node_modules/source-map-support/source-map-support.js:100:1)
        at Array.<anonymous> (node_modules/source-map-support/source-map-support.js:130:1)
        at node_modules/source-map-support/source-map-support.js:43:1
        at mapSourcePosition (node_modules/source-map-support/source-map-support.js:160:1)
        at wrapCallSite (node_modules/source-map-support/source-map-support.js:327:1)
        at node_modules/source-map-support/source-map-support.js:362:1
        at Array.map (native)
        at Function.prepareStackTrace (node_modules/source-map-support/source-map-support.js:361:1)
        at CapturedTrace.get stack [as stack] (native)

And generally nothing works right.

My current solution is to have a toggle, to either enable Bugsnag (and log errors) or node-source-map-support (and see the actual file names and line numbers in my stack traces... and again, this is [independent of source maps](https://github.com/petkaantonov/bluebird/issues/363)!). But that is obviously not an ideal solution.

I don't know whether the problem is with Bugsnag or with node-source-map-support, but I figure you guys can at least help assess that :)

**Comment by kattrali** [comment]
Thanks for the report, @dumbmatter. I’ve had some trouble reproducing this issue, would it be possible to provide a gist of an example project? I’ve got some theories but haven’t been able to validate them.

**Comment by eanakashima** [comment]
Going to close this out for now, but if anyone comes up with a gist or example project that will help us reproduce, please comment and we'll take a look.
