### ISSUE TITLE
Request Drain Hook

### ISSUE THREAD

**Issue by gtowne** [bugsnag/bugsnag-js#1813]
### Description
In our Express application on shutdown we want to make sure that in-flight requests to Bugsnag have drained before we exit.

**Describe the solution you'd like**
It would be helpful if the SDK provided a method that we could call on shutdown where we could pass a callback to be called when outstanding requests have drained.

Example:
``` Javascript
Bugsnag.stop(() => {
    // in-flight requests have now drained
})
```

**Describe alternatives you've considered**
Our current workaround is to add an arbitrary delay on shutdown, but this negatively impacts restart times.

**Comment by luke-belton** [comment]
Hi @gtowne - thanks for raising this. Please could you tell us a bit more about your use case and what your main concerns are that mean you'd want to make sure in-flight requests are completed before your app exits? [By default](https://docs.bugsnag.com/platforms/javascript/express/configuration-options/#onuncaughtexception) for unhandled exceptions Bugsnag's Node.js notifier does keep the process alive for long enough to send the error report before logging the error and exiting with a non-zero status code, which is in line with the default Node.js behaviour.

If you e.g. had an issue with network connectivity that meant requests to Bugsnag weren't being delivered immediately - do you envision that you'd keep your app alive for long enough that these could be sent?

**Comment by gtowne** [comment]
Thanks for the quick reply, @luke-belton !

In our application there are some code paths on which we want to forcibly kill the process with `process.exit(1)` to allow it to more quickly be replaced. Before we do that, we want to make sure that the error that caused us to need to shutdown is fully reported to Bugsnag.

I don't anticipate issues with intermittent network connectivity like you describe will be an immediate need for us. When we get into one of these forcible shutdown scenarios I don't think we'd ever want to keep the process alive for more than a few seconds to report an error.

**Comment by luke-belton** [comment]
Hi @gtowne - apologies for the slow response on this one. Rather than using `process.exit(1)`, could you use [`server.close()`](https://nodejs.org/api/http.html#serverclosecallback) to prevent your server from accepting any new connections; this would give Bugsnag (and anything else in-progress) the opportunity to finish any in-flight requests before the process exits. For example something like:
```
app.get("/your_route", (req, res) => {

    //... your app code
	
	var healthy = checkIfServerHealthy()

	// decide to terminate the process
	if (!healthy) {
		// start a new event request to notify.bugsnag.com
		req.bugsnag.notify(new Error("Something went wrong - terminating"));

    	res.sendStatus(503);

		server.close();
	}
});

var server = app.listen(1234, () => {
  console.log("App listening at http://localhost:1234");
});
```

**Comment by johnkiely1** [comment]
Hi @gtowne. 

How did you get on with the suggestion above? Does this give you a suitable way forward? I'm going to close out the issue for now as we believe this should be the recommended solution.  Happy to reopen if necessary.

**Comment by mclack** [comment]
Hi @andrewzey 

If you're unable to use `server.close()` as an alternative workaround, then would you potentially be able to implement a wrapper to keep track of your app's network requests? For example, are you able to create a `new Set()` of `inFlightRequests`, and add a new `requestId` (maybe created using `Symbol()`) to `inFlightRequests` each time a request is made, and then once the request has finished you could delete the `requestId` from `inFlightRequests`? Once `inFlightRequests` no longer contains any BugSnag requests, you could then `process.exit(1)`.

Please let us know if something like this would be possible, or if there are any issues with this sort of approach.

**Comment by djskinner** [comment]
> I would like to second this request. We have a node script running in a cron job that needs to process.exit(1), but only after all Bugsnag events have been flushed. There is no server.close() method to use in this context.

I wonder if the in-flight plugin could be made use of for this. Something like:

```
const bugsnagInFlight = require('@bugsnag/in-flight')
bugsnagInFlight.trackInFlight(client)

const flushTimeoutMs = 1000 // resolve anyway after 1s even if all requests are not complete
await bugsnagInFlight.flush(flushTimeoutMs)
process.exit(1)
```
