### ISSUE TITLE
Rails 7 Front End integration?

### ISSUE THREAD

**Issue by softwaregravy** [bugsnag/bugsnag-js#1849]
Is there any advice on integrating with Rails 7 front end? I.e. stimulus and turbo?

Thanks

**Comment by luke-belton** [comment]
Hi @softwaregravy - we don't have any specific advice for those frameworks, however we'd generally recommend separate projects in Bugsnag for your Rails and JavaScript code using the respective notifiers for those platforms ([Rails](https://docs.bugsnag.com/platforms/ruby/rails/), [JavaScript](https://docs.bugsnag.com/platforms/javascript/#installation)).

If you're having trouble configuring Bugsnag in your apps, feel free to write into support@bugsnag.com and we'd be happy to explore this more with you 👍

**Comment by johnkiely1** [comment]
Hi @softwaregravy.  As we haven't heard anything from you in a while we are going to close this out. As Luke mentioned do write in to us at [support@bugsnag.com](mailto:support@bugsnag.com) as necessary.
