### ISSUE TITLE
Android JCenter

### ISSUE THREAD

**Issue by dawidchyrzynski** [bugsnag/bugsnag-js#1854]
### Describe the bug
Android build fails due to JCenter's unavailability.

### Steps to reproduce
Just try to build RN app with @bugsnag/react-native 7.18.1

### Environment
* Bugsnag version: 7.18.1
* React Native version: 0.69.4

### Error message

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':bugsnag_react-native:verifyReleaseResources'.
> Could not resolve all task dependencies for configuration ':bugsnag_react-native:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :bugsnag_react-native
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out
```

**Comment by iuliiaivanova** [comment]
I can reproduce it for:
@bugsnag/react-native: 7.14.1
react-native: 0.67.3

**Comment by vadim312** [comment]
me too

`* What went wrong:
A problem occurred configuring root project 'stoovo'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.bugsnag:bugsnag-android-gradle-plugin:5.+.
     Required by:
         project :
      > Failed to list versions for com.bugsnag:bugsnag-android-gradle-plugin.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml'.
               > Read timed out`

**Comment by JavoxirNazarov** [comment]
same

**Comment by henrymoulton** [comment]
> JCenter global issue check status https://status.gradle.com/incidents/c65zmfw32lpm

The link posted shows that the incident is resolved, however we're still experiencing this issue. https://jcenter.bintray.com/

**Comment by krishan-kumar-mourya** [comment]
Same for me

**Comment by shakawy** [comment]
new JCenter incident
https://status.gradle.com/incidents/9740r6bzx438

**Comment by shakawy** [comment]
I think package is not mirrored

![Screen Shot 2022-10-31 at 4 28 46 PM](https://user-images.githubusercontent.com/12873943/199032128-5db4c3c8-8464-4797-9e06-842b1d45234e.png)

**Comment by shakawy** [comment]
Build now is working fine!

**Comment by fusandy** [comment]
I have similar error below, not sure if it's the same.
But there was not any errors last week... lol

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.bugsnag:bugsnag-android-gradle-plugin:5.+.
     Required by:
         project :
      > Failed to list versions for com.bugsnag:bugsnag-android-gradle-plugin.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Failed to list versions for com.bugsnag:bugsnag-android-gradle-plugin.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/bugsnag/bugsnag-android-gradle-plugin/maven-metadata.xml'.
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by shakawy** [comment]
@fusandy what is the version of `com.android.tools.build:gradle` you are using?

**Comment by fusandy** [comment]
@shakawy  thanks for the reply! here's the dependencies. 

```
dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:5.+"
        classpath "com.google.gms:google-services:4.3.10"
}
```

**Comment by luke-belton** [comment]
Hi all - we believe the jCenter outage has now been resolved and there should be no further build issues.

We understand that builds were sometimes failing because of Bugsnag's internal dependencies which used the jCenter repository. We are also taking steps to mitigate any future issues should there be another jCenter outage, for example https://github.com/bugsnag/bugsnag-js/pull/1856 👍 

@fusandy if you're still experiencing problems, please feel free to write into support@bugsnag.com and we can help you investigate.
