### ISSUE TITLE
Permission denied to access property "apply"

### ISSUE THREAD

**Issue by bhmeister** [bugsnag/bugsnag-js#1867]
Has been fixed before here https://github.com/bugsnag/bugsnag-js/issues/608

### Describe the bug

In our production environment, we have error reports:
> Permission denied to access property "apply"

Line: `if (typeof prevOnError === 'function') prevOnError.apply(this, arguments);`
Source: `node_modules/@bugsnag/browser/dist/bugsnag.js`

### Environment
* Bugsnag version: 7.1.0
* Browser framework version (if any):
    * React: 16.12.0
* Browser version (e.g. chrome, safari): Firefox 102-106.0.0
* Device (e.g. iphonex):
    * Linux
    * WIndows 10

**Comment by luke-belton** [comment]
Hi @bhmeister - would you mind updating to the latest version of `bugsnag-js` to see if this helps resolve the issue please? The latest version is https://github.com/bugsnag/bugsnag-js/releases/tag/v7.18.2.

If the issue persists after updating we can investigate this further - it would be handy if you can share a full stacktrace/reproduction steps at that stage too please 👍

**Comment by bhmeister** [comment]
I can say that it's still happening in `7.18.0`. Don't know how to reproduce. Only additional info I can provide is that a few milliseconds before this bug gets recorded there are breadcrumbs such as these:

```
errorClass: Error
errorMessage: too much recursion
severity: error
```

```
errorClass: Error
errorMessage: ResizeObserver loop completed with undelivered notifications.
severity: error
```

Not sure if this is related or where this is coming from. It could be on our own end but then I'm not sure how it would influence bugsnag. Maybe it's a browser thing (only Firefox affected)...
So far it appears though that the volume has gone down since updating to `7.18.0`.

**Comment by johnkiely1** [comment]
Hi @bhmeister, 

Thanks for the update. Without a reproduction case for us to work with its going to be difficult for us to continue investigating this. I presume this error does not appear in the Bugsnag dashboard? How often is this occurring? Perhaps you could share your Bugsnag configuration code along with any callbacks you are implementing? Are you doing anything non standard in its or your project setup?

**Comment by bhmeister** [comment]
> Without a reproduction case for us to work with its going to be difficult for us to continue investigating this.

Understandable.

> I presume this error does not appear in the Bugsnag dashboard? 

It does.

> How often is this occurring?

150 all-time events in a 5 month window. Active user base is around 100k. Only 10 users are affected though. So I'm going to assume the problem is on their end. I can not share any more details on configuration. We're doing nothing out of the ordinary. 

Happy to close this, thanks.

**Comment by luke-belton** [comment]
Hi @bhmeister - if you're able to write into support@bugsnag.com with a link to these errors in your Bugsnag dashboard, we can investigate this further from there 👍

**Comment by johnkiely1** [comment]
Going to close this out. Do let us know if you are able to reproduce this reliably and we can reopen
