### ISSUE TITLE
SOURCE_MAP could not be found

### ISSUE THREAD

**Issue by rodrigobertolottizinsp** [bugsnag/bugsnag-js#1868]
### Describe the bug
After updating to react-native version 0.70 im not able to archive the project for iOS on Xcode, I was able to archive for react native 0.67 and 0.68. It seems like im not being able to generate the source maps automatically, or the place where the source map are saved or grabbed has changed, im taking a look at bugsnag-react-native-xcode.sh and try to find the issue there but no luck yet.

This is the error log im getting in Xcode:

Warning: SOURCE_MAP was not specified, falling back to /Users/rodrigobertolottizinsp/Library/Developer/Xcode/DerivedData/zinspector3-guxlphxgeuartsfaqwlwocehjcmh/Build/Intermediates.noindex/ArchiveIntermediates/zinspector3.prod/BuildProductsPath/Release-iphoneos/main.jsbundle.map
Error: SOURCE_MAP /Users/rodrigobertolottizinsp/Library/Developer/Xcode/DerivedData/zinspector3-guxlphxgeuartsfaqwlwocehjcmh/Build/Intermediates.noindex/ArchiveIntermediates/zinspector3.prod/BuildProductsPath/Release-iphoneos/main.jsbundle.map could not be found.
Ensure the --sourcemap-output option is passed to the react-native bundle command.
Command PhaseScriptExecution failed with a nonzero exit code 

### Steps to reproduce
Archive project

### Environment
* React Native: 0.70.5
* React: 18.1.0
* bugsnag/react-native: 7.17.3
* bugsnag/source-maps: 2.3.1

### Build phases: 

On build phases I have:  

Upload source map to Bugsnag:

if [ "$DEPLOYMENT_LOCATION" != "YES" ]; then
 echo "Skipping source map upload for developer build."
 exit 0
fi

../node_modules/@bugsnag/react-native/bugsnag-react-native-xcode.sh

Thank you very much in advance

**Comment by rodrigobertolottizinsp** [comment]
I was able to create the Archive doing this steps: 

On here: https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/ 
yo specify to add this in **Bundle React native code and images Xcode build phase** , 

```
+ export EXTRA_PACKAGER_ARGS="--sourcemap-output $TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"
set -e

export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

but the file bugsnag-react-native-xcode.sh we are trying BUNDLE_FILE like this:

``BUNDLE_FILE="$CONFIGURATION_BUILD_DIR/main.jsbundle"` and then defining `SOURCE_MAP="$BUNDLE_FILE.map"`
but really we are saving the file in `"$TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"` as it is specified on the tutorial I pasted the link above.

I was able to create the archive like this, but I had to modify am doing something wrong?

**Comment by luke-belton** [comment]
Hi @rodrigobertolottizinsp - apologies if our docs are unclear in this area or I am misunderstanding something, but it sounds like you've got to the point as described in our docs here: https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#source-maps, where you include the `SOURCE_MAP` environment variable when running the `bugsnag-react-native-xcode.sh` script?

Are you still having problems uploading your source maps or mapping events on React Native 0.70?

**Comment by rodrigobertolottizinsp** [comment]
Hi! Thanks for the reply.
What im trying to say is that the file saved in this line 
+ export EXTRA_PACKAGER_ARGS="--sourcemap-output $TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"
don't match the location of the file that the bugsnag-react-native-xcode.sh script is trying to find, that's why I had to replace 

SOURCE_MAP="$BUNDLE_FILE.map"

with 

SOURCE_MAP="$TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"

in the script file

**Comment by johnkiely1** [comment]
Hi @rodrigobertolottizinsp, 

I'm glad you have found a solution. This does align with what our current documentation would suggest regarding setting the SOURCE_MAP location. We have not made any changes in this area recently so I'm not sure why your previous configuration only started breaking now. We would have always recommended setting it like so

`SOURCE_MAP="$TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"`

I'm going to close this out as I don't believe there is anything on our side we need to fix.
