### ISSUE TITLE
hide PII div's in breadcrumbs

### ISSUE THREAD

**Issue by jhuangtw-dev** [bugsnag/bugsnag-js#188]
Hi there! is there a way to exclude elements that may contain PII info from BugSnag's breadcrumbs?
similar to this behavior: http://help.fullstory.com/spp/138664

**Comment by wordofchristian** [comment]
There isn't currently a UI for this like the behavior you described on full story. The best way to accomplish it would be with a [before notify hook](https://docs.bugsnag.com/platforms/browsers/customizing-error-reports/) . This let's you modify the exception payload before it is sent to Bugsnag.

```js
Bugsnag.beforeNotify = function(payload, metaData) {
  // Filter out sensitive information
  payload.breadcrumbs = payload.breadcrumbs.map(function(crumb){
    // Check 
    if(crumb.metaData.targetSelector.match(/SOMEREGEX/) {
      crumb.metaData.targetText = 'HIDDEN';
    }
    return crumb;
  });
}
```
