### ISSUE TITLE
Non working `autoBreadcrumbsConsole` preference

### ISSUE THREAD

**Issue by sidoruk-sv** [bugsnag/bugsnag-js#189]
This `if` checks only first condition, which usually returns `true` and any other conditions aren't checked:
```
if(!window.console || typeof window.console.log !== "function" || !getBreadcrumbSetting("autoBreadcrumbsConsole")) {
  return;
}
```

https://github.com/bugsnag/bugsnag-js/blob/d1a157861e15d67cfe7864c8879269a30e05e90a/src/bugsnag.js#L294

**Comment by wordofchristian** [comment]
The first condition only returns true if window.console is undefined. However, I think that we probably don't need the first two checks. We should just track the breadcrumb even if the browser doesn't support console logging.
