### ISSUE TITLE
Express plugin not capturing body when the type is not an object 

### ISSUE THREAD

**Issue by coxrichuk** [bugsnag/bugsnag-js#1890]
### Describe the bug
I am sending a string to an express app which I then have a text body parser (`bodyParser.text()`)

When the app then throws an error Bugsnag does not capture the body as the body is not an object

I have narrowed it down to 

https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-express/src/request-info.js#L21

### Environment
* Bugsnag version: ^7.2.1

* Server framework version (if any):
    * Express: ^4.18.1

**Comment by johnkiely1** [comment]
Hi @coxrichuk, 

Is this for a handled or unhandled error? Are you able to explain a little more around your use case for bodyParser.text() as we would obviously expect there to be an object at that point.  
 
If you could share any code or small reproduction example that demonstrates this, that would be useful.

**Comment by johnkiely1** [comment]
Hi @coxrichuk 
Going to close this out as we haven't heard from you in a while.  Happy to re-open if you can provide us with some of the additional information requested above.
