### ISSUE TITLE
Source maps not uploaded from Webpack

### ISSUE THREAD

**Issue by villesau** [bugsnag/bugsnag-js#1892]
### Steps to reproduce
1. Have following plugin for webpack prod:

```
  new BugsnagSourceMapUploaderPlugin({
    apiKey: '<Notifier API key>',
    appVersion: appVersion,
    publicPath, // the same variable as passed to the `output: {publicPath}`
    overwrite: true
  })
```

2. no source maps uploaded to bugsnag, latest source maps visible in bugsnag are from time when it was able to download them from the cdn.

### Environment
* Bugsnag version: 7.17.0
* Webpack version: 5.73.0

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
  new BugsnagSourceMapUploaderPlugin({
    apiKey: '<Notifier API key>',
    appVersion: appVersion,
    publicPath, // same variable as passed for the publicPath in `output: {publicPath}`
    overwrite: true
  })
```

<details><summary>Error messages:</summary>

```

```
</details>

In our case the source map plugin is the second latest plugin just before compression plugin. before moving to use upload, bugnsag was able to download the source maps from cdn. Now the latest source map visible on Bugsnag is before that time. However, the plugin does not explicitly fail in uploading so it at least looks like it would be working correctly while nothing actually ends up to bugsnag.

**Comment by johnkiely1** [comment]
Hey @villesau, we have responded to you on the support ticket raised, as we need some additional information to investigate further

**Comment by villesau** [comment]
Hi, @johnkiely1 I've not received any response to my email unfortunately.
