### ISSUE TITLE
Source map not being applied on fresh project

### ISSUE THREAD

**Issue by MorganTrudeau** [bugsnag/bugsnag-js#1908]
### Describe the bug
I have been debugging why my source map cannot be applied on Bugsnag. I stripped down my project to a single App component rendering an empty view and still my source map was not applied. I created a fresh react-native init project and still source map was not applied with this App component.

Turns out ```async componentDidMount()``` was breaking the source map. Removing ```async``` from ```componentDidMount``` resolved the issue. Here is the App component below...

```
import React from 'react';
import { View } from 'react-native';
import Bugsnag from '@bugsnag/react-native';

Bugsnag.start();

class App extends React.PureComponent {
  async componentDidMount() {
    Bugsnag.notify('test');
  }

  render() {
    return <View style={{ flex: 1 }} />;
  }
}

export default App;
```

I am confused why this can happen. Now I know a simple change like this can break my source map being applied I am unsure how to debug my source maps not being applied. Is this a bug or is there something I can do to prevent this? I appreciate any guidance anyone can provide. Thanks very much.

### Steps to reproduce
1. Create a new project on bugsnag and get the api key.
2. Create a new react-native project on version 0.70.5 using typescript ```npx react-native init newproject --template react-native-template-typescript@6.12.9```
3. Init bugsnag ```npx @bugsnag/react-native-cli init``` using lastest versions of everything and opt into deploying sourcemap during gradle build.
4. Replace ```App.tsx``` with App component snippet above.
5. Assemble release android build ```cd android && ./gradlew clean && ./gradlew assembleRelease```
6. Install the apk ```adb install app/build/outputs/apk/release/app-release.apk```
7. Open the app to report the "test" bug to bugsnag.
8. Open bugsnag inbox and view "test" error report. See the sourcemap cannot be applied.

### Environment
* @bugsnag/react-native version: 7.18.2
* @bugsnag/source-maps version: 2.3.1
*  Bugsnag Android gradle plugin: 7.+
* React-native version: 0.70.5

**Comment by johnkiely1** [comment]
Going to close this out in favour of continuing conversations via [support@bugsnag.com](mailto:support@bugsnag.com)
