### ISSUE TITLE
React Native 0.71 compatibility for Android

### ISSUE THREAD

**Issue by swrobel** [bugsnag/bugsnag-js#1910]
### Describe the bug
I upgraded my React Native app from 0.70 to 0.71 and it won't run anymore. I instead get the error:

```
Failed to initialise the native Bugsnag Android client, please check you have added Bugsnag.start() in the onCreate() method of your Application subclass, js engine: hermes
```

### Steps to reproduce
I followed the manual setup instructions [here](https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/) when I set up Bugsnag several React Native versions ago. It was working fine until the 0.71 upgrade which I know changed a lot of the gradle code under the code.

### Environment
* Bugsnag version: 7.18.0
* Device (e.g. iphonex): Android simulator

**Comment by mclack** [comment]
Hi @swrobel,

I’ve been investigating this but have been unable to reproduce the same error you are seeing so far, although we do think there may be some compatibility issues with the latest version of React Native and BugSnag.

Before we investigate further, have you double checked that the `Bugsnag.start()` has not been stripped out of your `onCreate()` method like the error suggests? It’s also worth checking your `AndroidManifest.xml` to make sure the BugSnag metadata is still there with your API key, as outlined here: https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/#basic-configuration

**Comment by deroke** [comment]
Hi @swrobel,

you should try this: https://docs.bugsnag.com/build-integrations/gradle/#installation
I had the same issue.

`<project_dir>/build.gradle`
```gradle
buildscript {
    dependencies {
        // ...
        classpath "com.bugsnag:bugsnag-android-gradle-plugin:7.+"
    }
}
```

`<project_dir>/<module_name>/build.gradle`
```gradle
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"
apply plugin: "com.bugsnag.android.gradle"
```

**Comment by swrobel** [comment]
> Before we investigate further, have you double checked that the `Bugsnag.start()` has not been stripped out of your `onCreate()` method like the error suggests?

@mclack I'm not sure what `onCreate()` is referring to, but if it's referring to some java code, I never had any calls to Bugsnag there, nor was I aware that I needed to have any. Nothing changed in my Bugsnag config from 0.70 to 0.71 - the config is all still in AndroidManifest.xml, and I still call `Bugsnag.start()` in my `index.js` file for my React Native app...

@deroke thanks for the tips, but I've had all of that `build.gradle` config in the right places since I added Bugsnag to my app, so nothing changed there with 0.71 either.

**Comment by johnkiely1** [comment]
Hi @swrobel, perhaps you may have originally used the cli to install Bugsnag which  as part of that process would have added a `Bugsnag.start()` call automatically to your java layer in the `MainApplication.java ` class. It would not have been possible to get Bugsnag to work without adding the calls in your native layers. 

For the current issue however, it's possible that this call has been lost as part of the upgrade from 0.70 to 0.71 as it may have modified the app. The default content contained within `MainApplication.java` has been known to change across RN versions. 

At this stage it would be worth checking each of the steps here: https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/ to ensure your application does contain all the necessary elements. Do let us know how you get on with this.

**Comment by swrobel** [comment]
Ok, it works now after adding `Bugsnag.start(this);` as shown below. I don't know how it ever worked before, as I never had this in there, but it works now!

```java
import com.bugsnag.android.Bugsnag;

public class MainApplication extends Application implements ReactApplication {
    @Override
    public void onCreate() {
        super.onCreate();
        Bugsnag.start(this);
        // ...
    }
}
```
