### ISSUE TITLE
Github releases for versions since 3.0.0

### ISSUE THREAD

**Issue by binhums** [bugsnag/bugsnag-js#192]
The releases page for this project doesn't show anything since the rc1 release for 3.0.0.

https://github.com/bugsnag/bugsnag-js/releases

I got some information from the changelog and the docs, I'm assuming we're at a point where 3.0.x is stable?

![image](https://cloud.githubusercontent.com/assets/831043/19014677/994bf65a-87eb-11e6-9e1b-ed1b76c7185e.png)

**Comment by jacobmarshall** [comment]
Versions newer than rc1 have still been tagged, but they're just not "releases" in GitHub. https://github.com/bugsnag/bugsnag-js/tags

**Comment by wordofchristian** [comment]
Should be addressed now. Thanks. I wonder if there is an easy way to automate this as part of the release script?

**Comment by binhums** [comment]
Thanks @wordofchristian. Are you using anything to enforce changelog entries on release? Perhaps there's a natural hook there.

**Comment by wordofchristian** [comment]
We have a [set of grunt commands](https://github.com/bugsnag/bugsnag-js/blob/master/CONTRIBUTING.md#releasing) used for releasing. Could probably add it there.
