### ISSUE TITLE
maxBreadcrumbs limit is still validated to be below 100

### ISSUE THREAD

**Issue by DaniilOvoshchnikov-TomTom** [bugsnag/bugsnag-js#1921]
### Describe the bug
maxBreadcrumbs limit has recently been increased to 500, but validation still requires it to be below 100: https://github.com/bugsnag/bugsnag-js/blob/9e02b9bf33e463579de4db24d583da60b72a2d7c/packages/core/config.js#L99 

### Steps to reproduce
1. increase max breadcrumbs to 500
2. observe yellowbox warning about incorrect config (in React-native)

### Environment
* Bugsnag version: 7.18.2
* Browser framework version (if any):
    * Vue:
    * React:
    * Angular:
* Server framework version (if any):
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari):
* Device (e.g. iphonex):

**Comment by johnkiely1** [comment]
Hi @DaniilOvoshchnikov-TomTom

Could you confirm how you are increasing the breadcrumb config? Are you doing it a Native or a JS layer level? Any code snippets you are using would be helpful. 

Could you also confirm if you are using React Native or Expo?

**Comment by johnkiely1** [comment]
Going to close this out as we haven't heard back from you. 

It's worth mentioning if you are using React Native you should set this config in the native layers, which allows up to 500 breadcrumbs be stored. 

If however you are using Expo this is still currently limited to 100.
