### ISSUE TITLE
Using @bugsnag/js with cypress

### ISSUE THREAD

**Issue by daiaimfirst** [bugsnag/bugsnag-js#1928]
code in ```test.cy.js```
```js
describe('My First Test', () => {
  it('Does not do much!', () => {
    var Bugsnag = require('@bugsnag/js');
    Bugsnag.start({
      apiKey: Cypress.env("API_KEY"),
    });
    Bugsnag.notify(new Error(`Error example`), null, (err, event) => {
      if (err) {
        console.log('Failed to send report because of:\n' + err.stack);
      } else {
        console.log('Successfully sent report "' + event.errors[0].errorMessage + '"');
      }
    });
  })
})
```
console till log ```Successfully sent report Error example```, but bugsnag dashborad never show it. And i can't see any error

**Comment by johnkiely1** [comment]
Hi @daiaimfirst, Would you be able to write in to support@bugsnag.com with some details about you Bugsnag account, namely which organisation and project do you expect this error to appear in. If you could also share the API key you are using that would be helpful.

**Comment by daiaimfirst** [comment]
Hi @johnkiely1. Thank you
I was find the reason. it seems Cypress test case doesn't use nodejs engine (browser). And here is my solution https://docs.cypress.io/api/commands/task (Execute code in Node)
