### ISSUE TITLE
delivery-xml-http-request `sendEvent` does not pass valid error when request fails.

### ISSUE THREAD

**Issue by KevinMind** [bugsnag/bugsnag-js#1929]
### Describe the bug

Bugsnag browser sets the delivery method to either XDomainRequest or XMLHttp request ([here](https://github.com/bugsnag/bugsnag-js/blob/9551d5173299f23740c93c8fa43569da5dcdf93e/packages/browser/src/notifier.js#L69)) based on the current browser.

When the delivery-xml-http-request package isused, it does not appropriately handle errors when sending requests.

According to the [docs](https://docs.bugsnag.com/platforms/javascript/restify/reporting-handled-errors/#post-report-callbacks) notify should accept a third argument `postReportCallback` function that expects to receive an `error` and the `event` passed to the notify function.

```js
Bugsnag.notify(new Error('uh oh'), null, function (err, event) {
  if (err) {
    console.log('Failed to send report because of:\n' + err.stack)
  } else {
    console.log('Successfully sent report "' + event.errors[0].errorMessage + '"')
  }
})
```

the xml-http-request package is instead passing [null](https://github.com/bugsnag/bugsnag-js/blob/aced3db494a4a779cb2911dbfbdd9e6c529c807c/packages/delivery-xml-http-request/delivery.js#L19), making it hard to reason about the nature of the error. It should instead create a new Error and pass this to the callback.

### Steps to reproduce

1. setup a bugsnag client using the js-browser library (follow [this](https://docs.bugsnag.com/platforms/javascript/#basic-configuration) guide)
2. enable one of the adblockers that block requests to notify.bugsnag.com
3. trigger an error using Bugsnag.notify and ensure to pass a postReportCallback

```js
Bugsnag.notify(new Error('somerthing'), undefined, (err, event) => console.log(err));
```

Expected Result: you get an error object in the callback if the request fails, you will get null if it passes. You can trigger this behaviour by enabling/disabling the adblocker

Actual Result: you get null always, making it impossible to know if the request succeeded. In our case, if we get failing calls to bugsnag, we want to proxy those calls to our app and send them server side to ensure we have visibility in all cases.

### Environment
* Bugsnag version: 7.20.0
* Browser framework version (if any): you don't need a framework
    * Vue:
    * React: Yes
    * Angular:
* Server framework version (if any):
    * Koa:
    * Express:
    * Restify:
* Browser version (e.g. chrome, safari): Chrome  110.0.5481.96 (Official Build) (arm64)
* Device (e.g. iphonex): Macbook M1 Pro

**Comment by KevinMind** [comment]
You can add error handlers for XMLHttpRequests: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/error_event

**Comment by matth-bugsnag** [comment]
Hi Kevin, 
Thanks for letting us know about this bug.
We have been able to re-produce it with what you have shared and will be looking into applying a bug fix. 
We will keep this issue updated with any developments.
