### ISSUE TITLE
Limit the number of breadcrumbs

### ISSUE THREAD

**Issue by siebertm** [bugsnag/bugsnag-js#193]
When using breadcrumbs, I noticed that they are never cleared or limited. In a long-running SPA, this can lead to significantly large breadcrumbs.

Our application, for example is to be opened once per day and then worked with the whole day without a reload or real page navigation.

I would suggest to limit the breadcrumbs to 50 (just a random number!) by default.

**Comment by wordofchristian** [comment]
We originally had a limit of 20, I don't recall why we removed it entirely. 50 sounds like a pretty good number.

**Comment by GrahamCampbell** [comment]
Is this something that needs to change across the other libraries too?

**Comment by GrahamCampbell** [comment]
Infinite breadcrumbs does sound bad though, in terms of payload size.

**Comment by eanakashima** [comment]
@siebertm ah good catch. Since we're using 20 in some of the other notifiers, let's stick with that for now. I'll open a PR with a fix.
