### ISSUE TITLE
Feature Request : Include a no-op Client

### ISSUE THREAD

**Issue by sakshamsaxena** [bugsnag/bugsnag-js#1930]
### Description

Right now, the way I instrument bugsnag client is on the basis of some config etc that varies with environment. Subsequent usage of notify also ends up on the same lines, which is weird because ideally I don't want to add instrumentation related checks inside my logic (or even in wrappers).

**Describe the solution you'd like**

`Client` should be an interface with the current implementation as a default implementation, and an additional no-op/dummy implementation that can be used as well so that in the actual app we're not messing about it.

**Describe alternatives you've considered**

I was almost halfway writing a bare minimal dummy client when I felt that this should definitely be a part of the core library itself.

**Additional context**

Willing to contribute/drop a PR to this, if the team is aligned.

**Comment by sakshamsaxena** [comment]
Sure. Adding a disclaimer that I'm currently using v6 but planning to upgrade to v7 shortly, so my snippets may not reflect v7 specific nuances / syntax.

Say I've a little wrapper module 
```

if (process.env.BUGSNAG_KEY) {
  bugsnagClient = bugsnag({
    apiKey: configs.bugsnagKey,
    autoNotify: true,
    releaseStage: configs.env,
    appVersion: configs.api.version,
    appType: 'API server'
  })
  bugsnagClient.use(bugsnagExpress)
}
```

Currently the expectation is that for non-production environments, `bugsnagClient` is assumed `null`, so such `null` checks get introduced across the codebase, something like this:

```
const bugsnagClient = require('../bugsnag') // the wrapper module

if (bugsnagClient) {
    bugsnagClient.notify( ... )
}
```

So to avoid such checks I ended up creating a default no-op client in the same wrapper module like:
```
var bugsnagClient = {
  getPlugin: (_plugin) => {
    return {
      requestHandler: (req, res, next) => next(),
      errorHandler: (req, res, next) => next()
    }
  },
  notify: (err, opts, cb) => {}
};
```

This helped me to get rid of `null` checks elsewhere in the project. However, I'd have preferred if I could have used bugsnag module to create a no-op client instead, something like:
```
bugsnagClient = bugsnag({
    dummy: true
  })
```

**Comment by johnkiely1** [comment]
Thanks @sakshamsaxena. 

It's worth mentioning in v7 we have the static Bugsnag accessors so there shouldn't be any need to create and pass around a null/no-op client explicitly. 

Reading in-between the lines a bit it sounds like you are looking for a way to disable BugSnag reporting in non production environments. If so you might be able to look at using [enabledReleaseStage](https://docs.bugsnag.com/platforms/javascript/configuration-options/#enabledreleasestages) as an alternative. This used in combination with setting a [releaseStage](https://docs.bugsnag.com/platforms/javascript/configuration-options/#releasestage) would allow you to configure Bugsnag to only report for `production` stages. Is this something that might work for you?

**Comment by johnkiely1** [comment]
@sakshamsaxena, I'm going to close this out on the basis that one of the above suggestions will suit your needs and we haven't heard form you in a while.
