### ISSUE TITLE
Failure to archive React Native iOS build caused by upload source maps script

### ISSUE THREAD

**Issue by The0racle** [bugsnag/bugsnag-js#1941]
### Describe the bug
The upload source maps run script is causing an error whenever I attempt to archive an iOS build in XCode. Issue seems to be related to one of `bugsnag/source-maps` dependency, [Consola](https://github.com/unjs/consola).

### Steps to reproduce
1. Install bugsnag on React Native app
2. Follow [this](https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#manual-setup) steps to automate source maps upload (use `npx @bugsnag/react-native-cli automate-symbolication
`).
3. Open XCode 14.2 and try to archive the build

### Environment
* Bugsnag version:    
`@bugsnag/react-native": "^7.19.0"`
`"@bugsnag/source-maps": "^2.3.1"`

* Browser framework version (if any):
    * React:    
    `"react": "17.0.2",`
    `"react-native": "0.66.5"`
* Device (e.g. iphonex): Archive for any iOS device (arm64)
* Node version: 14.7.5

<details><summary>Error messages:</summary>

```
/Users/xxxxxxxxxx/xxxxxxxxxxx/node_modules/consola/dist/consola.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";function u(u){return u&&"object"==typeof u&&"default"in u?u.default:u}var D=u(require("util")),e=require("path"),t=require("fs"),r=u(require("os")),n=u(require("tty"));"undefined"!=typeof globalThis?globalThis:"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self&&self;function s(u,D){return u(D={exports:{}},D.exports),D.exports}var o,i=(o=Object.freeze({__proto__:null,default:[{name:"AppVeyor",constant:"APPVEYOR",env:"APPVEYOR",pr:"APPVEYOR_PULL_REQUEST_NUMBER"},{name:"Bamboo",constant:"BAMBOO",env:"bamboo_planKey"},{name:"Bitbucket Pipelines",constant:"BITBUCKET",env:"BITBUCKET_COMMIT"},{name:"Bitrise",constant:"BITRISE",env:"BITRISE_IO",pr:"BITRISE_PULL_REQUEST"},{name:"Buddy",constant:"BUDDY",env:"BUDDY_WORKSPACE_ID",pr:"BUDDY_EXECUTION_PULL_REQUEST_ID"},{name:"Buildkite",constant:"BUILDKITE",env:"BUILDKITE",pr:

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/xxxxxxxx/xxxxxxxxxx/node_modules/@bugsnag/source-maps/dist/Logger.js:23:32)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
Command PhaseScriptExecution failed with a nonzero exit code
```
<img width="1521" alt="Screenshot 2023-03-28 at 4 12 13 PM" src="https://user-images.githubusercontent.com/4213174/228344248-3febc970-97e8-483d-b1db-321f1d0a94d2.png">

<img width="1229" alt="Screenshot 2023-03-28 at 4 18 52 PM" src="https://user-images.githubusercontent.com/4213174/228344694-91a4829f-dfeb-4f33-8f1f-c0c28acebe05.png">

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/4213174/228344662-3b7ef99a-132f-4a9d-acea-2b9bbf16c6e9.png">

</details>

**Comment by matth-bugsnag** [comment]
Hi Thiago,

Thanks for reaching out and apologies for the delay in response.

So far I have been unable to reproduce the error with `@bugsnag/source-maps` you have reported, when running an archive build using the following versions for an ARM64 device:

React: 17.0.2

React-Native 0.66.5

@bugsnag/react-native: 7.19.0

@bugsnag/source-maps: 2.3.1

So that we can continue investigating this could you provide us with a minimal reproduction project which throws the error you are seeing?

**Comment by johnkiely1** [comment]
Hey @The0racle, 

Going to close this out as we haven't heard from you and we are unable to reproduce. Happy to reopen as necessary if you can help us out with a repro project.
