### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by mMarcos208** [bugsnag/bugsnag-js#1944]
### Describe the bug

Undefined symbols for architecture x86_64

### Steps to reproduce
react-native run-ios

### Environment
"@bugsnag/plugin-react-navigation": "^7.19.0",
 "@bugsnag/react-native": "^7.19.0",

### Error

❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_Bugsnag
> Referenced from: objc-class-ref in AppDelegate.o

❌  ld: symbol(s) not found for architecture x86_64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by johnkiely1** [comment]
Hi @mMarcos208, 

To help us investigate could you write in to us at support@bugsnag.com and include some additional information: 

Which Bugsnag account and project is this relating to.  
Could you tell us how you have configured Bugsnag? Particularly all the Bugsnag references in your AppDelegate class. Any code snippets and or screen shots would be useful. 
Did you use the CLI tool or integrate Bugsnag manually?
What version of Xcode are you using? 
What version of React Native are you using?

Thanks

**Comment by mMarcos208** [comment]
I'm upgrade react native e Xcode, I'm using 

- Xcode 14.3
- React Native 0.71.6
- I'm using cli tool to configure

Running react-native run-ios

**Comment by johnkiely1** [comment]
Thanks.

> Could you tell us how you have configured Bugsnag? Particularly all the Bugsnag references in your AppDelegate class. Any code snippets and or screen shots would be useful.

Would you mind also providing the above to help us try and reproduce.
