### ISSUE TITLE
interaction-breadcrumbs.js click handler chokes on whitespace

### ISSUE THREAD

**Issue by alcohol** [bugsnag/bugsnag-js#1945]
### Describe the bug

Bugsnagjs has an issue with a page that contains somewhat questionable html markup. The page becomes completely frozen and chrome offers to kill it once I 'click' anywhere.

```
[Violation] 'click' handler took 85672ms bugsnag.min.js:1
```

It looks like in `interaction-breadcrumbs.js` the following value `let text = el.textContent || el.innerText || ''` contains an insane amount of whitespace, which is causing the `text = text.replace(/^\s+|\s+$/g, '') // trim whitespace` to basically take up an enormous amount of time. Since the next line is only taking the first 140 characters of this (`return truncate(text, 140)`), I reckon this could probably be improved upon somehow?

Additional details:

```javascript
el.textContent.length
// 438228

let txt = el.textContent
console.time('replace'); 
txt = txt.replace(/^\s+|\s+$/g, ''); 
console.timeEnd('replace');
// replace: 78925.93701171875 ms
```

**Comment by alcohol** [comment]
Cheers :-)

**Comment by alcohol** [comment]
Out of curiousity, how often is your CDN hosted version updated? We're still receiving 7.19.0 at https://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js

**Comment by imjoehaines** [comment]
> Out of curiousity, how often is your CDN hosted version updated? We're still receiving 7.19.0 at https://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js

Hey @alcohol, thanks for pointing this out! `v7.20.2` is now on the CDN
