### ISSUE TITLE
Possible to restart or start with new configuration

### ISSUE THREAD

**Issue by thuongtv-vn** [bugsnag/bugsnag-js#1964]
### Description

It should be possible to restart or start bugsnag again with new configuration if any changes.

**Describe the solution you'd like**

BugSnag.start(configs). It should be always possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by johnkiely1** [comment]
Hi @thuongtv-vn, 

Thanks for the suggestion. could you explain a little more about your use case, what would you expect to change?

**Comment by jcstringer** [comment]
I'm interested in this as well, following. My use case is when we intentionally change the release stage within the same application, and we want to reload bugsnag (or stop and start it again). AFAICT there is no way to do this in the current javascript API and it sounds like calling `start()` again won't actually reload it?

**Comment by johnkiely1** [comment]
Hi @jcstringer, can you explain your workflow in a little more detail.  How do you determine when you need to intentionally change the release stage? Any additional information you can share around your project setup and technologies used would also be helpful.

**Comment by hannah-smartbear** [comment]
Hi @jcstringer, I can see that you’ve opened a support request with this question. We can continue this conversation via that ticket

**Comment by johnkiely1** [comment]
@thuongtv-vn, have you seen the above message? It would be good to understand your use case.

**Comment by johnkiely1** [comment]
@thuongtv-vn Going to close this out as we would need some additional context to understand the reasons for considering a change like this. Happy to reopen if you can provide this.   

At present we do offer the ability to [add metadata](https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#addmetadata) that you could use  if you need to track specific information or changes that occur.
