### ISSUE TITLE
New library @bugsnag/plugin-hono

### ISSUE THREAD

**Issue by DarkGL** [bugsnag/bugsnag-js#1968]
### Description
I have noticed that there is no library similar to [@bugsnag/plugin-express](https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-express) designed for [hono](https://github.com/honojs/hono) 

**Describe the solution you'd like**
I would like a library that provides similar integration with hono as `@bugsnag/plugin-express` and `express.js`

**Additional context**
As `hono` continues to grow in popularity, I believe the development of such a library would be highly beneficial to the wider community.

**Comment by johnkiely1** [comment]
Hi @DarkGL, thanks for the suggestion, I've passed it on to our product team for consideration. We will post here with updates as we have them.

**Comment by efstathiosntonas** [comment]
@johnkiely1 hi, are there any updates on this one? Thanks

**Comment by clr182** [comment]
Hi @efstathiosntonas 

No update as of yet. When we do have an update we will be sure to update this thread with more information.

**Comment by efstathiosntonas** [comment]
@clr182 thanks for the update but I could not wait for 1.5 year 🤯

I switched do different bug tracker ever since.
