### ISSUE TITLE
Bugsnag is not defined & installVueErrorHandler() was called unnecessarily.

### ISSUE THREAD

**Issue by joshmakar** [bugsnag/bugsnag-js#1992]
### Describe the bug
I'm attempting to troubleshoot why Bugsnag is not receiving my test errors from my local environment. I'm troubleshooting by going through the [integration guide](https://docs.bugsnag.com/platforms/javascript/), but I'm getting a couple of issues when I follow the guide fully. I'm wanting to work through these two issues so I can eliminate them as possible causes for why Bugsnag is not receiving my errors.

When I attempt to run `Bugsnag.notify(new Error('test'))`, I get the following error.

> ReferenceError: Bugsnag is not defined

Note: I can add `window.Bugsnag = Bugsnag;` in my app.js file to resolve this error, but that's not in the directions so I don't know if that's correct.

I don't know if this has anything to do with it, but when following the instructions in the [integration guide](https://docs.bugsnag.com/platforms/javascript/), I'm getting the following warning.

> [bugsnag] installVueErrorHandler() was called unnecessarily

### Steps to reproduce
Follow the [integration guide](https://docs.bugsnag.com/platforms/javascript/).

### Environment
* Bugsnag version: 7.2.0
* Browser framework version (if any):
    * Vue: 2.7.0
* Browser version (e.g. chrome, safari): Chrome

### Example code snippet 

Here's the gist of how my app.js file is configured.
```js
import Bugsnag from '@bugsnag/js';
import BugsnagPluginVue from '@bugsnag/plugin-vue';

import Vue from 'vue';
window.Vue = Vue;

Bugsnag.start({
    apiKey: import.meta.env.VITE_BUGSNAG_API_KEY,
    plugins: [new BugsnagPluginVue()],
    enabledReleaseStages: ['production', 'staging'],
    releaseStage: import.meta.env.VITE_APP_ENV,
});

const bugsnagVue = Bugsnag.getPlugin('vue');
bugsnagVue.installVueErrorHandler(Vue);

// I can add this to stop the Bugsnag undefined error
// window.Bugsnag = Bugsnag;

new Vue({
    el: '#app',
});
```

And here is the gist of the component.
```js
<template>
    <div>
        Test
    </div>
</template>

<script>
export default {
    created() {
        Bugsnag.notify(new Error('Test error bugsnag direct'));
    },
}
</script>
```

And my .env (with API_KEY masked)
```
APP_ENV=production
BUGSNAG_API_KEY=################################
VITE_APP_ENV="${APP_ENV}"
VITE_BUGSNAG_API_KEY="${BUGSNAG_API_KEY}"
```
</details>

**Comment by clr182** [comment]
Hi @joshmakar 
It looks like the script you are using to call `notify()` is missing the import for Bugsnag which is resulting in the error `ReferenceError: Bugsnag is not defined.` 

It should look similar to this: 

`<template>
    <div>
        Test
    </div>
</template>

<script>
import Bugsnag from '@bugsnag/js'

export default {
    created() {
        Bugsnag.notify(new Error('Test error bugsnag direct'));
    },
}
</script>`

**Comment by joshmakar** [comment]
Thanks, @clr182. That's likely a more clean way to handle the _ReferenceError: Bugsnag is not defined_ as opposed to binding the class to the window object.

I'm still curious about the _[bugsnag] installVueErrorHandler() was called unnecessarily_ issue though.

Thanks!

**Comment by clr182** [comment]
Hi @joshmakar 

Could you please verify that you have removed the line `window.Vue = Vue;` from your `main.js` file and whether you are still receiving this unnecessary call to `installVueErrorHandler()` warning after removing it?

**Comment by clr182** [comment]
Hi,
As this issue hasn't seen any activity for some time I will be closing it out. Please feel free to reopen if there are any further questions.
