### ISSUE TITLE
not working with angular

### ISSUE THREAD

**Issue by jmchaves** [bugsnag/bugsnag-js#2005]
### Describe the bug
After the files have been uploaded correctly in bugsnag, the error does not show the source map. Keeps saying: 
```Ensure uploaded source maps match this version or make your JavaScript files accessible from our servers. (Note that events are not reprocessed after source maps are uploaded.)```

### Environment
* Bugsnag version: 
``` "@bugsnag/js": "^7.16.1" ```
``` "@bugsnag/plugin-angular": "^7.16.1"```
* Browser framework version (if any):
    * Angular: 13.2.2

![Screenshot from 2023-08-14 16-27-28](https://github.com/bugsnag/bugsnag-js/assets/2567814/8a28a2d4-191f-45f0-9e8d-98bfe824fb0b)

![Screenshot from 2023-08-14 16-20-31](https://github.com/bugsnag/bugsnag-js/assets/2567814/500c8617-e95d-40eb-ae60-468be13fd909)

![Screenshot from 2023-08-14 16-23-26](https://github.com/bugsnag/bugsnag-js/assets/2567814/8a583c5a-cb9a-43a3-acab-bb9afef28744)

**Comment by mclack** [comment]
Hi @jmchaves

For further investigation, would you please be able to send us a link to the error you have screenshotted from your BugSnag dashboard?

Please feel free to contact us on [support@bugsnag.com](mailto:support@bugsnag.com) to raise a ticket with us, as this is a public thread that anyone can view.

Once we have a link to the error we will be able to look into this further and check this against the source maps you have uploaded for the project.

**Comment by jmchaves** [comment]
This issue was already addressed. Thank you!
