### ISSUE TITLE
@bugsnag/web-worker using cuid package which does not run in Web Workers

### ISSUE THREAD

**Issue by rtymchyk** [bugsnag/bugsnag-js#2017]
### Describe the bug
Bugsnag for Web Workers appears to be using a fork of [cuid package](https://github.com/bugsnag/cuid) to generate IDs like for [Session creation](https://github.com/bugsnag/bugsnag-js/blob/c6927dcd8c328381a7eafe2362122a69b02caf34/packages/core/session.js#L4). 

Inside `cuid`, `navigator.mimeTypes` is accessed like this (https://github.com/bugsnag/cuid/blob/662b859fea9f546dbbb6525d687558cd46a6518a/lib/fingerprint.browser.js#L8), which seems to fail in Web Worker.

### Steps to reproduce
1. Turn on session tracking
2. Attempt to pause and resume session

### Environment
* Browser framework version (if any):
    * React: 7.19.0
    * Web Worker: 7.20.1
* Browser version (e.g. chrome, safari): Safari
* Device (e.g. iphonex): iOS

<details><summary>Error messages:</summary>

```
undefined is not an object (evaluating 'navigator.mimeTypes')
```
</details>

**Comment by mclack** [comment]
Hi @rtymchyk 
Thanks for bringing this to our attention. We are looking into this, and will keep this thread updated with any developments.

**Comment by mclack** [comment]
Hi @rtymchyk 

We've looked into this, and can confirm we have a test that successfully sends a session: https://github.com/bugsnag/bugsnag-js/blob/86e96f9ad275f870dff28d3139bd8f07f387ec42/test/browser/features/web_worker.feature#L45-L48

`navigator` is also defined in web workers, so we would not expect this to be an issue: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/navigator

We are unaware of any other users having this problem and I have also been unable to reproduce it. If you're still encountering this, are you able to elaborate on how you are pausing and resuming your sessions? As this is a public thread, please feel free to open a ticket with us by contacting support@bugsnag.com and reference this issue. To further aid our investigation, could you also please attach code snippets/screenshots of your BugSnag configuration and any session instrumentation you are performing.

**Comment by rtymchyk** [comment]
> Hi @rtymchyk
> 
> We've looked into this, and can confirm we have a test that successfully sends a session:
> 
> https://github.com/bugsnag/bugsnag-js/blob/86e96f9ad275f870dff28d3139bd8f07f387ec42/test/browser/features/web_worker.feature#L45-L48
> 
> `navigator` is also defined in web workers, so we would not expect this to be an issue: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/navigator
> 
> We are unaware of any other users having this problem and I have also been unable to reproduce it. If you're still encountering this, are you able to elaborate on how you are pausing and resuming your sessions? As this is a public thread, please feel free to open a ticket with us by contacting [support@bugsnag.com](mailto:support@bugsnag.com) and reference this issue. To further aid our investigation, could you also please attach code snippets/screenshots of your BugSnag configuration and any session instrumentation you are performing.

Thanks @mclack. I am not pausing/resuming sessions at all, just a simple `Bugsnag.start({..})` in the global namespace, with an API key, release stage, and app version. I assumed it was session tracking related based on this:
>Sessions are captured and reported by default. This behavior can be disabled using the [autoTrackSessions configuration option](https://docs.bugsnag.com/platforms/javascript/configuration-options/#autotracksessions).

But even with this disabled there issue persists.

I'll try to collect some more information and reach out via a ticket once I have it!
