### ISSUE TITLE
@bugsnag/electron: infinite requests loop to notify.bugsnag.com

### ISSUE THREAD

**Issue by trungutt** [bugsnag/bugsnag-js#2023]
👋 Thanks for working on this project.

### Environment
Bugsnag version: "@bugsnag/electron": "^7.21.0" (latest at the time of writing)

### Describe the bug

We are getting an infinite loop of requests hitting `notify.bugsnag.com` (default Bugsnag endpoints configuration) while using `@bugsnag/electron`

https://github.com/bugsnag/bugsnag-js/blob/86e96f9ad275f870dff28d3139bd8f07f387ec42/packages/electron/src/config/common.js#L26-L28

After digging into the code, a possible cause is:

- Bugsnag tried to [send](https://github.com/bugsnag/bugsnag-js/blob/86e96f9ad275f870dff28d3139bd8f07f387ec42/packages/delivery-electron/delivery.js#L151) a session request on app startup (which might help calculate [stability score](https://www.bugsnag.com/product/stability-score/) or something). Nothing could stop this request, even by specifying `autoTrackSessions: false` (documentation [here](https://docs.bugsnag.com/platforms/electron/configuration-options/#autotracksessions))
- When we have a corporate proxy that requires authentication/or DNS blocker (pi-hole/Adguard... which automatically blocks Bugsnag), this session request failed with 407 (Proxy Authentication Required)

<img width="938" alt="Screenshot 2023-10-11 at 09 59 56" src="https://github.com/bugsnag/bugsnag-js/assets/18528548/ac6fa05a-672a-42ab-a584-0a9b66067801">

- This failure somehow triggered an `uncaughtException` that was handled in [this handler plugin](https://github.com/bugsnag/bugsnag-js/blob/86e96f9ad275f870dff28d3139bd8f07f387ec42/packages/plugin-node-uncaught-exception/uncaught-exception.js#L12). This plugin comes builtin with `@bugsnag/electron`

https://github.com/bugsnag/bugsnag-js/blob/86e96f9ad275f870dff28d3139bd8f07f387ec42/packages/plugin-node-uncaught-exception/uncaught-exception.js#L12

which tried to notify Bugsnag endpoint `notify.bugsnag.com`. Like session request, notify request also failed with 407, which then triggered another `uncaughtException` which notified `notify.bugsnag.com` which then failed => infinite loop!

This happens in real world of corporates with proxy setup, that consumes CPU cycles of our machines. That happened to our end users' machines too.

### Steps to reproduce
1. Use `@bugsnag/electron` in a dummy Electron project
2. Setup a local proxy, for the sake of simplicity, I use https://mitmproxy.org/, detail of setup could be found in this [blog](https://earthly.dev/blog/mitmproxy/)
3. Run `mitmproxy --proxyauth foo:bar --showhost`
4. Configure your OS system to use `127.0.0.1:8080` as proxy (default address of mitm)
5. Start Electron application and see the infinite Bugsnag loop in the console

Below is real log from our corporate proxy

![bugsnag](https://github.com/bugsnag/bugsnag-js/assets/18528548/c7f1711e-a7b6-4140-9cec-662b9d1a004b)

For now we put a dirty patch in @bugsnag/delivery-electron before this call [here](https://github.com/bugsnag/bugsnag-js/blob/86e96f9ad275f870dff28d3139bd8f07f387ec42/packages/delivery-electron/delivery.js#L96-L98) to avoid calling it infinitely in case we hit 407. It's clearly not a long term viable solution.

Another possibility would be disabling [enablederrortypes](https://docs.bugsnag.com/platforms/electron/configuration-options/#enablederrortypes) to avoid this infinite loop, but that would defeat the purpose of Bugsnag as bug tracking tool.

Please let me know if anything I can help to fix it.

TIA for feedbacks!

**Comment by clr182** [comment]
Hi @trungutt 
This issue seems to stem when there is a proxy authentication error. Electron net emits an error event on the response stream rather than a request, which we do not currently handle. As we are not handling this response, it falls through to the uncaught exception handler, which will then in turn notify and cause an infinite loop of failed requests. We do now have an item on our backlog aimed at handling these responses however I do not currently have a firm ETA. We will be sure to update this thread once we have more information.

**Comment by clr182** [comment]
Hi @trungutt 

We have just released [Bugsnag-js v7.22.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.22.1) which should fix the infinite notify loop you reported. After update if you are still seeing issues please let us know.
