### ISSUE TITLE
@bugsnag/electron - Unable to prepack due to error with Bugsnag

### ISSUE THREAD

**Issue by GlobalGamer2015** [bugsnag/bugsnag-js#2026]
### Describe the bug
  • electron-builder  version=22.11.4 os=10.0.22621
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@bugsnag/plugin-electron-app@7.19.0, @bugsnag/plugin-electron-client-state-persistence@7.19.0 platform=win32 arch=x64
  • rebuilding native dependency  name=@bugsnag/plugin-electron-app version=7.19.0
  • rebuilding native dependency  name=@bugsnag/plugin-electron-client-state-persistence version=7.19.0
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! Missing script: "install"
    npm ERR!
    npm ERR! Did you mean this?
    npm ERR!     npm uninstall # Remove a package
    npm ERR!
    npm ERR! To see a list of scripts, run:
    npm ERR!   npm run

    npm ERR! A complete log of this run can be found in: C:\Users\dpipe\AppData\Local\npm-cache\_logs\2023-10-14T11_05_34_694Z-debug-0.log

                    command='E:\Program Files\nodejs\node.exe' 'E:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js' run install
                    workingDir=E:\[Redacted]\[Redacted]\src\node_modules\@bugsnag\plugin-electron-client-state-persistence
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Steps to reproduce
1. Use a electron example that requires starting with "electron .".
2. Install `electron-builder@22.11.4`
3. Install `@bugsnag/electron`
4. Add `"prepack": "yarn electron-builder --dir",` to scripts in package.json
5. Start prepack script: `npm run-script prepack`
6. See error

### Environment
* Bugsnag version: 7.21.0
* Browser framework version (if any):
    * None
* Server framework version (if any):
    * Express: 4.17.1
* Browser version (e.g. chrome, safari): 117.0.5938.132
* Device (e.g. iphonex): Desktop

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by clr182** [comment]
Hi @GlobalGamer2015 

Thank you for your patience as we discussed this internally. I just wanted to let you know that we don't claim any support for `electron-builder` and it would require us to investigate further and look into this as a feature. Unfortunately, this doesn't seem to be something we aim to support any time soon but if we change our minds we will be sure to keep you updated.
It may also be worth suggesting you to reach out on the electron-builde's issues list as well to request support for BugSnag.
