### ISSUE TITLE
Can't execute code from a freed script.

### ISSUE THREAD

**Issue by radiofrequency** [bugsnag/bugsnag-js#203]
In my single page app all versions of IE spam this error to the console when i remove a Backbone View.

If i remove bugsnag it stops happening.

I'm using bugsnag-js 3.0.5.  These seems to have been introduced in recent builds as i didn't have this problem before.

Stacktrace shown by bugsnag.

../js/bugsnag.js:254[unknown]  
              lastScript = null;
            }
          } else {
            **var ret = _super.apply(this, arguments);**
            // in case of error, this is set to null in window.onerror
            lastScript = null;
            return ret;

**Comment by eanakashima** [comment]
Hmm, that's interesting. I wonder if the way we're wrapping some built-in functions is problematic for removing modules after the fact. Is there a public page you can point us to where you can reproduce this error?

**Comment by radiofrequency** [comment]
Yup https://www.datememe.com. Click try anon and click around on the top navigation.  I've been testing with edge on windows 10 but getting reports from versions of I.E. also.

**Comment by eanakashima** [comment]
I followed the steps you listed with IE11 win7 but I wasn't able to reproduce the error. In Bugsnag 3.x we wrap some built-in functions to support the breadcrumb timeline feature — I wonder if bugsnag-js references to built-ins in old views are somehow being called async and triggering this error. It might be worth trying to disable all or some variants of autoBreadcrumbs [docs](https://docs.bugsnag.com/platforms/browsers/configuration-options/#autobreadcrumbs) to see if that fixes it.

**Comment by radiofrequency** [comment]
Thanks for taking a look. That's weird you can't reproduce I have a bunch of reports from IE 11 on windows 7 in my bugsnag account.  I will update to 3.0.6 and try disabling breadcrumbs to see if that resolves it.

**Comment by kattrali** [comment]
Closing this out for now, but feel free to reopen if the issue persisted after updating.
