### ISSUE TITLE
build failed when enable react native new arch

### ISSUE THREAD

**Issue by iwater** [bugsnag/bugsnag-js#2101]
<img width="573" alt="截屏2024-03-25 10 32 12" src="https://github.com/bugsnag/bugsnag-js/assets/108937/a4773493-5e06-4e72-ad53-5fd2ccb29a64">

### Describe the bug
build failed when enable react native new arch

### Steps to reproduce
1. init a new react-native app
2. enable new arch
3. install @bugsnag/react-native
4. build & See error

### Environment
* Bugsnag version: 7.22.6
* ReactNative Version: 0.73.6

**Comment by clr182** [comment]
Hi @iwater 

Thank you for reaching out. 

We not have an item on our backlog to investigate this further when priorities allow. Once we have more information we will be sure to reach out and share an update! 

Kind regards,
Christian

**Comment by toniewypada** [comment]
Hello 👋🏻, 
We’ve released new version of our JS notifier, [v7.22.7](https://github.com/bugsnag/bugsnag-js/pull/2121), which contains fix to the build issue, you’ve reported. The update should move BugsnagReactNative from objective-c to objective c++ while building React Native app.
If the issue still persists after updating the React Native SDK, please let us know and we’ll investigate further.
