### ISSUE TITLE
Support for Atlassian Forge

### ISSUE THREAD

**Issue by dacevedo12** [bugsnag/bugsnag-js#2104]
### Description
Atlassian Forge is a platform to develop 3rd-party applications for atlassian products, such as Jira, confluence, etc.

Atlassian Forge provides a backend that runs on a custom node runtime (AWS lambda underneath from what the docs mention)
https://developer.atlassian.com/platform/forge/runtime-reference/native-nodejs-runtime/. 

This custom node runtime does not provide a global fetch function, but a custom one https://developer.atlassian.com/platform/forge/runtime-reference/fetch-api.basic/

AFAIK there is no way in bugsnag-js to pass a custom fetch function to be used by bugsnag's delivery function.

**Describe the solution you'd like**
Support for Atlassian Forge or at least a way to pass a custom fetch function.

**Additional context**
Sentry has something like https://community.developer.atlassian.com/t/how-do-i-track-errors-or-send-custom-metrics-in-my-ui-kit-app-solution-inside/50510, https://www.npmjs.com/package/@atlassian/sentry-transport-forge

**Comment by clr182** [comment]
Hi @dacevedo12 

Thanks for reaching out. 

While we do not currently have support for Atlassian Forge - We do have a workaround that should accomplish what you are trying to do. 

Something like the following code in your BugSnag configuration should work to pass custom fetch functions
```
import { fetch } from '@forge/api'
import Bugsnag from '@bugsnag/js'
import bugsnagFetchDelivery from '@bugsnag/delivery-fetch'

Bugsnag.start('api key')
Bugsnag._client._setDelivery(
  client => bugsnagFetchDelivery(client, fetch)
)
```

For this to work you would be required to install `@bugsnag/delivery-fetch`. After trying this please let us know if you encounter any further issues. 

Additionally it's worth mentioning that `_client` and `_setDelivery` are private. As such, may be subject to breaking changes in any release.

**Comment by clr182** [comment]
Hi @dacevedo12 

I am closing this ticket out as there has been no update on this thread in some time.
If you have any further updates. Please do reach out again with more information and we can investigate further.
