### ISSUE TITLE
Is there a strict version dependency or binding between bugsnag-js and bugsnag-cocoa?

### ISSUE THREAD

**Issue by change2hao** [bugsnag/bugsnag-js#2182]
n my iOS project, we have integrated both bugsnag-js and bugsnag-cocoa. We only want to update bugsnag-cocoa to the latest version while keeping bugsnag-js at version 7.18.1. Is there any problem with this?

**Comment by RobertoSmartBear** [comment]
Hi,

It's challenging to provide specific advice without understanding more about your app architecture. If you are using React Native and you check the [release notes for bugsnag-js v7.18.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.18.1), you will see that the supported `bugsnag-cocoa` versions range from v6.23.1 to v6.24.0.

The [latest bugsnag-cocoa release](https://github.com/bugsnag/bugsnag-cocoa/releases) (at the time of writing) is v6.30.1, so this would not be compatible.

Unless you have a very specific reason for such an update, we'd generally recommend keeping all of our SDKs up to date to take advantage of bug fixes and performance improvements, as well as possible additional features.

Are you able to provide any more detail about why you would like to update `bugsnag-cocoa` to the latest version while keeping `bugsnag-js` at version 7.18.1?

**Comment by mclack** [comment]
Hi @change2hao 

As we have not had any updates on this in a while, we are now going to close the issue.

 If you have any further questions or need assistance with anything else, please feel free to open a ticket with us directly by contacting support@bugsnag.com.
