### ISSUE TITLE
Specify custom notifyHandler

### ISSUE THREAD

**Issue by jacobmarshall** [bugsnag/bugsnag-js#219]
See https://github.com/bugsnag/bugsnag-js/issues/217#issuecomment-272056126

> I am thinking that an option to specify a custom transport to send requests would be useful here. This way an app could implement both sendBeacon (which is URL-limited as well) and POST JSON.

This was kind of always my intention when I originally created #123. It should be an extremely minor addition.

**Comment by kattrali** [comment]
Thanks for the contribution, @jacobmarshall. The intent to make the delivery mechanism more configurable is a good idea. In the longer term, I think it makes the most sense that we modularize the various cases to make the logic easier to follow and hopefully easier to document. 

For example, [here are the Python `Delivery` implementations](https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/delivery.py#L32). We could potentially do something similar for JavaScript, where we have a few different ways a report can be delivered (XHR, Image, something modern which uses `JSON.stringify`, custom handlers, etc). It's still something I'm thinking about, and I don't think it makes sense to expand the API until the idea is a little more formally defined and takes into account browser compatibility and performance concerns (execution speed and library size specifically).

**Comment by jacobmarshall** [comment]
Fair enough. I think that's a good idea all round. 👍
