### ISSUE TITLE
electron-builder cant build msi after upgrade

### ISSUE THREAD

**Issue by avivsalman** [bugsnag/bugsnag-js#2233]
### Describe the bug
got error when packing app with electron-builder version 25.1.8

### Environment
* Bugsnag version: 8.0.0
* Electron: 30.0.8
* electron-builder: 25.1.8

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
⨯ Exit code: 103. Command failed: C:\Users\XXX\AppData\Local\electron-builder\Cache\wix\wix-4.0.0.5512.2\light.exe -out C:\XXX\dist\dokopos\dokopos 7.1.1.msi -v -spdb -sw1076 -dappDir=C:\XXX\dist\dokopos\win-unpacked -pedantic -wx project.wixobj
C:\XXX\dist\dokopos\__msi-x64\project.wxs(2716) : error LGHT0103 : The system cannot find the file 'C:\XXX\dist\dokopos\win-unpacked\resources\app.asar.unpacked\node_modules\@bugsnag\plugin-electron-client-state-persistence\build\Release\obj\bugsnag_pecsp_bindings\bugsnag_.E1E0FB2C.tlog\bugsnag_pecsp_bindings.lastbuildstate'.
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by toniewypada** [comment]
Hi @avivsalman 👋🏻, 

I’m unable to reproduce this issue on my end. For further investigation, could you please share the BugSnag configuration in your app? 

In case you don’t want to share these details in a public GitHub issue, you can contact us at [support@bugsnag.com](mailto:support@bugsnag.com) referencing the number of the issue [#2233 ](https://github.com/bugsnag/bugsnag-js/issues/2233)
