### ISSUE TITLE
enableNotifyUnhandledRejections missing from TypeScript definitions

### ISSUE THREAD

**Issue by warhammerkid** [bugsnag/bugsnag-js#230]
It appears that `enableNotifyUnhandledRejections()`, `disableNotifyUnhandledRejections()`, and the `notifyUnhandledRejections` setting are all missing from the TypeScript definitions. I'd be happy to submit a pull request, but I'm not sure whether to add all of them or just the setting, as the auto breadcrumb enable and disable methods are also all missing from the TypeScript definitions but their setting properties are available.

**Comment by kattrali** [comment]
Thanks for the reminder, @warhammerkid. It makes sense to add all of them, and a PR would be welcome. I'll update the release guide to ensure the definitions are up to date before each release.

**Comment by kattrali** [comment]
Fixed by #231
