### ISSUE TITLE
Bugsnag is not working with webpacks source maps and its hot-loader

### ISSUE THREAD

**Issue by pdiniz13** [bugsnag/bugsnag-js#238]
After adding bugsnag all logs and errors are coming from bugsnag.js?d6b6:628 
```
  function enhance(object, property, newFunction) {
    var oldFunction = object[property];
    object[property] = function() {
      newFunction.apply(this, arguments);
      if (typeof oldFunction === "function") {
        oldFunction.apply(this, arguments);
      }
    };
  }
```
Also webpacks hot reload is throwing this error
```
bugsnag.js?d6b6:628 [HMR] Update check failed: Error: Manifest request to http://localhost:8080/client-assets/6737aaffea21c52cb7c6.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (http://localhost:8080/client-assets/app.6737aaffea21c52cb7c6.js:62:22)
```

**Comment by wordofchristian** [comment]
That's no good. We'll have to look into this closer, but in the meantime you might try doing this when running in the development environment to see if it solves the immediate problem:
```
// Disable all automatic breadcrumbs
Bugsnag.disableAutoBreadcrumbs();
```

**Comment by pdiniz13** [comment]
that solved the problem with the manifest but the hot reloader is still not working

**Comment by bengourley** [comment]
Hi @pdiniz13 did you find a solution to your problem? If not could you provide an example repo where the problem can be reliably reproduced? I'm closing the issue but feel free to reopen :)
