### ISSUE TITLE
Request: Bugsnag.onNotify event

### ISSUE THREAD

**Issue by soygul** [bugsnag/bugsnag-js#240]
So we will know when a bug report is sent. Useful for apps that reload the page after a critical error. Sometimes page reloads faster than the report can be sent. `image` element has onload and xhr has callback to provide this.

**Comment by jmshal** [comment]
There's been quite a lot of discussion around this. Such as https://github.com/bugsnag/bugsnag-js/issues/219 and https://github.com/bugsnag/bugsnag-js/issues/218.

But I'm fairly certain that XHR requests get aborted the same way as requests made by Images. So if anything, providing beacon support would be preferable - as beacons are intended for this purpose. 

I also liked @sompylasar's idea of implementing this using a queue https://github.com/bugsnag/bugsnag-js/issues/218#issuecomment-271988329 - but it's really a matter of how much I can compact the offline feature https://github.com/bugsnag/bugsnag-js/pull/151#issuecomment-301088268.

**Comment by soygul** [comment]
Alright I like the sendBeacon much better. Didn't even know that such api existed for this exact purpose so closing this.
