### ISSUE TITLE
Yield removes requestData

### ISSUE THREAD

**Issue by Fjandin** [bugsnag/bugsnag-js#243]
I have had this problem with bugsnag `cannot set user of undefined` when i try to set user data on `bugsnag.requestData`

Upon furter investigation i found this.

```js
app.use((req, res, next) => {
    console.log('requestData', !!bugsnag.requestData);
    next();
});
const test = co.wrap(function * test(req, res, next) {
    yield Promise.resolve();
    console.log('requestData', !!bugsnag.requestData);
    next();
});
app.use(test);
```

and also 

```js
app.use((req, res, next) => {
    console.log('requestData', !!bugsnag.requestData);
    next();
});
app.use((req, res, next) => {
    Promise.resolve().then(() => {
        console.log('requestData', !!bugsnag.requestData);
        next();
    });
});
```

This will log out

`requestData true`
`requestData false`

Somehow promises and yield remove the `requestData`

I'm on Node 6.11.0 and i'm using native promises
bugsnag@1.11.0
express@4.15.3

**Comment by jmshal** [comment]
Hi @Fjandin, the repo for the npm module `bugsnag` is actually located [here](https://github.com/bugsnag/bugsnag-node). I'm not sure if generator functions have the same issue as Promises, but it may be worth checking out https://github.com/bugsnag/bugsnag-node/issues/99.

**Comment by bengourley** [comment]
Closing because this issue with the node platform.
