### ISSUE TITLE
why can't bugsnag log local variables / function arguments?

### ISSUE THREAD

**Issue by grigored** [bugsnag/bugsnag-js#248]
As the title says, logging local variables or at least the function arguments besides the stack trace would be immensely useful. Using for example the `arguments` variable would make it pretty easy to log the last function's arguments. Any reason why this is not available?

**Comment by jmshal** [comment]
Sadly JavaScript doesn't natively have the capability of doing any of these things. You can always manually pass `arguments` and any local variables to `notify` through the metadata, but I don't see this being easily automated any time soon - if ever.
