### ISSUE TITLE
BugSnag type definitions cause error after update to 3.2.0

### ISSUE THREAD

**Issue by TobiasKrogh** [bugsnag/bugsnag-js#251]
Hi,

I am using BugSnag in a NPM project and importing it via `import 'bugsnag-js';` in my codebase. After updating to version 3.2.0 I get the following error when compiling.

```
Error at node_modules/bugsnag-js/src/bugsnag.d.ts:150:13: Subsequent variable declarations must have the same type. Variable 'Bugsnag' must be of type 'any', but here has type 'BugsnagStatic'.
```

I honestly have no real idea on how to fix it. I updated TypeScript at the same time and my first thought it was due to the update. I tried resetting both individually. After resetting `bugsnag-js` to 3.1.0 the error disappeared - error occurred with both TypeScript versions (2.3 and 2.4). No critical thing for me right now but I was wondering if I did something wrong. I am not sure what type of additional info might be needed.

Any help is appreciated.

Kind regards

**Comment by kattrali** [comment]
Thanks for the report, @TobiasKrogh. We'll look into it.

**Comment by jmshal** [comment]
Hi @TobiasKrogh 

I've tried to replicate the issue on my end, but so far everything seems to be working fine. I'm also using Typescript 2.4 and Bugsnag JS 3.2.

The following produces no errors when running `tsc`.

**src/main.ts**
```ts
import bugsnag = require('bugsnag-js');

bugsnag.apiKey = 'foobar';
```

**package.json**
```json
{
  "scripts": {
    "build": "tsc src/main.ts"
  },
  "dependencies": {
    "bugsnag-js": "^3.2.0",
    "typescript": "^2.4.2"
  }
}
```

I can get some other kind of error messages if I try to reference multiple instance of the `bugsnag.d.ts` file, or if I import the package like `import bugsnag from 'bugsnag-js'` - all without defining a tsconfig.json.

You may have tried this already, but do you get the same issue when nuking the `node_modules` folder?

Also, do you have anything in your `typings.d.ts` file for Bugsnag? Any additional information you have may help 😛

**Comment by TobiasKrogh** [comment]
@jmshal thanks for the hint. Yes for whatever reason there was an entry about Bugsnag in the `typings.d.ts`. I should have checked that as well. Will not happen again 😉 

Have a nice day
