### ISSUE TITLE
truncateDeep() throws with objects not inheriting hasOwnProperty()

### ISSUE THREAD

**Issue by brianreavis** [bugsnag/bugsnag-js#261]
https://github.com/bugsnag/bugsnag-js/blob/67753db6e65ad96fc4a726dc76d2c76fe195aa97/src/bugsnag.js#L761

This line is not safe and breaks `history.pushState` and `history.replaceState` when `state` contains object(s) that do not inherit `hasOwnProperty` (e.g. were created with `Object.create(null)`).

### Observed behavior
```
TypeError: e.hasOwnProperty is not a function
```
### Steps to reproduce
* Have auto breadcrumbs enabled and call `history.pushState` with a `state` containing object(s) that do not not inherit `hasOwnProperty`.

```js
var plainObject = Object.create(null);
plainObject.dummyProperty = true;
var state = {myObject: plainObject};
history.pushState(state, 'foo', 'bar.html');
```

### Version
3.x

**Comment by bengourley** [comment]
Hey @brianreavis, thanks for the bug report. I'll get this looked into.

**Comment by brianreavis** [comment]
Thanks @bengourley!

**Comment by bengourley** [comment]
Hey @brianreavis, v3.3.1 was just released containing the fix for this. If you are using the CDN link, the latest version will be fetched automatically and should _just work™_. Otherwise, please manually upgrade and let me know how you get on. Cheers!
