### ISSUE TITLE
Webpack build fails when using bugsnag on windows

### ISSUE THREAD

**Issue by shift-keshav-pudaruth** [bugsnag/bugsnag-js#266]
### Expected behavior
Webpack bundle should output properly. 

### Observed behavior
Webpack bundle fails to build, on windows 10 64-bit, whilst requesting access to 'fs' events due to bugsnag dependency

### Webpack Output:

> Hash: 74456dc24b052ce39268
> Version: webpack 3.6.0
> Time: 84491ms
>                  Asset       Size  Chunks                    Chunk Names
>       vendor.bundle.js    3.59 MB       0  [emitted]  [big]  vendor
>          app.bundle.js     597 kB       1  [emitted]  [big]  app
>     manifest.bundle.js    1.36 kB       2  [emitted]         manifest
>   vendor.bundle.js.map    11.7 MB       0  [emitted]         vendor
>      app.bundle.js.map    1.42 MB       1  [emitted]         app
> manifest.bundle.js.map    7.64 kB       2  [emitted]         manifest
>          manifest.json  232 bytes          [emitted]
> [./app/App.jsx] ./app/App.jsx 931 bytes {1} [built]
> [./app/Index.jsx] ./app/Index.jsx 1.59 kB {1} [built]
> [./app/bugsnag/config.jsx] ./app/bugsnag/config.jsx 338 bytes {1} [built]
> [./app/reducers/authReducer.jsx] ./app/reducers/authReducer.jsx 1.05 kB {1} [built]
> [./app/reducers/businessSector/ListReducer.jsx] ./app/reducers/businessSector/ListReducer.jsx 563 bytes {1} [built]
> [./app/reducers/businessSector/ProfilerReducer.jsx] ./app/reducers/businessSector/ProfilerReducer.jsx 2.08 kB {1} [built
> ]
> [./app/reducers/candidateStatus/ListReducer.jsx] ./app/reducers/candidateStatus/ListReducer.jsx 764 bytes {1} [built]
> [./app/reducers/company/ListReducer.jsx] ./app/reducers/company/ListReducer.jsx 2.76 kB {1} [built]
> [./app/reducers/company/ProfilerReducer.jsx] ./app/reducers/company/ProfilerReducer.jsx 3.37 kB {1} [built]
> [./app/reducers/contact/ProfileReducer.jsx] ./app/reducers/contact/ProfileReducer.jsx 5.92 kB {1} [built]
> [./app/reducers/evaluation/ProfileReducer.jsx] ./app/reducers/evaluation/ProfileReducer.jsx 2.08 kB {1} [built]
> [./app/store/configureStore.jsx] ./app/store/configureStore.jsx 5.28 kB {1} [built]
>    [0] multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-local
> es-supported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title reac
> t-dom react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-s
> ystem react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select reac
> t-table react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore u
> rl-search-params uuid validate.js velocity-react 544 bytes {0} [built]
> [./app/store/globalStore.jsx] ./app/store/globalStore.jsx 137 bytes {1} [built]
> [./config/production.js] ./config/production.js 1.85 kB {1} [built]
>     + 1735 hidden modules
> 
> WARNING in ./node_modules/bugsnag/lib/utils.js
> 32:30-54 Critical dependency: the request of a dependency is an expression
> 
>ERROR in ./node_modules/bugsnag/lib/error.js
> Module not found: Error: Can't resolve 'fs' in 'F:\localhostpublichtml\profiler_projects\profiler_react\public\js\node_modules\bugsnag\lib'
>  @ ./node_modules/bugsnag/lib/error.js 4:9-22
>  @ ./node_modules/bugsnag/lib/bugsnag.js
>  @ multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-locales-s
> upported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title react-do
> m react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-syste
> m react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select react-ta
> ble react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore url-s
> earch-params uuid validate.js velocity-react
> 
> ERROR in ./node_modules/request/lib/har.js
> Module not found: Error: Can't resolve 'fs' in 'F:\localhostpublichtml\profiler_projects\profiler_react\public\js\node_m
> odules\request\lib'
>  @ ./node_modules/request/lib/har.js 3:9-22
>  @ ./node_modules/request/request.js
>  @ ./node_modules/request/index.js
>  @ ./node_modules/bugsnag/lib/notification.js
>  @ ./node_modules/bugsnag/lib/bugsnag.js
>  @ multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-locales-s
> upported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title react-do
> m react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-syste
> m react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select react-ta
> ble react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore url-s
> earch-params uuid validate.js velocity-react
> 
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'F:\localhostpublichtml\profiler_projects\profiler_react\public\js\node_
> modules\forever-agent'
>  @ ./node_modules/forever-agent/index.js 6:10-24
>  @ ./node_modules/request/request.js
>  @ ./node_modules/request/index.js
>  @ ./node_modules/bugsnag/lib/notification.js
>  @ ./node_modules/bugsnag/lib/bugsnag.js
>  @ multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-locales-s
> upported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title react-do
> m react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-syste
> m react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select react-ta
> ble react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore url-s
> earch-params uuid validate.js velocity-react
> 
> ERROR in ./node_modules/tough-cookie/lib/cookie.js
> Module not found: Error: Can't resolve 'net' in 'F:\localhostpublichtml\profiler_projects\profiler_react\public\js\node_
> modules\tough-cookie\lib'
>  @ ./node_modules/tough-cookie/lib/cookie.js 32:10-24
>  @ ./node_modules/request/lib/cookies.js
>  @ ./node_modules/request/index.js
>  @ ./node_modules/bugsnag/lib/notification.js
>  @ ./node_modules/bugsnag/lib/bugsnag.js
>  @ multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-locales-s
> upported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title react-do
> m react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-syste
> m react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select react-ta
> ble react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore url-s
> earch-params uuid validate.js velocity-react
> 
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'net' in 'F:\localhostpublichtml\profiler_projects\profiler_react\public\js\node_
> modules\tunnel-agent'
>  @ ./node_modules/tunnel-agent/index.js 3:10-24
>  @ ./node_modules/request/lib/tunnel.js
>  @ ./node_modules/request/request.js
>  @ ./node_modules/request/index.js
>  @ ./node_modules/bugsnag/lib/notification.js
>  @ ./node_modules/bugsnag/lib/bugsnag.js
>  @ multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-locales-s
> upported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title react-do
> m react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-syste
> m react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select react-ta
> ble react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore url-s
> earch-params uuid validate.js velocity-react
> 
> ERROR in ./node_modules/forever-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'F:\localhostpublichtml\profiler_projects\profiler_react\public\js\node_
> modules\forever-agent'
>  @ ./node_modules/forever-agent/index.js 7:10-24
>  @ ./node_modules/request/request.js
>  @ ./node_modules/request/index.js
>  @ ./node_modules/bugsnag/lib/notification.js
>  @ ./node_modules/bugsnag/lib/bugsnag.js
>  @ multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-locales-s
> upported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title react-do
> m react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-syste
> m react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select react-ta
> ble react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore url-s
> earch-params uuid validate.js velocity-react
> 
> ERROR in ./node_modules/tunnel-agent/index.js
> Module not found: Error: Can't resolve 'tls' in 'F:\localhostpublichtml\profiler_projects\profiler_react\public\js\node_
> modules\tunnel-agent'
>  @ ./node_modules/tunnel-agent/index.js 4:10-24
>  @ ./node_modules/request/lib/tunnel.js
>  @ ./node_modules/request/request.js
>  @ ./node_modules/request/index.js
>  @ ./node_modules/bugsnag/lib/notification.js
>  @ ./node_modules/bugsnag/lib/bugsnag.js
>  @ multi axios bugsnag draft-js draftjs-to-html es6-promise-debounce formsy-material-ui formsy-react intl intl-locales-s
> upported material-ui moment moment-timezone prop-types react react-cookie react-dimensions react-document-title react-do
> m react-draft-wysiwyg react-dropzone react-infinite-any-height react-motion react-mui-speeddial react-notification-syste
> m react-notification-system-redux react-redux react-router react-router-transition react-scrollbar react-select react-ta
> ble react-tap-event-plugin react-timeago react-tooltip redux redux-debounce redux-saga redux-undo store underscore url-s
> earch-params uuid validate.js velocity-react

### Webpack Config:

```javascript

require('dotenv').config({path: '../../.env'});
let webpack = require('webpack');
let path = require('path');
let environment = 'production';
let ManifestPlugin = require('webpack-manifest-plugin');
let BugsnagSourceMapPlugin = require('bugsnag-sourcemap-webpack-plugin');
let Dotenv = require('dotenv-webpack');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
//let BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const pkg = require('./package.json');

module.exports = {
    devtool: 'hidden-source-map',
    entry: {
        vendor: Object.keys(pkg.dependencies),
        app: './app/App.jsx'
    },
    externals: {
        'react/addons': true
    },
    output: {
        path: path.join(__dirname, '/webpack/'),
        filename: '[name].bundle.js',
        chunkFilename: '[id].chunk.js',
        publicPath: '/'
    },
    resolve: {
        modules: [
            'node_modules',
            path.resolve(__dirname,'./app')
        ],
        alias: {
            config: path.join(__dirname,'./config/'+environment+'.js')
        },
        extensions: ['.js','.jsx']
    },
    module: {
        rules: [
            {
                test: /\.jsx$/,
                exclude: /(node_modules|bower_components|config)/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            babelrc: false,
                            presets: [
                                ['env', { modules: false }],
                                'stage-0',
                                'react'
                            ],
                            plugins: [
                                'transform-runtime'
                            ]
                        }
                    }
                ]
            }
        ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: ({ resource }) => /node_modules/.test(resource),
        }),
        new webpack.optimize.CommonsChunkPlugin('manifest'),
        new webpack.NamedModulesPlugin(),
        new Dotenv({
            path: '../../.env', // Path to .env file (this is the default)
        }),
        new UglifyJSPlugin({
            sourceMap: true,
            parallel: true
        }), //minify everything
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en|fr/), //Load only en & fr locales for moment
        new ManifestPlugin(),
        // new BugsnagSourceMapPlugin({
        //     apiKey: process.env.BUGSNAG_JS_API_KEY,
        //     publicPath: process.env.ASSET_CDN+'/build/js'
        // })
        //new BundleAnalyzerPlugin()
    ],
};

```

### Version
Webpack: 3.6.0
NPM: 5.4.2
Bugsnag: 2.0.0
Node: 7.10.0

### Additional information
If the bugsnag dependency is removed, webpack bundle completes successfully.

**Comment by bengourley** [comment]
Hey @shift-keshav-pudaruth it looks like you're using the npm module`bugsnag` (which is for node). This module (for browser JS is on npm as `bugsnag-js`. Try installing that instead and let me know how you get on!

**Comment by shift-keshav-pudaruth** [comment]
@bengourley Thanks for the clarification. Working as intended. It would be amazing if the readme had an installation section with npm/yarn since the official docs at docs.bugsnag.com mentions it in passing.

**Comment by bengourley** [comment]
> It would be amazing if the readme had an installation section with npm/yarn

I fully agree with you on this. We centralised all of our documentation at [docs.bugsnag.com](https://docs.bugsnag.com), but basic installation instructions in the `Readme.md` here – at the very least showing the package name on npm – would definitely help others from getting into the situation you found yourself in.

Additionally we are in the process of revamping the browser js notifier. As part of this the docs will have an overhaul, and will describe how to install from npm as well as the CDN.

Thanks for your feedback! 🙌
