### ISSUE TITLE
Auto notify not working

### ISSUE THREAD

**Issue by alejandromagnorsky** [bugsnag/bugsnag-js#268]
I'm configuring Bugsnag v3.3.1 as following:
```javascript
define(['bugsnag'], function () {
    var bugsnag = function (config_constants) {
        Bugsnag.apiKey = 'API_KEY';
        Bugsnag.metaData = config_constants;
        Bugsnag.autoNotify = true;
        Bugsnag.releaseStage = config_constants.debug ? 'development' : 'production';
        Bugsnag.notifyReleaseStages = ['production'];
        Bugsnag.notify('example');
    };
    bugsnag.$inject = ['config_constants'];
    return bugsnag;
});
```

The `Bugsnag.notify('example')` is working as expected. However, if I make a mistake on purpose in one of my controllers, for example: I add an undefined variable `asdasd` to trigger `ReferenceError: asdasd is not defined`. In that case, it does not show in Bugsnag's dashboard.

I'm using RequireJS and AngularJS.

Thanks.

**Comment by bengourley** [comment]
Hey @alejandromagnorsky!

Sounds like something may be catching the error and logging to your console before it can bubble up to Bugsnag's uncaught error handler.

Which version of Angular are you using?

**Comment by bengourley** [comment]
If you are on Angular 1.x, try hooking this up to Bugsnag notify(): https://docs.angularjs.org/api/ng/service/$exceptionHandler

If you are on Angular 2/3/4… take a look at this example: https://github.com/bugsnag/bugsnag-js/tree/master/examples/angular4

**Comment by alejandromagnorsky** [comment]
Oh, I see!
Yes, we are using Angular v1.6 and we had a decorator already. So, the solution was to fire the Bugsnag.notifyException() from there. Cool.

```javascript
$provide.decorator('$exceptionHandler', ['$delegate', function ($delegate) {
            Bugsnag.apiKey = 'API_KEY';
            Bugsnag.metaData = config_constants;
            // Only track production
            Bugsnag.releaseStage = config_constants.debug ? 'development' : 'production';
            Bugsnag.notifyReleaseStages = ['production'];

            return function (exception, cause) {
                var exceptionsToIgnore = ['Possibly unhandled rejection: canceled'];
                if (_.includes(exceptionsToIgnore, exception)) return;

                Bugsnag.notifyException(exception);
                $delegate(exception, cause);
            };
        }]);
```

**Comment by bengourley** [comment]
👍
