### ISSUE TITLE
Proper way to filter out 3rd party errors?

### ISSUE THREAD

**Issue by eramdam** [bugsnag/bugsnag-js#270]
I'm writing code that gets embedded on websites, unfortunately I get _a lot_ of noises since Bugsnag is catching exceptions coming from 3rd party code (libraries, scripts other than mine).

I thought I should use the `beforeNotify` callback to filter out those, unfortunately I'm struggling as to how I'm supposed to identify (if even possible) exceptions that don't come from my own bundle. Here is the callback I have right now

```js
bugsnag.beforeNotify = (payload) => {
  const isFromUs = payload.stacktrace.indexOf('myscriptdomain.com') > -1 && payload.stacktrace.indexOf('webpack:///src/') > -1;
  if (isFromUs) {
    return payload;
  }

  return false;
};
```

I tried to rely on `payload.file` before but quickly found out it was almost never filled in. Is there a documentation of the `payload` object somewhere and/or is there a preferred way to do this? 

While the code is a React App, I also use error boundaries and _could_ only use those, but then I would miss exceptions that happen outside of my component tree, wouldn't it?

Happy to provide more details if needed.

**Comment by snmaynard** [comment]
As a quick answer - in the settings in the dashboard there is a setting where you can control which domains we process errors from. If you set that to your domain and/or where you host your js that can significantly help in the short term.

**Comment by eramdam** [comment]
@snmaynard I thought about this but was not sure if an error thrown on `domainA.com` by a script hosted on `mydomain.com` would get processed if I put `mydomain.com` on the whitelist?

(Also WOW, thanks for such a quick reply, I was not expecting this 😅 😬 )

**Comment by snmaynard** [comment]
I believe that it just checks the top most line of the stacktrace (so most recent call) to see if it comes from a script hosted on your domain. In that case it would get processed if you included `mydomain.com` in the whitelist.

**Comment by bengourley** [comment]
Hey @eramdam, I'm going to close this off as it looks resolved, but feel free to add to this if you still have problems. Thanks!

**Comment by eramdam** [comment]
No worries, I totally forgot to check back on this! The domain whitelist feature works perfectly for this indeed!

**Comment by EskelCz** [comment]
Is this filtering running on the client-side? My library will be on hundreds of websites, that's a ton of traffic and errors that I don't need to be tracking/paying for.

**Comment by xander-jones** [comment]
@EskelCz, if using dashboard settings to filter, such as domain allow-listing this is a server-side filter so reports will need to be sent over before being filtered. However, if you choose to use [callbacks](https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#discarding-events) to discard events, this will be done on the client-side. It sounds like you'd be better off using the latter here.
