### ISSUE TITLE
How can I trigger Bugsnag.notify in Angular 4 outside the error-handler?

### ISSUE THREAD

**Issue by Bramzor** [bugsnag/bugsnag-js#274]
### Expected behavior
I would like to use Bugsnag.notify in Angular 4 outside of the error-handler class to handle my own errors.

### Observed behavior
I have an providers class where I try the following: 
/// <reference path="../../bugsnag.d.ts" />
Bugsnag.releaseStage = "development";

This works in the browser but fails when building it for an ionic app (showing white page). Seems that Bugsnag is undefined while it is working with the error-handler.ts file.

### Steps to reproduce
- Create an ionic app
- Include the above code in any page.
- Run it in emulator. (Will work in the browser)

### Version
Ionic 3
Angular 4

**Comment by bengourley** [comment]
Hey @Bramzor. I created a blank Ionic project to try this out on. My `error-handler.ts` ended up looking like this, and it worked for me:

```js
import Bugsnag from 'bugsnag-js'
import { ErrorHandler } from '@angular/core';

Bugsnag.apiKey = '9e68f5104323042c09d8809674e8d0bb'

export class BugsnagErrorHandler implements ErrorHandler {
  handleError(error: any) {
    Bugsnag.notifyException(error, {
      angular: !error.ngDebugContext
        ? undefined
        : { component: error.ngDebugContext.component, context: error.ngDebugContext.context }
    })
    console.error(error)
  }
}

export { Bugsnag };
```

The part of the app that needs a "provider" must do `import { BugsnagErrorHandler } from './error-handler';` but other areas of the app can just pull in the Bugsnag lib with: `import { Bugsnag } from './error-handler';`

This worked for me in the web and in the emulator versions. Let me know how you get on!

**Comment by Bramzor** [comment]
Thanks for your feedback! Apparently we shouldn't be using "/// <reference path='bugsnag.d.ts' />" but instead we should npm the bugsnag-js package and this indeed allows us to export Bugsnag.

Was set on the wrong track by the example. Would be better if it was updated the npm install and removed the reference path?

**Comment by bengourley** [comment]
It should be possible to load it either way – as a script tag loading via CDN, or from via node_modules. Taking the CDN approach, the `///` directive would be required for the TypeScript compiler to know where to load the types from.

Anyway, I'm glad you were able to get up and running!
