### ISSUE TITLE
v4 is twice the size of v3

### ISSUE THREAD

**Issue by xPaw** [bugsnag/bugsnag-js#277]
I just wanted to upgrade to v4 as it was announced, but I quickly realized that the minified version is 30kb (gzipped) compared to ~15kb of v3.

I don't feel like the size increase is justified especially when things like `env.NODE_ENV` get left in the minified version.

Also, what does the size badge represent in the readme, because these sizes don't match up.

**Comment by bengourley** [comment]
Hey Pavel, the gzipped size is 9kB 🙂

**Comment by xPaw** [comment]
Oh yeah, Chrome devtools was showing me the non-gzip size, my bad.

**Comment by bengourley** [comment]
Yeah I saw this too - I think it's because cloudfront sets tx encoding as
chunked rather than providing content length. Chrome then uses the
uncompressed size. Firefox gets it right 👌
