### ISSUE TITLE
v4 Failing To Load With Laravel Mix

### ISSUE THREAD

**Issue by aaronhuisinga** [bugsnag/bugsnag-js#279]
### Expected behavior
Bugsnag loads and functions properly when running [Laravel Mix](https://github.com/JeffreyWay/laravel-mix)

### Observed behavior
Currently, v4 will not initiate and work properly with Laravel Mix. It works when running Mix in development mode, but as soon as assets are compiled using the production command, Bugsnag fails to load with the error:
```
r._logger.warn(e) is not a function
```
It appears that something with how Webpack is compiling the libraries is preventing Bugsnag from loading properly. I'm genuinely not sure if this is an issue with Bugsnag or Mix (or maybe I'm just missing something simple), but I figured it made sense to open an issue since Mix is a pretty popular library and I'm assuming I'm going to be the only one with this issue. v3 worked without issue using Mix, and my v4 code worked fine when running via development.

### Steps to reproduce
1. Install Laravel Mix ([Instructions](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md))
2. Install Bugsnag v4.0.0 as NPM dependency
3. Edit content of app.js file referenced in webpack.mix.js to load bugsnag-js and attempt to initiate Bugsnag
4. Run ``npm run production`` command in Terminal
5. Load website to see error referenced above

I apologize for the work involved in reproducing this one! Kind of a pain.

### Version
v4.0.0

### Additional information
Again, I'm uncertain if this is something with Bugsnag JS or Laravel Mix (@JeffreyWay), and I can open this issue in their repository if it's a better fit there. This is, however, the only library I've had any problems with while using Mix, and Bugsnag JS v3 worked properly.

Let me know if there is anything more I need to dig up.

**Comment by bengourley** [comment]
Hi @aaronhuisinga thanks for the report! I've managed to reproduce, so thanks for the detailed steps.

> I apologize for the work involved in reproducing this one! Kind of a pain.

Don't worry 😂 this was relatively straightforward to get set up!

I'll let you know where I get with it.

**Comment by bengourley** [comment]
It looks like by default laravel mix uses the [`drop_console` compressor option](https://github.com/mishoo/UglifyJS2#compressor-options) in uglify.

I'm surprised this doesn't break other libararies and user code! I'll see if there's something we can do about it.

**Comment by JeffreyWay** [comment]
@bengourley Hmm, I wasn't under the impression that activating that option as a default would potentially break any libraries. I can tag a new release that removes it, if needed.

**Comment by jbrooksuk** [comment]
@JeffreyWay is this the same for Laravel Elixir?

**Comment by JeffreyWay** [comment]
@jbrooksuk In production mode, yes, I think it drops console.

**Comment by jbrooksuk** [comment]
@JeffreyWay that'll do it. Any chance we could get a new version out that doesn't? We're not yet able to make the upgrade to Mix (we're working on it) but we'd really like to get the Bugsnag Vue stuff out.

**Comment by JeffreyWay** [comment]
Yep, today I'll tag both packages to set that drop_console option to false by default.

**Comment by jbrooksuk** [comment]
Thanks @JeffreyWay 🍻

**Comment by bengourley** [comment]
Thanks for being responsive on this @JeffreyWay. I'm going to ship a version of bugsnag-js that scoots around this issue too (#281), as you're probably not the only one doing so!

**Comment by JeffreyWay** [comment]
Okay, Laravel Mix 1.7 has been tagged. We no longer strip console.logs.

**Comment by jbrooksuk** [comment]
Thanks @JeffreyWay!

**Comment by aaronhuisinga** [comment]
Thanks so much for the quick fix @JeffreyWay and @bengourley! You guys are great.
