### ISSUE TITLE
Most types used in public APIs are not exported for TypeScript

### ISSUE THREAD

**Issue by paavohuhtala** [bugsnag/bugsnag-js#282]
### Expected behavior
The TypeScript typings for `bugsnag-js` should export most if not all types used in public interfaces.

### Observed behavior
Only `Client` and `IPlugin` are exported. Others types are not accessible without type system hacks or manual copy paste.

### Version
`4.0.1` from npm

### Additional information
It's really hard and/or fragile to build abstractions over Bugsnag and integrate it into a pre-existing system in a type-safe way without access to the types. My current solution is to copy-paste the relevant interfaces into my code, which is not ideal in any way.

The most important types I need exported include `NotifiableError` and `INotifyOpts`, but there is practically no reason not to export everything. 🙂 

The easiest way to implement this would be to add `export { ... } from ...` clauses into `bugsnag.d.ts`.

**Comment by bengourley** [comment]
Hey @paavohuhtala, thanks for the feedback! I'd love to support your use case.

Could you supply a small example of how you're trying to extend Bugsnag so I can be sure to fix it. I think I understand from your description, but it would be excellent to have a piece of TypeScript which fails to compile before I make changes and then successfully compiles afterwards.

Cheers ✨

**Comment by paavohuhtala** [comment]
@bengourley My use case is as follows:

I'm currently in progress of refactoring our Bugsnag integration and upgrading it from `3.X` to `4.X`.

We want to provide a clean, minimal interface to the rest of the application, meaning that we only want to expose `BugsnagClient.notify()`, and always use the same singleton instance of the client. In short, we want to create a function with the same signature as `notify`.

So something like this should compile after exposing the types:
```typescript
// Initialised lazily and can remain undefined if the module was imported
// in unit tets or in a local development environment.
let bugsnagInstance: Bugsnag.Client | undefined = undefined;

// This line won't compile, because neither argument type has been exported.
export function notify(error: NotifiableError, opts?: INotifyOpts): boolean {
  if (bugsnagInstance === undefined) {
    return false
  }

  return bugsnagInstance.notify(error, opts)
}

 ```
