### ISSUE TITLE
Documentation of chrome-extension, beforeSend

### ISSUE THREAD

**Issue by DJWassink** [bugsnag/bugsnag-js#285]
Not an issue with this module, but more an issue concerning the documentation about this module.

The explanation about extensions and having to edit the stacktrace on: https://docs.bugsnag.com/platforms/browsers/vue/faq/#how-can-i-get-error-reports-from-browser-extensions

is telling us to use the following snippet:

```js
bugsnag({
  beforeSend: function (report) {
    report.stacktrace = report.stacktrace.map(function (frame) {
      return frame.file.replace(/chrome-extension:/g, 'chrome_extension:')
    })
  }
})
```

But the stacktrace is not a string but an object, after the replace all the other data except the location is lost (so no column/line/method).

Instead something like this should be used:

```js
bugsnag({
  beforeSend: function (report) {
    report.stacktrace = report.stacktrace.map(function (frame) {
      frame.file = frame.file.replace(/chrome-extension:/g, 'keepinghrome:');
      return frame;
    })
  }
})
```

This is obvious if using typing with typescript, the code mentioned in the documentation simply won't compile.

**Comment by bengourley** [comment]
Thanks @DJWassink, good spot. I'll make sure we get this fixed 👍

**Comment by kattrali** [comment]
Docs change deployed. 👍
