### ISSUE TITLE
TypeScript missing properties on Client

### ISSUE THREAD

**Issue by DJWassink** [bugsnag/bugsnag-js#286]
### Expected behavior
Should be able to set user and metaData properties on the bugsnagClient
https://docs.bugsnag.com/platforms/browsers/js/#identifying-users

### Observed behavior
Not (safely) possible in TypeScript

### Steps to reproduce
-

### Version
4.0.1

The `Client` which gets returned from the bugsnag constructor doesn't specify the `user` and `metaData`
https://github.com/bugsnag/bugsnag-js/blob/408d6c42efee413f9d6817f82ca8c2d16caf9666/types/client.d.ts#L5-L20

Since the documentation specifies that we can set a user/metaData (maybe even more? not sure) on the client object I would assume this simply got missed in the type definitions? Note that the `notify` method does allow a second param where we are able to specify these properties.

**Comment by bengourley** [comment]
Thanks for the report. I'll make sure we correct this when we address the types for #282.
