### ISSUE TITLE
Dist folder is empty

### ISSUE THREAD

**Issue by alejandromagnorsky** [bugsnag/bugsnag-js#291]
I tried to download the version 4 from bower but the `dist` folder, that should contain the JS files, is empty.

**Comment by nasa42** [comment]
This also seems to have broken https://rails-assets.org/#/components/bugsnag.

**Comment by ankurk91** [comment]
https://www.npmjs.com/package/bower-npm-resolver

**Comment by bengourley** [comment]
Hi @alejandromagnorsky. The `dist` folder is intentionally empty in the git repo. The built JS files are only created for a release and get pushed to npm and our CDN. Was the package @ankurk91 suggested helpful?

**Comment by alejandromagnorsky** [comment]
I tried the command:
`bower install "https://unpkg.com/bugsnag-js@4.0.3/dist/bugsnag.js"`
However, this message showed up:
`bower                     ENORESTARGET URL sources can't resolve targets`

Furthermore. I understand that the dist folder is empty in the repo. However, AFAIK, when using bower it should build as well.

**Comment by bengourley** [comment]
We changed our minds on this and are now populating `dist` in the repo. As of `v4.1.1` bugsnag-js should resume support for bower.

**Comment by XueDong369** [comment]
@bengourley It will be an empty folder now? I tried to `bower install bugsnag-js=https://github.com/bugsnag/bugsnag-js` and I always get the empty folder.

**Comment by bengourley** [comment]
@XueDong369 the link you used does point to a built file so I don't know what could be going wrong for you there.

The latest CDN version is hosted at https://d2wy8f7a9ursnm.cloudfront.net/v4.7.3/bugsnag.min.js
