### ISSUE TITLE
Upgrading 2 different script tags listed

### ISSUE THREAD

**Issue by naeohmi** [bugsnag/bugsnag-js#293]
In bugsnag-js/UPGRADING.md, both:

<script src="//d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.js"></script>
and
<script src="//d2wy8f7a9ursnm.cloudfront.net/4.x.x/bugsnag.js"></script>

are listed. Unclear if this is a typo, or these are two different options. Please help out with more information to clarify the differences. Thanks!

**Comment by bengourley** [comment]
Thanks for the report! This is fixed in 55a5c662097667bb2d5ce19cc7e01e3b3204dd57.
