### ISSUE TITLE
Client and session client user information

### ISSUE THREAD

**Issue by langri-sha** [bugsnag/bugsnag-js#308]
### Expected behavior

The client uses `client.config.user` information when composing the user for reports, which provides rooms for plugins to add their extra information.

The sessions user doesn't seem to respect this. Not really clear how user data is supposed to be attached now (or should only `user.id`, `user.name` and `user.email` be used for session users).

### Observed behavior

The session user is always `client.user`.

### Version

v4.1.2

**Comment by bengourley** [comment]
Hey @langri-sha. Nothing should set or change `client.config.user` directly, not even plugins. When the client is initialized, it takes the value from `client.config.user`:

https://github.com/bugsnag/bugsnag-js/blob/557db3e067e972b284d879d6c68d9cab44b7fae7/base/client.js#L65

After that, `client.user` is the value which is used for notify and session payloads. `client.user` can be set and tweaked accordingly. Currently only `{ id, name, email }` are the properties we care about.

I'm unsure what problem you're having exactly so if my explanation hasn't helped, let me know! Thanks

**Comment by langri-sha** [comment]
Thanks, this already clears up a lot of things and I've just found this out after posting https://docs.bugsnag.com/platforms/browsers/configuration-options/#user.

I'm just migrating from v2 to v4 and my application does add some custom user data, but some of it is fetched after the user's session would start. This shouldn't break notifications and sessions in Bugsnag, correct?

**Comment by bengourley** [comment]
Adding more data will be fine. Any additional properties you add to `user` will be shown in the "user" tab on your events.

So…
- no the extra detail will not "break" notifications/sessions
- the information is taken from error payloads (not sessions) so don't worry about trying to add that data before the session is sent

Hope this helps!

**Comment by langri-sha** [comment]
Thanks @bengourley :clap:
