### ISSUE TITLE
Exported typing for a Client is not working properly

### ISSUE THREAD

**Issue by rokerkony** [bugsnag/bugsnag-js#316]
### Expected behavior
`Client` should be possible to use as a type.

### Observed behavior
Even when build is completed successfully the running application throws: `Cannot read property 'Client' of undefined`

### Steps to reproduce
1. Go to: https://github.com/rokerkony/bugsnag-js-type-example (it is generated app by ng-cli + added bugsnag-js)
2. In the second commit you can see that the usage of a type is working but with any
`constructor (private client: any) {}`
3. In the third commit is already broken solution
https://github.com/rokerkony/bugsnag-js-type-example/commit/d69a8a5f570579a3b2ce6a5c8e84acffc1b8f3f3
You can run an app with `npm start` and see in the console an error.

You can also spot that in both commits this is working: `const bugsnagClient: Bugsnag.Client = ...`.
Which leads me to the idea that the solution could be to expose the interface instead of a class (just a guess).

### Version
since 4.0.2 (4.0.1 was working as it had types exported in a different way)

_I can do something wrong and I will welcome any solution._

**Comment by rokerkony** [comment]
I can also add that in v4.0.1 this was working:

```ts
import * as bugsnag from 'bugsnag-js';

class C {
    constructor (private client: bugsnag.Client) {}
}
```

**Comment by bengourley** [comment]
Hey @rokerkony thanks for the steps to reproduce. I figured it out – this was a weird one!

It has to do with the way Angular behaves in development. When you build your app for production `ng serve --prod` I noticed that this wasn't an issue. However in development, it sends the .ts files to the browser and compiles them on the fly. This meant that is was relying on the types being loaded in the browser too which they weren't.

I've made a change which fixes your test case for me, please could you confirm?

If you do `npm install "bugsnag/bugsnag-js#angular-dev-types"` you should pickup the fixed version to test. Thanks!

**Comment by rokerkony** [comment]
Hey, thanks for looking into it.
I just tried it on a bigger project we have and it was working just as expected 👍
Thanks
