### ISSUE TITLE
Uncaught Error: No ErrorHandler. Is platform module (BrowserModule) included?

### ISSUE THREAD

**Issue by grantfeldman** [bugsnag/bugsnag-js#321]
### Expected behavior
Able to build and deploy angular 5 application with bugsnag using `ng build --prod`

### Observed behavior
The follow error occurs straight away. `Uncaught Error: No ErrorHandler. Is platform module (BrowserModule) included?`

### Steps to reproduce
Follow bugsnag angular 5 integration instructions

### Version
4.2.0

### Additional information
package.json dependancy
`"@angular/platform-browser": "^5.2.2",`

Importing BrowserModule at top of app.module
`import { BrowserModule } from '@angular/platform-browser';`

Adding BrowserModule to imports
```
imports: [
        BrowserModule,
        ...
    ],
```

`ng build` works fine (development). After removing the following line `{ provide: ErrorHandler, useClass: BugsnagErrorHandler }` everything is fine.

![2018-01-26_18-19-28](https://user-images.githubusercontent.com/5257972/35428881-7f90294c-02c5-11e8-8d07-5653b755d58e.png)

**Comment by grantfeldman** [comment]
Hi @bengourley that seems to have fixed the problem. I haven't checked that the error handling functionality still works but at least the app loads. Also, would this work just as well?
`{ provide: ErrorHandler, useFactory: () => new BugsnagErrorHandler(bugsnagClient) }`

**Comment by bengourley** [comment]
I read mixed things about the AOT compiler – one said that you mustn't use lambdas in places like that. But I saw some conflicting example that said it translates examples like that into something like:

```js
export function a0 () { return new BugsnagErrorHandler(bugsnagClient) }

{ provide: ErrorHandler, useFactory: a0 }
```

So I erred on the side of caution in the example, but you are free to tweak as desired!

**Comment by grantfeldman** [comment]
I guess ultimately those lambdas are going to be transpiled into a function anyway..

**Comment by bengourley** [comment]
`v2.0.0` of bugsnag-angular is now released.

**Comment by grantfeldman** [comment]
Thanks @bengourley
