### ISSUE TITLE
Performance issues when logging large amounts of data

### ISSUE THREAD

**Issue by tur-nr** [bugsnag/bugsnag-js#324]
### Expected behavior
No bottlenecks whenever bugsnag is leaving breadcrumbs.

### Observed behavior
Bugsnag has a huge impact on performance whenever logging large amounts of data to the console. _Development only._

![image](https://user-images.githubusercontent.com/817134/35787795-ea6c7dd0-0a84-11e8-9192-8a496fe63687.png)

![image](https://user-images.githubusercontent.com/817134/35787813-0afc48f0-0a85-11e8-9b97-0a87fee64a4a.png)

### Steps to reproduce
1. Add bugsnag to an application with `{ consoleBreadcrumbsEnabled: true }`.
2. Open performance tab in Chrome.
3. Record.
4. Do tasks in Application that log a decent set of data.
5. Stop recording.
6. Review performance.

### Version
v4.2.0

### Additional information
Just to give your team some context. We are developing quite a large scale application that handles large amounts of data sets. During development we log these states to the console for review after certain actions. So we can follow the applications state pre/post action.

Our setup is your standard React + Redux. However we use Redux Logger that subscribes to the store's actions and state changes, logging them to the console.

We recently upgrade to v4 from v3 and found that parts of our application where extremely sluggish during development. Upon giving it a performance review we noticed the stringify and leave breadcrumbs functions where very time consuming due to application state being logged.

**Comment by bengourley** [comment]
Hey @tur-nr thanks for the report. In development you should switch off the `autoBreadcrumbsEnabled` option if you're logging large objects. We need to stringify the objects in order to test for duplicates and things like that, so it's just best to only enable that option in environments where you're not doing tonnes of logging.

**Comment by bengourley** [comment]
Hey @tur-nr. I'd still recommend switching off `consoleBreadcrumbsEnabled` if you know you're going to be logging large objects frequently. However, try the latest release v4.3.1. We've optimised the breadcrumb process to avoid perf issues as much as possible. Let us know how you get on! Cheers.
