### ISSUE TITLE
Infinite loop when exceptions occur within Observable streams (Angular 5)

### ISSUE THREAD

**Issue by grantfeldman** [bugsnag/bugsnag-js#325]
### Expected behavior
Angular errors / exceptions are logged to the console

### Observed behavior
CPU goes to 100% and browser locks up. No errors are output.

### Steps to reproduce
Setup and configure bugsnag in ng5 app as per instructions. Throw an exception within an Observable.

### Version
Latest

### Additional information
Angular 5

**Comment by bengourley** [comment]
Hi @grantfeldman, thanks for the report.

Please could you supply more information on how to reproduce this, specifically around what you are doing in this part:

> Throw an exception within an Observable.

Supplying a reduced test case would be the best, but a snippet illustrating what you are doing would be useful. This will help us to investigate the problem for you. Thanks!
