### ISSUE TITLE
Crash when accessing history.state on IE10

### ISSUE THREAD

**Issue by remko** [bugsnag/bugsnag-js#343]
### Expected behavior

No crash.

### Observed behavior

IE10 throws an 'Unspecified error' when bugsnag-js tries to access window.history.state.

### Steps to reproduce

I can't exactly tell how to reproduce this. In my case, it happens when I open the page, and then do 'refresh'.

### Version

bugsnag-js 4.5.0

### Additional information

Searching for this issue brings up other repositories the same issue, e.g. https://github.com/angular/angular.js/issues/10367 I've seen this being fixed by just wrapping the read of history.state in a try {} catch ().

(e.g. https://github.com/netman92/angular.js/commit/3bd03ff56f898cddc078791b85a127fafad3ec3c )

**Comment by bengourley** [comment]
Hey @remko thanks for letting us know about this issue. I'll take a look.
