### ISSUE TITLE
Browser address bar not updating in latest 4.6.1 release

### ISSUE THREAD

**Issue by dguillamot** [bugsnag/bugsnag-js#346]
### Expected behavior
Expect browser address bar to update when navigating

### Observed behavior
While navigating through our app, after including the the latest Bugsnag bundle version 4.6.1 released 2 hours ago, we no longer see the browser address bar updating. Removing the Bugsnag bundle fixes the issue. Perhaps related to: https://github.com/bugsnag/bugsnag-js/commit/58fd5ee3cb1bbe6be9dc5b2ab4506a8cc2ec7a35 

Also, reverting to 4.6.0 is confirmed to work. 

### Steps to reproduce
Note - We are using react-router

### Version
4.6.1

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by bengourley** [comment]
Hi @dguillamot thanks for raising this and sorry for the inconvenience. I have pulled v4.6.1 from the the CDN and npm registry. We will publish a fixed version in due course.

**Comment by dguillamot** [comment]
Awesome @bengourley thank you for the fast response!

**Comment by marcacyr** [comment]
We just yanked Bugsnag and cancelled our companies account with you guys, FYI. We can't afford for this to happen, ever.
