### ISSUE TITLE
npm ERR! No git binary found in $PATH

### ISSUE THREAD

**Issue by flrnt** [bugsnag/bugsnag-js#349]
### Expected behavior
run fine :)

### Observed behavior

got this in stacktrace
```
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/bengourley/stack-generator.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
```
### Steps to reproduce
`npm install` on my production server

### Version
4.6.0

I think it's relative to ssh path of the remote url, maybe need to switch to https ?

**Comment by bengourley** [comment]
It looks like you're trying to install Bugsnag on a machine that doesn't
have git installed? Some of bugsnag-js's dependencies are pulled in via git
so you'll need to install git first.

**Comment by flrnt** [comment]
works like a charm, ty @bengourley

**Comment by AidenFaulconer** [comment]
I am having a similar issue. Except, I have installed git, windows PowerShell recognised I have git, why won't this recognise I have it?

Error Log from console: 

[22:25:08] Installing dependencies...
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/expo/vector-icons.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by lylest** [comment]
so how to solve this??

**Comment by jxnielle** [comment]
> so how to solve this??

Download git: 
https://git-scm.com/downloads

**Comment by FangMingHong** [comment]
I have installed Git and configured environment variables,but not solve it

**Comment by snmaynard** [comment]
You need to install git and have it available in your path then it should work.
