### ISSUE TITLE
Possibility of an afterNotify callback?

### ISSUE THREAD

**Issue by Kequc** [bugsnag/bugsnag-js#35]
Similar to being able to define a beforeNotify method, afterNotify would tell my application something had gone wrong and application state was unknown.

From this I could start checking my javascript objects or perhaps reload the page without interrupting the notification from being sent.

**Comment by tommedema** [comment]
@ConradIrwin one win from a `afterNotify` call would be that it's a safe time to inform the user that something went wrong, without risking causing another exception before the event was sent to bugsnag
