### ISSUE TITLE
Compatibility with Rollup

### ISSUE THREAD

**Issue by pieterbeulque** [bugsnag/bugsnag-js#350]
### Expected behavior
A passing build, as suggested in [the documentation](https://docs.bugsnag.com/platforms/browsers/js/#npm-yarn).

### Observed behavior
Rollup throws an error:

```Error: 'default' is not exported by node_modules/bugsnag-js/dist/bugsnag.js```

### Steps to reproduce
1. Create a file, e.g. `bugsnag.js`
2. `import bugsnag from 'bugsnag-js';`
3. Build the file with Rollup
4. Rollup throws the error above

### Version
4.6.3

### Additional information
I use rollup-stream with rollup-plugin-node-resolve to work with packages installed through NPM.

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by bengourley** [comment]
Hi @pieterbeulque, you'll need to add [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) to your rollup build. We do [export a default property](https://github.com/bugsnag/bugsnag-js/blob/6f13b49b4e93fb107ebd99adf35e1e674b6ef800/browser/index.js#L145) but I don't know why rollup won't pick it up.

**Comment by pieterbeulque** [comment]
That was it! Thanks a lot.
