### ISSUE TITLE
error in metadata field is not logged as intended

### ISSUE THREAD

**Issue by daisy1754** [bugsnag/bugsnag-js#356]
### Expected behavior
Take code below as example. Both `foo` and `bar` should be recorded on bugsnag

```:javascript
const err = new Error("test");
client.notify(
    new Error("Debug metadata"),
    {
      metaData: {
        field,
        foo: err,
        bar: { name: err.name, message: err.message, stack: err.stack },
      },
      severity: "info",
    });
```

### Observed behavior
`foo` above is not recorded as bugsnag.
I think this is because the library uses https://github.com/bugsnag/safe-json-stringify internally to convert object to JSON, and safe-json-stringify doesn't treat properly stringify `error` object.

FWIW, I have recently reported a similar issue to bugsnag-react-native
https://github.com/bugsnag/bugsnag-react-native/issues/239

### Steps to reproduce
Please see my note above

### Version
4.4.0

**Comment by dnunes** [comment]
I see that you guys already published a new version of the safe-json-stringify. I added a comment with a potential improvement on the solution at https://github.com/bugsnag/safe-json-stringify/commit/8f891784d7628970196c593a2588121035da0129#r31851745. It may be useful for future version as it would include more info for the error, specially the "stack", that may even get a special treatment with "split" over the "\n" creating a sub-array that would be very easy to read on bugsnag dashboard.
