### ISSUE TITLE
Angular 1.x application route changes are following with new session requests to bugsnag

### ISSUE THREAD

**Issue by mesin** [bugsnag/bugsnag-js#364]
### Expected behavior
The only one session request should be sent?
Problem is that every request sends different session ID.

### Steps to reproduce
Just create angular app and use angular ui-router library for navigation.
Every route change is followed by new session request.

### Version
angular: 1.6.9
angular-ui-router: 0.4.2
Bugsnag JavaScript: 4.7.2

### Additional information

Initialization:

```
      window.bugsnagClient = bugsnag({
        apiKey: '***',
        notifyReleaseStages: [ 'production', 'staging' ],
        releaseStage: 'production'
      });
```

<img width="930" alt="bugsnag-many-sessioins-on-angular-route-changes" src="https://user-images.githubusercontent.com/297536/42424881-fb52427c-831c-11e8-86db-95244496b78e.png">

**Comment by bengourley** [comment]
Hey @mesin. This is desired behaviour, documented [here](https://docs.bugsnag.com/platforms/browsers/js/#session-tracking). We send a new session any time a page is loaded or the URL/route changes.

If you don't want this behaviour, you can [set `autoCaptureSessions: false` and call `bugsnagClient.startSession()` manually](https://docs.bugsnag.com/platforms/browsers/js/configuration-options/#autocapturesessions) at times when you deem appropriate.

Note that our product's definition of a "session" is a little different to that of a typical "web" session, which accounts for multiple interactions from the same user.
Our definition is more synonymous with an engagement with an application, such as a mobile application entering the foreground, web server handling a single request, and for browser js, a page load or a route change.

Of course if your route changes frequently, but doesn't result in massively different codepaths from being exectuted, it would make a lot of sense to switch off automatic session tracking and call `startSession()` manually.

Hope this helps. Let me know if you have any more questions. Cheers!

**Comment by mesin** [comment]
@bengourley yes this explains a lot of things to me!
Thanks for such a great and fast answer 👍 🥇
