### ISSUE TITLE
Can I disable the message "Session not sent due to..."?

### ISSUE THREAD

**Issue by waynebloss** [bugsnag/bugsnag-js#376]
### Expected behavior
I'd like to be able to disable the following logging message that I get when I disable reporting via `releaseStage/notifyReleaseStages`:

```
 Session not sent due to releaseStage/notifyReleaseStages configuration
```

### Observed behavior
I am not sure how to do this.

### Steps to reproduce

1. Disable error reporting via `releaseStage/notifyReleaseStages`.
2. Cause an error.

### Version
4.7.2

### Additional information
Thanks!

**Comment by bengourley** [comment]
Hi @waynebloss, you can set `logger: null` in your configuration to switch off logging:

https://docs.bugsnag.com/platforms/browsers/js/configuration-options/#logger

Let me know if you need anything else!

**Comment by gaastonsr** [comment]
But that will disable *all* logging. What if I want to disable those diagnostic errors?

**Comment by bengourley** [comment]
We don't have granular configuration for every kind of log message. If you opt in to logging you get them all. That particular log message is a `warn()` so you could provide a custom logger that only logs error level.

```js
function noop () {}
var logger = {
  debug: noop,
  info: noop,
  warn: noop,
  error: function () { console.log.apply(console, arguments) }
}

bugsnag({
  logger: logger
})
```

That is just one example. You could get more creative and filter out just the messages you don't want to see and continue to include `debug`/`info` logs. It's up to you!

Hope this helps.

**Comment by govi218** [comment]
Has this changed since?

**Comment by mclack** [comment]
Hi @govi218 

In order to configure the logs, you would still need to define your own `logger` and provide `debug`, `info`, `warn` and `error` methods. You can read more about this in our documentation here: https://docs.bugsnag.com/platforms/javascript/configuration-options/#logger
