### ISSUE TITLE
bugsnag.js is too big

### ISSUE THREAD

**Issue by perevezencev** [bugsnag/bugsnag-js#379]
Why does bugsnag.js take the same places as the rest of my application?
<img width="582" alt="2018-07-30 22 23 54" src="https://user-images.githubusercontent.com/5954104/43419077-a63dfd3e-9448-11e8-82e0-8020ff86ed11.png">

What am I doing wrong?

**Comment by bengourley** [comment]
bugsnag-js/dist/bugsnag.js includes an inline source map, for ease of debugging. When you minify your code the source map will be removed. Are you using uglify js for example?

**Comment by perevezencev** [comment]
Yes. Now I'm not sure that the webpack bundle analyzer is working correctly. I'm sorry for the trouble.
