### ISSUE TITLE
Error in Microsoft Edge 18+ "lineNumber must be a Number"

### ISSUE THREAD

**Issue by corymsmith** [bugsnag/bugsnag-js#393]
### Expected behavior
Correctly log error w/ stacktrace.

### Observed behavior
Errors out at the line in the below screenshot. 

### Steps to reproduce
This seems to only be happening on Microsoft Edge 18+ versions and no other browsers.

### Version
4.7.2

### Additional information
![screen shot 2018-08-29 at 11 19 14 am](https://user-images.githubusercontent.com/7315/44804071-8971d300-ab7d-11e8-97dc-38f5b86c6d40.png)

**Comment by bengourley** [comment]
Hi @corymsmith, thanks for raising this. Sorry for the delay in getting back to you.

This looks similiar to #392. It is essentially the same issue, but may have a different set of conditions which result in the same problem. Either way, solving #392 will solve this too. I'll get that reviewed and published in due course.

**Comment by corymsmith** [comment]
No worries @bengourley, thanks for the update.
