### ISSUE TITLE
Permission denied to access property "reason"

### ISSUE THREAD

**Issue by apexskier** [bugsnag/bugsnag-js#394]
We've seen bugsnag reports for a couple users with the error message `Permission denied to access property "reason"` coming from within the bugsnag js library.

Stacktrack:
```
Error Permission denied to access property "reason" 
    node_modules/bugsnag-js/dist/bugsnag.js:1833 listener
```

```
  | var error = event.reason;
  | var isBluebird = false;
  |  
--| if (event.detail && event.detail.reason) {
  | error = event.detail.reason;
  | isBluebird = true;
  | }
```

It's been reported on Firefox 60 and 61 on both macOS 10.11 and Windows 7.

The bugsnag (for our organization) is here, if you're able to look at it in more detail https://app.bugsnag.com/remitly/remitlywebapp/errors/5b895c63bc77370017320483

**Comment by bengourley** [comment]
Hi @apexskier, thanks for the report.

This looks like a violation of the [same origin policy](https://en.wikipedia.org/wiki/Same-origin_policy). Are there any frames included on the page which originate from different domains?

Regardless of whether you can figure out how this is happening on your app, we can certainly try to handle this situation better, at the very least by wrapping the property access in a `try`/`catch`. The stacktrace or the name/message from the error might be salvageable, even if there are some attached properties which belong to a different domain. It could be a lost cause though!

I'll add a ticket to our internal backlog to look in to this.

**Comment by apexskier** [comment]
We do have an external frame on the site. It's been present for quite a bit longer than we started seeing this bug though (but with the low number of bugs that might just be a coincidence).

If it's coming from an external frame, we definitely don't need to receive all data, but if we could know which frame it's coming from that would help. Thanks for the info!
