### ISSUE TITLE
User-defined breadcrumb type doesn't show up on the Bugsnag website

### ISSUE THREAD

**Issue by ClementParis016** [bugsnag/bugsnag-js#396]
### Expected behavior

The `leaveBreadcrumb()` method on the Bugnsnag client instance accepts a `type` parameter of type `String` at third position. When setting this value to a custom string, I expect it to be displayed on the Bugsnag website (possibly with the same circle icon used to represent breadcrumbs that have a "manual" type, which is the default value).

### Observed behavior

Breadcrumbs with a custom type are not displayed at all in the error report on the Bugsnag website.

### Steps to reproduce

Call the `leaveBreadcrumb` method with a custom `type` value, other than "request", "navigation", "user", "log" and "manual", then trigger an error and look at it's Breadcrumbs tab on the Bugsnag website.

### Version

bugsnag-js@v.4.7.3

**Comment by bengourley** [comment]
Hey @ClementParis016, apologies for the confusion but this is the correct behaviour. We have a list of allowed types which are associated with the appropriate icons etc, but all others should be `manual`. 

If you want to provide custom data to a manual breadcrumb, you can add it via the `metaData` parameter.
