### ISSUE TITLE
Errors logged with `.notify` are not logged to the console

### ISSUE THREAD

**Issue by gaastonsr** [bugsnag/bugsnag-js#397]
When I'm developing an application I log some errors manually with `.notify` and I expect those not just to be sent to bugsnag but also to appear on my console so I can fix them.

### Expected behavior
To see errors logged to console.

### Observed behavior
Error is sent directly to bugsnag without logging it to the console.

### Steps to reproduce
`bugsnagClient.notify(new Error('I will not appear on the console :)')`

**Comment by bengourley** [comment]
Hi @gaastonsr, it's possible to do this yourself with a wrapper function like so:

```js
function reportError(err) {
  bugsnagClient.notify(err)
  if (IS_DEV_ENV) console.error(err)
}
```

And replace all of your calls to `bugsnagClient.notify(err)` with `reportError(err)`.

Meanwhile I've added a note to discuss internally if this is something our notifiers should do by default.
Cheers

**Comment by gaastonsr** [comment]
That's simple and effective approach, I'll take it :)

Thanks!
