### ISSUE TITLE
Cannot add property _restore, window.history object is not extensible

### ISSUE THREAD

**Issue by drdmitry** [bugsnag/bugsnag-js#399]
### Expected behavior
bugsnag-js client installed on the web page without errors

### Observed behavior
There is an error occured during the bugsnag-js client init process.
It seems window.history object marked with preventExtensions() command and this avoids its changes.

![image](https://user-images.githubusercontent.com/4129726/46663599-d0aca400-cbbe-11e8-8da8-18fcefed0a00.png)

### Steps to reproduce
Open page https://www.patientenfragen.net/search.php?searchid=792341 and look at console for an error.

### Version
4.7.0

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by drdmitry** [comment]
After additional investigation, I found that some external library redefining the `window.history` object, and this causes an exception on bugsnag initialization:

![image](https://user-images.githubusercontent.com/4129726/47359097-1c397480-d6cc-11e8-8f08-ce241f5f25cb.png)

What might help is to have an exceptions handling (try catch) during the bugsnag initialization.

**Comment by bengourley** [comment]
Thanks for this issue @drdmitry. We certainly can look at wrapping this (or all plugins initialisation) in a try/catch. Is it possible for you to load Bugsnag _before_ the script that modified the history object?

Arguably the script that is making the history object non-configurable should be changed, but if it's prevalent or common enough, then Bugsnag should adapt.

**Comment by drdmitry** [comment]
@bengourley thanks for your reply. For the mentioned case - code which uses bugsnag is loaded (or executed) separately from the website and the load order cannot be changed.
