### ISSUE TITLE
v4 - access to original exception in beforeSend

### ISSUE THREAD

**Issue by dadleyy** [bugsnag/bugsnag-js#420]
### Desired Behavior & Use Case

Currently in `v4.x`, the `beforeSend` callback receives a [report object](https://docs.bugsnag.com/platforms/browsers/js/customizing-error-reports/#the-report-object ) that does not include the original exception objects that are associated w/ the report. Having the original error instance included in the report would allow clients to leverage more sophisticated logic when determining whether or not to send the report along to the server. This would enable ember applications to leverage things like [`isAjaxError`](https://github.com/ember-cli/ember-ajax/blob/101c357645cff3ac7f5a6b0d4315275ddc882e62/addon/errors.ts#L82-L84).

Related to #43.

**Comment by bengourley** [comment]
This seems like something we can consider. I see how it could be useful for you.

**Comment by broofa** [comment]
+1 on this.  Specifically, it's not uncommon for 3rd-party libraries to put essential information about errors in ad-hoc properties.  Some specific examples I've run into include:

- `SendGrid`: `error.response.body.errors` for errors returned from their service API
- `Sequelize`:  `error.original.sql` for the raw SQL query,  `error.errors` for data validation errors
- `Joi`: `error.annotate()` for validation error details
- `AJV`: `error.errors` for validation error details

Being able to append this information to a bug report would be extremely helpful.
