### ISSUE TITLE
Breadcrumb name truncated to 30 characters

### ISSUE THREAD

**Issue by forresto** [bugsnag/bugsnag-js#431]
It seems that our custom breadcrumb `name` is getting truncated to 30 characters in the UI. This makes some of our breadcrumb trails less useful, as the unique part exists past 30 characters.

Can this be fixed in the UI? The request to `https://notify.bugsnag.com/` has the full `name`s.

(I contacted support about this as well.)

**Comment by snmaynard** [comment]
I'm going to close this issue as its not an issue with the notifier, more a dashboard issue. The support team will get back to you on your ticket there. Thanks!
