### ISSUE TITLE
Duplicate error events during change detection( Angular)

### ISSUE THREAD

**Issue by TwunTee** [bugsnag/bugsnag-js#433]
Bugsnag error handler sends duplicate errors if an error happens during change detection. 

If there is some undefined variable thats used in the template, infinite loop of error occurs due to the way change detection works. 

```
<div *ngIf=undefinedVariable></div>
```
Errors are infinitely logged in the console until the window is closed. A discussion is going on in angular repo regarding the way such errors are handled https://github.com/angular/angular/issues/17010. I was using sentry before and haven't faced this issue in it.

**Comment by TwunTee** [comment]
The errors are grouped together but it add towards the event count. It does stop reporting after hitting the limit though, right now i am using that as a work around and using max limit as 3.

**Comment by bengourley** [comment]
Hi @TwunTee, I've looked into this and have figured out a few things:

- the example you provided doesn't produce an error at all – the `undefinedVariable` expression is deemed "falsey" by the renderer and it just doesn't render that `<div>`
- I swapped that out for an expression which does error, and the maximum number of times it would happen is 2 – so not an infinite loop (I tried this on Angular 5 and Angular 7 with Ivy enabled)

We could look at fingerprinting the errors and making sure that a certain amount with a unique fingerprint get through per time frame, but for the complexity that would add, I don't know if it's worth it and it seems like something that should be fixed on Angular's side anyway.

I'm going to close this off but if you think there is something we can do or you need some help configuring Bugsnag, give us a message at support@bugsnag.com.

Cheers!
