### ISSUE TITLE
client._logger is not a function

### ISSUE THREAD

**Issue by DanWilliamsAu** [bugsnag/bugsnag-js#436]
I'm trying to set up a new bugsnag project with an isomorphic js app running express.  I've set up bugsnag and express according to [these instructions](https://docs.bugsnag.com/platforms/javascript/express/).  At this stage, I'm just trying to get bugsnag working on the server.

When an unhandled exception in production occurs, I'm seeing an error show up in my bugsnag project, however the error is related to bugsnag itself, not the error from my application. 

```
TypeErrornode_modules/@bugsnag/node/dist/bugsnag.js:1939
client._logger is not a function
```

And the top of the the stack trace

```
node_modules/@bugsnag/node/dist/bugsnag.js:1939:30
---
  }
  }), {}, function (e, report) {
  if (e) return client._logger('Failed to send report to Bugsnag');
  client.config.onUnhandledRejection(err, report, client._logger);
  });
  };

```

Here's a screenshot in the bugsnag app.
![image](https://user-images.githubusercontent.com/5985804/49185513-41e62780-f3b6-11e8-9747-dba54392bbb1.png)

What am I missing here? 

bugnsag/js version: 5.0.0
node version: 10.13.0

Other information, the app is bundled with webpack, with babel-loader and awesome-typscript-loader and other things in the mix.  Could webpack be an issue?

Potentially related, but I'm also noticing in development mode if I try to import the bugsnag client anywhere in the bundled code, I'm getting 

```MODULE_NOT_FOUND: Cannot find module 'error-stack-parser'```

Which may be another clue.

Thanks in advance for any light you may be able to shed on this!

**Comment by bengourley** [comment]
Hi @DanWilliamsAu, thanks for opening this up and posting a lot of detail. It looks like there are a few things going on here, so I'm going to try to unravel them:

1. The actualy error report that you're seeing in the dashboard is bug with notifier which we will fix. That line says `client._logger(msg)` but it should be `client._logger.error(msg)`.

2. The actual error in your application, as you can just about see from the context there and the code path, was an unhandled promise rejection, a synchronous exception was thrown when trying to send the report here:

    https://github.com/bugsnag/bugsnag-js/blob/4109aa682f6132670e54c898f868a5a96d7d8391/packages/delivery-node/delivery.js#L7-L26

    The `logger.error(e)` message may have been output to your console if you have access to logs for this situation. Any chance you can retrieve that? It could be the `config.endpoints.notify` is not set to a valid URL, or the payload failed to serialize, or there was a value passed to `config.proxy` that was not valid… if you can't find the log, then perhaps you could paste the output of your Bugsnag config (blank out any sensitive values of course).

3. Re: `MODULE_NOT_FOUND: Cannot find module 'error-stack-parser'`, this sounds like either an issue with the installation, the bundler doing something funky with `require()`, or the bundler looking for the module in the wrong place. When you install `@bugsnag/js` this is the dependency tree that you would get on successful install… you can see that `error-stack-parser` is there:
    ```
    @bugsnag/js@5.0.0
    └─┬ @bugsnag/node@5.0.0
      ├── byline@5.0.0
      ├── error-stack-parser@2.0.2
      ├── iserror@0.0.2
      ├── pump@3.0.0
      ├── request@2.88.0
      └── stack-generator@2.0.3
    ```

Whilst I fix the bug from point (1) any more information you can provide regarding your Bugsnag configuration would be helpful. And if you could provide a stripped back project which reproduces any of these problems that will be super helpful.

Thanks!

**Comment by DanWilliamsAu** [comment]
Thanks for looking at this and fixing part 1!

2. I found the logs for that particular error and it seems like the issue was `[bugsnag] Error: payload exceeded 1MB limit`.  I'm not 100% sure why the log would have been so massive, but for what it is worth, here's the stack trace: https://gist.github.com/DanWilliamsAu/f4230b487949201b530e8435dbacdafe 

3.  I can see that I am not the only person having this problem: https://github.com/bugsnag/bugsnag-js/issues/441 I think that issue does a good job of explaining the problem in better detail. so I'm happy to consider this particular issue resolved for now and I'll follow the progress of that issue.

Thanks!

**Comment by bengourley** [comment]
Thanks, we'll track 3. on #441 then.

re: 2., if this is consistently happening, adding a `beforeSend` which logs out the report as JSON, might help you spot the offending part:

```js
beforeSend: function (report) {
  console.log(JSON.stringify(report, null, 2))
}
```

The library removes `metaData` from the report and tries sending again, so it must be in another part of the payload:

https://github.com/bugsnag/bugsnag-js/blob/83908fff2abeb4177c891ceab6680f3c20035c06/packages/core/lib/json-payload.js#L18-L29

**Comment by DanWilliamsAu** [comment]
Thanks for your prompt response and advice! :) 

We ended up removing bundling node_modules for our server bundle, which ended up fixing problem 3.

I think we are all good now so  I'll close this!
