### ISSUE TITLE
notifyReleaseStages prevents exception logging to console

### ISSUE THREAD

**Issue by jgentes** [bugsnag/bugsnag-js#449]
If I use `notifyReleaseStages` to prevent sending reports when we're running in dev, it also swallows the errors in the console. All I see is:

```
bugsnag.js:1581 Loaded!
bugsnag.js:281 Report not sent due to releaseStage/notifyReleaseStages configuration
```

For now we're reporting all exceptions, even in dev as a workaround, and we're overloading our quota. Could really use a fix for this one.

**Comment by snmaynard** [comment]
You can use a beforeNotify function that returns false in dev after printing the error in the console (as an interim measure).

**Comment by mfouad** [comment]
I think the problem is that the default onUncoughtExpection is not called in that case
or any callback sent to notify() in that case

```
if (isArray(this.config.notifyReleaseStages) && !includes(this.config.notifyReleaseStages, releaseStage)) {
      this._logger.warn("Report not sent due to releaseStage/notifyReleaseStages configuration");
      return false; // ISSUE: should call cb() here 
}
```

**Comment by snmaynard** [comment]
I wouldnt use notifyReleaseStages in that case. You can just return false in dev yourself from the callback

**Comment by mfouad** [comment]
> You can use a beforeNotify function that returns false in dev after printing the error in the console (as an interim measure).
I think you mean beforeSend in the new library. From the code it seems wont be called in this case too. so no luck :disappointed:

**Comment by mfouad** [comment]
> I wouldnt use notifyReleaseStages in that case. You can just return false in dev yourself from the callback

I think you mean beforeSend in the new library. From the code it seems wont be called in this case too. so no luck :disappointed:

**Comment by jgentes** [comment]
I've tried to get this to work, but the bugsnag report isn't great if just logged to the console. I've tried creating a real Error object out of it, but haven't had much success:

```
beforeSend: function (report) {
    if (Env.DEV) {
      // create an object that has Error properties
      report = {
        message: report.errorMessage,
        stack: report.stacktrace
      }
      // try to log this to console as a real exception
      try {
        throw(report);
      } catch(e) {
        return false;
      }
    }
```

Unfortunately the throw never makes it to the console, perhaps because it ends up getting swallowed in the same loop? Not sure, but any ideas on how to convert the bugsnag report object into a real error would be appreciated.

**Comment by snmaynard** [comment]
You should be able to do something like `console.error(report.errorClass + ": " report.errorMessage)` and optionally `console.error(report.stacktrace)` It might not look exactly like the uncaught exception output but hopefully gets you close to what you want without having to wait for us to implement.

**Comment by broofa** [comment]
[Disclosure:  I work with the OP, but have run into this problem independent of his report here]

The proposed workaround in the previous comment is not an adequate solution.   Not only is it overly verbose, it drops essential information.  E.g. In the sample below note how the first four lines of the original log output, that describe where the syntax error _actually is_, are not included in the workaround output.

At the risk of being overly dramatic, this sort of issue - where bug reporting software gets "in between" me and the code I'm trying to debug, quickly becomes a showstopper issue.  Do with that what you will.

Original console output:
```
/Users/kieffer/tend/code/cellmate/sidekick/lib/BaseClient.js:293
    const realtimeItem = {time: now;
                                   ^

SyntaxError: Unexpected token ;
    at createScript (vm.js:80:10)
<< 14 stack frames clipped >>
    at Module.require (module.js:597:17)
```

"Workaround" output:
```
SyntaxError: Unexpected token ;
[ { file: 'vm.js',
    method: 'createScript',
    lineNumber: 80,
    columnNumber: 10,
    code: undefined,
    inProject: undefined },
<< 97 lines of stack info cut >> 
  { file: 'module.js',
    method: 'Module.require',
    lineNumber: 597,
    columnNumber: 17,
    code: undefined,
    inProject: undefined } ]
```
