### ISSUE TITLE
Question: Are bugsnag client instances isolated in browser environments?

### ISSUE THREAD

**Issue by keattang** [bugsnag/bugsnag-js#454]
In the previous version of this library, before the move to make it universal, bugsnag would write itself to the window, meaning you couldn't have multiple instances of the client with different API keys. 

To get around this there was an undocumented `noConflict` method that you could use to get an isolated instance. I notice that there is no such method anymore. 

Does this mean that instances are now isolated by default?

**Comment by bengourley** [comment]
Instances are isolated, yes. However, when you initialize them they do hook in to some global event handlers and therefore have some side effects which would conflict or result in duplicate error reports.

If you want to initialize multiple clients on the same page, you should use the [`autoNotify: false`](https://docs.bugsnag.com/platforms/javascript/configuration-options/#autonotify) option on at least on of the clients (as you will only want one of them to report unhandled errors).

Out of interest, what is your use case for creating multiple clients on the same page?

**Comment by keattang** [comment]
Cool thanks @bengourley. When you say 
> use the `autoNotify: false` option on at least on of the clients 
do you mean that I should disable `autoNotify` on all the clients except one?

We have a rather large single page react app that we have modularised into sub apps so that our different development teams can work on/own/release separate parts of the app. Each team wraps their sub apps in a react error boundary that catches any errors inside and reports them to bugsnag. We use separate bugsnag apps for each sub app so that it's easier to understand which part of the larger app the bug is coming from and so that teams don't have to deal with or see other team's bugs.

We also have an over arching app that orchestrates and knows how to find/mount the sub apps. It is also wrapped in an error boundary that reports to its own bugsnag app. In this scenario, would you suggest that we disable `autoNoftify` on all the sub apps and leave it enabled in the orchestrator app?

**Comment by akinnee** [comment]
We use a microfrontend architecture. Navigating between different tools owned by different teams in our product does not trigger a full page reload. We are running into issues where errors are showing up in the wrong bugsnag project if bugsnag was initialized in one tool, then the user navigated to another tool, then an uncaught exception occurred. Having separate bugsnag instances is totally valid, and should be supported.
