### ISSUE TITLE
Allow "groupingHash" to be passed on "opts" when using bugsnag.notify(err, opts)

### ISSUE THREAD

**Issue by dnunes** [bugsnag/bugsnag-js#457]
In the previous version of bugsnag, one could use:
```js
bugsnag.notify(new Error('error message'), {
  'metaData': {...},
  ...,
  'groupingHash': 'MY_CUSTOM_GROUPING_HASH'
});
```

Now I see this possibility is missing from the code, requiring you to use a "beforeSend" callback. I took a quick look and it looks like it could use the same logic as in https://github.com/bugsnag/bugsnag-js/blob/next/packages/core/client.js#L178, using something like:
```js
report.groupingHash = { ...report.groupingHash, ...this.groupingHash, ...opts.groupingHash }
```

It looks like the property is present in https://github.com/bugsnag/bugsnag-js/blob/next/packages/core/report.js just like the others, it is just not being set by the client.js code.

Is there any plans to add that back? Or is there any other way I am missing?

**Comment by dnunes** [comment]
Oh, I just saw that this exact limitation is documented in the "UPGRADING.md". Is there any rationale behind that change? Why is groupingHash no longer used from the `opts` arg?

**Comment by bengourley** [comment]
The reason it's not in the options hash is to discourage its usage. Setting `groupingHash` should be a last resort when Bugsnag's own grouping logic is causing problems.

This is usually something you should contact support about to see if there is something obvious or something we can do better. Or if you're happy to post the detail here, feel free to do so. What kinds of errors are you seeing grouped incorrectly?

**Comment by bengourley** [comment]
We've discussed this internally. Although we want to make sure this option is only used in the right circumstances, it does seem unnecessary to omit it from the options hash so we will add it.

**Comment by dnunes** [comment]
> This is usually something you should contact support about to see if there is something obvious or something we can do better. Or if you're happy to post the detail here, feel free to do so. What kinds of errors are you seeing grouped incorrectly?

I have an app that do a lot of async networking talking with multiple APIs that fails periodically (multiple times every hour, for example). As I don't want expected network errors to wake me up at 3am, I have a handling logic that logs warnings and handle the retry logic, throwing errors only after certain criteria (3 times in a row, 5 times in a 10 minute window etc).

Every network call return goes through the same handling routine (and the actual `new Error()` is run inside this internal library), so bugsnag "sees" all the bugs as being the same based on top stack/file name/line number. Although I can go through the stack frames and mark they as being unimportant, because of the nature of this app, even the "pre-handling" run inside high-level functions on abstract classes and would not be very useful for grouping as well. My need is to group errors based on which service I called and what call failed, but I use a lot of abstract methods and callbacks/promises/closures for API-specific code, so the parts that deals with errors are inside the parent classes.

With something like:
```js
class AbstractParent {
  okCallback(networkReturn) { throw new Error('not implemented'); }
  doRequest(params) {
    return request(params, this.handleReturn.bind(this));
  }
  handleReturn(networkReturn) {
    if (networkReturn.code !== 200) {
      let errMessage = `${this.getAPIID()} - error while checking yadda yadda`;
      throw new Error(errMessage);
    }
    return this.okCallback(networkReturn);
  }
}

class ApiSpecific1 extends AbstractParent {
  okCallback(networkReturn) { console.log('I do not come in peace.'); }
  doRequest() {
    // api specific data, auth and params
    return super.doRequest(params);
  }
}

class ApiSpecific2 extends AbstractParent {
  okCallback(networkReturn) { console.log('Im afraid I cant do that'); }
  doRequest() {
    // api specific data, auth and params
    return super.doRequest(params);
  }
}
```
With something like this, errors from different APIs and with different messages would be grouped in a single item in bugsnag dashboard, even though the messages can be quite different from one another. To get more meaningful grouping I have been using a groupinghash that is best suitable for my usage, based on the error message + some specific metaData that may be present.


> We've discussed this internally. Although we want to make sure this option is only used in the right circumstances, it does seem unnecessary to omit it from the options hash so we will add it.

That's nice to hear. I have implemented a hacky handler that goes:
```js
if (report.metaData._groupingHash) {
  report.groupingHash = report.metaData._groupingHash;
  report.removeMetaData('_groupingHash');
}
```
and I am looking forward to remove that from the code :)
