### ISSUE TITLE
console logs dont get captured to appear in breadcrumbs

### ISSUE THREAD

**Issue by joao-carvalho-newvision** [bugsnag/bugsnag-js#461]
I'm using 

@bugsnag/js and @bugsnag/plugin-react

In the configuration [guide](https://docs.bugsnag.com/platforms/javascript/react/#leaving-breadcrumbs) is said that by default console logs, warnings, and errors are automatically captured;

I was not able to do that (all exceptions are recorded with no info about the console logs)

How to achieve that?

My configuration code 

```
import bugsnag from '@bugsnag/js';
import bugsnagReact from '@bugsnag/plugin-react';

export const bugsnagClient = bugsnag({
  apiKey: '....',
  maxBreadcrumbs: 40,
  // I'v tried several configurations with this options bellow:
  // autoBreadcrumbs
  // autoBreadcrumbsConsole
  // autoBreadcrumbsconsole
  // consoleBreadcrumbsEnabled
});

bugsnagClient.use(bugsnagReact, React);
```

Thanks

**Comment by bengourley** [comment]
Are you setting `releaseStage: 'development'`?

As per the docs for [`consoleBreadcrumbsEnabled`](https://docs.bugsnag.com/platforms/javascript/configuration-options/#consolebreadcrumbsenabled-browser-only) this feature is switched off in development so that it doesn't obscure line numbers.

**Comment by bengourley** [comment]
Looks like this may have something to do with #465.

**Comment by joao-carvalho-newvision** [comment]
@bengourley It seems that was the problem; I did not configured anything about releasestage so I guess it was development by default.

I was able in some moment to track console messages but is still not showing nothing if I use/mix diff configs with xxxBreadcrumbsEnable options so it looks like the issue you mention in your last comment is pointing the error cause.

Thanks
