### ISSUE TITLE
Koa error handler overwrites ctx.throw error status

### ISSUE THREAD

**Issue by my-name-was-already-taken** [bugsnag/bugsnag-js#471]
Hey guys,

we are currently integrating Bugsnag with our Koa app; we've noticed your error handler middleware always ends up throwing a 500 error, even when we call ``return ctx.throw(400, "Error");`` from within a route; apparently as Bugsnag always defaults to a 500 error if headers aren't sent yet.

Can you guys investigate changing the code e.g. so that the error.status is also checked and not just always overwritten, so that the error handler works with Koa apps out of the box / doesn't change Koa behavior?

Thanks!

**Comment by bengourley** [comment]
Thanks for the feedback. Really our middleware shouldn't be called for "bad requests" (e.g. validation errors), only for unhandled errors (things in the `50x` class) so we'll take a look into this and see what we can do better. Your suggestion sounds reasonable, but if there is a way to not enter to callback at all on a 30x, 40x error then that would be better.
