### ISSUE TITLE
plugin-koa has deprecated/wrong peer dependency @bugsnag/node

### ISSUE THREAD

**Issue by my-name-was-already-taken** [bugsnag/bugsnag-js#473]
When installing @bugsnag/plugin-koa e.g. via yarn (tested with v1.12.1) as per instructions, yarn complains

`warning " > @bugsnag/plugin-koa@5.2.0" has unmet peer dependency "@bugsnag/node@* || >=5.0.0-alpha.0".`

as  @bugsnag/node is in plugin-koa's package.json peerDependencies, even though the bugsnag-node package has been marked deprecated by Bugsnag and one is told to install @bugsnag/js instead.

**Comment by bengourley** [comment]
This is the same as https://github.com/bugsnag/bugsnag-js/issues/438. Everything works, but the warning is a problem so we'll figure out a fix!

**Comment by bengourley** [comment]
This was fixed in #480 and will go out with `v6.0.0` in the next few weeks.
