### ISSUE TITLE
Documenting/Using 3rd param of `notify()`

### ISSUE THREAD

**Issue by PeteFromSales** [bugsnag/bugsnag-js#481]
It looks like there's a 3rd parameter of `notify()` that is a callback for after the notify request is sent to the servers (unsuccessfully or otherwise). Is this meant to be or safe to be used? 

My project already has an existing handler for `"uncaughtException"` (`process.on('uncaughtException' ...)`), and the handler ends with exiting the process. As a result, the bugsnagClient.notify() request is never actually sent, and when `notify()` is called from within the handler, it exits with a `0` code, which isn't desired.

**Comment by bengourley** [comment]
Sounds like you could use the documented [`onUncaughtException` callback](https://docs.bugsnag.com/platforms/javascript/configuration-options/#onuncaughtexception-node-js-only) for your use case. The callback in `notify()` was implemented for internal use and I wouldn't recommend relying on it for now.

I'm interested in why you would want your uncaught exception callback to exit the process with a zero status code though?

**Comment by PeteFromSales** [comment]
I'm trying to keep the existing code structure so that Bugsnag is something that is dropped in, as opposed to being a somewhat coupled dependency. Initially, the `uncaughtException` handler was doing the usual of, "notify service1 that something went wrong", "notify service2 ...", "some cleanup", etc. So I was planning on `bugsnagClient.notify(error)` being just another line in that handler. Something like the following being desired:

```javascript
const unCaughtHandler = (err) => {
    service1.call(err);

    if (config.bugsnag.enabled) { // or something similar
       service2.notify(err); // aka, bugsnag
    }
    
    cleanup();
}
```

Unfortunately, when I do the above, it causes node to exit with a `0` status code when notify() is called. Which is something I _don't_ want. Very possible just some rewriting I have to do on my end.  Another thing is that bugsnag isn't always loaded for every environment, so ideally the code is structured (in a "clean" way) to take that into consideration.

All that said, thanks for letting me know about the callback. In the time being, I just did things in a slightly different way.
