### ISSUE TITLE
Error on client initialisation in IE

### ISSUE THREAD

**Issue by SamStonehouse** [bugsnag/bugsnag-js#483]
I'm not sure if you support IE, though I didn't see anywhere which states it's not supported.

I get the following error on initialisation: 

`Object doesn't support property or method 'validate'`

Which points to the following block of code in @bugsnag/browser/dist/bugsnag.js (line 4):

```
_$config_5.validate = function (opts, schema) {
  if (!opts || !schema) throw new Error('opts and schema objects are required');
  var errors = __reduce_5(__keys_5(schema), function (accum, key) {
    if (schema[key].validate(opts[key], opts)) return accum;
    return accum.concat({
      key: key,
      message: schema[key].message,
      value: opts[key]
    });
  }, []);
  return {
    valid: !errors.length,
    errors: errors
  };
};
```

The value of `key` when it fails is `"m"`. From what I can tell, the opts/schema passed is incorrect, on Chrome the keys correctly reflect the keys as provided as options by my initialisation call:

```
import bugsnagJS from '@bugsnag/js';

// ... 

this.client = bugsnagJS({
    appVersion: opts.appVersion,
    notifyReleaseStages: opts.notifyReleaseStages,
    apiKey: _config.bugsnag.apiKey,
    releaseStage: _config.bugsnag.releaseStage,
    beforeSend: opts.beforeSend,
});
```

So I believe there's a chance this could be some kind of webpack error instead, but I'm not so sure

This is with @bugsnag/js version 5.2.0

**Comment by SamStonehouse** [comment]
I actually think this may be an issue with deepmerge rather than bugsnag, sorry for wasting your time! I'll close this and ask for it to be reopened if I find it's not.

**Comment by bengourley** [comment]
The earliest version of IE we support (and test on) is 8 so let us know if you find something wrong there.

**Comment by SamStonehouse** [comment]
Thanks, I still have the issue, I don't think it was deepmerge, deepmerge was causing another issue in IE which lead me down the wrong path.

This is using IE 11.

What I have so far is that the following line (3157) assigning __schema_2 is different in IE

`var __schema_2 = ___extends_2({}, _$config_5.schema, _$config_1);`

In Chrome the properties of __schema_2 correctly reflect the values I pass in as options

In IE, the properties of __schema_2 end up being `c, m, p, s` which map to various values and `d, n, o, r, t` which map to various functions.

Some of the properties indicate they link to things regarding imports/exports, such as `c['../../../node_modules/@bugsnag/browser/dist/bugsnag.js'].exports = "../../../node_modules/@bugsnag/browser/dist/bugsnag.js"`

Which points me in the direction of a webpack issue, but nothing else has been affected by this (as far as I know)

**Comment by SamStonehouse** [comment]
Fixed: I was loading babel polyfill wrong which caused IE to misbehave with the extends function. My bad!

**Comment by bengourley** [comment]
Nice, glad you got it fixed!
