### ISSUE TITLE
Discussion, how to use the option of .notify  in this scene

### ISSUE THREAD

**Issue by 951565664** [bugsnag/bugsnag-js#484]
```js
var bugsnagClient = bugsnag({
  beforeSend: function (report) {
    // Example: Disable reporting from internal routes
    if (/internal\//.test(report.request.url)) report.ignore()
  }
})
```

I want to follow the usage below

```js
/* === a.js === */
export var bugsnagClient = bugsnag({
//...some public option
})
/* === b.js === */
import {bugsnagClient} from 'a.js'

//... some custom option 
bugsnagClient.beforeSend = function (report) {
    // Example: Disable reporting from internal routes
    if (/internal\//.test(report.request.url)) report.ignore()
  }
```
Usually, I will put the public configuration together and generate bugsnagClient, but some people want to have some special configuration. This kind of scenario is not common for business, but it is necessary.

**Comment by bengourley** [comment]
In `b.js` you can do:

```js
bugsnagClient.config.beforeSend.push(function (report) {
  // your custom before send
})
```

It's not ideal to do that, better to configure in a single place if you can. Be aware that this will affect all errors, not just those that come from `b.js`.

Alternatively if you only want this for handled errors you can do:

```js
function beforeSend (report) { /* ... */ }
bugsnagClient.notify(e, { beforeSend: beforeSend })
```

Which will apply only to that error.

If you have any more questions about the usage of the libary, please write in to support@bugsnag.com. Thanks!
