### ISSUE TITLE
autoCaptureSessions: false doesn't work on SPA

### ISSUE THREAD

**Issue by dekker-m** [bugsnag/bugsnag-js#488]
I'm not sure if i'm reading the manual correctly and if this is a bug or the intended behavior. If I set `autoCaptureSessions` to `false` I would not expect any API calls to sessions.bugsnag.com, unless I manually call startSession(). However, navigations-breadcrumbs.js does not seem to honor the autoCaptureSessions setting.

Whenever pushState or replaceState is called in our single page application then a new session is started, even when `autoCaptureSessions` is set to `false`. It seems https://github.com/bugsnag/bugsnag-js/blob/c2020c6522fc075d284ad9441bbde8be155450d2/packages/plugin-navigation-breadcrumbs/navigation-breadcrumbs.js#L73 does not look at `autoCaptureSessions`, but just starts a new session anyway.

**Comment by bengourley** [comment]
Agreed, this looks like a bug. Thanks for reporting!
