### ISSUE TITLE
New API keys not working with new or old bugsnag-js. Old keys are fine.

### ISSUE THREAD

**Issue by kushalj** [bugsnag/bugsnag-js#490]
Using the new @bugsnag/js lib we can notify() using our existing keys but no newly created or regenerated API keys are working.

To be clear, the lib seems fine with older keys so it's unlikely to be the lib. It seems the new API keys are ignored, but still give a 2xx status response, so the messages just disappear.

**Comment by snmaynard** [comment]
Can you write into support@bugsnag.com with this? They can help figure out whats going on for you! Thanks!
