### ISSUE TITLE
`BugsnagClient.getPlugin( "react" )` is `undefined`.

### ISSUE THREAD

**Issue by joshuapinter** [bugsnag/bugsnag-js#494]
Hi There, 

I followed your React integration guide to a T, trying to get Bugsnag reporting from our Electron app. 

I have the following: 

```js
import Bugsnag      from "@bugsnag/js";
import BugsnagReact from "@bugsnag/plugin-react";

const BugsnagClient = Bugsnag( "my_api_key" );
const ErrorBoundary = BugsnagClient.getPlugin( "react" );

console.log( "ErrorBoundary", ErrorBoundary ); // => undefined
```

But, as is shown above, `ErrorBoundary` is `undefined`.

Thoughts?

Also, is `import BugsnagReact from "@bugsnag/plugin-react";` necessary since it's not referenced anywhere?

Thanks!

**Comment by bengourley** [comment]
> Also, is import BugsnagReact from "@bugsnag/plugin-react"; necessary since it's not referenced anywhere?

This is what's missing – you do need it. You need to do `bugsnagClient.use(bugsnagReact, React)` per the [docs](https://docs.bugsnag.com/platforms/javascript/react/#basic-configuration).

Let us know if you need any more assistance by emailing support@bugsnag.com. Thanks!

**Comment by joshuapinter** [comment]
Oh damn! I must have skipped over that line completely and just went to the code block below. I'll give that a try and let you know. Thanks for your help!

**Comment by mariasierraloynaz** [comment]
I am using 7.1  follow https://nicedoc.io/bugsnag/bugsnag-js/blob/master/UPGRADING.md.  ErrorBoundary is undefined

**Comment by johnkiely1** [comment]
Hi @mariasierraloynaz

I think it may be worth you emailing in to support@bugsnag.com describing the issue you are facing in a bit more detail as I think you are encountering a different issue.

Thanks

**Comment by petarproko** [comment]
For those who are still having issues try executing Bugsnag.start() function before ErrorBoundary object.

**Comment by durgesh94** [comment]
The issue is that you're calling Bugsnag.getPlugin('react') before you call Bugsnag.start().
