### ISSUE TITLE
plugin-express typescript defintion should extend the express Request object

### ISSUE THREAD

**Issue by ajsharp** [bugsnag/bugsnag-js#501]
I put the following in `typings/@bugsnag-plugin-express/index.d.ts` in my project, so now I can do `req.busgnag.notify` in express endpoints without typescript warnings.

```typescript
import { Bugsnag } from '@bugsnag/node'

declare global {
  namespace Express {
    interface Request {
      bugsnag: Bugsnag.Client;
    }
  }
}
```

**Comment by mattdyoung** [comment]
Fixed in [v7.1.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.1.0)
