### ISSUE TITLE
Angular 7 - Class constructor ErrorHandler cannot be invoked without 'new'

### ISSUE THREAD

**Issue by tomardern** [bugsnag/bugsnag-js#505]
Hi,

We've recently upgraded to angular 7 and typescript 3.2.4

We've followed the instructions here: https://docs.bugsnag.com/platforms/javascript/angular/

But we are getting the following error:

```
TypeError: Class constructor ErrorHandler cannot be invoked without 'new'
    at new BugsnagErrorHandler (index.js:15)
    at errorHandlerFactory (app.module.ts:78)
    at _callFactory (core.js:27000)
    at _createProviderInstance (core.js:26943)
    at initNgModule (core.js:26846)
    at new NgModuleRef_ (core.js:27978)
    at createNgModuleRef (core.js:27961)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:30474)
    at NgModuleFactory_.create (core.js:31572)
    at ngZone.run (core.js:22412)
```

Line 15 being:
![image](https://user-images.githubusercontent.com/1135454/54920286-c840ef00-4efa-11e9-8594-50f55ae7316d.png)

Might be related to this - https://github.com/bugsnag/bugsnag-js/issues/482

Anyone else having this issue?

**Comment by tomardern** [comment]
Interestingly, changing the code to this:
![image](https://user-images.githubusercontent.com/1135454/54920719-d93e3000-4efb-11e9-9f8d-b36af330fa4b.png)
Enables our app to start, but I'm not too sure on the implications here

**Comment by tomardern** [comment]
As a "fix", I've moved this file:
`https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-angular/src/index.ts`

Into our codebase and is built during the 'standard' `ng build` command

**Comment by Ukmandal** [comment]
go to tsconfig.json file and change your target to es5 (ECMAScript 5) like this :

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"]
  }
}

**Comment by tomardern** [comment]
Updating to the new bugsnag library fixes this.

Thanks!

**Comment by suikast42** [comment]
> go to tsconfig.json file and change your target to es5 (ECMAScript 5) like this :
> 
> {
> "compileOnSave": false,
> "compilerOptions": {
> "baseUrl": "./",
> "outDir": "./dist/out-tsc",
> "sourceMap": true,
> "declaration": false,
> "module": "esnext",
> "moduleResolution": "node",
> "emitDecoratorMetadata": true,
> "experimentalDecorators": true,
> "importHelpers": true,
> "target": "es5",
> "typeRoots": ["node_modules/@types"],
> "lib": ["es2018", "dom"]
> }
> }

U save my day
