### ISSUE TITLE
Node: express: uncaught exceptions sent with 200 status code instead of 500

### ISSUE THREAD

**Issue by hefox** [bugsnag/bugsnag-js#510]
Upgrading from the bugsnag 2.x to 6.x and trying to get an express app erroring correctly. Right now when it errors via an uncaught expectation (I added ```sdfsa.fafsadf;``` so it threw an undefined error, to a route), it throws a 200 with "Internal server error" 

Looking at node js, res.status is how a status code is set, but it's a function https://expressjs.com/en/api.html#res.end

in the bugsnag express code, it's
```
 res.status = 500
 res.end('Internal server error')
```
switching it to res.status(500) correctly sends a 500 status code

**Comment by bengourley** [comment]
Thanks for the report. Since we also support Connect using the same middleware, this needs to be `res.statusCode = 500` rather than `res.status()`. I've scheduled a fix.
