### ISSUE TITLE
Updating global metadata after starting application

### ISSUE THREAD

**Issue by Jay031** [bugsnag/bugsnag-js#527]
Hi guys, 

I want to update the metadata of the global handler in a later stage.
When a user uses the application, afterwards it can choose some options and Angular knows more information like userdata, settings and permissions; I want to add it like this in my app.component:

```
var bugsnagClient = bugsnag(<IConfig>{
            apiKey: BUGSNAG_KEY,
          })
      
          bugsnagClient.metaData = {
            settings: settings,
            userData: this.auth.userData
          }
```

But this will only bind the metadata to any following .notify() functions I call myself.
Is there any way to bind this new metadata to the global errorhandler:

```
// configure Bugsnag ASAP, before any other imports
const bugsnagClient = bugsnag(BUGSNAG_KEY);

// create a factory which will return the bugsnag error handler
export function BugsnagErrorHandler() {
  return new errorHandlerFactory(bugsnagClient);
}
```

Thanks in advance!

**Comment by bengourley** [comment]
Adding `metaData` should have the effect you desire (provided the error happens _after_ the bugsnagClient.metaData = …` assignment).

Feel free to contact support@bugsnag.com for further assistance using the notifier. Thanks!

**Comment by Jay031** [comment]
@bengourley I know what you mean. But when I start my angular application, people can login and fill in information. I want the Global handler to include this metadata.
I can't find any possibility to edit the 'main' bugsnag client which was initialized in the app.module
I know that I can catch my own errors and add the metadata, but I want to change the metadata of the un-catched errors.

**Comment by bengourley** [comment]
If you have access to `bugsnagClient` then setting `bugsnagClient.metaData` on it will result in that data being present in reports for handled and unhandled errors. There should only be one `bugsnagClient` in your application for the majority of use cases.

If you're setting `bugsnagClient.metaData` and you're _not_ seeing it in unhandled error reports then it's a bug. Let us know if that is the case.

**Comment by Olgagr** [comment]
@bengourley  I have the same issue in the production mode. In the dev mode all metadata are in the reports. However, the application in the prod mode only reports user IP. Does custom metadata works with production mode in Angular app?

**Comment by mattdyoung** [comment]
@Olgagr I can see you've now raised https://github.com/bugsnag/bugsnag-js/issues/733 so we'll investigate there.

**Comment by Olgagr** [comment]
@mattdyoung Thanks!
