### ISSUE TITLE
Enhance `notifyReleaseStages` option

### ISSUE THREAD

**Issue by migueloller** [bugsnag/bugsnag-js#534]
Would a PR adding support for enhancing the `notifyReleaseStages` option be accepted?

I'm thinking that the option could take not just an array but also a regular expression, an array of regular expressions, or a function that returns `true` if it should notify.

**Comment by snmaynard** [comment]
It would increase the bundle size and we really want to try to reduce the size of the library. Could you not use a beforeNotify callback and return false from that to stop notifying in a given release stage?

**Comment by migueloller** [comment]
@snmaynard, yes, I'm using `beforeSend` as a current workaround.

**Comment by abigail-bugsnag** [comment]
As this can be adequately achieved using the `beforeSend` callback, this is not something we plan to implement.

**Comment by migueloller** [comment]
@abigail-bugsnag, thanks for taking a look anyway!
