### ISSUE TITLE
FallbackComponent and beforeSend do not work

### ISSUE THREAD

**Issue by oldwin** [bugsnag/bugsnag-js#535]
I'm trying to render error page using `FallbackComponent`. I created simple application and if you click button the error appears in browser console and Bugsnag UI, but I can not see rendered `FallbackComponent` and `beforeSend` does not firing on button click. I just can click the button again and again and see new errors in console (means Bugsnag catch it and re-render tree)

![изображение](https://user-images.githubusercontent.com/16270391/57641636-2d8d9400-75be-11e9-8f99-9f37b91138ee.png)

```js
import bugsnag from '@bugsnag/js'
import bugsnagReact from '@bugsnag/plugin-react'
import React from 'react'
import ReactDOM from 'react-dom'

const bugsnagClient = bugsnag({
  apiKey: MY_API_KEY,
  notifyReleaseStages: ['dev'],
  releaseStage: 'dev'
})

bugsnagClient.use(bugsnagReact, React)
const ErrorBoundary = bugsnagClient.getPlugin('react')

const FallbackComponent = () => <div>ERROR!!!</div>

ReactDOM.render(
  <ErrorBoundary
    beforeSend={(report) => { console.log({ report })}}
    FallbackComponent={FallbackComponent}
  >
    <div>
      Test
      <button onClick={() => { throw new Error('Test error') }}>
        throw error
      </button>
    </div>
  </ErrorBoundary>,
  document.getElementById('root')
)
```

```
@bugsnag/js: 6.2.0,
@bugsnag/plugin-react: 6.2.0,
react: 16.6.0
```

Anything I'm doing wrong? Any ideas why it happening?

**Comment by bengourley** [comment]
Errors in button press callbacks are not caught by error boundaries. Error boundaries only catch errors during the render() of a component.

This isn't an issue with Bugsnag, it's just a nuance of how errors in React work. See the react example in this repo for reference.

If you need any more support getting set up, we'll gladly help over at support@bugsnag.com.

Cheers!

**Comment by tommedema** [comment]
@bengourley how do you explain then that he does see it in the Bugsnag UI even though `beforeSend` is not called?

**Comment by bengourley** [comment]
Bugsnag reports errors that happen outside of React's error boundaries too, but it would only run the `beforeSend` callback configured in the error boundary if the error boundary caught it. Hope that makes sense!
