### ISSUE TITLE
Angular 8 - Class constructor ErrorHandler cannot be invoked without 'new'

### ISSUE THREAD

**Issue by duncandean** [bugsnag/bugsnag-js#545]
The issue from #505 arises again with Angular 8's differential loading. 
Target of `es2015` will cause the same error. Changing back to `es5` resolves the error.

**Comment by duncandean** [comment]
Maybe a duplicate of #482.

**Comment by tomlongridge** [comment]
@duncandean, this should now be fixed in #540 and released in v6.3.0.

**Comment by duncandean** [comment]
Thank you! Just realised after updating. 🙂
