### ISSUE TITLE
Catch iframe errors

### ISSUE THREAD

**Issue by LionelPaulus** [bugsnag/bugsnag-js#547]
Is there a way for Bugsnag to catch also errors coming from webpage in iframe?

**Comment by bengourley** [comment]
Hey @LionelPaulus, errors from iframes don't bubble up to the parent window so this is something you would have to do manually right now, either by calling the parent window's `onerror` method or by passing error data via `window.postMessage`.

A word of warning – it's fraught with complexity and you're likely to run into CORS errors unless all JS and content is served from the same domain. The simplest and most foolproof solution is to simply load Bugsnag in every frame, but if you care about page weight that's obviously not ideal.

The combination of the complexity (high) and the demand (low) for this feature is why we haven't investigated building it yet, but we are tracking it on our internal roadmap and I have added your interest to that.

Cheers
