### ISSUE TITLE
BrowserStack IE error SCRIPT5009: 'Proxy' is undefined

### ISSUE THREAD

**Issue by bjm88** [bugsnag/bugsnag-js#550]
We noticed an error in our console coming from bugsnag-client.js
const getErrorBoundary = (client) => {
  client.use(bugsnagReact, React);
  return client.getPlugin('react');
};

export const client = getClient();  <-----on this line error is thrown
export const ErrorBoundary = getErrorBoundary(client);

error was "'Proxy' is undefined"
This was only seen while running in BrowserStacks testing environment on Windows 10 IE 11.  Let us know if any ideas, thx.

**Comment by bengourley** [comment]
Hi @bjm88, `getClient()` is not one of the functions that Bugsnag defines and also we don't mention `Proxy` anywhere in the browser codebase. Additionally our tests run successfully on IE11 on BrowserStack.

I'm inclined to think this isn't a problem with Bugsnag, but happy to stand corrected. Could you provide some more information, a reduced test case, or an error location that is actually coming from Bugsnag's source?

Thanks
