### ISSUE TITLE
6.3.0 seems missing on CDN 

### ISSUE THREAD

**Issue by zenoplex** [bugsnag/bugsnag-js#551]
I'm not sure I should report it here but most recent v6.3.0 seems to be either missing or blocked on CDN.

6.3.0 is not accessible.
`https://d2wy8f7a9ursnm.cloudfront.net/v6.3.0/bugsnag.min.js`

Where as 6.2.0 is.
`https://d2wy8f7a9ursnm.cloudfront.net/v6.2.0/bugsnag.min.js`

**Comment by bengourley** [comment]
Hi @zenoplex. Thanks for noticing and creating an issue!

We were staggering the release of `v6.3.0` to npm first as some internals changed and we didn't want to release everywhere all at once. It's been gradually adopted by enough people that we can roll it out so I've now pushed it out to the CDN now.

Cheers!
