### ISSUE TITLE
Using plugin-react, but cannot see React tab in dashboard

### ISSUE THREAD

**Issue by charl3sj** [bugsnag/bugsnag-js#553]
I have setup Bugsnag in my create-react-app in the following manner:
```
// bugsnag.js
import React from 'react';
import bugsnag from '@bugsnag/js';
import bugsnagReact from '@bugsnag/plugin-react';

const bugsnagClient = bugsnag(<API_KEY>);
bugsnagClient.use(bugsnagReact, React);

const ErrorBoundary = bugsnagClient.getPlugin('react');

export { bugsnagClient, ErrorBoundary };
```

```
// index.js
...
...
import { ErrorBoundary } from "./bugsnag";

ReactDOM.render(
  <ErrorBoundary>
    <Provider store={store}>
      <App/>
    </Provider>
  </ErrorBoundary>
  , document.getElementById('root')
);
```

And finally, raise the error in App.js:
```
import { bugsnagClient } from './bugsnag';

const App = () => {
  bugsnagClient.notify(new Error('Test error'));
  return (...);
}
```

Bugsnag gets notified of the error, but the [docs](https://docs.bugsnag.com/platforms/javascript/react/#basic-configuration) say extra debugging info would be visible in a "React" tab.

However, this is what I see:
<img width="1136" alt="Screen Shot 2019-06-16 at 9 26 19 AM" src="https://user-images.githubusercontent.com/1017170/59558833-012fc200-9019-11e9-974c-f085e0dc4964.png">

What am I missing?

**Comment by bengourley** [comment]
Hi @charl3sj, you'll only see the "React" tab when there is extra info from React that we can get. That means it only appears when the `<ErrorBoundary/>` captures the error.

If you `throw new Error('Test error')` inside your `App` function you should see the component info in the "React" tab, but your example manually calls Bugsnag's `notify()` function, so the error came straight from you and not via React.

Hope this helps.

**Comment by charl3sj** [comment]
Got it. Thanks!
