### ISSUE TITLE
Extended Error Info

### ISSUE THREAD

**Issue by enVolt** [bugsnag/bugsnag-js#557]
When we notify an error to bugsnag using `bugsnag.notify(error)`, by default it shows Error name, stack trace and message in Bugsnag App. 

If the error is a custom Error (extended), which may include more info, that data is not visible anywhere (not sure if it's captured in the first place). 

For example, consider following error class -

`EError.js`
```javascript
module.exports = class EError extends Error {
    constructor (message, statusCode, details) {
        super(message);
        this.statusCode = statusCode || 500;
        this.details = details;
        this.name = "EError" + (statusCode ? ` (${statusCode})` : "");
    }
};
```

I have 2 additional properties `statusCode` and `details`, which I want to be included in Bugsnag error. If I pass the error (instanceof EError) to bugsnag notify, the extra properties are no where to be found in the captured Bugsnag error.

```js
let details = { sess: "7e5c1c4a-11e3-41a2-a935-c1a0068e521b" };
let err = new EError("Bad Email Address", 400, details);
bugsnag.notify(err);
```

I tried pushing the err as metaData, even then the details and statusCode is no where to be found on bugsnag.

```js
bugsnag.notify(err, { metaData: {err} }); 
```

Only `message` and `name` captured in metadata.

What can I do to capture more info about the error. Not just that this custom error class has more info, most of the libraries has custom error with more details where message would not be sufficient to debug error. E.g check Sequelize [Unique Constraint Error](https://github.com/sequelize/sequelize/blob/b875b7aa320047b913733e2ed6760778ab224b4d/lib/errors/validation/unique-constraint-error.js), it has so many info which is just lost when captured on Bugsnag.

I'm currently on v6.2.0 of `@bugsnag/node` (using with NodeJS v8.11.1)

**Comment by fractalwrench** [comment]
Hi @enVolt thanks for getting in touch. The approach we'd recommend taking here is to extract the value of each property from the `Error` object and add it to the `MetaData` directly. This would look quite similar to the approach you've already arrived it, just with the following change:

```
bugsnag.notify(err, { metaData: {statusCode: err.statusCode} }); 
```

Bugsnag doesn't serialise every value on extended `Error` objects as in JavaScript Error's properties are not enumerable, which means we'd need to check for each key individually when serialising a report.

**Comment by enVolt** [comment]
Hi @fractalwrench, this is actually not feasible, as there are multiple types of extended error instance. and all include different type of information.

By the way, extra attributes of extended Error are actually enumerable. Please correct me if I misunderstood you.

```js
class EError extends Error {
    constructor (message, statusCode, details) {
        super(message);
        this.statusCode = statusCode || 500;
        this.details = details;
        this.name = "EError" + (statusCode ? ` (${statusCode})` : "");
    }
};

let e = new EError("xyz", 400, {foo: "bar"});

console.log(Object.keys(e));  // [ 'statusCode', 'details', 'name' ]
```

**Comment by enVolt** [comment]
If Bugsnag, **doesn't** enumerate over Error or extended Error, then one possible solution I can thinks of is this -

```js
let errorInfo = { message: error.message }; // though already captured
if (Object.keys(error).length) {
    Object.keys(error).forEach(key => { errorInfo[key] = error[key]; });
}

bugsnag.notify(err, { metaData: {errorInfo} }); 
```

**Comment by bengourley** [comment]
Whilst this is true

> extra attributes of extended Error are actually enumerable

The built in attributes (name, message) are not – see the following examples:

```
> Object.keys(new Error('oops'))
[]
> JSON.stringify({ error: new Error('oops') })
'{"error":{}}'
```

Now, we could go poking around [in our serialisation library](https://github.com/bugsnag/safe-json-stringify/blob/e3ab85fdb188627a4e4193522a01847199762b00/index.js#L95) once we've established an error is being serialised and loop over all its possible, additional enumberable keys (we'd have to use a `for x in obj` loop because we have to support IE8) but that library can easily mess up the entire notifier by being a) too slow, b) too big or c) (worst of all) error prone.

I think the best solution for you right now is to add a `beforeSend` callback which runs for every error and extracts what you want from the `report.originalError` (added in v6.1.0, not yet documented – I'll add a note to update that). We'll add a ticket to our internal roadmap to see if some of these custom error properties like `details` and `statusCode` are common enough that we should extract them into metadata of the report.

```js
const bugsnagClient = bugsnag({
  apiKey: 'YOUR_API_KEY',
  beforeSend: report => {
    report.updateMetaData('error info', {
      details: report.originalError.details,
      statusCode: report.originalError.statusCode
    })
  }
})
```

**Comment by gaastonsr** [comment]
Agree with @enVolt here, getting all the extra enumerable properties from the `Error` object should be the default and it shouldn't be complex or error prone. Knowing how to handle `Error` objects properly is something I would expect out of the box.

**Comment by GuillaumeCisco** [comment]
Hello there.

Is there any easy way to display extended error?

**Comment by luke-belton** [comment]
Hi @GuillaumeCisco - please could you expand a bit more on this please? Are you able to share a code snippet or a link to an event in your Bugsnag dashboard to demonstrate what you mean? Feel free to write into support@bugsnag.com if you'd prefer 👍
