### ISSUE TITLE
Error 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode

### ISSUE THREAD

**Issue by hassanasad** [bugsnag/bugsnag-js#564]
Getting this weird error randomly in my app.

```
'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
```

<img width="797" alt="Screenshot 2019-06-24 20 51 45" src="https://user-images.githubusercontent.com/7580112/60033513-25973880-96c2-11e9-8183-0b3b526a6ed0.png">

**Comment by bengourley** [comment]
Hi @hassanasad. I'm able to reproduce this but only when I set "strict mode" on the entire script and I attempt to notify Bugsnag with something that isn't an error (and so is missing the `.stack` property).

How is your code being bundled?
Which browsers are you seeing this in?

I think we can be defensive about not trying to walk the call stack when we're in strict mode but I'd like to understand the situations where this happens first.

**Comment by hassanasad** [comment]
Hi @bengourley - I am using bugsnag in an Angular 8 app. It was working fine on older versions of bugsnag. When i upgrades to the new bugsnag-js plugin and then plugin-angular i started seeing this error. I am using bugsnag the way its mentioned on one of your readme pages with bugsnag being part of the core module.
This event is firing on all sorts of browser, Chrome 75, Safar 12.1.1 etc on the production app. I have about 3k events in one of my app reported on bugsnag itself.

**Comment by nicolae-olariu** [comment]
@bengourley I'm having the same issue with the exact same setup as @hassanasad . Upgraded a few hours ago to Angular 8, bugsnag is set up the way your doc mentioned. It only happens after we build the solution. ng serve works OK.

![image](https://user-images.githubusercontent.com/4962542/60178819-f8af6680-9824-11e9-9d86-99b0566e1850.png)

**Comment by nicolae-olariu** [comment]
For everyone else that has this issue, you should unfortunately downgrade the typescript compilerOptions target from es2015 (es6) to es5.

Code that works: "target": "es5"

![image](https://user-images.githubusercontent.com/4962542/60184357-94929f80-9830-11e9-8273-46c16bfae6de.png)


As a note: we've also tested the @6.3.2-alpha.0 version of BugSnag but unfortunately we had the same runtime exception.

**Comment by bengourley** [comment]
I can't reproduce this. I'm using the following versions:

- `@bugsnag/js@6.3.1`
- `@bugsnag/plugin-angular@6.3.2-alpha.0`
- `@angular/core,compiler,common,etc.@8.0.2`

And with the following __tsconfig.json__ (relevant parts only):
```json
  "compilerOptions": {
    "target": "es2015"
  },
  "angularCompilerOptions": {
     "enableIvy": true
  }
```

I can make a speculative fix, but I want to be able to reproduce the problem to ensure we fix it. The following two conditions must be present in your application for this issue to occur:

1. `@bugsnag/js` must be bundled into file with `"use strict"` at the top, causing the entire bundle (including third party modules that rely on non-strict mode) to operate in strict mode OR the function importing bugsnag must be using "use strict".
2. the error passed to Angular's error handler callback must not have a `stack` property (i.e something is thrown that is not an `Error` object – this is bad practice but Bugsnag should tolerate it). I acheived this by throwing a string in an app component method that gets called during `render()` – `throw "some error"`.

I have only managed to recreate condition 2. None of the Angular settings I have used (`--aot`, `--prod` have caused `"use strict"` to appear at the top of the file for me, nor bundled Bugsnag in such a way that it is forced to operate in strict mode.

Please can you help by making a reduced test case that exhibits this behaviour? Starting with a fresh project created with `ng new` would be ideal. Thanks for your assistance and patience!

**Comment by hijamoya** [comment]
Same issue here.

**Comment by bengourley** [comment]
@hijamoya can you help me reproduce the problem? Would be very helpful, thanks!

**Comment by hijamoya** [comment]
With the following config, you can reproduce:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
And
```
ng build --aot
```

**Comment by bengourley** [comment]
@hijamoya I used your `tsconfig.json` settings and still couldn't reproduce. Can you provide steps to reproduce the same kind of error too?

**Comment by hijamoya** [comment]
@bengourley I found that it happens when an error occurs but you don't have a `handleError` function in `BugsnagErrorHandler`.

In my case, I post a url and get 403 forbidden:

```
post()
.subscribe(() => {
// data
});
```
if you don't handle onError, the the error occurs.
However, if you:
```
post()
.subscribe(() => {
// data
}, err => console.log(err));
```
Then the error won't appear.

**Comment by bengourley** [comment]
I've tried this and it still works for me. There must be something else going on. I've pushed up [the code I'm using](https://github.com/bugsnag/angular-debug-issue-546) so you can see.

Please can you try the following:
- Clone https://github.com/bugsnag/angular-debug-issue-546 and see if you can reproduce the problem
- If you can't, add compare it with what you have in you project setup and see if you can spot what causes the problem

**Comment by hijamoya** [comment]
I just create a pr which can reproduce the problem:
https://github.com/bugsnag/angular-debug-issue-546/pull/2

Run
```
npm start
```
And you will see the error.
I think it relates to angular version.

**Comment by bengourley** [comment]
Thanks @hijamoya, I can now reproduce the problem! I'll investigate and get a fix out as soon as possible.

**Comment by bengourley** [comment]
So comparing the differences between a project running Angular `8.0.2` vs. `8.1.0` it looks like the bundling is exactly the same, but the script tag that gets rendered in `index.html` changed like this:

```diff
+ <script src="vendor.js" type="module"></script>
- <script src="vendor.js"></script>
```

I can't pinpoint the exact change in Angular (I think it's in [`@angular/cli`](https://github.com/angular/angular-cli/) somewhere).

When the script attribute `type="module"` is used, this causes [the entire script to be executed in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules). I can envisage this breaking any other vendored modules that expect to run in non-strict mode (I'm sure there are some) so it would be good to file an issue with Angular too if you can find the right place.

We'll update Bugsnag so it tolerates being bundled into a strict mode context and I'll let know when that gets released.

Thanks again for providing the steps to reproduce, it really helps to understand the cause of the issue  and helps make sure we address it properly! 🙇

**Comment by hijamoya** [comment]
@bengourley It seems that you don't need to modify code to tolerate in strict mode. Since it will be removed in angular 8.2.
See:
https://github.com/angular/angular-cli/issues/14956

**Comment by abigail-bugsnag** [comment]
This has now been released in the latest version of bugsnag-js: https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.0
