### ISSUE TITLE
Set handled/unhandled state

### ISSUE THREAD

**Issue by sandstrom** [bugsnag/bugsnag-js#569]
Currently there is no easy way to set the handled/unhandled state for an error. This makes the stability score useless to us.

In our JS app we are catching all exceptions, for logging + sending to Bugsnag. While we do "handle" the exception, in the sense that we're catching it, the user will see an error message.

So, from a stability perspective it wasn't handled. Thus, we'd like these errors to worsen the Bugsnag stability score. And for that to work we'd like to set the handled/unhandled state via `notify`.

See similar issue for ruby: https://github.com/bugsnag/bugsnag-ruby/issues/549

**Comment by bengourley** [comment]
This isn't documented as it's an API that we only really surface for authoring plugins, but if you look at the React plugin (for example), you can see how to construct your own `Report` with the desired `handledState`:

https://github.com/bugsnag/bugsnag-js/blob/c4ee9a72c246dd5c1ea6fb5c9bd4bdb3e6ac3094/packages/plugin-react/src/index.js#L17-L18

You can then pass that `report` object to `bugsnagClient.notify(report)`.

Be aware that the `severityReason` object is not "free-form" – it has a schema that you must conform to, which you can find if you drill down to `events > severityReason` in our [Error reporting API docs](https://bugsnagerrorreportingapi.docs.apiary.io/#reference/0/notify/send-error-reports).

We are looking at ways to make the handled state modifiable in a more user-friendly way across the board, but this should help you in the interim.

Cheers!

**Comment by sandstrom** [comment]
@bengourley Thanks! Looking forward to a public API for setting the modified state. That would make the stability score useable, which would be a great reason to upgrade our plan.

Have a good weekend!

**Comment by sandstrom** [comment]
@bengourley Hey! Saw that you released a JS SDK update just now. 

Has anything changed on the handled/unhandled state front in the most recent release?

**Comment by johnkiely1** [comment]
Hi @sandstrom 
This has not changed in the latest release but we are planning to work on this soon.

**Comment by sandstrom** [comment]
@johnkiely1 Thanks for the update!

How about the Ruby SDK? (https://github.com/bugsnag/bugsnag-ruby/issues/549) Same there, not included yet but will be?

**Comment by johnkiely1** [comment]
Just to give you a little more information the unhandled flag would have a large impact to the way data is interpreted on the Bugsnag dashboard. Therefore we're having to look at the impact of this for all our notifiers. Once this has been agreed it will be rolled out in due course across the platforms.

**Comment by sandstrom** [comment]
@johnkiely1 Thanks!

Problem now is that we handle all errors on our end, but still don't want to mark them as handled, because that makes the releases dashboard and stability score stuff useless. That's our use-case (hope it helps!)

Have a great weekend! 🔆

**Comment by sandstrom** [comment]
@johnkiely1 Another related idea:

The 'severity' scale that you have now, which is 'warning' or 'error' is easy to mix up and confuse with log levels. It would be better if you used another scale, e.g. (Minor, Moderate, Severe, and Critical).

We have warning log messages sent in as breadcrumbs, and they are different from setting the severity level or various errors.

![image](https://user-images.githubusercontent.com/122287/82474605-8f36e700-9acb-11ea-925a-b9c71847710a.png)

**Comment by sandstrom** [comment]
@johnkiely1 Any update on this?

I noticed you released user stability (which looks great! 😄), which we cannot use because of the problem described in this issue.

**Comment by johnkiely1** [comment]
Hi @sandstrom,

Nothing new to report on timeframes on this yet. We are still looking to address this across all of our platform specific notifiers which makes this a bigger piece of work to implement. Other priorities have meant this has slipped somewhat. Updates will be added here when we have them.

**Comment by sandstrom** [comment]
I think this was fixed in 7.5.4. Is that correct? Feel free to close in that case.

https://github.com/bugsnag/bugsnag-js/blob/next/CHANGELOG.md#v754-2020-12-10

Aside: I noticed 7.5.5 isn't published to NPM.

**Comment by xander-jones** [comment]
Hey @sandstrom, yes this has been released in [v7.5.4](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.5.4). Here's the documentation on how to adjust the handled state of an event: https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#unhandled

v7.5.5 is for Expo/React Native updates only, so the latest JavaScript notifier is v7.5.4 😄

**Comment by sandstrom** [comment]
Awesome!

Would still expect the latest release to be available in NPM, even though some of the bug fixes therein only pertain to certain platforms.
***

Somewhat related (since it affects session counting and stability scores, which this is related to):

uBlock seems to be blocking Bugsnag.

1. Would it be possible for us to send "a user was active and this is the user agent string, ip, etc" request from our backend, for tracking 'user stability'. That way we wouldn't be affected by session tracking being blocked? Something you have thought of or discussed internally?

2. Ideally we'd also pipe error reports through our backend, since those are being blocked too.

Stability score is less useful if ~30% of users aren't included (due to ad blockers).
