### ISSUE TITLE
BugSnag Error Boundary Not Logging Error in Bugsnag

### ISSUE THREAD

**Issue by chobo2** [bugsnag/bugsnag-js#571]
Hi

I have this

```
bugsnagClient.use(bugsnagReact, React)
const ErrorBoundary = bugsnagClient.getPlugin('react')

<ErrorBoundary FallbackComponent={ErrorFallbackComponent}>
    <AppContainer />
</ErrorBoundary>

export const ErrorFallbackComponent =  () => <div>An error has occurred</div>
```

However I noticed only error that I actually do  bugsnagClient.notify(new Error(error.errorMessage));

I am wondering if I have to add  bugsnagClient.notify(new Error(error.errorMessage)); into my error boundry and if so how?

**Comment by bengourley** [comment]
Hi @chobo2, what errors are you expecting to see in Bugsnag that aren't showing?

By default Bugsnag will report:

- unhandled exceptions
- unhandled promise rejections

And with the react integration you're using:

- render errors from react components

You don't need to put a `notify()` call in your error boundary – we sent the report for you.

Let us know some more information about your setup and what kind of errors you're expecting to see and we'll be able to help. Cheers

**Comment by chobo2** [comment]
@bengourley 

Ok, well I am seeing some random errors that are occurring because of Mobs state tree  when it tries to reference something it thinks is a duplicate.

The error is random and seems to happen when I don't have my debugger open so that's how I noticed that bugsnag was not logging it.

I will try to try to get the error message next time it happens and report it here.

**Comment by bengourley** [comment]
We've seen a [similar issue with `redux-saga`](https://github.com/bugsnag/bugsnag-react-native/issues/191) where it swallows an error and then logs it to the console with `console.error()` so Bugsnag never sees it. The solution there was to hook in to Redux's error handler function.

I would suggest taking a look at the `onError()` and `onReactionError()` options of MobX ([on this docs page](https://mobx.js.org/refguide/api.html)) and connecting those up with Bugsnag.

Essentially Bugsnag will report any unhandled exception, or unhandled promise rejection – so if an error is not handled by anything else it will be reported. If it is caught and logged to the console it won't be reported.

I'm going to close this off until this can be reproduced.
