### ISSUE TITLE
file paths with spaces not reported properly in stack traces

### ISSUE THREAD

**Issue by jeremyspiegel** [bugsnag/bugsnag-js#586]
Because of this [issue](https://github.com/stacktracejs/error-stack-parser/issues/46) in [error-stack-parser](https://github.com/stacktracejs/error-stack-parser), I'm seeing incorrect file paths reported in stack traces where the file path contains spaces. This causes the [projectRoot](https://docs.bugsnag.com/platforms/javascript/configuration-options/#projectroot-node-js-only) option to not work properly, and thus issues are not being bucketed correctly.

My issue is with an Electron application, but I would expect the problem to exist in any node project.

It appears that the `error-stack-parser` project isn't currently active. Is bugsnag open to switching to a fork with a fix?

**Comment by jeremyspiegel** [comment]
I should note that the problematic line is [here](https://github.com/stacktracejs/error-stack-parser/blob/master/error-stack-parser.js#L61) (the `.split(/\s+/)` in particular).

**Comment by mattdyoung** [comment]
Hi @jeremyspiegel 

Note that `error-stack-parser` isn't unmaintained, it just doesn't change very often. One of Bugsnag's developers has commit access to that repository so we should be able to fix and ask the owner to publish a new version to resolve your `projectRoot` issue here.

I'll raise this with the team and see how soon we're able to schedule the work.

Thanks!

**Comment by jeremyspiegel** [comment]
Got it, thanks for clarifying @mattdyoung!

**Comment by abigail-bugsnag** [comment]
@jeremyspiegel This has now been released in the latest version of bugsnag-js: https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.0

**Comment by jeremyspiegel** [comment]
Thanks @abigail-bugsnag!
