### ISSUE TITLE
Bugsnag swallows error logging in node/koa

### ISSUE THREAD

**Issue by keattang** [bugsnag/bugsnag-js#602]
Hi, 

When using bugsnag with Koa, bugsnag swallows the error log in the console. This is particularly unhelpful in local development where I don't want the errors sent to bugsnag but I do want to see them in my console. I'd also still like to see the errors in my production environment logging.

I have a repro here https://github.com/keattang/bugsnag-bug-repro

This is a bug that I reported in the previous, non-universal, version of the bugsnag node client. It was fixed then but appears to have come back.

**Comment by mattdyoung** [comment]
Hi @keattang 

Thanks for the report. Yes, this looks like a bug. We'll aim to fix this in a future release.

**Comment by keattang** [comment]
Great, thanks!

**Comment by mattdyoung** [comment]
This was fixed in [v6.4.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.1).
