### ISSUE TITLE
Permission denied to access property "apply"

### ISSUE THREAD

**Issue by lifeiscontent** [bugsnag/bugsnag-js#608]
| browserName | browserVersion | locale | osName | time | userAgent |
| -------------- | --------------- | ------ | -------- | ----- | ---------- |
| Firefox | 68.0.0 | en-US | Windows 10.0 | 2019-08-02T13:14:32.371Z | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 |

https://github.com/bugsnag/bugsnag-js/blob/668c26fd3e6b38e2869eec1509d3d5cd5b5880e2/packages/plugin-inline-script-content/inline-script-content.js#L24

**Comment by kattrali** [comment]
Thanks for the report, @lifeiscontent - is this potentially the same as https://github.com/bugsnag/bugsnag-js/issues/469?

**Comment by mattdyoung** [comment]
This was fixed in [v6.4.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.1).
