### ISSUE TITLE
Client.setOptions() types definition is wrong

### ISSUE THREAD

**Issue by StefanoMagrassi** [bugsnag/bugsnag-js#609]
The [type definition](https://github.com/bugsnag/bugsnag-js/blob/next/packages/core/types/client.d.ts#L20) of `Client.setOptions()` does not comply with the [js implementation](https://github.com/bugsnag/bugsnag-js/blob/next/packages/core/client.js#L63) both for the input parameter and for the output value.

The right definition should be:
```ts
declare class Client {
  // ...
  public setOptions(opts: Partial<common.IConfig>): void;
  // ...
}
```
The input parameter should be "partialized" because `common.IConfig` declares a mandatory `apiKey` field which is not actually required on js-side (`this._opts = { ...this._opts, ...opts }`) and the output value is just a `void` not the `Client` instance.

**Comment by abigail-bugsnag** [comment]
@StefanoMagrassi thanks for the feedback. This is an API which we don't think would be used often, so is relatively low priority. We will look into updating this.

**Comment by johnkiely1** [comment]
This has now been fixed in v7.
https://github.com/bugsnag/bugsnag-js/releases/tag/v7.0.0
