### ISSUE TITLE
Missing clientIp and referer in request object

### ISSUE THREAD

**Issue by aroslov** [bugsnag/bugsnag-js#615]
Compare code at 

https://github.com/bugsnag/bugsnag-js/blob/86b60fa1205b91e7c3833a4250c8a7951557980f/packages/plugin-koa/src/koa.js#L82

and 

https://github.com/bugsnag/bugsnag-js/blob/86b60fa1205b91e7c3833a4250c8a7951557980f/packages/plugin-koa/src/request-info.js#L1

First function expects requestInfo.clientIp and requestInfo.referer attributes, but second function doesn't provide it. Looks like a bug.

**Comment by abigail-bugsnag** [comment]
@aroslov Thank you for your comments. We will look into this.

**Comment by mattdyoung** [comment]
This was fixed in [v6.4.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.1).
