### ISSUE TITLE
express.js session reporting

### ISSUE THREAD

**Issue by lifeiscontent** [bugsnag/bugsnag-js#618]
Hi there, I'm creating a next.js application with express.js as a custom server, in the client of the next.js app the user is reported properly, but on the server side, the app is not recording the user automatically.

how can I setup this behavior properly? I'd like to identify the user via a cookie.

**Comment by mattdyoung** [comment]
Hi @lifeiscontent 

In your Express.js server if you can identify the user from your cookie, you can then either set the user info at the point the error is reported in a `beforeSend` callback or set the user on the bugsnag client which would then be sent with all subsequent error reports:
https://docs.bugsnag.com/platforms/javascript/express/#identifying-users

Thanks!

**Comment by mattdyoung** [comment]
Hi @lifeiscontent 

Just a quick followup on this following a discussion with a colleague.

For Express, Koa and Restify our `requestHandler` middleware attaches a request-scoped Bugsnag client to `req.bugsnag` as mentioned here:
https://docs.bugsnag.com/platforms/javascript/express/#reporting-handled-errors

You can set the relevant user details on the request-scoped Bugsnag client like this:
```
app.use(function (req, res) {
  req.bugsnag.user = {
    id: req.user.id,  // get user info from wherever it has been extracted
    name: req.user.name
  }
})
```

These user details will then be included in any unhandled errors thrown processing the request, or you should use `req.bugsnag.notify(err)` if reporting a handled error.

**Comment by lifeiscontent** [comment]
Thanks @mattdyoung, that was just the information I was looking for! :)

As a side note, it might be worth pointing this out in the docs, that's where I went first and realized this information was missing.

**Comment by mattdyoung** [comment]
Thanks. Yes, we'll look at making this clearer in the documentation as it's not easy to find currently.
