### ISSUE TITLE
[plugin-express] body not showing up in request tab.

### ISSUE THREAD

**Issue by azizhk** [bugsnag/bugsnag-js#620]
![Screenshot 2019-09-13 at 3 13 52 PM](https://user-images.githubusercontent.com/5094296/64853540-34deb000-d639-11e9-837a-907596391260.png)

So I have a POST request which throws an error, but body does not get logged as shown in the image.
The problem is that bugnsag generated the metadata in the middleware instead of the errorHandler. (Don't know why this is done, please don't add overhead and allow application code to run first)

The code over here expects req.body to be an object:
https://github.com/bugsnag/bugsnag-js/blob/7231ea7463e4d3bc63f46f9694fb694eb17fa01f/packages/plugin-express/src/request-info.js#L21

We use [body-parser](https://www.npmjs.com/package/body-parser) to create req.body into an object, but that middleware is after the bugsnag middleware. (As bugnsag recommends that the first middleware should be the bugnsags over [here](https://docs.bugsnag.com/platforms/javascript/express/))

I've moved the bugsnag middleware to be after body-parser for now. But I would ideally like if bugsnag can move the request metadata creation to the errorHandler.

**Comment by mattdyoung** [comment]
Hi @azizhk 

Thanks for the report. We're taking a look and will decide on the best way forward.

**Comment by phillipsam** [comment]
Hi @azizhk - we have released a fix for this in [v7.2.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.2.0).
