### ISSUE TITLE
When will you make a release that includes this fix?

### ISSUE THREAD

**Issue by lifeiscontent** [bugsnag/bugsnag-js#623]
@bugsnag/browser still hasn't been released with this fix.

when will you guys cut a release?

https://github.com/bugsnag/bugsnag-js/blob/ec5765492960c42a3ccc3858c7ecb0c888e3474e/packages/plugin-inline-script-content/inline-script-content.js#L24

**Comment by bengourley** [comment]
Released this in [v6.4.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.1) – thanks for waiting!
