### ISSUE TITLE
Capture DOMException's

### ISSUE THREAD

**Issue by laukstein** [bugsnag/bugsnag-js#629]
Please capture also DOMException's, see https://heycam.github.io/webidl/#idl-DOMException-error-names

We recently experienced our user having DOMException QuotaExceededError and Bugsnag wasn't able to capture it.

**Comment by bengourley** [comment]
Using [this example](https://arty.name/localstorage.html), I'm unable to see a `QuotaExceededError` being thrown. I tried with Firefox, Chrome and Safari.

If you can put together a reproduction case where the error occurs, we can see if it's possible for Bugsnag to catch it automatically.

**Comment by laukstein** [comment]
@bengourley we experienced QuotaExceededError on Android device, it is likely that user device storage was full and set IndexDB data exceeded it. Try to reproduce it on mobile having full storage.

Chrome is working on a way to test IndexedDB 'QuotaExceededError' without filling disk, issue https://bugs.chromium.org/p/chromium/issues/detail?id=945786
> It's a very common problem that mobile users have no storage available

**Comment by mattdyoung** [comment]
So if I understand correctly, the `QuotaExceededError` doesn't occur when the IndexedDB is full, but does occur if the underlying OS filesystem runs out of storage while writing to IndexedDB.

I'll add this to our backlog as a feature request, so we can look into whether it's possible for bugsnag-js to capture this type of error condition in the future.

**Comment by mattdyoung** [comment]
Hi @laukstein 

We've been investigating adding support for these. We do already catch a DOMException QuotaExceededError but only if it's thrown and not caught. Our investigations have shown that in this scenario these errors are not thrown but are passed to an `onabort` callback handler on the transaction.

It's going to be tricky for us to catch these errors automatically without being fairly invasive, but if you add the `onabort` handler, you should be able to report these errors to Bugsnag either by throwing them or by passing them to `.notify(err)`.

**Comment by phillipsam** [comment]
We are not currently going to investigate any further for catching these errors automatically. Closing.
