### ISSUE TITLE
bugsnag.ts in npm package

### ISSUE THREAD

**Issue by GDreyV** [bugsnag/bugsnag-js#631]
By some reason npm package v 6.4.2 has extra empty .ts file in @bugsnag\browser\dist\types\bugsnag.ts which causes error on build Angular app:
ERROR in ./node_modules/@bugsnag/browser/dist/types/bugsnag.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /root/src/frontend/node_modules/@bugsnag/browser/dist/types/bugsnag.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

**Comment by bengourley** [comment]
This reason this file was added is discussed in https://github.com/bugsnag/bugsnag-js/issues/523.

Maybe Angular's AOT mode is fixed now and we can remove it…

**Comment by GDreyV** [comment]
I'm building it in pretty silly way, just `ng build --eval-source-map --prod`. With `ng build --eval-source-map --prod --aot` I'm getting exactly the same error. Angular version is `"@angular/core": "~7.2.0"`

**Comment by mattdyoung** [comment]
Hi @GDreyV 

Thanks for the PR! Our team will review it and follow up with any comments there.

**Comment by mattdyoung** [comment]
Fixed in [v6.4.3](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.4.3)
