### ISSUE TITLE
Significant performance decrease in IE

### ISSUE THREAD

**Issue by bigrocketgames** [bugsnag/bugsnag-js#635]
We recently noticed an issue of decreased performance in IE.  We introduced an error to our page that causes `bugsnagClient.notify()` to be called ~180 times.  We haven't changed the defaults for the amount of errors sent per page load (so it still should be 10 which I was I believe we only see the 10 calls in the network tab).

Before we fixed it, we noticed that our page load time in IE was affected.  Looking at the `network` tab in the IE devtools showed that the calls to `https://notify.bugsnag.com/` with much longer in time `~60 seconds` compared to Chrome and other browsers `<1 second`.  When we comment out `bugsnagClient.notify()` we see consistent load times across browsers.

Below are the screenshots of the from the devtools:

IE - 11:
![IE_network_details](https://user-images.githubusercontent.com/13439789/67316628-aa059680-f4bd-11e9-8884-82323f5dd076.png)

Chrome - 77:
![chrome_network_detail](https://user-images.githubusercontent.com/13439789/67316641-affb7780-f4bd-11e9-8a76-15b83ad13d44.png)

We are using `@bugsnag/js 6.4` with `@bugsnag/plugin-react 6.4`

**Comment by mattdyoung** [comment]
Hi @bigrocketgames 

We're not currently aware of anything that could cause this behavior. We'll attempt to reproduce.

**Comment by mattdyoung** [comment]
Hi @bigrocketgames 

We've tried reproducing running a localhost site which calls `notify` 180 times in a loop, testing this on Browserstack with IE11 on Windows 8.1 but can't see the behavior you describe:
![Screenshot 2019-10-24 at 11 56 59](https://user-images.githubusercontent.com/43782078/67479381-d5bb8480-f655-11e9-875d-37bd39fe045d.png)

Are you still able to reproduce the same behavior? If so can you provide a reproduction example?

**Comment by mattdyoung** [comment]
Closing for now, but please get back in touch if you're able to provide a way to reproduce.

Thanks!
