### ISSUE TITLE
Bugsnag UI: All issue-events are deleted when filter only shows some events

### ISSUE THREAD

**Issue by gerbus** [bugsnag/bugsnag-js#640]
This probably doesn't belong here. Can someone point me to where issues with the bugsnag UI should go?

### Description
🤦‍♂ When using the filter search bar in the bugsnag UI, and deleting issues, hidden events are deleted as well.

### Steps to Reproduce
1. Filter issue list using the search field
2. Put a checkmark beside an issue where the event count is less than it would be without the filter
3. Delete the issue

### Expected Behavior
Just deletes the events that pass through the filter

### Actual Behavior
Deletes the issue, not the events in the issue

**Comment by mattdyoung** [comment]
Hi @gerbus 

For any issues with Bugsnag which aren't suspected bugs in the open source libraries simply contact support@bugsnag.com.

It's not possible to delete individual events (i.e. error occurrences) via the Bugsnag UI. The delete action applies to the error, so even if you've applied a filter and only some of the events on the error are visible, deleting the error will still delete all occurrences.
