### ISSUE TITLE
Bugsnag is breaking production

### ISSUE THREAD

**Issue by lifeiscontent** [bugsnag/bugsnag-js#645]
https://github.com/bugsnag/bugsnag-js/blob/5e241be93dc03a7bd536aa9ecaa4f588738358a3/packages/plugin-network-breadcrumbs/network-breadcrumbs.js#L119

`Error was not caught TypeError: Cannot read property 'polyfill' of null` for browsers that don't implement fetch

**Comment by mattdyoung** [comment]
Hi @lifeiscontent 

As far as we're aware it shouldn't be possible for that error to be triggered from that line of code as for browsers which don't support `fetch` it should be `undefined`.

I've tried this on IE11 and haven't been able to reproduce the error.

Can you confirm which browser you saw this on and that the error is definitely being triggered by Bugsnag?

**Comment by phillipsam** [comment]
@lifeiscontent 
Closing this as we haven't had a response. Please contact Bugsnag support if you're still having issues.
