### ISSUE TITLE
Sourcemaps for dynamic urls NEXT.js

### ISSUE THREAD

**Issue by andreimc** [bugsnag/bugsnag-js#652]
Is there a way to get source maps for dynamic urls in next js where the file is served as /[orderId]/index.js --- and the actual url will be /123/index.js ?

**Comment by mattdyoung** [comment]
Hi @andreimc 

If the `index.js` is just being served from a different location you should be able to use a wildcard option on the minified URL when you upload the source maps to Bugsnag to allow Bugsnag to match the location in the stacktrace to the source map.

If you write in to support@bugsnag.com with full details of your configuration and which project this is for we can take a look and see why the source maps aren't being applied.

**Comment by mclack** [comment]
Hi @andylacko 

If your JavaScript bundles have dynamic URLs, you can use wildcards when uploading the corresponding source map to support this. You can read more about this in our documentation here: https://docs.bugsnag.com/api/js-source-map-upload/#do-you-support-partial-matching-wildcards-for-the-minified-url

For example, if the same JS bundle is served from both `http://staging.example.com/assets/example.min.js` and `https://example.com/assets/example.min.js`, you could use wildcards as shown below to match both of these URLs to a single source map upload:

`minifiedUrl=http*://*example.com/assets/example.min.js`

If you need further assistance with this, please feel free to open a ticket with us directly by contacting support@bugsnag.com, along with further details of the URLs you are looking to support and how you are currently uploading your source maps. A link to an error on your BugSnag dashboard which is failing to match to an uploaded source map would also be useful.
