### ISSUE TITLE
stop monkeyPatching fetch API

### ISSUE THREAD

**Issue by lifeiscontent** [bugsnag/bugsnag-js#660]
today I found this in my code, wondering why `fetch` was not returning `fetch() { [native code] }`

only to find this.

```js
var monkeyPatchFetch = function () {
  // only patch it if it exists and if it is not a polyfill (patching a polyfilled
  // fetch() results in duplicate breadcrumbs for the same request because the
  // implementation uses XMLHttpRequest which is also patched)
  if (!('fetch' in win) || win.fetch.polyfill) return;
  var oldFetch = win.fetch;

  win.fetch = function fetch() {
    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
      args[_key] = arguments[_key];
    }

    var url = args[0],
        options = args[1];
    var method = 'GET';

    if (options && options.method) {
      method = options.method;
    }

    return new Promise(function (resolve, reject) {
      // pass through to native fetch
      oldFetch.apply(void 0, args).then(function (response) {
        handleFetchSuccess(response, method, url);
        resolve(response);
      })["catch"](function (error) {
        handleFetchError(method, url);
        reject(error);
      });
    });
  };

  if ("production" !== 'production') {
    restoreFunctions.push(function () {
      win.fetch = oldFetch;
    });
  }
};
```

why is this something you add to apps that use your software?

**Comment by bengourley** [comment]
It's the only way to track network requests as breadcrumbs, since the browser doesn't offer an event for it.

You can switch this off with the [`networkBreadcrumbsEnabled` option](https://docs.bugsnag.com/platforms/javascript/configuration-options/#networkbreadcrumbsenabled-browser-only) if it is having undesirable side-effects.

**Comment by sassomedia** [comment]
@bengourley The `networkBreadcrumbsEnabled` options does not work, `network-breadcrumbs.js` is still loaded. What can be done about this? 3rd-party libraries really should not alter native objects.

Using v6 of Bugsnag, btw.

**Comment by xander-jones** [comment]
@sassomedia, in `v6` this option looks slightly different: https://docs.bugsnag.com/platforms/javascript/configuration-options/#enabledbreadcrumbtypes

Use:
```js
Bugsnag.start({ 
  enabledBreadcrumbTypes: ['error', 'log', 'navigation', 'user']
})
```
Omitting `'request'` from this list.

**Comment by sassomedia** [comment]
@xander-jones Thanks for the quick reply, although I don't see this working either. `v6` used to have a `bugsnagClient` setup and that's basically what we have, simplified example here: https://codepen.io/sassomedia/pen/GRZegrB.

That `console.log(fetch)` in the example should output `ƒ fetch() { [native code] }` but I'm always getting the monkey-patch. Is there something else I'm missing? Thanks!

**Comment by xander-jones** [comment]
@sassomedia, sorry made an error in my comment above, this is for `v7` 🙈.  I've amended my comment above. For `v6`, this would be the following option: https://docs.bugsnag.com/platforms/javascript/legacy/configuration-options/#networkbreadcrumbsenabled-browser-only.

I think the issue you're seeing is that you're changing the Bugsnag config after instantiating Bugsnag, so at this point `fetch()` has already been patched.

If you use [the following](
https://codepen.io/xander-jones/pen/gOrEpgO), you can use Bugsnag, and we won't be patching `fetch()`:

```js
var bugsnagClient = bugsnag({
  apiKey: 'cdd848e5d2da0a26bda6f31a42452428',
  networkBreadcrumbsEnabled: false
});
window.bugsnagClient = bugsnagClient;
console.log(fetch);
```

Results in:
```
ƒ fetch() { [native code] }
```

**Comment by sassomedia** [comment]
@xander-jones Ah ok, yes that makes sense. Works for me, thanks a bunch!
