### ISSUE TITLE
Expo SDK 36 Error due to react-native-netinfo

### ISSUE THREAD

**Issue by vikrantnegi** [bugsnag/bugsnag-js#668]
Hi,

I just upgraded my expo app to sdk 36 and I'm getting an error with `react-native-netinfo` import. I believe this can be related to this expo/expo#4764 

![Screenshot_2019-12-10-10-20-04-197_host exp exponent](https://user-images.githubusercontent.com/3294287/70496787-edcc6200-1b36-11ea-8e56-f4232b0de2ed.jpg)

**Comment by rafamrs** [comment]
I also got this, and this is definitely related with https://github.com/expo/expo/issues/4764

**Comment by mattdyoung** [comment]
@vikrantnegi  @rafamrs 

Thanks for the report. We're working on testing the fix and aim to have a release out by Monday.

**Comment by rafamrs** [comment]
Thats great to hear @mattdyoung. Thanks for addressing the issue so quickly

**Comment by vikrantnegi** [comment]
Thank you @mattdyoung I will be waiting for the fix to test it out on my app.

**Comment by phillipsam** [comment]
@vikrantnegi @rafamrs 
released in [v6.5.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.5.0)
