### ISSUE TITLE
Console.log comes from bugsnag.js:2042

### ISSUE THREAD

**Issue by VadymBoguslavsky** [bugsnag/bugsnag-js#686]
Hi. I have question about domains. At `localhost:3000` when i try to log something it comes from from the file where i write console.log, but when i choose to other domain that we have like `lvh.me:3000` to test how it works, console log comes from bugsnag js. It seems that bugsnag think that its an error and log it from its own file. Can there be a way to fix it?
My bugsnag file if it would be necessary.

And the other question is can we not init bugsnag in dev? Because for now we just set different keys for prod and dev. In dev its just a string for not sending.
```
const bugsnagClient = bugsnag({
  apiKey: process.env.BUGSNAG_API_KEY,
  appVersion: process.env.APP_VERSION,
  logger: null,
  beforeSend(report) {
    const reportApp = report.app;
    const requestUrl = report.request.url;
    if (requestUrl.match(/(?:.+\.)?domain\./g)) {
      reportApp.releaseStage = 'production';
      reportApp.notifyReleaseStages = 'production';
    } else {
      reportApp.releaseStage = process.env.NOW_GITHUB_BRANCH;
      reportApp.notifyReleaseStages = process.env.NOW_GITHUB_BRANCH;
    }
  }
});

bugsnagClient.use(bugsnagReact, React);
```

**Comment by phillipsam** [comment]
Hi @VadymBoguslavsky

Which version of `bugsnag-js` are you using?

Are you providing your own logger somewhere? 
https://docs.bugsnag.com/platforms/javascript/configuration-options/#logger

If you would like to not send notifications to Bugsnag in development, you can set the `releaseStage` in your configuration (basically defining when you are in production and when you are in development):
https://docs.bugsnag.com/platforms/javascript/configuration-options/#releasestage
And then you can set `notifyReleaseStages` in your configuration to only notify the release stages you are interested in:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#notifyreleasestages

**Comment by Haraldson** [comment]
How is this supposed to work in 2022?

I’m doing

```babel
{
    releaseStage: 'local',
    enabledReleaseStages: [
        'production',
        'demo',
        'stage',
        'test',
        'dev'
    ]
}
```

...but still having my `console` hi-jacked by Bugsnag. The settings only seems to affect _sending data to Bugsnag_, and not the whole interception thing.
