### ISSUE TITLE
Expo client crash after update stack navigation 2.0

### ISSUE THREAD

**Issue by sweebee** [bugsnag/bugsnag-js#698]
I've updated the react navigation stack to 2.0. But when I create the ErrorBoundry the app crashes at launch:

```
const ErrorBoundary = bugsnag().getPlugin('react');
```

If i remove this line everything works fine.

**Comment by bengourley** [comment]
Hi @sweebee, what's the exact error you're seeing and what versions of the following are you using?

- `expo`
- `@bugsnag/expo`

I'm assuming the "react navigation stack" module you're referring to is this one? https://github.com/react-navigation/stack

**Comment by sweebee** [comment]
I'm getting no exceptions. The Expo client just crashes without any crashlogs and also the console shows no errors.

i'm using ```6.5.0``` for ```@bugsnag/expo``` and ```expo``` version ```36.0.2```

**Comment by serg2801** [comment]
Yes. I have same crashes after upgrade to 6.5.0

**Comment by bengourley** [comment]
It looks to me like this is another instance of #700. Are you testing on iOS by any chance? If so this issue appears in the same way you describe:

> The Expo client just crashes without any crashlogs and also the console shows no errors.

FYI, you can actually find the logs for this crash, they're just harder to track down than on Android and in this instance, unfortunately they don't lead you to the source of the problem. Nonetheless, if you open `Console.app` and look at the logs for `Exponent` on your device you'll see them:

![image](https://user-images.githubusercontent.com/609579/71971812-4c9efd00-3203-11ea-8fd1-36ce8f31ab7f.png)

**Comment by bengourley** [comment]
This should now be fixed in [v6.5.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.5.1). 

Please upgrade and let us know how you get on.

**Comment by sweebee** [comment]
thanks, its working now.

**Comment by serg2801** [comment]
thanks, its working now.
