### ISSUE TITLE
Expo SDK 36: RNCNetInfo.getCurrentState got 3 arguments, expected 2

### ISSUE THREAD

**Issue by srmagura** [bugsnag/bugsnag-js#700]
I had Bugsnag working in my app on Expo SDK 35, but it is no longer working after upgrading to SDK 36.

I have upgraded to `@bugsnag/expo` and `@bugsnag/js` to 6.5.0 to get the `@react-native-community/netinfo` fix discussed in #668.

I receive this error immediately after starting my app:
<img src="https://user-images.githubusercontent.com/801549/71930571-f0d46580-3169-11ea-9481-d455fe84af36.png" width="400">
(I can only test on Android right now, but can try to reproduce on iOS later this week if desired.)

The error goes away if I comment out all references to bugsnag. 

`expo diagnostics` output and `package.json` dependencies here: https://pastebin.com/KHmvKF15

**Comment by srmagura** [comment]
Minimal repro here: https://github.com/srmagura/bugsnag-netinfo-repro

**Comment by bengourley** [comment]
Thanks for the report and the detailed steps to reproduce ✨

We have a fix for this (#691) which is not yet released. I will check it against your repro and get it shipped it ASAP.

**Comment by bengourley** [comment]
Verified that this fixes the problem on your repro (had to comment out the font loading as the assets were not included).

The fix has now been released in [v6.5.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v6.5.1).
