### ISSUE TITLE
V4 is not loading in Chrome

### ISSUE THREAD

**Issue by caki0915** [bugsnag/bugsnag-js#702]
# Environment:
Google Chrome | 79.0.3945.88 (Official Build) (64-bit) (cohort: Stable)
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Windows 10 OS Version 1903 (Build 18362.535)
JavaScript | V8 7.9.317.32
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

I found the issue while browsing the Shopify apps store which is using v4 of Bugsnag. v5 and v6 work fine. It's only Chrome, Tested Edge browser and Postman and both works fine. 

## Steps to reproduce:
1. Open Chrome and a new Incognito tab
2. Go to:  `https://d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.min.js`

## Expected Result:
Bugsnag script should load

## Actual Result
Request fails after around 30s

![image](https://user-images.githubusercontent.com/1438153/72011722-ba2a4800-325a-11ea-8e41-bcb7eb71b77b.png)

**Comment by snmaynard** [comment]
It loads instantly for me, I dont know why a single browser would have an issue with it. I am using 79.0.3945.117 of chrome and thats ok.

**Comment by caki0915** [comment]
Yes, It's very strange! 
I made a step by step video:
https://www.youtube.com/watch?v=g60PU08AA9Q

**Comment by snmaynard** [comment]
Is there any kind of extension running that might be blocking it? Sometimes ad trackers get overzealous and block our requests (though I wouldnt expect that to hang, but who knows).

**Comment by caki0915** [comment]
I don't think so since I'm using an incognito window.

**Comment by tomlongridge** [comment]
@caki0915 - we're not able to reproduce this. Do you have any other machines with Chrome to try this on at your site?

**Comment by caki0915** [comment]
After deleting `C:\Users\carlj\AppData\Local\Google` and reinstalling Chrome and, It works 🙌
I can't tell for sure what was the source of the problem but it looks like it's not Bugsnag.

Thank you

**Comment by mattdyoung** [comment]
Thanks for letting us know!
