### ISSUE TITLE
Bugsnag CDN returns 404

### ISSUE THREAD

**Issue by sica07** [bugsnag/bugsnag-js#724]
As specified in the documentation, I'm trying to load bugsnag using the CDN:
`<script src="//d2wy8f7a9ursnm.cloudfront.net/v6/bugsnag.min.js"></script>`
but I receive a 404 error. 
I tried from v6.2 till v6.5 but I get the same result.
Am I doing something wrong?

**Comment by phillipsam** [comment]
Hi @sica07 - thanks for reaching out! Have you tried taking a look at our example app to see any differences between the configuration in that and your own app? 
https://github.com/bugsnag/bugsnag-js/tree/next/examples/browser-cdn

**Comment by sica07** [comment]
I've just discovered that the d2wy8f7a9ursnm.cloudfront.net was marked as spam by the "Malicious Site Blocking" functionality of my router. Sorry for the false alarm!

**Comment by mattdyoung** [comment]
@sica07 
We'd be interested to know which model of router this was and how the malicious site blocking as configured in case the CDN we use has somehow ended up on a supplier's blacklist. Would you be able to email the details to support@bugsnag.com?
