### ISSUE TITLE
Prevent failed AJAX requests to get reported 

### ISSUE THREAD

**Issue by ankurk91** [bugsnag/bugsnag-js#778]
Hi,

I am receiving error reports when an AJAX request is failed. For example 403 from server.
I am using `axios` js library with vue js.

Here is the screenshot

<img width="1120" alt="Screenshot 2020-03-20 at 2 44 36 PM" src="https://user-images.githubusercontent.com/6111524/77150636-50c88000-6aba-11ea-941c-e856d105cdf5.png">

Is there any way to prevent such error from being logged.
Could not find any option in docs.

**Comment by mattdyoung** [comment]
Hi @ankurk91 

Yes, to prevent specific errors being captured you can implement a `beforeSend` callback and conditionally return `false` as shown here:
https://docs.bugsnag.com/platforms/javascript/vue/customizing-error-reports/#disabling-error-reporting

The request is also shown on the breadcrumbs leading up to this or other error reports, which can be disabled with the `networkBreadcrumbsEnabled` setting:
https://docs.bugsnag.com/platforms/javascript/vue/configuration-options/#networkbreadcrumbsenabled

If you have any further questions on configuring the library we'd recommend asking via the Contact Support link in the Bugsnag dashboard.
