### ISSUE TITLE
Possible to bug NetInfo to 5.7.0?

### ISSUE THREAD

**Issue by rafmst** [bugsnag/bugsnag-js#792]
Hello bugsnag team, I just updated a Expo project using @bugsnag/expo package to Expo SDK 37 and I got an error related with @react-native-community/netinfo. This should be solved if you guys bumped the version to 5.7.0.

Thanks for your time.

**Comment by mattdyoung** [comment]
Hi @rafmst 

We're aware and this should be fixed shortly:
https://github.com/bugsnag/bugsnag-js/pull/781

**Comment by rafmst** [comment]
Perfect :) stay safe

**Comment by bengourley** [comment]
Expo 37 is now supported by @bugsnag/expo v6.6.0
