### ISSUE TITLE
Add Ember CLI

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-js#80]
http://reefpoints.dockyard.com/2014/06/24/introducing_ember_cli_addons.html

**Comment by davidpike7** [comment]
:+1: Would be great if Bugsnag supported this

**Comment by ivanvanderbyl** [comment]
I've released an Ember CLI addon which does this https://github.com/ivanvanderbyl/ember-bugsnag

**Comment by jessicard** [comment]
Hey @ivanvanderbyl - thanks for releasing that! It looks great. I'm going to close this issue for now and point people to your Ember CLI addon.
