### ISSUE TITLE
BugsnagPluginVue.constructor() types definition is wrong

### ISSUE THREAD

**Issue by aki77** [bugsnag/bugsnag-js#807]
The right definition should be:

```typescript
declare class BugsnagPluginVue {
  constructor(Vue?: VueConstructor)
}
```

**Comment by johnkiely1** [comment]
Thanks for this, we are currently reviewing.

**Comment by aki77** [comment]
Thank you.
This type definition has led me to the following workaround.

```typescript
plugins: [new BugsnagPluginVue(Vue as any)],
```

**Comment by xander-jones** [comment]
The fix for this will be released in v7.0.1 of bugsnag-js, re-opening this issue until the release is made.

**Comment by aki77** [comment]
Thanks!

**Comment by phillipsam** [comment]
[v7.0.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.0.1) has now been released.
