### ISSUE TITLE
Get pass jest tests and getting error _pluginReact.default is not a constructor

### ISSUE THREAD

**Issue by simkessy** [bugsnag/bugsnag-js#812]
I get this error when running jest tests on version 7

![image](https://user-images.githubusercontent.com/5871660/79942546-ed64a180-841b-11ea-916a-1b73c3ac67d0.png)

**Comment by phillipsam** [comment]
Hi @simkessy - can you please confirm that you have updated both @bugsnag/js and @bugsnag/plugin-react to v7. Prior to v7, the React plugin was not a constructor which would explain this behaviour.

**Comment by simkessy** [comment]
Yes they are both v7

**Comment by phillipsam** [comment]
@simkessy thanks for clarifying. 
We would not generally recommend trying to run Bugsnag in your tests, and instead mocking this out.

Would you be able to write into support@bugsnag.com with a full reproduction example of this? We have tried to reproduce what you are seeing and are currently not able to. This appears to work fine with with jest, react, @bugsnag/js and @bugsnag/plugin-react.

**Comment by simkessy** [comment]
Please provide example of how you tested it so I can do the same thing.

**Comment by mattdyoung** [comment]
We ran this in [jest](https://jestjs.io/en/) using `npx jest -- browser`:
```
const Bugsnag = require('@bugsnag/js')
const BugsnagPluginReact = require('@bugsnag/plugin-react')
const React = require('react')
Bugsnag.start({
  apiKey: '12341234123412341234123412341234',
  plugins: [ new BugsnagPluginReact(React) ]
})
describe('test', () => {
  it('should be ok', () => {
    expect(Bugsnag).toBeTruthy()
  })
})
```

**Comment by simkessy** [comment]
The browser setting helped. Thank you.

**Comment by simkessy** [comment]
What's the solution on jest 25/26 where the browser option is deprecated

**Comment by mattdyoung** [comment]
You have to specify a custom jest resolver:
https://jestjs.io/docs/en/configuration.html#resolver-string

But again, we'd generally recommend not trying to run Bugsnag in your tests, and instead mocking this out.

**Comment by simkessy** [comment]
How do you mock it out?

**Comment by simkessy** [comment]
@mattdyoung  

I wrote this test: 

```
import React from 'react';
import { render } from '@testing-library/react';
import { BugSnag } from './BugSnag';

const BadComponent = () => {
  return new Error();
};

describe('error boundary - bugsnag', () => {
  it('displays errorMessage', () => {
    const { getByText } = render(
      <BugSnag>
        <BadComponent />
      </BugSnag>
    );

    const error = getByText(/slack channel/i);
    expect(error).toBeTruthy();
  });
});
```

and sometimes I get this error: 

```
Summary of all failing tests
FAIL src/components/global/BugSnag.test.jsx
  ● error boundary - bugsnag › displays errorMessage
    Network Error
      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:83:14)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:315:27)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:266:3)
      at XMLHttpRequestEventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:212:11)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:127:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:57:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:675:20)
      at Request.onRequestError (node_modules/request/request.js:877:8)
```

**Comment by simkessy** [comment]
@mattdyoung what's the proper way to mock bugsnag? There shouldn't be Network requests during tests.

**Comment by xander-jones** [comment]
Hey @simkessy, agree that Bugsnag network requests should not be present during testing. We'd suggest stubbing Bugsnag, and pointing the `notify()` call to `jest.fn()` and then making your `expect()` call to see if the conditions expected were met.

A nice approach would be, for the following in your application code: 
```js
import Bugsnag from '@bugsnag/js'

function SomeFunction() {
  Bugsnag.notify(new Error("An error"))
}
```

Then in your tests you can do:
```js
jest.mock('@bugsnag/js', () => ({
  // stub the `notify()` function
  notify: jest.fn(),
}))
test('notify was called', () => {
  SomeFunction();
  expect(Bugsnag.notify).toHaveBeenCalledWith(new Error("An error"))
})
```

**Comment by fleonard** [comment]
@mattdyoung Is there any update on a mock example for Bugsnag?
I'm having the same troubles while trying to set up my test environment.

**Comment by mattdyoung** [comment]
@fleonard What are you trying to achieve? Does the example my colleague @xander-jones shared above not do what you need?

**Comment by phillipsam** [comment]
Closing this issue for now as we haven't heard back. If you wish to follow up then please comment below with the details and we'll reopen the issue.
