### ISSUE TITLE
Is it possible to do an exportable Bugsnag config?

### ISSUE THREAD

**Issue by Freddie-Pike** [bugsnag/bugsnag-js#837]
Hey, big fan of Bugsnag here! Been doing some googling and reading the docs and I haven't seen an instance of someone doing an exportable config. My usecase is that I have two different error boundary's that I define in my app, and I want to wrap both of them in the bugsnag error boundary. To accomplish this, I have to do the following:

UIErrorBoundary1.jsx
```
import React from 'react';
import Bugsnag from '@bugsnag/js';
import BugsnagPluginReact from '@bugsnag/plugin-react';

const bugsnagConfigOptions = {
  apiKey: '...',
  plugins: [new BugsnagPluginReact(React)],
  ...,
};
configOptions.user = {
  ...
};

Bugsnag.start(bugsnagConfigOptions);
const BugsnagErrorBoundary = Bugsnag.getPlugin('react');

class UIErrorBoundary1 extends React.Component {
  render() {
    <BugsnagErrorBoundary>
      ...
    </BugsnagErrorBoundary>
  }
}
```

UIErrorBoundary2.jsx
```
import React from 'react';
import Bugsnag from '@bugsnag/js';
import BugsnagPluginReact from '@bugsnag/plugin-react';

const bugsnagConfigOptions = {
  apiKey: '...',
  plugins: [new BugsnagPluginReact(React)],
  ...,
};
configOptions.user = {
  ...
};

Bugsnag.start(bugsnagConfigOptions);
const BugsnagErrorBoundary = Bugsnag.getPlugin('react');

class UIErrorBoundary2 extends React.Component {
  render() {
    <BugsnagErrorBoundary>
      ...
    </BugsnagErrorBoundary>
  }
}
```

What I would like to do is something like this instead:

bugsnagsetup.js
```
import React from 'react';
import Bugsnag from '@bugsnag/js';
import BugsnagPluginReact from '@bugsnag/plugin-react';

const bugsnagConfigOptions = {
  apiKey: '...',
  plugins: [new BugsnagPluginReact(React)],
  ...,
};
configOptions.user = {
  ...
};

export const Bugsnag = Bugsnag.start(bugsnagConfigOptions);
export const BugsnagErrorBoundary = Bugsnag.getPlugin('react');
```

UIErrorBoundary1.jsx
```
import React from 'react';
import { BugsnagErrorBoundary } from 'bugsnagsetup';

class UIErrorBoundary1 extends React.Component {
  render() {
    <BugsnagErrorBoundary>
      ...
    </BugsnagErrorBoundary>
  }
}
```

UIErrorBoundary2.jsx
```
import React from 'react';
import { BugsnagErrorBoundary } from 'bugsnagsetup';

class UIErrorBoundary2 extends React.Component {
  render() {
    <BugsnagErrorBoundary>
      ...
    </BugsnagErrorBoundary>
  }
}
```

This would reduce duplicate code and possibly prevent multiple Bugsnag instances from being defined(which I haven't tested, but I'm hoping this wouldn't' cause multiple Bugsnag errors to be sent if bugsnag is started in multiple different files).

Is this possible?

**Comment by mattdyoung** [comment]
Hi @Freddie-Pike 

With the recently released bugsnag-js v7.x, you can call any client method on the static `Bugsnag` interface, which forwards the method call onto the initialized client:
https://github.com/bugsnag/bugsnag-js/blob/next/UPGRADING.md

So if you call `Bugsnag.start` with the config you need in your app's entry point:

**index.js**
```
Bugsnag.start({
  apiKey: 'YOUR_API_KEY',
  plugins: [new BugsnagPluginReact(React)],
  otherOptions: value
})
```
then you can access that same client from within your other components, e.g. in your example of wrapping your own error boundary in the Bugsnag error boundary you can do this:

**UIErrorBoundary1.jsx**
```
import React from 'react'
import Bugsnag from '@bugsnag/js'

class UIErrorBoundary1 extends React.Component {
  render() {
    var ErrorBoundary = Bugsnag.getPlugin('react');
    <ErrorBoundary>
      ...
    </ErrorBoundary>
  }
}
```
and any errors caught by the Bugsnag error boundary will be reported via the previously initialized bugsnag client.
