### ISSUE TITLE
How to report the unhandledrejection events in Bugsnag v7?

### ISSUE THREAD

**Issue by lukejagodzinski** [bugsnag/bugsnag-js#846]
Did something change about how to handle that case? In the example here https://github.com/bugsnag/bugsnag-js/blob/next/examples/js/browser-cdn/app.js#L11 I can see that it looks like now users have to do it manually. Is it correct?

**Comment by bengourley** [comment]
Hi @lukejagodzinski, [`unhandledrejection` events are still reported by default in V7](https://docs.bugsnag.com/platforms/javascript/#reporting-unhandled-errors).

The code you linked to in the example creates a button that when clicked will cause an unhandled exception to be thrown – this is unrelated to uhandled rejection reporting (it's not a promise) and it's just to give the user control over when the exception is thrown in the example.

Hope this makes sense. Feel free to contact support@bugsnag.com if you need any help getting set up, or upgrading from V6 to V7.

**Comment by lukejagodzinski** [comment]
So apparently it doesn't work in my case. No errors are caught and reported to bugsnag

**Comment by bengourley** [comment]
Please write in to support with as much info as you can, and we'll help you get set up.

**Comment by lukejagodzinski** [comment]
Sure, thanks
