### ISSUE TITLE
Update Bugsnag version in CDN

### ISSUE THREAD

**Issue by laukstein** [bugsnag/bugsnag-js#855]
6 days ago was released v7.0.2 https://github.com/bugsnag/bugsnag-js/releases/tag/v7.0.2,
why http://d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js still is having v7.0.1?

![grabilla Hp2280](https://user-images.githubusercontent.com/183966/82214151-09c20400-991e-11ea-9c5c-47e9e413a3d3.png)

**Comment by mattdyoung** [comment]
Hi @laukstein 

Only the `@bugsnag/browser` package is served from the CDN, but there were no changes in that package between v7.0.1 and v7.0.2, so the v7.0.1 browser code being served is the latest.
