### ISSUE TITLE
onError callback ignored

### ISSUE THREAD

**Issue by sandstrom** [bugsnag/bugsnag-js#858]
When using multiple onError callbacks only one is called.

Also, would prefer if the onError callback passed into `notify` is called last, so that it can override the defaults. For example, to override the `severity` value.

```js
let bugsnagClient = Bugsnag.createClient({
  apiKey: 'abc',
  appVersion: '1.0.0',
  onError: (event) => {
    // I'm called
    event.severity = 'warning';
  },
});

bugsnagClient.notify(err, {
  onError: (event) => { 
    // NEVER CALLED :(
    event.severity = 'error';
  },
});
```

**Comment by bengourley** [comment]
In V7 the signature of `notify()` changed such that the second argument _is_ the `onError` callback:

```js

bugsnagClient.notify(err, (event) => { 
  event.severity = 'error';
});
```

This will work, and it will run last as you desire!

**Comment by sandstrom** [comment]
Ah, got it! Thanks @bengourley 🎉
