### ISSUE TITLE
[@bugsnag/plugin-react] createErrorBoundary() type

### ISSUE THREAD

**Issue by antoinerousseau** [bugsnag/bugsnag-js#868]
Using TS 3.9.3, with

```ts
export const ErrorBoundary = Bugsnag.getPlugin("react")?.createErrorBoundary(React)
```

I get this error:
```
JSX element type 'ErrorBoundary' does not have any construct or call signatures.
ts(2604)
```

![Capture d'écran 2020-05-24 21 50 55](https://user-images.githubusercontent.com/160279/82763557-eeb52f80-9e08-11ea-9437-b8e6d2014dfd.png)

**Comment by mattdyoung** [comment]
Hi @antoinerousseau 

Can you confirm which version of bugsnag-js you're using? The syntax above was only introduced in [v7.1.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.1.0), so wouldn't be expected to work on earlier versions.

**Comment by antoinerousseau** [comment]
Yes I'm talking about v7.1.0

**Comment by mattdyoung** [comment]
Hi @antoinerousseau 

I don't get that error using typescript 3.9.3 and bugsnag-js 7.1.0. Can you share a complete reproduction example including all of your Bugsnag initialization code?

**Comment by antoinerousseau** [comment]
Ok, as I was trying to make a reproduction example, I realized that it's because `createErrorBoundary()` can return `undefined`, as clearly mentioned in the doc, my bad, so I should test for the existence of its return value.

```jsx
const children = (
  <UserProvider>
    <App />
  </UserProvider>
)
return ErrorBoundary ? (
  <ErrorBoundary FallbackComponent={ErrorComponent}>{children}</ErrorBoundary>
) : (
  children
)
```

Sorry for the false alarm!

Also it would be cool to export the `BugsnagErrorBoundary` and `BugsnagPluginReactResult` in order to sometimes use them :)

In particular, I would like to do this:

```ts
const plugin = Bugsnag.getPlugin("react") as BugsnagPluginReactResult
export const ErrorBoundary = plugin.createErrorBoundary()
```

Because I know the plugin exists, and this would simplify the use of the boundary since it wouldn't be typed as `| undefined`

**Comment by andrewjaanuu** [comment]
Bump, there is no way to customize react fallback components like `<ErrorBoundary FallbackComponent={<ErrorComponent prop1="value1">}>{children}</ErrorBoundary>`, which should be a common use case

**Comment by ryanpcmcquen** [comment]
This is what ended up working for me as a one-liner:
```ts
const ErrorBoundary = (Bugsnag.getPlugin('react') as BugsnagPluginReactResult).createErrorBoundary(React);
```
