### ISSUE TITLE
Log breadcrumbs not saved in dev stage, can't reenable

### ISSUE THREAD

**Issue by petrkrizek** [bugsnag/bugsnag-js#882]
Hi,
in the docs it's mentioned that when app is in releaseStage='development', console breadcrumbs are disabled. Is there any way to reenable it? 

If no, can you please point me where is the code responsible for this?

Thanks

**Comment by xander-jones** [comment]
Hey @petrkrizek, the code responsible for this can be seen here: https://github.com/bugsnag/bugsnag-js/blob/796f4ca6a5fcb525e6f69c90772f3a7cf3cac8a7/packages/plugin-console-breadcrumbs/console-breadcrumbs.js#L10

You can re-enable these by using any release stage that is not `dev` or `development`.

**Comment by petrkrizek** [comment]
Thanks. Can we add some config parameter that would 'enforce' tracking console log even in dev stage? We use stage to describe server env (and server pipeline is dev -> stage -> prod). 

Thanks for consideration.

**Comment by johnkiely1** [comment]
Hi @petrkrizek 

I will pass this suggestion on to our products team who will consider it for a future release.
