### ISSUE TITLE
@bugsnag/plugin-vue not working in ssr

### ISSUE THREAD

**Issue by JulianMar** [bugsnag/bugsnag-js#895]
Hi, 

I moved to the new Plugin init function as in the [upgrade guide](https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md), but I noticed it doesn't work with SSR Apps.

There is a reference to the window on this [line](https://github.com/bugsnag/bugsnag-js/blob/796f4ca6a5fcb525e6f69c90772f3a7cf3cac8a7/packages/plugin-vue/src/index.js#L4) and another one a little further down.

As for now I can just use the old method but would be cool to fix this bug!

Thanks for the great Plugin :)

**Comment by xander-jones** [comment]
Hey @JulianMar, thanks for letting us know about this. At the time of the server side render `window` is not available, and would throw an error like (as I believe you're seeing):
```
ReferenceError: window is not defined
```
We'll take a look into a fix!

**Comment by phillipsam** [comment]
A fix for this was released in [v7.2.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.2.1)
