### ISSUE TITLE
Can I pass in props to the FallBack component? 

### ISSUE THREAD

**Issue by simkessy** [bugsnag/bugsnag-js#898]
I have a HOC wrapped around my components: 

```
const withErrorBoundary = (Component: ComponentType<any>, errorMessage: string) => (
  props: Object
) => (
  <ErrorBoundary errorMessage={errorMessage}>
    <Component {...props} />
  </ErrorBoundary>
);

export default withErrorBoundary;
```

I use it like this: `export default withErrorBoundary(TemplateManager, 'Error in Template Editor.');`

My ErrorBoundary looks like this: 

```
import React from 'react';
import { Box, Text, Divider, Icon } from 'gestalt';

import Bugsnag from '@bugsnag/browser';
import { LogRocketInstance as LogRocket } from '../components/global/LogRocket';

const ErrorDisplay = ({ error }) => {
  LogRocket.captureException(error);
  LogRocket.trace(errorMessage);

  return (
    <>
          <Text align="center" color="darkGray" weight="bold">
            {`${errorMessage || error || 'Error Loading this component'}`}
          </Text>
    </>
  );
};

const ErrorBoundary = Bugsnag.getPlugin('react');
export const BugSnag = ({ children, errorMessage = '' }) => {
  return <ErrorBoundary FallbackComponent={ErrorDisplay}>{children}</ErrorBoundary>;
};
```

How do I get

**Comment by mattdyoung** [comment]
@simkessy 
Your question seemed to get cut short?

Can you explain what it is you're trying to achieve? To do something with the the error captured by the Bugsnag `ErrorBoundary` you can use the `onError()` to pass in an `onError` callback as described here:
https://docs.bugsnag.com/platforms/javascript/react/#customizing-the-error-boundary

**Comment by mattdyoung** [comment]
Closing issue for now as we haven't heard back. If you wish to follow up then please comment below with the details and we'll reopen the issue.

**Comment by andrewjaanuu** [comment]
Bump, there is no way to customize react fallback components like <ErrorBoundary FallbackComponent={<ErrorComponent prop1="value1">}>{children}</ErrorBoundary>, which should be a common use case

**Comment by yousif-bugsnag** [comment]
Hi @andrewjaanuu, it's possible to pass in static values that way, but I'm guessing you want to pass in props dynamically - can you tell us more about your specific use case and what you are trying to achieve?
