### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by nrako** [bugsnag/bugsnag-js#91]
I know this package is published on bower but why isn't it published on npm too? Under `bugsnag-js`? I believe it would make a lot of sense; managing updates on published package is lot more simpler than through a git URL e.g: `"bugsnag-js": "git+ssh://git@github.com:bugsnag/bugsnag-js.git#v2.4.6"`. And bower doesn't have anything that come close to `npm shrinkwrap`.

When using commonJS and for the above reasons npm is much more useful than bower.

**Comment by jacobmarshall** [comment]
:+1: for NPM support :)

**Comment by PrototypeAlex** [comment]
:+1:

**Comment by PrototypeAlex** [comment]
Also, you'll probably need to fix https://github.com/bugsnag/bugsnag-js/issues/100 first.

**Comment by ConradIrwin** [comment]
Fixed, v2.4.7 is published to npm as `bugsnag-js` (not to be confused with `bugsnag` which is the node notifier).
