### ISSUE TITLE
Possible to set global client?

### ISSUE THREAD

**Issue by logicbomb421** [bugsnag/bugsnag-js#919]
I'm trying to write the `Bugsnag.start` logic in a common module that all my applications share, however I'm noticing this does not set the client on consuming apps since the `Bugsnag` modules are seen as separate.

Currently I can work around this by manually setting `Bugsnag._client` after the initialized client is returned from my common module, but this seems like a smell.

Is there a proper way to set the global client from outside the `Bugsnag` module _without_ calling `start`?

Thanks!

**Comment by mattdyoung** [comment]
Hi @logicbomb421 

`Bugsnag` is shared across all imports of the same bundle, so within the same bundle the following works:

**index.js:**
```
import Bugsnag from '@bugsnag/js'
import render from './app.js'
Bugsnag.start(API_KEY)
render()
```
**app.js:**
```
import Bugsnag from '@bugsnag/js'
export function render () {
  Bugsnag.notify('implement me')
}
```

However, if you're wanting this to work across different bundles we'd recommend importing `Bugsnag` once and setting it as a global variable, e.g.

**index.js:**
```
import Bugsnag from '@bugsnag/js'
Bugsnag.start(API_KEY)
window.Bugsnag = Bugsnag
```

In that case you'd need to make sure the bundle where you call `Bugsnag.start` always executes first.

**Comment by logicbomb421** [comment]
I am using this on the backend right now, and am initializing the module within a core module that is imported and essentially bootstraps my applications. When I initialize Bugsnag within the common module, the consuming application does not see the internal client since the initialized Bugsnag module is scoped to the core module that runs my apps.

Currently I have to pass the initialized client returned from `start` out of my bootstrap logic and monkeypatch it onto `Bugsnag._client` in order for the consuming application to even see the initialized client.

For example:

#### core-app.js (independent package named `@myorg/core`)
```
const Bugsnag = require('@bugsnag/js');

module.exports = function startApplication() {
  const client = Bugsnag.start({...});
  // other app-init logic
  return client;
} 
```

#### backend-app.js
```
const startApplication = require('@myorg/core');
const Bugsnag = require('@bugsnag/js');

const bugsnagClient = startApplication();
Bugsnag._client = bugsnagClient;
```

I have many services that all use this common application bootstrapping logic to reduce copy/pasted code, so I would like to be able to initialize Bugsnag there, too.

While accessing `_client` is working, it appears to be intended for internal use, which means it could potentially change at a later date. I am proposing adding a simple method, `setModuleClient`, to the root-level of the `Bugsnag` module to allow for this use case without accessing internals.

Is Bugsnag only for frontend applications? The documentation seems to indicate it should be full-stack?

Thanks

**Comment by xander-jones** [comment]
Bugsnag can be used for backend too! Ordinarily, we'd recommend instantiating the client in your backend, and also in your front-end application since they're operating in different environments. It's up to you whether these both report to the same project or not.

However, you could in `backend-app.js` call:
```js
const startApplication = require('@myorg/core');
const Bugsnag = startApplication();
```
which would avoid any use of `._client`. We suspect you may have had to go through the route described above if you have a directory structure that looked like:
```
consuming-app/
  node_modules/
    @bugsnag/js
    @my-org/core/
      node_modules/
        @bugsnag/js
```
If you make sure that it's actually as follows, noting only one instance of `@bugsnag/js`:
```
consuming-app/
  node_modules/
    @bugsnag/js
    @my-org/core/
      node_modules/
```
Hope this helps solve your issue! 😄
