### ISSUE TITLE
Set unhandled when calling Bugsnag.notify

### ISSUE THREAD

**Issue by logicbomb421** [bugsnag/bugsnag-js#926]
I am trying to figure out how to set an error as unhandled when using `Bugsnag.notify`. The stability score is somewhat useless when using `Bugsnag.notify` as-is, since handled errors don't factor into the score. Even though we are 'handling' the error, we still need what we report to be factored into the score for it to provide really any value for us.

I found #569, which is a year old. I managed to figure out that `BugsnagReport` was refactored into `Bugsnag.Event`, but it does not seem that `Bugsnag.notify` expects an `Event` anymore, as it internally creates one and completely overwrites the `handledState` that I attempted to provide.

After reading [the docs on customizing errors](https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/), I thought I'd found the solution by setting `unhandled` to `true`, until noticing:

> This property is readonly: changing the value in a callback will not affect the value sent to Bugsnag.

I also attempted to achieve this by setting the `severity` field to `error` in the error callback, however this does not seem to have any effect on the handled state.

How can I send an 'unhandled' error with `Bugsnag.notify`? Or alternatively, is there a way to have 'handled' errors factor into the stability score?

Thanks!

**Comment by johnkiely1** [comment]
Hi @logicbomb421 

Similar to the solution suggested for #569 there is a way for you to do it with the current version. This would involve making use of [this](https://github.com/bugsnag/bugsnag-js/blob/4bacc8c8a30ea5abf068d709d8e701c4161b8f6b/packages/core/client.js#L265) method whereby you can pass an event to it. You can set the handled/unhandled state on the event at that point.

An example of how to use it can be seen [here](https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-koa/src/koa.js#L35) as this approach has been used on one of our own plugins.

**Comment by xander-jones** [comment]
Closing out as there is a solution to this posted above. Let us know if you have any comments/questions.
