### ISSUE TITLE
plugin-react typings missing export

### ISSUE THREAD

**Issue by logicbomb421** [bugsnag/bugsnag-js#937]
I am trying to access `formatComponentStack` from my TypeScript application, which [is exported](https://github.com/bugsnag/bugsnag-js/blob/fd9523d9d7920522ec4d61c2c4a70b58249242fe/packages/plugin-react/src/index.js#L92) but [not typed](https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-react/types/bugsnag-plugin-react.d.ts) for some reason.

Currently able to work around by augmenting the module:
```ts
declare module '@bugsnag/plugin-react' {
  export function formatComponentStack(stack: string): string;
}
```

Just wanted to let you guys know there's a mismatch. Thanks!

**Comment by mattdyoung** [comment]
Hi @logicbomb421 

The `formatComponentStack` function is an internal implementation detail which is why it's not in the public type definition. It's not intended to be used directly by applications using the Bugsnag React plugin and may change in future versions.

**Comment by logicbomb421** [comment]
Hi @mattdyoung 

Thank you for the reply. I am actually in need of calling `Bugsnag._notify` from within my own error boundary component, similar to #638, which is what lead me to ask this question.

I recognize the solution in that issue was reverse-engineered by the OP and not officially supported, but I am curious on your thoughts on this need? Currently we have Bugsnag behind a feature-flag in our applications as we roll it out. I ran into a situation where, if Bugsnag has not yet been enabled for a particular app, we cannot retrieve the `ErrorBoundary` component from `Bugsnag.getPlugin('react')` and can potentially end up without an error boundary. 

My solution for this was to create my own error boundary component that wraps the same functionality as the Bugsnag component, but that _also_ allows me to provide a fallback logging mechanism in the case that Bugsnag has not yet been enabled.

I also have a need to pass the large majority of errors in as 'unhandled' (#926), so they will factor into the stability score. To accomplish this, I am using the suggestion in the linked issue, which works well, but brings me back to my need of creating my own error boundary that has Bugsnag event creation and notification logic within.

Would you happen to have a suggestion on an official way to create my own error boundary component that mirrors how the Bugsnag component reports (hence my usage of `formatComponentStack`)?

Thanks!

**Comment by steve-nester-uk** [comment]
@logicbomb421 Thanks, yes technically your solution works fine, i.e. if you want to use the internal implementation, you are free to do so, in which case manually providing types for it, seems like a good solution.  

Closing the discussion for now but the thread is still open in case you have further questions/comments..
