### ISSUE TITLE
Integration With Spike.sh

### ISSUE THREAD

**Issue by noob-master147** [bugsnag/bugsnag-js#939]
Greetings @steve-nester-uk 
We at [Spike.sh](Spike.sh) are building an incident management service and we wish to integrate with Bugsnag. 

One of Bugsnag customer is also a customer at Spike.sh and they requested us integration with Bugsnag. We find this a great opportunity to integrate Bugsnag with Spike.sh 😃😃

### As to my understanding we can work together to: 
- ### Get Bugsnag listed at Spike.sh
![image](https://user-images.githubusercontent.com/43108912/87804993-49e82900-c872-11ea-8009-30552386965a.png)

- ### Get Spike.sh listed at Bugsnag
![image](https://user-images.githubusercontent.com/43108912/87803365-fc6abc80-c86f-11ea-8337-d28e8d76178a.png)

# Let us know what you require from our side and we can take this forward. 😃😃

**Comment by snmaynard** [comment]
Going to close this issue as its not an issue with our js library. I see you are speaking with support too so we'll pick this up there.
