### ISSUE TITLE
Busgnag notify sync (running in a CLI script)

### ISSUE THREAD

**Issue by diogopms** [bugsnag/bugsnag-js#972]
Hi, I have a node.js application with a couple of CLI scripts and I would like to know if it's possible to run the **Bugsnag.notify sync.**

example:

config/bugsnag
```js
import Bugsnag from '@bugsnag/js'
import BugsnagPluginExpress from '@bugsnag/plugin-express'

const bugsnagClient = Bugsnag.start({
  apiKey: 'xpto'
    ......
  })
}
export default bugsnagClient
```

```js
import bugsnag from '../../config/bugsnag'

const func = async () => {
  try {
    console.log('Start')
    // Do stuff
    bugsnag.notify('This is a test')
    process.exit(0)
  } catch (error) {
    // wait to notify (sync)
    bugsnag.notify(error)
    process.exit(1)
  }
}
; (async () => {
  await func()
})()
```

Best regards
Diogo

**Comment by xander-jones** [comment]
Hey @diogopms, `Bugsnag.notify()` is synchronous by standard. If you run it within an async function, it will be synchronous within that function (your CLI script). But not synchronous with the caller (your Node.js application). Can you please clarify what you're aiming to do here?

**Comment by diogopms** [comment]
Hi @xander-jones, thanks for the feedback.
The issue was not related with the `bugsnag-js` lib but the **bugsnag.notify** was not working when you have a **process.exit(0)** (i don't know why :( ) 

**not working:**
```js
import 'dotenv/config'
import bugsnag from '../../config/bugsnag'

const func = async () => {
  bugsnag.notify('New error')
  console.log('End')
  process.exit(0)
}

;(async () => {
  await func()
})()
```
I will remove the **process.exit(0)** for now, from the CLI script do you suggest a better way to handle this CLI script?

**Comment by xander-jones** [comment]
Hey @diogopms, to clarify: `notify()` _is_ asynchronous, but it’s not `async` – it will return immediately but do the work to send later. So, when you call `process.exit(0)` immediately after `bugsnag.notify()` it will always exit before the notification has been sent. 

If you'd like to exit the process after calling `bugsnag.notify()`, you can use a callback as follows:
```js
Bugsnag.notify(error, null, () => process.exit(0))
```
The signature of `notify` in Javascript is `notify(error, onError, callback)`. Sorry for the mis-steer, but hope this helps you out. Let us know if you have any other questions 😄
