### ISSUE TITLE
Client beforeNotify vs onError difference?

### ISSUE THREAD

**Issue by simkessy** [bugsnag/bugsnag-js#976]
What is the difference between the two? I found that when trying to add metadata to errors reported in BugSnag, beforeNotify would not work but when I moved the logic to onError things worked as expected:

For example: 

![image](https://user-images.githubusercontent.com/5871660/89089842-20d89580-d354-11ea-920e-c80e6280c4db.png)

**Comment by bendulum** [comment]
Which version? `beforeNotify` doesn't exist anymore in recent versions. https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md Look at the docs https://docs.bugsnag.com/platforms/javascript/reporting-handled-errors/

**Comment by snmaynard** [comment]
Yeah - in the v7 of the notifier it is now called `onError` - its largely a rename. The upgrading guide linked above is useful to rundown the changes.
