### ISSUE TITLE
Some fields are always redacted

### ISSUE THREAD

**Issue by bendulum** [bugsnag/bugsnag-js#979]
Version `7.0.0`.
I'm using `redactedKeys: [],` in my configuration.
`request.clientIp` and `user.id` always end up being `[REDACTED]`.
Prior to upgrading to this version (from `6.x`), I didn't explicitly set the `filters` option (which is now `redactedKeys`) and the fields were not redacted.
Is there something else I'm missing?

**Comment by snmaynard** [comment]
I assume you saw this but pasting here for future travelers -> https://docs.bugsnag.com/platforms/javascript/configuration-options/#collectuserip-browser-only
