### ISSUE TITLE
Errors pops up while getting packages using yarn

### ISSUE THREAD

**Issue by Gilwe** [bugsnag/bugsnag-js#982]
Hi, are you aware of errors returning when trying to `yarn install @bugsnag/node`?

`error An unexpected error occurred: "https://registry.yarnpkg.com/@bugsnag/node/-/node-6.5.2.tgz: Request failed \"404 Not Found\"".`

This error pops up in our CI, happens also for `@bugsnag/browser` and `@bugnsnag/js`, also using yarn.
It started in the last hour

**Comment by FlorianB385** [comment]
same Problem with "npm i @bugsnag/js"
Not Found - GET https://registry.npmjs.org/@bugsnag%2fjs - Not found

**Comment by mattdyoung** [comment]
We believe this is likely due to the ongoing issue just reported on the NPM status page:
https://status.npmjs.org/

**Comment by mattdyoung** [comment]
This issue is now reported as resolved:
https://status.npmjs.org/incidents/cksjqc1w11v5

Can you confirm if the install is now working?

**Comment by steve-nester-uk** [comment]
Based on the resolution above, assuming closed for now.  Please comment if the resolution did not fix the issue.
