### ISSUE TITLE
`lastEvent` is not reset at the end of event handler wrapper

### ISSUE THREAD

**Issue by jc0n** [bugsnag/bugsnag-js#99]
Unless I am mistaken, the intent of logging the last event is when it was likely the trigger for the error. I was reading the notifier code (https://github.com/bugsnag/bugsnag-js/blob/master/src/bugsnag.js) 
 and realized `lastEvent` is never reset anywhere which suggests to me that if an event handler fires `lastEvent` is set with that event and then sent back with the next error on the page which may be completely unrelated to the event. I would have expected lastEvent to be cleared at the end of any event handler wrapper, because if the error didn't happen in the handler, it is no longer relevant.

**Comment by jacobmarshall** [comment]
I understand, but actually it's come in very handy in the past. Where an `onclick` event has been the `lastEvent` and I have been able to correctly determine where the user was, and how they caused the error to occur. That event could be a second or two in the past, but the whole idea of `lastEvent` is to capture the last known event that fired, so it shouldn't ever be 'cleared'. I understand that if the last event was 2 minutes ago, it's probably irrelevant, but I don't really ever see that happen.

Let me know if that makes any sense :smile:

**Comment by ConradIrwin** [comment]
This is definitely the intended behaviour, often you see something like this:

click "refresh" -> AJAX -> throw exception.

It's really handy to be able to see that it was refresh that was clicked. Obviously sometimes it's misleading, as correlation does not imply causation, but overall it seems positive to me.

In the future we'll move this to use the nascent breadcrumb support (bugsnag-android is the only library using it right now), but for now this is working as intended.
